CDCgov/prime-reportstream

- prime-router/metadata/receivers.yml
- prime-router/metadata/schemas/AZ/az-covid-19.schema
- prime-router/metadata/schemas/PA/pa-covid-19.schema
- prime-router/metadata/schemas/PrimeDataInput/pdi-covid-19.schema
- prime-router/metadata/schemas/covid-19.schema
- prime-router/metadata/valuesets/common.valuesets
- prime-router/metadata/valuesets/covid-19.valuesets
- prime-router/metadata/valuesets/tribal.valuesets
- prime-router/src/main/kotlin/Element.kt
- prime-router/src/main/kotlin/FakeTable.kt
- prime-router/src/main/kotlin/MappableTable.kt
- prime-router/src/main/kotlin/Metadata.kt
- prime-router/src/main/kotlin/Receiver.kt
- prime-router/src/main/kotlin/Schema.kt
- prime-router/src/main/kotlin/Translators.kt
- prime-router/src/main/kotlin/ValueSet.kt
- prime-router/src/main/kotlin/main.kt
- prime-router/src/test/kotlin/ElementTests.kt
- prime-router/src/test/kotlin/FakeTableTest.kt
- prime-router/src/test/kotlin/MappableTableTests.kt
- prime-router/src/test/kotlin/MetadataTests.kt
- prime-router/src/test/kotlin/ReceiverTests.kt
- prime-router/src/test/kotlin/SchemaTests.kt
- prime-router/src/test/kotlin/TranslatorTests.kt
- prime-router/src/test/unit_test_files/common.valuesets
- prime-router/src/test/unit_test_files/covid-19.valuesets
**Why**
This PR focuses on cleaning-up the metadata that is used by MappableTable. It is a precursor to writing HL7 messages. 
**Issues**
fixes #7 
fixes #20 
**Changes**
- A new file type called ValueSet to encode the mapping tables from LONIC, SNOMED, or HL7 that are specified by the HHS guidance. 
- Element types CODED, CODED_HL7, ... are now just CODE
- ValueSet is used by FakeTable and Mappings support using ValueSets
- The Schema companion object is now in its own Metadata object file
- The Metadata's interface doesn't leak implementation
- The naming of standard elements is now all lower-case to avoid input problems
> ValueSets and other metadata improvements

- .github/pull_request_template.md
- CONTRIBUTING.md
This PR updates the contributors.md document from the CDC template to something to start the project. This part of the work for #17. It was based on the ElastiSearch contributors doc. 
- Issues and Enhancements request
- Coding convention recommendation
- Squash PRs rule
- Review rules
- #17 - Engineering and Getting started
> Contributing.md and PR template

- prime-router/docs/getting_started.md
- prime-router/src/main/kotlin/Metadata.kt
This PR allows for orginizations.yml files in the local environment
- can create an environment variable PRIME_ENVIRONMENT and copy organizations to organizations-${PRIME_ENVIRONMENT}.yml to support local dev
- by default, if there isnt a PRIME_ENVIRONMENT variable organizations.yml will be used
- #issue
- #issue
> organization.yml supports local

- prime-router/src/main/kotlin/Element.kt
- prime-router/src/main/kotlin/Hl7Converter.kt
- prime-router/src/test/kotlin/ElementTests.kt
This PR does adds formatting flexibility for phone numbers. The default remains 10 digits, but there is much greater flexibility for input and output. This change was requested by the AZ PHD
- Used the Google phone number utility to parse phone numbers
- Support for $country, $area, $exchange, and $subscriber parts of the phone number
- Support for International numbers
- Changed the default which is used by AZ to be a plain 10 digits
> Normalize phone number and its formatting

- prime-router/metadata/organizations-prod.yml
- prime-router/metadata/organizations-test.yml
This PR establishes a prod & test organizations.yml file to support different deployment environments
- organizations-prod.yml sends AZ files via SFTP to actual site
- organizations-test.yml sends AZ files to the test SFTP location
- #issue
- #issue
> add prod and test instances of organizations.yml

- prime-router/metadata/schemas/AZ/pima-az-covid-19-csv.schema
- prime-router/metadata/schemas/PrimeDataInput/pdi-covid-19.schema
- prime-router/metadata/schemas/covid-19.schema
- prime-router/src/main/kotlin/Report.kt
- prime-router/src/main/kotlin/azure/BlobAccess.kt
This PR adds the three additional columns expected by Pima.
- Add three more columns: order_test_date, illness_onset_date, patient_role, to both PDI and Pima.
- Add in a few device_type SimpleReport might send us, to the Pima mapping.
- Fixed weirdness in our filename timestamps
- Fixed .csv.csv file extensions.
- #104 
- Consider having an optional ability to "just pass on the string as is" for CODE value mappings, in cases where the incoming value is missing from our tables.   Could do this for both code -> display and display -> code mappings.
> Threema for Pima Schema

- prime-router/metadata/schemas/AZ/az-covid-19-csv.schema
Turns out there are two places in the AZ data that show Lab/Org/Facility names.
> Fixed yet another az column to include organization_name

- prime-router/metadata/schemas/AZ/pima-az-covid-19-csv.schema
- prime-router/metadata/schemas/PrimeDataInput/pdi-covid-19.schema
This PR temporarily rolls back the Patient_ID change, while we work with SimpleReport on how best to do IDs. 
They are NOT currently sending a Patient_Lookup_ID
> Fixed Patient_ID issue in AZ

- .github/workflows/build.yml
- .github/workflows/release.yml
Due to limitations in passing a build artifact between workflows, I updated the CI/CD workflow to redo the build stage within the release workflow.  This will prevent and upstream PR from building and pushing a docker image that is not in sync with the one that is to be deployed by the release workflow as all are referencing the `latest` image tag.  This can be iterated upon, but for now this will avoid any unwanted by-products of multiple builds happening at the same time.
> Move ACR Push to Release Phase

- prime-router/documentation/covid-19.md
- prime-router/src/main/kotlin/DocumentationFactory.kt
This PR adds a couple improvements to the generate docs function
- Table types now list the table name and column
- For elements which do not have a specific format, use the type format.
> Docs for table element types

- .gitignore
- prime-router/src/main/kotlin/Report.kt
This PR fixes the filename used by reports created in Azure. It was creating names with an 2021 year in the future. 
- report.name function had a bug
> Fix the report name in Azure storage blobs

- .gitignore
- prime-router/metadata/organizations-local.yml
- prime-router/metadata/organizations-test.yml
- prime-router/src/main/kotlin/azure/DatabaseAccess.kt
- prime-router/src/main/kotlin/azure/WorkflowEngine.kt
- prime-router/src/scripts/loop.sh
This PR fixes a problem where the database connections would become exhausted in Azure. 
This problem was found in production and reproduced locally. My local build would exhaust after 10 successful requests. The connection pool was also set to a connection size of 10 — more than a coincidence.  The code was not releasing database connections as expected. The fix was to switch Jooq to use a data source provider. Data sources are what is used if you have a connection pool. The fix was tested by posting 1000 times to my local instance. 
- Use a data-source configuration in Jooq
- Fixed organization-local.yml to support the new multi-transport
- #issue
- #issue
> Data Source Fix

- prime-router/src/main/kotlin/azure/ReportFunction.kt
- prime-router/src/main/kotlin/azure/WorkflowEngine.kt
- prime-router/src/test/kotlin/azure/WorkflowEngineTests.kt
This PR makes the report end-point save the received report as well as translating and routing the report to destinations. Keeping the received report around is a safety measure. Note: the current prod deployment keeps received reports, but it is running old code. The recording of received reports was lost in a recent rework of the report end-point function. 
- receiveReport method for the WorkflowEngine 
- Tests
> Record the receiving of a report

- .github/workflows/release.yml
Setting the function app keys is now removed.  This will cause the occasional failure if the function app does not restart quickly enough.  Since a restart does not destroy the keys - they do not need to be set with each deploy.  Instead, they can be managed via the Azure portal.
> Remove Setting Fxn App Keys

- prime-router/metadata/organizations-local.yml
- prime-router/metadata/organizations-test.yml
- prime-router/metadata/organizations.yml
- prime-router/metadata/schemas/covid-19-redox.schema
- prime-router/src/main/kotlin/JurisdictionalFilters.kt
- prime-router/src/main/kotlin/Translator.kt
- prime-router/src/test/kotlin/JurisdictionalFilterTests.kt
This PR improves the edge condition handling of the Jurisdictional Filters. These changes were needed for the STRAC application which has a different schema than SimpleReport. 
Our current jurisdictional filters work for SimpleReport's schema, but we need to make them work for the STRAC schema. The STRAC schema doesn't have the same elements as SR. In particular, elements in filters like `ordering_facility_county` are missing. This is not a problem, because the STRAC report only goes to PA. 
- Jurisdictional filters handle the case where the element being matched is not in the input schema.  
- Translation functions always succeed with empty report input. 
- #issue
> Jurisdictional filters to handle STRAC

- prime-router/src/main/kotlin/azure/SendFunction.kt
- prime-router/src/main/kotlin/transport/ITransport.kt
- prime-router/src/main/kotlin/transport/RedoxTransport.kt
- prime-router/src/main/kotlin/transport/SftpTransport.kt
- prime-router/src/test/kotlin/azure/SendFunctionTests.kt
This PR fixes a problem that the .csv extension was hardcoded in sftp send.  Also added logging to better see failures.   This is all part of getting ready to send hl7 data to AZ.    (This release also includes Redox send for the first time.)
> Fixed hardcoded .csv extension in sftp send.   Added a bunch of logging

- prime-router/metadata/organizations-local.yml
- prime-router/metadata/organizations-prod.yml
- prime-router/metadata/organizations-test.yml
- prime-router/metadata/organizations.yml
- prime-router/metadata/schemas/PA/pa-covid-19-redox.schema
- prime-router/metadata/schemas/STRAC/strac-covid-19.schema
- prime-router/metadata/schemas/covid-19-redox.schema
- prime-router/src/main/kotlin/FakeReport.kt
- prime-router/src/main/kotlin/cli/main.kt
- prime-router/src/main/kotlin/transport/RedoxTransport.kt
- prime-router/src/main/resources/log4j2.xml
This PR supports the changes requested by PA as well as the changes requested by Redox
- One destination per PA county. Initially provisioning 3 counties. 
- STRAC's ID and KIT ID mapped placer and filler order number
- Filling the producer field with the school name
- Better logging in the Redox transport functions. 
- There is an issue on how to report the County PHD CLIA that is being resolved by Redox
> PA and STRAC changes

- prime-router/metadata/organizations-local.yml
- prime-router/src/main/kotlin/azure/SendFunction.kt
- prime-router/src/main/kotlin/transport/SftpTransport.kt
- prime-router/src/test/kotlin/azure/SendFunctionTests.kt
This PR disables retry and adds more logging to discover why SFTP send is failing in production.
- Disable retry
- Adds more logging
- On local docker-compose sent a fake PDI data (happy path)
- On local docker-compose add a IOException into SFTP code. (failure path)
> Bug Fix: Erroneous retries in AZ

- prime-router/metadata/organizations-local.yml
- prime-router/metadata/organizations-prod.yml
- prime-router/metadata/organizations-test.yml
- prime-router/metadata/organizations.yml
- prime-router/src/main/kotlin/Metadata.kt
- prime-router/src/test/kotlin/MetadataTests.kt
This PR fixes a bug in our PA Organization Services where two services had the same name. 
- Removed the duplicate service name "pa-chester-staging" 
- Added validation code to catch this error at build time.
> Bug Fix: Chester and Montgomery County

- prime-router/metadata/organizations-local.yml
- prime-router/metadata/organizations-test.yml
- prime-router/src/main/kotlin/transport/RedoxTransport.kt
- prime-router/src/test/redox/initializerJson.json
The CO services did not have a transport specified. This PR adds the Redox transport information
- Logging of Redox MessageId
- Clean up of Redox emulator JSON
- #issue
- #issue
> CO/Redox Fix

- prime-router/metadata/schemas/PA/pa-covid-19-redox.schema
- prime-router/metadata/schemas/STRAC/strac-covid-19.schema
- prime-router/src/main/kotlin/serializers/RedoxSerializer.kt
This PR adds a patient_id element for a STRAC app result, even if one doesn't exist. 
The STRAC app does not have the concept of a patient id. Redox requires a Paitent ID (fails if it is not present). After some discussion, it was decided to use a per-test id the placer_order_id to make Redox happy. Redox will not pass this ID to PA when it generates the HL7 message, so PA will be happy. 
- Define patient_id as the placer_order_number for Redox
- Change patient_county to the FIPS county code per PA's request
- Code clean-up on the RedoxSerializer
> Add a patient_id for STRAC when none exists

- prime-router/src/main/kotlin/azure/DatabaseAccess.kt
👋 Howdy, this is my first PR for this project. This is a pretty small fix for an issue I noticed while first getting the application running.
If you check connections by requesting `POST /api/reports?option=CheckConnections`, the response is an error if the database is down and the application has never connected to it before, but it *succeeds* if the database has gone down *after* the application has previously connected to it.
This resolves the issue by making sure we actually try to transact with the database when checking its connection.
To reproduce:
1. Start Postgres
2. Start application
3. Request `POST /api/reports?option=CheckConnections`. You should receive a 200 response.
4. Stop Postgres
5. Request `POST /api/reports?option=CheckConnections`. Before applying this patch, you …
> Actually connect to DB when checking connections

- prime-router/metadata/organizations-prod.yml
- prime-router/src/main/kotlin/serializers/RedoxSerializer.kt
This PR adds the connections to PA PROD and fix for Binax Now kit id transmission
- PA PROD services 
- A workaround for Redox's inability to handle HL7 escaped characters. 
- #issue
- #issue
> PA PROD values

- prime-router/Dockerfile_dev
- prime-router/docker-compose.yml
- prime-router/docs/getting_started.md
This PR adds the ability to disable SSL validations when downloading dependencies locally. Some agencies like CMS intercept SSL requests and re-sign the certificate, breaking the SSL signature.
- Documented how to disable SSL validation for Maven builds
- Adds a build arg `INSECURE_SSL` to our `Dockerfile_dev` to disable SSL validation
- Adds an environment variable `PRIME_DATA_HUB_INSECURE_SSL` to our docker-compose to set the build arg `INSECURE_SSL`
- Documents how to disable SSL validation for Docker builds
- #issue
- #issue
> SSL Validation Override

- .gitignore
- prime-router/.vault/config/init.sh
- prime-router/.vault/config/local.json
- prime-router/docker-compose.yml
- prime-router/docs/getting_started.md
This PR begins work on Secrets Management (#190) by adding a local Hashicorp Vault (#292). This PR only addresses standing up a local Hashicorp Vault instance; at this time the Vault is not used for anything, but it will in follow-on PRs.
- Adds the official Hashicorp Vault Docker image to our `docker-compose.yml`
- Creates a persistent Docker volume to store the encrypted local Vault
- This will allow the secrets to persist locally across `docker-compose up` and `docker-compose down` actions
- Configures Vault to use the file storage engine, leveraging the persistent Docker volume
- Adds a custom Vault startup script to automatically initialize and unseal the Vault, reducing developer burdon for running Vault locally
- Stores vault keys and tokens in `.vault/env` and adds the path to …
> Secrets Management: Local Hashicorp Vault Docker container

- prime-router/docs/playbooks/Stop_a_batch_or_send.md
- prime-router/docs/playbooks/readme.md
- prime-router/src/main/kotlin/azure/BatchFunction.kt
- prime-router/src/main/kotlin/azure/SendFunction.kt
- prime-router/src/main/kotlin/azure/WorkflowEngine.kt
This PR adds the simple ability to stop a queued Batch or Send task by directly manipulating the DB. 
If a mistake is made in production, operators would like the ability to stop a batch or a send task in production by hand. Today this is accomplished by deleting the entire report task row in the database. 
To stop a pending send, an operator with a DB connection can change the `next_action` value to `none`. Note: this is an improvement over deleting the row and the records associated with it.
An example query to find all tasks with pending retries.
```
SELECT report_id, next_action, created_at FROM task WHERE retry_token is not null;
```
An example query to stop pending send. 
```
UPDATE task
SET next_action = 'none'
WHERE report_id = '673bcfe9-3d4e-4aaa-97eb-a0f8e173d706';
```
- …
> Simple Stop Batch or Send Support

- .github/workflows/build.yml
- .github/workflows/release.yml
- prime-router/pom.xml
This is an example of a solution for the build issues in https://github.com/CDCgov/prime-data-hub/pull/262#issuecomment-757544632. It’s mainly meant to illustrate the suggested changes, but could also be merged as a complete fix.
The current GitHub Actions workflows depend on secret values that are not available to external PRs, causing them to always fail on PRs from forks. This is real barrier for non-CDC/USDS folks wanting to contribute to the project.
This change attempts to fix the issue by no longer using secrets for database configuration in workflows. These secrets weren't actually sensitive values or used outside the workflow environment to begin with, so it's fairly safe, and makes understanding configuration simpler. This also removes some duplicate database configuration and …
> Make actions work for external PRs

- prime-router/src/main/kotlin/azure/DownloadFunction.kt
This PR does reads/sets the redirect directly.  Previously it was obtained from request.uri but that isnt valid in test/production
> setting redirect directly

- prime-router/metadata/schemas/covid-19-redox.schema
This PR fixes a typo in the Redox JSON. 
- `Orders[].ResultsStatus` was `Orders[].ResultStatus`
> Redox ResultsStatus typo

- prime-router/quick-test.sh
- prime-router/src/main/kotlin/DocumentationFactory.kt
- prime-router/src/main/kotlin/cli/main.kt
- prime-router/test-ingest.sh
The CLI had several options that were mutually exclusive, as well as options that behaved differently depending on some of those exclusive options (for example, `--output` behaved differently depending on whether `--generate_docs` was set). This breaks the CLI up into multiple subcommands, both to clarify behavior for users and to make the implementation a bit more organized.
The new commands are:
- `data` (the "main" command that most options used to apply to — **I’d love some feedback on whether this is a good name; the right answer here is less clear to me than the other two**)
- `list`
- `generate-docs`
I've also tried to rework the help text here to be clearer and more informative. Unsupported options that are placeholders for future behavior now throw errors when used rather than …
> Break CLI into multiple subcommands

- prime-router/docs/releases/next-release.md
- prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
- prime-router/docs/schema_documentation/covid-19.md
- prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
- prime-router/docs/schema_documentation/pa-pa-covid-19-redox.md
- prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
- prime-router/docs/schema_documentation/strac-strac-covid-19.md
- prime-router/docs/schema_documentation/tx-tx-covid-19-hl7.md
- prime-router/metadata/schemas/PrimeDataInput/pdi-covid-19.schema
- prime-router/metadata/schemas/covid-19.schema
This PR added Corrected_result_ID to the columns we read from SimpleReport, in support of their sending corrections to prior tests.  (The Test_result_status field is also needed for this, but its already in the schema)
- #344 
- SimpleReport has asked for two potential follow-on features:
1. Optionally prevent redundant submissions by validating that every Result_ID is unique.  That is, validate that each Result_ID has not been previously submitted.
2. Optionally confirm that a Corrected_result_ID does indeed point to a valid previous Result_ID.
These need discussion, prioritization, and are dependent on other work first.
> Added Corrected_result_id, per #344

- prime-router/devenv-infrastructure.sh
- prime-router/docker-infrastructure.yml
- prime-router/docs/getting_started.md
This PR adds an option to run PostgreSQL infrastructure from Docker instead of on the developer machine itself. Supporting docker-based PostgreSQL infrastructure also enables testing the prime-data-hub system against new releases and alternate configurations of the database.
- Added `docker-infrastructure.yml` docker-compose configuration
- Added `docker-infrastructure.sh` shell script to document the `docker-compose -f docker-infrastructure.yml up --detach` command.
- Updated `docs/getting-started.md` to reflect the three options for running PostgreSQL.
> Added docker-based PostgreSQL infrastructure option.

- .github/workflows/build.yml
- .github/workflows/release.yml
- prime-router/docs/schema_documentation/pa-pa-covid-19-redox.md
- prime-router/docs/schema_documentation/strac-strac-covid-19.md
After seeing #344, I noticed that, even though we have some autogenerated docs in the repo, they are not always kept up-to-date. This adds an action to the build workflow that fails if there are uncommitted docs updates in a PR.
It will add a check like:
And post comments to the PR like:
The comments include a list of files it expected to see changed (basically the output of `git status docs`), since displaying a full diff seemed excessive. To see a full diff, you can click the “details” link on the status check to look at the workflow’s logs:
**This is focused on a pass/fail approach, but we could do something different and auto-commit the generated docs.** @jimduff-usds suggested this and I tried it out, but committing to the PR branch is not so great: either you re-run the build a …
> Add a PR check to verify that docs are up-to-date

- prime-router/src/main/kotlin/azure/ActionHistory.kt
- prime-router/src/main/kotlin/azure/SendFunction.kt
- prime-router/src/main/kotlin/transport/SftpTransport.kt
This PR fixes these issues with linage tracking related to failed sftps:
- fixes a bug where failed sftps were of type `send` instead of `send_error`.
- fixes a bug where failed sftp were generating new rows in the report_file table, which seems unnecessary and confusing.
- improves the database information tracking in the action_result column, when a failed sftp occurs.
> Minor fixes

- prime-router/assets/csv-download-site/login__inline.html
- added Okta CSS subresource integrity fingerprint.
- converted to HTML5 doctype to match `index__inline.html`
- fixed minor local var scope issue
> Added Okta CSS subresource integrity fingerprint.

- prime-router/src/main/kotlin/Report.kt
- prime-router/src/main/kotlin/azure/ReportFunction.kt
This PR does fixes a mistake that the HL7 Batching PR had.
- Report.bodyFormat can be overridden to the INTERNAL format rather than the destination format. 
-
> Fix for the HL7 Batch

- prime-router/metadata/organizations-prod.yml
- prime-router/metadata/organizations-test.yml
This PR changes the timing of data pushes to AZ from 6 times a day to once per day.  This is in anticipation of simple report changing to sending data to us many times a day.
> Change AZ to once a day, anticipating SR change to many per day

- prime-router/metadata/organizations-local.yml
- prime-router/metadata/organizations-test.yml
This PR removes the test environment's connection to PA and CO since both are in production. 
We have been using our test environment as a staging environment. Both PA and CO were configured to send data to the PHDs. This PR removes these connections, so the test deployment does not send data anywhere.
> Disable PR

- prime-router/src/main/kotlin/Report.kt
- prime-router/src/main/kotlin/cli/main.kt
This PR changes the way we synthesize the names of patients and DOBs to afford more protection for patients by
- Always faking the names
- Converting the DOB to a different day and month, but preserving the year so the age graph is approximately the same shape
- #484
> Synthetic Data Improvements

- prime-router/docs/releases/2021-02-12-release-notes.md
- prime-router/src/main/kotlin/Metadata.kt
- prime-router/src/main/kotlin/azure/ActionHistory.kt
- prime-router/src/main/kotlin/azure/DatabaseAccess.kt
- prime-router/src/main/kotlin/azure/ReportFunction.kt
This PR changes the format of destinations in our return Json from informal sentences
```
"destinations" : [ "Sending 58 items to Jones County Public Health Dept (prod-elr) at 2021-02-08T12:00-07:00", etc ]
```
to more formal json:
```
"destinations" : [ {
"organization" : "Jones County Public Health Dept",
"organization_id" : "prod-phd",
"service" : "prod-elr",
"sending_at" : "2021-02-08T12:00-07:00",
"itemCount" : 58
}, {
```
Also adds a 
`destinationCount`
If the data is valid, but is going nowhere, you'll see:
"destinations" : [ ],
"destinationCount" : 0,
- Request from SR.
- #issue
> Put destinations into formal JSON

- prime-router/src/main/kotlin/azure/ActionHistory.kt
- prime-router/src/main/kotlin/azure/ReportFunction.kt
- prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
This PR fixes an off by one bug in the itemCount field in the destinations response json.
The fix was literally one character, but I wrapped it with a gigantic test as a mea culpa.
> Fixed bug in itemCount in destinations report

- operations/app/src/modules/nat_gateway/main.tf
Rename the public IP for the NAT Gateway back to the original (generic) naming.  Azure currently doesn't support renaming an IP address without destroying and re-creating.  Since we don't want the static IP to change, the name is being reverted.
> Rename NAT Gateway Public IP

- operations/app/src/modules/function_app/main.tf
Added app settings specific to the production instance of the Function App.  Since the production app is on an Elastic Premium service plan it requires additional environment variables not necessary in the test version of the Function App.
> Add prod-specific conditionals for Function App environment

- prime-router/metadata/organizations-local.yml
- prime-router/metadata/organizations-prod.yml
- prime-router/metadata/organizations-test.yml
- prime-router/metadata/schemas/STRAC/strac-covid-19.schema
This PR adds the support requested by the Chester and Montgomery counties.
- Adds a `model` field to STRAC schema
- Adds Chester and Montgomery 
Note: Chester support both Chester and Delaware counties
#501 
#496
> PA Download

- operations/app/src/environments/dev/main.tf
- operations/app/src/environments/prod/main.tf
- operations/app/src/environments/test/main.tf
- operations/app/src/modules/front_door/main.tf
- operations/app/src/modules/front_door/variables.tf
- operations/app/src/modules/prime_data_hub/main.tf
- operations/app/src/modules/prime_data_hub/variables.tf
This PR fixes prime.cdc.gov not being selected on the front_door in production. It also configures test.prime.cdc.gov and allows other environments to have certs in the future.
- Adds a local variable for frontend_endpoints, which included prime.cdc.gov in production.
- Adds a variable `https_cert_name` that is used to configure the cert on the front door. Null skips the configuration.
- #issue
> Fix unselected prime.cdc.gov domain

- prime-router/metadata/organizations-test.yml
This PR adds the new Prime organization as a fake public health department to Test.   It now exists in command line, -local, and -test, but not in -prod.
- This is part of the overall API hardening work - giving us better ways to test our API.
- Figure out what to do with Redox tests - should we push to a redox test endpoint, or stand up a mock redox in test?
> Added new Prime organization to organizations-test.yml

- .github/workflows/build.yml
- .github/workflows/release.yml
While the `prime-data-hub-test` resource group is being pentested, we want to deploy our testable changes to the `prime-data-hub-staging` resource group.  This PR updates the CI/CD workflow to do so.
> Deploy master to staging environment during pentesting

- operations/app/src/modules/key_vault/main.tf
This PR adds two key vaults for secret management.
- Adds `pdh*-appconfig` key vault
- Adds `pdh*-clientconfig` key vault
- Grants dev access to both key vaults
- #issue
- After this PR rolls out, we need to populate the key vaults with secrets.
- Follow on PRs will switch our apps and configs to use the key vaults.
> Add key vaults for secret management

- operations/app/src/modules/storage/main.tf
This PR fixes an issue where Terraform suggests making a change to the storage log diagnostic setting. The issue was a missing metric type in the Terraform module.
-
- 
- #issue
- #issue
> Fix for Terraform plan suggesting changes

- operations/app/src/modules/database/main.tf
- operations/app/src/modules/metabase/main.tf
- operations/app/src/modules/metabase/variables.tf
- operations/app/src/modules/prime_data_hub/main.tf
This PR provisions Metabase within the production environment.  Because the production environment uses an Elastic Premium service plan for the function apps, a separate service plan is required so that Metabase can be provisioned.  The Elastic Premium option is only available for Function Apps.
> Provision Metabase in Production

- operations/app/src/modules/function_app/main.tf
- operations/app/src/modules/function_app/variables.tf
- operations/app/src/modules/prime_data_hub/main.tf
- Adds missing access policies for the Key Vaults / Function App
- Note: There is a bug in the Terraform module for function apps. I have a workaround, but it requires two deploys. See my comment in the code for more info.
> Hotfix: Add Key Vault access policies for the function app

- .github/workflows/build_frontend.yaml
- .github/workflows/build_hub.yml
- .github/workflows/release.yml
This PR improves our GitHub actions.
- Fixes #457
- Builds only run when files in a directory they care about are modified
- This means ops PRs will not have failing tests because we didn't update the docs directory (yay!)
- Breaks our actions into separate flows to enable the above, and also sets us up for a GitHub action for terraform
- Renames the actions to descriptive names
> Discrete GitHub Action Builds

- prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
- prime-router/docs/schema_documentation/az-az-covid-19.md
- prime-router/docs/schema_documentation/az-pima-az-covid-19.md
- prime-router/docs/schema_documentation/co-co-covid-19-redox.md
- prime-router/docs/schema_documentation/covid-19-redox.md
- prime-router/docs/schema_documentation/covid-19.md
- prime-router/docs/schema_documentation/fl-fl-covid-19.md
- prime-router/docs/schema_documentation/la-la-covid-19.md
- prime-router/docs/schema_documentation/nd-nd-covid-19.md
- prime-router/docs/schema_documentation/nm-nm-covid-19.md
- prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
- prime-router/docs/schema_documentation/pa-pa-covid-19-redox.md
- prime-router/docs/schema_documentation/pa-pa-covid-19.md
- prime-router/docs/schema_documentation/pdi-covid-19.md
- prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
- prime-router/docs/schema_documentation/standard-standard-covid-19.md
- prime-router/docs/schema_documentation/strac-strac-covid-19.md
- prime-router/docs/schema_documentation/tx-tx-covid-19.md
- prime-router/docs/schema_documentation/vt-vt-covid-19.md
- prime-router/metadata/schemas/covid-19.schema
- prime-router/src/main/kotlin/DocumentationFactory.kt
- prime-router/src/main/kotlin/cli/main.kt
This PR adds a documentation option to create a data dictionary for simple report. This data dictionary lists all HL7 elements that SimpleReport will generate. See prime-router/docs/schema_documentation/pdi-covid-19.md for an example output. 
-  `--mapped-hl7-elements` flag for generating documents
- builds a special schema when this flag is set
#577
> SimpleReport data dictionary

- .github/workflows/build_frontend.yaml
- .github/workflows/build_hub.yml
Too many pre-jobs are running. This syntax is cleaner and gets us to GitHub action runs faster.
> Fix Fork GitHub Action Check

- .github/workflows/release.yml
Environment variables were manually being set using the Azure CLI via stored GitHub secrets.  This is no longer desired as the secrets are now in Azure Key Vault and their reference is derived by terraform.  Removing this code prevents secrets being reverted from Key Vault references to their original values stored in GitHub.  Once this PR is merged, these secrets will be purged from GitHub.
> Remove setting env vars manually

- prime-router/settings/organizations-local.yml
- prime-router/settings/organizations-test.yml
- prime-router/src/main/kotlin/TransportType.kt
- prime-router/src/main/kotlin/azure/BatchFunction.kt
- prime-router/src/main/kotlin/azure/SendFunction.kt
- prime-router/src/main/kotlin/transport/NullTransport.kt
This PR creates a NullTransport which doesn't send anything but creates ActionHistory. This transport is just intended for benchmarking purposes. 
- NullTransport
- Switched IG.HL7 receiver to use the NullTransport to help narrow down a throughput bottleneck
- Added a better logging for the outer handler of the Send and Batch function
- #issues in GitHub
- Stuff still to done
> Null Transport

- prime-router/docs/schema_documentation/tcp-tcp-covid-19.md
- prime-router/metadata/schemas/TCP/tcp-covid-19.schema
- prime-router/metadata/tables/zip-code-data.csv
This PR updates the TPC schema to include more default fields that make the HL7 look fuller and includes a mapper for the county for patients.
> Adds logic to map the zip code to the county for routing

- prime-router/src/main/kotlin/azure/DownloadFunction.kt
This PR fixes a bug wherein .hl7 files were given an .csv file extension on download.
- Bug that file extensions for hl7 downloads were erroneous.
- Confirm on various browsers.  I tested on Firefox and Safari
> Fixed download file extension issue

- prime-router/src/main/kotlin/Mappers.kt
- prime-router/src/test/kotlin/MapperTests.kt
This PR fixes a bug in the split mappers so they never fail with an error but just return null.
- #issues in GitHub
- Stuff still to done
> Fixes bug in mapper

- prime-router/docker-compose.yml
This PR removes the requirement that changes to `organizations-local.yml` be `mvn package` before running `docker-compose up` 
- `organizations-local.yml` is now bound to the container instead placed into the container. 
- 
- #issues in GitHub
- Stuff still to done
> Improve local docker-compose settings

- operations/app/src/modules/app_service_plan/main.tf
Renaming an app service plan requires the destruction and re-provisioning of it.  I am reverting this so that it can be avoided in the environments where it is not necessary.
> Revert Service Plan Name

- prime-router/docs/openapi.yml
- prime-router/docs/releases/2021-03-15-release-notes.md
- prime-router/src/main/kotlin/Translator.kt
- prime-router/src/main/kotlin/azure/ReportFunction.kt
- prime-router/src/main/kotlin/azure/SendFunction.kt
- prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
- prime-router/src/test/kotlin/azure/WorkflowEngineTests.kt
Two changes to the `/api/reports` end-point to assist in sending reports to a particular receiver. This is type action will typically be done when a new receiver is defined after a results are received by the hub. 
- `SendImmediately` value for the `option` query parameter to bypass any timing found on the receiver.
- `routeTo` query parameter restricts the list of receivers which a report can be routed to. 
The `routeTo` parameter **does not** bypass the jurisdictional filters of the receiver, so results meant for one receiver still cannot be sent to another receiver.
- As described above
- Note that the jurisdictional filters are not bypassed by the `routeTo` function.
- #issue
- #issue
> Add options for to assist backfill of results

- operations/app/src/modules/function_app/main.tf
This PR sets the environment variables required for the function app to use the Key Vault.
This must be deployed before #392 so the environment variables are in place. The Key Vault will not be used until the application code is deployed.
A follow on PR will be submit after this rolls out successfully to remove the old environment variables.
> Use Key Vault for client secret management

- prime-router/src/main/kotlin/azure/DownloadFunction.kt
- prime-router/src/main/kotlin/secrets/AzureSecretService.kt
- prime-router/src/main/kotlin/secrets/EnvVarSecretService.kt
- prime-router/src/main/kotlin/secrets/SecretManagement.kt
- prime-router/src/main/kotlin/secrets/SecretService.kt
- prime-router/src/main/kotlin/transport/RedoxTransport.kt
- prime-router/src/test/kotlin/secrets/AzureSecretServiceTests.kt
- prime-router/src/test/kotlin/secrets/SecretServiceTests.kt
As part of the ongoing work to lock down our Azure environment to VPN only, we discovered that our Key Vault references do not work when our Key Vault is private only ([example Key Vault reference](https://github.com/CDCgov/prime-data-hub/blob/master/operations/app/src/modules/function_app/main.tf#L51)) ([Slack conversation thread](https://usds.slack.com/archives/C01HFHPNJEL/p1615916228012700)).
This PR adds a new SecretService, which supports fetching secrets via environment variables locally and in Azure Key Vault when the `SECRET_STORAGE_METHOD` environment variable equals `AZURE`.
- Adds a SecretService, heavily based off the work I did on building a CredentialService for SFTP credentials in Azure Key Vault.
- Migrates two environment variables calls that use Key Vault to the …
> Secret Management Service

- prime-router/src/main/kotlin/azure/CheckFunction.kt
- prime-router/src/main/kotlin/azure/HealthCheckFunction.kt
- prime-router/src/main/kotlin/azure/HttpUtilities.kt
- prime-router/src/main/kotlin/azure/ReportFunction.kt
This PR implements some cleanup to the sftpcheck.
- Renamed `api/check` instead of `api/healthcheck`
- New option:  `api/check?sftpcheck=all` will check all Transports.   Right now only sftp checks are implemented, however.    This will also tell you if the transport definition is missing.
- no known issues.
> check all sftp

- prime-router/settings/organizations-prod.yml
- prime-router/settings/organizations-test.yml
This PR updates the sftp path for LA in prod to have the checker pass. Also aligned the organizations-test file so everything is aligned.
- Changes path for SFTP for LA in prod
- Updates `organizations-test.yml` to match other organization files
- #issue
- #issue
> Updates path for SFTP in prod for LA and aligns test organization files

- prime-router/docs/schema_documentation/oh-oh-covid-19.md
- prime-router/metadata/schemas/OH/oh-covid-19.schema
This PR fixes problem with schema misnaming in OH schema. `report_facility` should be `reporting_facility`. 
- Fixes problem with misnaming in OH schema
> Fixes schema issue for OH

- prime-router/host.json
- prime-router/src/main/kotlin/azure/DatabaseAccess.kt
This PR addresses some of the timeout issues we've been seeing with SFTP connections.
- Increases available database connections from 10 to 20.
- Increases the connection timeout from 30 seconds to 60 seconds.
- Decreases the amount of queue items fetched from 16 to 8 (which will cap total number of items processing simultaneous to 8 + 4 = 12 which is  < the 20 available DB connections)
- #issue
- #issue
> Database Connection / Queue Tuning

- prime-router/pom.xml
- prime-router/settings/organizations-local.yml
- prime-router/settings/organizations-prod.yml
- prime-router/settings/organizations-test.yml
- prime-router/src/main/kotlin/TransportType.kt
- prime-router/src/main/kotlin/azure/CheckFunction.kt
- prime-router/src/main/kotlin/azure/SendFunction.kt
- prime-router/src/main/kotlin/azure/WorkflowEngine.kt
- prime-router/src/main/kotlin/transport/SftpLegacyTransport.kt
- prime-router/src/test/kotlin/secrets/SecretServiceTests.kt
Testing SFTP connections to Texas showed that we have issues connecting to their server. Testing showed that it was likely tied to the fact that they are only using `Diffie-Hellman Group Exchange SHA1` which is not recommended at this point. Our existing SSH library refuses to connect to servers that only offer `DHGexSHA1`.  
Multiple attempts to force `SSHJ` to connect were unsuccessful, and discussions with other engineers suggested it might be possible to use a different or older library in order to allow us to connect to Texas.
A test was done using `JSCH` which is an older SSH library for Java, and it was able to successful connect with the TX servers and communicate with them. 
Initially I considered doing class loading and dynamically loading the appropriate library based on a …
> Add legacy SFTP support for states using older encryption algorithms

- prime-router/src/main/kotlin/credentials/AzureCredentialService.kt
- prime-router/src/main/kotlin/secrets/AzureSecretService.kt
- prime-router/src/test/kotlin/credentials/AzureCredentialServiceTests.kt
- prime-router/src/test/kotlin/secrets/AzureSecretServiceTests.kt
This PR add a retry policy specifically to the Azure Key Vault access.
- Uses Azure's own build in retry policy, with exponential backoff, to retry fetching secrets
- 
- [] Ran `quickTest all`?
- #issue
- #issue
> Add retry policy for Azure Key Vault

- prime-router/src/main/kotlin/transport/RedoxTransport.kt
- prime-router/src/test/kotlin/transport/RedoxTransportTests.kt
This PR fixes a bug wherein a failure during a Vault credential lookup, during a retry of a previously partially successful Redox send, causes the subsequent retry to rerun everything, instead of just the retry items from the previously partially successful Redox send.
I actually think this is easier to understand by looking at the code changes, and not at that sentence.
I also added a printout of the RetryToken to the logging, as currently the RetryToken gets wiped out in the database, and I'm not putting it in the History tables at this time.
*none known.
- see above.
> Fixed bug when Redox failures mix with credential lookup failures

- prime-router/src/main/kotlin/azure/CheckFunction.kt
- prime-router/src/main/kotlin/cli/CredentialsCli.kt
- prime-router/src/main/kotlin/credentials/Credential.kt
- prime-router/src/main/kotlin/transport/SftpTransport.kt
This PR adds PPK authentication to the SftpTransport.
Since Key Vault supports secrets as large as 25,000 bytes, PPK files are within that limit and can be stored as Azure secrets. In my testing, a PPK file stored in our JSON container averaged 2,800 bytes.
- Refactors the SftpTransport to handle multiple authentication options
- Adds the ability to create UserPpk types via the CLI
- #issue
- #issue
> Support for PPK authentication via SFTP

- operations/app/src/modules/database/main.tf
This PR sets the `reportstream_pgsql_admin` AAD group as the admin for ReportStream's PostgreSQL servers.  This enables AAD to be used as the mechanism for authenticating with PostgreSQL as opposed to the local user account.
> Add AD Admin Group for PostgreSQL Server

- prime-router/docs/schema_documentation/mt-mt-covid-19-csv.md
- prime-router/docs/schema_documentation/tpca-tpca-covid-19.md
- prime-router/metadata/schemas/MT/mt-covid-19-csv.schema
- prime-router/metadata/schemas/TPCA/tpca-covid-19.schema
- prime-router/settings/organizations-local.yml
- prime-router/settings/organizations-prod.yml
- prime-router/settings/organizations-test.yml
- prime-router/settings/organizations.yml
This PR updates the organization files so they're matching across the different levels and updates VT, NM, and GU to have transport information in prod. This will require us to add their credential information into prod so we can test and verify the connections.
I also changed the name of TCP to match TPCA as it should be.
- Changed the name of TCP to TPCA
- Added organizations for VT, NM, and GU to prod and included their transport info
- Updated the docs
- Add the credential information for NM, GU, and VT into secrets storage on prod #712
> Sync'd the organization files and added transports for VT and NM and GU

- prime-router/docker-compose.yml
- prime-router/src/main/kotlin/azure/WorkflowEngine.kt
- prime-router/src/test/kotlin/secrets/SecretServiceTests.kt
This PR enables the use the setting database by default. 
- Behavior when FEATURE_FLAG_SETTINGS_ENABLED is missing to true
- #issue
- #issue
> Change the default behavior when SETTINGS_ENABLED is missing

- prime-router/docs/schema_documentation/mt-mt-covid-19-csv.md
- prime-router/metadata/schemas/MT/mt-covid-19-csv.schema
This PR fixes two errors in serialization found during running quick test for MT 
- Adds data type to `organization_name` and `patient_role`
- Updates docs
> Fixes errors from quick test for MT CSV schema

- prime-router/src/main/kotlin/LookupTable.kt
- prime-router/src/test/kotlin/LookupTableTests.kt
This PR adds an `ignoreCase` flag to `filter`, `lookupValue`, and `lookupValues` that is defaulted to `true`. In most cases, we don't really care about the case of the data passed in, and given the fact that the data can come in in different case than we expect, we should not fail a lookup because someone sends us something that does not explicitly match our tables.
In the `LIVD` table we have device names that we match on to them map their result codes to the LOINC values that organizations need. Specifically, a lab in Ohio was sending `ID Now` as the device name, but our LIVD table looks for `ID NOW` which caused the lookup to fail and pass through empty string for OBX-3.
- Adds `ignoreCase` to `filter`
- Adds `ignoreCase` to `lookupValue`
- Adds `ignoreCase` to `lookupValues`
- Adds …
> Added case insensitive search and tests for Lookup Tables

- prime-router/docs/how-to-onboard-a-sender.md
- prime-router/src/main/kotlin/Element.kt
This PR makes a two small changes from the demo cleanup, the most important is adding the documentation on how to onboard a sender. This is going to be important as more folks come on board to help. I want to get this merged as soon we can so folks can take a look. 
I'm sure the documentation will need some changes as we move on, but this is a good first pass.
- Adds catch to formatting a phone number because the Google phone number library will just throw an exception when parsing, and doesn't offer a `tryParse` method which would be helpful, or a way to validate if something is a phone number as a static method.
- Adds doc about how to onboard a sender
- #632
> Demo Clean Up

- operations/app/src/modules/database/main.tf
- operations/app/src/modules/database/variables.tf
- operations/app/src/modules/network/main.tf
- operations/app/src/modules/prime_data_hub/main.tf
This PR adds a read replica for our master PostgreSQL server.  This will allow us to 1) alleviate burden on the master server for heavy read workloads, and 2) fail-over and promote the read replica to the master server upon a disaster scenario with minimal downtime.
The replica server is provisioned within the West US region, which is a pair to the East US region.  Additionally, it is provisioned within a second virtual network that is peered to the virtual network that resides within the East US region.  During testing, the communication between the master and replica worked just fine with public traffic disabled to the replica and no peered virtual network provisioned, so it may not be needed.  However, I opted to keep it as part of this PR as it will make for a much quicker response …
> Add PostgreSQL Replica within Peered Virtual Network

- operations/app/src/environments/dev/main.tf
- operations/app/src/environments/prod/main.tf
- operations/app/src/environments/staging/main.tf
- operations/app/src/environments/test/main.tf
- operations/app/src/modules/front_door/main.tf
- operations/app/src/modules/front_door/variables.tf
- operations/app/src/modules/prime_data_hub/main.tf
- operations/app/src/modules/prime_data_hub/variables.tf
This PR adds the `reportstream.cdc.gov` frontend endpoint to the Front Door for the appropriate environment.
> Add frontend endpoint for reportstream.cdc.gov

- .github/vpn/dev.ovpn
- .github/vpn/staging.ovpn
- .github/workflows/release.yml
- operations/app/src/modules/storage/main.tf
This PR add the necessary infrastructure changes to deploy out the static website (#512). An example of the deployment can be seen at:
https://rheftpublic.z13.web.core.windows.net/
The URL for staging server will be known after the first deployment.
- Adds a storage account with public access designated for the website: ex. `rheftstatic`
- Azure storage account must be named with lowercase characters only, no special characters
- Adds a static website deployment step to our release GitHub action
- Improves the GitHub action with a DEV deployment flow, to make testing GitHub actions easier
- The storage account bucket is for public data only and will not be used to store any other type of data
- Deploy Terraform state before merging or release pipeline will fail
- When the website is ready …
> Static Storage Account

- prime-router/docs/getting_started.md
- prime-router/quick-test.sh
This PR adds Windows OS compatibility to the quick test.
**NOTE this change requires a test in Mac/Linux OS to make sure the script is not broken on those OS.**
1. Run quicktest all in a Windows OS workstation and verify all tests pass.
2. Run quicktest all in a Mac or Linux OS workstation and verify all tests pass.
- Fixed issue with filename text having extra quote or newline, hence breaking the test
- Added backslash to filename search patterns.  -- A potential more generic change is to get rid of the slashes all together.  Thoughts?
N/A
N/A
N/A
> Updated quick test for Windows compatibility

- prime-router/src/main/kotlin/azure/DatabaseAccess.kt
- prime-router/src/main/kotlin/azure/RequeueFunction.kt
- prime-router/src/main/kotlin/azure/SendFunction.kt
- prime-router/src/main/kotlin/azure/WorkflowEngine.kt
- prime-router/src/main/kotlin/transport/RedoxTransport.kt
This PR 
- fixes a bug in the requeue feature, where if, for whatever reason, the system had not even attempted to send data to Redox, requeue's sendFailed interpreted that as a Success.  It should be interpreted as a failure.
- adds yet more logging, in an attempt to isolate the 'lateinit' exception as outlined in #768 
- #768 , not done.
> Further work related to redox sends

- prime-router/host.json
- prime-router/src/main/kotlin/azure/DatabaseAccess.kt
This PR resolves several conflicts with the number of concurrent messages processing and the number of open database connections.
- Fixes an unexpected override of the `maximumPoolSize` in our database configuration. We thought the value was set at 20, but it was overridden to 8
- Sets the `maximumPoolSize` to 15
- Lowers the queue batch size to 4
- Explicitly sets the `newBatchThershold` at 2
With the above settings, the maximum number of open connections we should have at a time will 12; three lower than the `maximumPoolSize`. This is calculated with the below equation:
```
2 listening queues [BatchFunction and SendFunction]
x
6 [4 items fetched from the queue  + 2 items in the queue when fetched]
---
= 12 concurrent items processing in the queue
12 items < 15 maximumPoolSize
```
*List …
> Queue Connection Tweaks

- prime-router/host.json
- prime-router/src/main/kotlin/azure/DatabaseAccess.kt
This PR is a tweak of https://github.com/CDCgov/prime-data-hub/pull/779 by attempting to process more items at once.
- Sets the maximumPoolSize to 25
- Set queue batch size to 8
- Sets the newBatchThershold at 4
```
2 listening queues [BatchFunction and SendFunction]
x
12 [8 items fetched from the queue  + 4 items in the queue when fetched]
---
= 24 concurrent items processing in the queue
24 items < 25 maximumPoolSize
```
- #issue
- #issue
> Higher processing concurrency

- prime-router/settings/organizations-local.yml
- prime-router/settings/organizations-test.yml
- prime-router/settings/organizations.yml
- prime-router/settings/prod/0007-nj-doh.yml
- prime-router/settings/prod/0008-mn-doh.yml
- prime-router/settings/staging/0001-nj-doh.yml
- prime-router/settings/staging/0002-mn-doh.yml
This PR adds entries in the organizations for MN and NJ. 
- Adds MN to organization files
- Adds NJ to organization files
- Adds yamlitos to submit to staging and prod
> Onboarding NJ and MN

- prime-router/src/main/kotlin/FakeReport.kt
- prime-router/src/main/kotlin/Report.kt
- prime-router/src/test/kotlin/FakeReportTests.kt
- prime-router/src/test/kotlin/LookupTableTests.kt
This PR fixes an issue where the synthesizer is scrambling the data TOO much by recreating the row context for every single row in every single column. This ended up causing a problem where city, state, zip, and county would not match because they were all randomized.
Now, after the generation of the columns, we loop through the rows and set the city, state, zip, and county to the tied values created in the RowContext. This is obviously more expensive, but it's a more correct way to accomplish our goal. 
- Adds new tests to verify that filtering of tables works
- Adds new test to verify that the chaining of lookup values in the `RowContext` works as expected
- Adds logic to walk the rows and set the address information to something that is correct
> Fixes issue with the synthesizer scrambling TOO MUCH data

- operations/app/src/modules/storage/main.tf
This PR creates a partner-specific storage account for HHS Protect exports.
- Creates a partner storage account
- Sets up a private endpoint for the storage account
- Encrypts the storage account using CDC encryption keys
- Creates a blob container `hhsprotect` for HHS Protect files
- Adds a storage policy to delete files after 30 days
* Azure policy will automatically capture logs
* IP addresses of HHS Protect will not be exposed in logs
* A separate storage account was created to maintain separation of concerns
* After deployment, configure access keys for HHS Protect
> Storage account for HHS protect

- prime-router/settings/organizations-local.yml
- prime-router/settings/organizations.yml
- prime-router/settings/prod/0011-imagemover-orgs.yml
- prime-router/settings/staging/0004-imagemover-orgs.yml
This PR fixes a problem with the jurisdictional filter.
- It's `orEquals` not `or`.
- #issue
- #issue
> Fixes issue with bad jurisdictional filter

- operations/app/src/modules/storage/main.tf
This PR makes some changes to our partner storage account, allowing HHS Protect to connect.
- Switches the blob storage container to using "HNS" or hierarchical namespace. This allows the blob storage to accept Hadoop data connectors.
- Whitelists HHS Protect's ip addresses.
* HHS Protect IP addresses are stored in the Key Vault as a secret, to not expose their IPs
> HHS Protect Blob Storage Changes

- operations/app/src/modules/key_vault/main.tf
- prime-router/docs/playbooks/dns_or_sftp_restart.md
This PR grants @mauricereeves and @jimduff-usds access to the Key Vaults, so they can administer credentials.
- Adds Mo and Jim to the list of developer credentials.
- During deployment, it was discovered our DNS servers have all stopped over night, so it could not be deployed out. This PR also includes the directions to restart the DNS servers.
* Individually adding developers to resources is not the long term plan. We will be creating groups in #CDCGov/prime-devops#37
> Add Jim/Mo Key Vault Permissions + Container Restart Playbook

- prime-router/settings/organizations-local.yml
- prime-router/settings/organizations.yml
- prime-router/settings/prod/0012-nh-ma-organizations.yml
- prime-router/settings/staging/0005-nh-ma-organizations.yml
This PR fixes a bug with the organizations where I tried to use `orElse` instead of `orEquals`. 
- Fixes issue with organizations I introduced
> Fixes jurisdictional filter bug

- prime-router/src/main/kotlin/Receiver.kt
- prime-router/src/main/kotlin/azure/BlobAccess.kt
- prime-router/src/main/kotlin/cli/TestReportStream.kt
This PR adds a new load test and logging
- Added logging during blobstore transport
- Added a load test.  Works up to 100,000 Items / hour on local laptop runs.
- Increased default max reports per merge operation to 500 from 100, in preparation for further load testing.
- none known
> New load test; logging

- frontend/src/_data/content/index.yaml
- frontend/src/_includes/identifier.liquid
- frontend/src/_layouts/protected.liquid
- frontend/src/index.html
This PR ... 
Fixes #829 and makes some 508-ish related updates.
- Add `aria-label` to PDF download links on homepage
- Move product img text from `alt` to `title`
- Turn `div usa-identifier` into `footer`
- Add labels to footer
- Add more sections to main with `role=region`
- Remove multiple main elements in layout
- #issue
- #issue
> 508 tweaks

- prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
- prime-router/docs/schema_documentation/az-az-covid-19.md
- prime-router/docs/schema_documentation/az-pima-az-covid-19.md
- prime-router/docs/schema_documentation/ca-ca-scc-covid-19.md
- prime-router/docs/schema_documentation/co-co-covid-19-redox.md
- prime-router/docs/schema_documentation/covid-19-redox.md
- prime-router/docs/schema_documentation/covid-19.md
- prime-router/docs/schema_documentation/fl-fl-covid-19.md
- prime-router/docs/schema_documentation/gu-gu-covid-19.md
- prime-router/docs/schema_documentation/la-la-covid-19.md
- prime-router/docs/schema_documentation/mt-mt-covid-19-csv.md
- prime-router/docs/schema_documentation/mt-mt-covid-19.md
- prime-router/docs/schema_documentation/nd-nd-covid-19.md
- prime-router/docs/schema_documentation/nm-nm-covid-19-csv.md
- prime-router/docs/schema_documentation/nm-nm-covid-19.md
- prime-router/docs/schema_documentation/oh-oh-covid-19.md
- prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
- prime-router/docs/schema_documentation/pa-pa-covid-19-redox.md
- prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
- prime-router/docs/schema_documentation/standard-standard-covid-19.md
- prime-router/docs/schema_documentation/strac-strac-covid-19.md
- prime-router/docs/schema_documentation/tpca-tpca-covid-19.md
- prime-router/docs/schema_documentation/tx-tx-covid-19.md
- prime-router/docs/schema_documentation/vt-vt-covid-19.md
- prime-router/docs/schema_documentation/waters-waters-covid-19.md
- prime-router/metadata/schemas/NM/nm-covid-19-csv.schema
- prime-router/metadata/schemas/covid-19.schema
- prime-router/src/main/kotlin/azure/BlobAccess.kt
- prime-router/src/main/kotlin/cli/main.kt
- prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
This PR fixes an issue where the `TranslationConfiguration` was being cached in some instances causing information from one out report to leak into another. 
- Removes the `hl7Config` property and always pulls the translation configuration directly from the report
> Fixes issue with translation config being cached

- prime-router/docs/schema_documentation/pa-pa-covid-19-redox.md
- prime-router/docs/schema_documentation/strac-strac-covid-19.md
- prime-router/metadata/schemas/PA/pa-covid-19-redox.schema
- prime-router/metadata/schemas/STRAC/strac-covid-19.schema
- prime-router/src/main/kotlin/cli/TestReportStream.kt
This PR fixes a bug where a report from STRAC would fail on many states. 
- Added mappings to the STRAC schema to provide required data elements
- Moved a mapping for PA from the STRAC schema to PA schema
Generated fake STRAC data for AZ. This data failed before because of missing elements. Now it succeeds.
```
rickhawes@MacBook-Pro-16 ~/P/p/prime-router (rick/fix-strac-to-allstates)> ./prime data --input result_files/fake-az-strac.csv --input-schema=strac/strac-covid-19 --route --output-dir routed_files
10:37:19.263 [main][1] INFO  ca.uhn.hl7v2.util.Home - hapi.home is set to /Users/rickhawes/Projects/prime-data-hub/prime-router/.
10:37:19.274 [main][1] INFO  ca.uhn.hl7v2.VersionLogger - HAPI version is: 2.3
10:37:19.277 [main][1] INFO  ca.uhn.hl7v2.VersionLogger - Default Structure …
```
> Make STRAC data feed work for all states

- operations/app/src/environments/prod/main.tf
This PR will rotate the keys used for our storage account and database to use the CDC-managed keys. All access policies and service profiles have already been deployed out.
- Flips the switch to rotate keys
- 
- #issue
- #issue
> Rotate Production Keys to Use CDC Keys

- prime-router/settings/organizations-local.yml
- prime-router/settings/organizations.yml
- prime-router/settings/prod/0014-la-doh.yml
- prime-router/settings/staging/0006-la-org-update.yml
- prime-router/src/main/kotlin/Report.kt
- prime-router/src/main/kotlin/TranslatorConfiguration.kt
- prime-router/src/main/kotlin/cli/FileUtilities.kt
- prime-router/src/main/kotlin/cli/main.kt
- prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
This PR fixes an issue where the processing mode code was not carried through for Louisiana for their file name format, and VT flagged that date type AOE questions should be listed as `DT` value type, not `CWE`. 
- Adds overload for translation config values to feed the file name creation
- Fixes logic for the `DT/CWE` value type for AOE questions
> Fixes issue with LA name not using 'prod' and wrong value type for AOE date questions for VT

- prime-router/docs/schema_documentation/co-co-covid-19-redox.md
- prime-router/docs/schema_documentation/covid-19-redox.md
- prime-router/docs/schema_documentation/pa-pa-covid-19-redox.md
- prime-router/metadata/schemas/covid-19-redox.schema
- prime-router/src/main/kotlin/Mappers.kt
- prime-router/src/main/kotlin/cli/TestReportStream.kt
This PR fixes #920 
- Added altValues to the base covid-19-redox schema to cover the 'X' value coming from SimpleReport.    I went ahead and added all the other values too - not clear if they will ever be used.
- Fixed a bug I saw in the mapper while messing with the CO data.
- minor cleanup to TestReportStream
None known at this time
- #920
> Fix for Redox bug, fix to Mappers bug, minor test cleanup

- prime-router/pom.xml
This PR removes the project's dependency on BinTray.com which shutting down on May 1. 
This dependency is no longer needed for KotlinX packages. I think our builds will start to fail on May 1 without this change. 
- KotlinX repository is removed and the MavenCentral is used for KotlinX packages. 
- #issue
- #issue
> BinTray shutdown

- prime-router/docs/schema_documentation/waters-waters-covid-19.md
- prime-router/metadata/schemas/WATERS/waters-covid-19.schema
This PR fixes two missing field names in the waters schema
no known risks
> fixed missing csvFields in waters schema

- prime-router/docs/azure_database_login.md
This PR adds documentation for authenticating to Postgres via Azure Active Directory.
* Resolves CDCGov/prime-devops#5
* Resolves #556
- Reviewers should follow the steps documented and verify they have access to postgres.
- Verify both the write and read users to ensure permissions are correct.
> Documentation for logging into Postgres via Active Directory

- prime-router/docs/releases/2021-04-26-release-notes.md
- prime-router/pom.xml
- prime-router/src/main/kotlin/serializers/CsvSerializer.kt
- prime-router/src/test/kotlin/serializers/CsvSerializerTests.kt
This PR upgrades the `csv-kotlin-jvm` package and updates the behavior of the CsvSerialization.
Dependabot submitted a PR to upgrade the `csv-kotlin-jvm` package. Unfortunately, this PR broke the build because a CsvSerialization test failed.  
After an investigation, it was found that the new version of the package had better CSV formatting checking, which had the side effect of throwing an exception when none was thrown before.  See [https://github.com/CDCgov/prime-data-hub/pull/834](https://github.com/CDCgov/prime-data-hub/pull/834)
- Handle the new exceptions thrown by the package
- Release notes: Since the API behavior has changed a little for malformed CSV submissions. 
- Think about what tests should be tried for this change
-
> CsvSerialization update

- prime-router/src/main/kotlin/azure/Authentication.kt
- prime-router/src/test/kotlin/azure/AuthenticationTests.kt
This PR fixes a bug discovered during a bug bash where the web receiver would not see the organization name. The cause turned out to be a general authorization bug in the setting API. 
- checkClaim had a bug due the _ vs - difference in organization naming
- Added tests for this condition
- [] Downloaded a file from `http://localhost:7071/api/download`?
- #976
> Bug Fix Settings Authentication Bug

- .github/workflows/release.yml
This PR updates the release build script to use Gradle.  Unfortunately it cannot be tested without a merge.
- Update the release build script to use Gradle
Issue #239
> 239 - Fix Release build script to use Gradle

- prime-router/build.gradle.kts
This PR adds a property to the manifest for the jar to prevent warnings after building the fat jar. 
- Adds property to the manifest for the jar
> Adds manifest property to suppress fat jar warning

- operations/app/src/modules/front_door/main.tf
This PR increases the timeout for the front door from 30 seconds to 90 seconds. Resolves #1003.
- Front door timeout increased from 30 seconds to 90 seconds, to allow for slow SFTP checks as described in #1003.
- Function app checked for a similar timeout setting. [The function app's default timeout is 5 minutes](https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#functiontimeout) and does not require a change.
- Kotlin checked for a similar timeout. Our Kotlin code relies on Azure's HTTP server and the timeout is configurable via the function app, hence no setting to change.
> Increase timeout for front door app

- prime-router/build.gradle.kts
This PR adds a dependency to the Gradle test task to the settings files in the metadata and settings folders.  A change to any of those files will trigger a rerun of the Gradle test task.  I tested this changing files at the different folder levels.
To test:
1. Run `./gradlew test` twice.  The second time it will not run the tests as everything is up to date.
2. Change one or more files in settings (a YML file) and/or metadata (any file) and rerun `./gradlew test` and verify the test run.
- add a dependency to the Gradle test task to the settings files in the metadata and settings folders
-  https://github.com/CDCgov/prime-data-hub/issues/1005
> 1005 - Added dependency to setting files for test task

- prime-router/build.gradle.kts
This PR adds the SQL scripts to the build artifact.
To test:
1. Build and package the baseline by running `./gradlew clean package`
2. Inspect the contents of the file `build/azure-functions/prime-data-hub-router/prime-router-0.1-SNAPSHOT.jar` e.g. open as a ZIP file) and verify the SQL files exist in the `db/migration` folder
- Add SQL scripts to build artifact
- #1024
> Removed SQL exclusion from build script

- .github/workflows/build_frontend.yaml
- .github/workflows/build_hub.yml
This PR moves the steps under the Verify Docs build job into the Built Router Job to get rid of the need to save and restore build artifacts, which takes a long time.  The result of the build is the same.    This brought down the build time from about 12mins to 7 mins.
Test:
1. Verify the dev build is successful and that it runs the same steps as before.
- Moved the verify docs steps into the build job.
- Removed the save/restore of build artifacts.
- Note there are no changes to the release build
- Added the Github Actions build scripts to the dependency of the DEV builds.
- Rearranged the steps to leave the packaging at the end, so if there is a failure it happens earlier in the build
- #1060
- Need to remove the required …
> 1060 - Improve DEV build times for verify router step

- prime-router/docs/getting_started.md
- prime-router/docs/openapi.yml
- prime-router/docs/releases/2021-05-12-release-notes.md
- prime-router/src/main/kotlin/azure/ReportFunction.kt
- prime-router/src/main/kotlin/cli/TestReportStream.kt
- added "topic" to the POST Json response for /api/reports
- updated the openapi.yml to reflect the added Json element
- added an echo of the topic (right after Id) in end2end test which will fail if it doesn't exist with an "Unable to properly parse response json" message
- fixed a documentation link in the getting started doc that was going to 404 page
- [Y] Tested locally?
- [Y] Ran `quickTest all`?
- [-] Ran `./prime test` against local Docker ReportStream container?
I am seeing end2end, merge, garbage tests failing on this branch, but also fails on the current master branch
- [N] Downloaded a file from `http://localhost:7071/api/download`?
Not sure of the credentials to use here
- [Y] Added tests?
Checking for "topic" in the response Json payload, if it doesn't exist it fails
- [Y] …
> Issue 1007: Adding topic to /api/reports Json response

- operations/app/src/modules/application_insights/main.tf
This PR improves the useful of PagerDuty alerts in both staging and production.
- Enables alerting for staging (Resolves CDCGov/prime-devops#1)
- Alerts in staging never notify on-call support and post to the Slack channel `#prime-reportstream-engineering`
- Tiers the exception alerts so not every exception triggers a full-blown response
- Exception counts under 10 per hour will be considered a low-priority incident and can be configured with a more lenient response policy
- Increase the frequency alerting conditions are checked from every 30 minutes to every minute
- Checking every 30 minutes was not useful, as it could be over 30 minutes before we'd be alerted
- Adds a description field to the alerts to the fix the Azure alerting displaying a generic `(Incident triggered via the API)` …
> PagerDuty Alerting Improvements

- prime-router/docs/releases/2021-05-12-release-notes.md
- prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
- prime-router/docs/schema_documentation/az-pima-az-covid-19.md
- prime-router/docs/schema_documentation/co-co-covid-19-redox.md
- prime-router/docs/schema_documentation/covid-19-redox.md
- prime-router/docs/schema_documentation/covid-19.md
- prime-router/docs/schema_documentation/fl-fl-covid-19.md
- prime-router/docs/schema_documentation/gu-gu-covid-19.md
- prime-router/docs/schema_documentation/la-la-covid-19.md
- prime-router/docs/schema_documentation/mt-mt-covid-19-csv.md
- prime-router/docs/schema_documentation/mt-mt-covid-19.md
- prime-router/docs/schema_documentation/nd-nd-covid-19.md
- prime-router/docs/schema_documentation/nm-nm-covid-19.md
- prime-router/docs/schema_documentation/oh-oh-covid-19.md
- prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
- prime-router/docs/schema_documentation/pa-pa-covid-19-redox.md
- prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
- prime-router/docs/schema_documentation/standard-standard-covid-19.md
- prime-router/docs/schema_documentation/strac-strac-covid-19.md
- prime-router/docs/schema_documentation/tpca-tpca-covid-19.md
- prime-router/docs/schema_documentation/tx-tx-covid-19.md
- prime-router/docs/schema_documentation/vt-vt-covid-19.md
- prime-router/metadata/schemas/covid-19.schema
- prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
This PR adds the facility name to PID-3-4-1. Massachusetts noted that for messages to pass their processing they want to have the testing facility name in PID-3-4-1. This should be a non-breaking change because it is *not* moving the facility name to a different field, it is just outputting it to an additional segment. 
- Adds PID-3-4-1 to the `hl7OutputFields` collection for facility name
- Adds PID-3-4-1 to the list of HD fields that can be truncated
> Adds facility name to PID-3-4-1

- prime-router/src/main/kotlin/azure/HistoryFunctions.kt
This PR removes the exception around CSV having missing field Testing_lab_name
- removed exception around CSV having missing field Testing_lab_name
- changed exceptions to info without stack trace
- #issue
- #issue
> Removed exception around CSV having missing field Testing_lab_name

- prime-router/settings/staging/0016-waters.yml
- prime-router/src/main/kotlin/JurisdictionalFilters.kt
This PR tweaks the default quality filter so its now:
```
// valid human and valid test
"hasValidDataFor(" +
"message_id," +
"equipment_model_name," +
"specimen_type," +
"test_result," +
"patient_last_name," +
"patient_first_name," +
"patient_dob" +
")",
// has minimal valid location or other contact info (for contact tracing)
"hasAtLeastOneOf(patient_street,patient_zip_code,patient_phone_number,patient_email)",
// has valid date (for relevance/urgency)
"hasAtLeastOneOf(order_test_date,specimen_collection_date_time,test_result_date)",
```
- see above
- 
- [Y] Did you check for sensitive data, and remove any? 
no issues known
> Tweak default quality filter to be more lenient

- prime-router/src/main/kotlin/Element.kt
- prime-router/src/main/kotlin/Schema.kt
- prime-router/src/main/kotlin/serializers/CsvSerializer.kt
When posting a report that has unexpected column headers or invalid/unexpected data, the messages provided in the Json response use internal field names that are confusing to the client posting the report. On missing fields, the message shows the CSV header but not the external/internal combination. After discussion on issue #1066 this format was decided:
`'<external field(s)>' ('<internal field>')`
- added a custom getter to create the desired field mapping
- replaced the internal field name in all the messaging to the field mapping from the custom getter
- added a findElementByCsvName to the Schema class to find the Element and access the custom getter for missing fields
*** Tests FAILED:  garbage *** (known issue)
*List GitHub …
> Improving error/warning messages in Json response to report submission

- README.md
- frontend/README.md
- operations/README.md
- prime-router/README.md
- prime-router/assets/csv-download-site/index__inline.html
- prime-router/assets/csv-download-site/login__inline.html
- prime-router/assets/email-templates/test-results-ready.html
- prime-router/assets/email-templates/test-results-ready__inline.html
- prime-router/docs/getting_started.md
- prime-router/examples/data-lineage/readme.md
- prime-router/examples/upload-fake-data/readme.md
This PR ... 
- Replaces mentions of "data hub" with "ReportStream" in readme files.
- Replaces same mentions in OG download site markup
- #569 
- #issue
> Update references to "Data Hub" in readmes

- prime-router/build.gradle.kts
This PR adds the creation of the fat jar as part of the package task.
To test:
1. Build the router using `./gradlew clean package`
2. Verify the fat jar was created (build/libs/prime-router-0.1-SNAPSHOT-all.jar)
3. Run the prime tool (e.g. `./prime -h`)
- adds the creation of the fat jar as part of the package task
- #1099
> #1099 Added fat jar to package task

- prime-router/settings/organizations-prod.yml
- prime-router/settings/prod/0022-nm-sftp-repoint.yml
This PR adds a yamlito to repoint NM SFTP server. 
- Adds yamlito
- Updates organizations-prod.yml
- #1086
> Adds yamlito for NM SFTP repoint

- prime-router/src/main/kotlin/azure/DownloadFunction.kt
- prime-router/src/main/kotlin/azure/HistoryFunctions.kt
- prime-router/src/main/kotlin/transport/BlobStoreTransport.kt
- prime-router/src/main/kotlin/transport/RedoxTransport.kt
- prime-router/src/main/kotlin/transport/SftpTransport.kt
- prime-router/src/test/kotlin/transport/RedoxTransportTests.kt
This PR changes all logging to:
- use context.logging.{info|warning} in the case of info and warning
- not print the stack trace on instances of info and/or warning 
Reviewer should verify that all logging using context.logging.log is for sever logging only
context.logging.{info|warning} is used in all other cases
- use context.logging.{info|warning} in the case of info and warning
- not print the stack trace on instances of info and/or warning 
- #issue
- #issue
> Change all logging at the info/warning level to not print the stack trace

- prime-router/docs/how-to-create-and-manage-receiver-ppks.md
- prime-router/src/main/kotlin/azure/CheckFunction.kt
- prime-router/src/main/kotlin/transport/SftpTransport.kt
Added a `sendfile` flag to the URL and the ability to `POST` a file to test sending a file via SFTP to the receiver.
- added `POST` to the end point
- checking for a `sendfile` parameter in the query string and generating a test file based on `GET` or `POST`
- added an `rm` function to the `SftpTransport` class to remove the uploaded file
- changed logging / messaging slightly to account for new logic
*** Tests FAILED:  garbage *** known issue
Potential for testers to bog down the end point trying to upload a large file. Also could inundate the end point with lots of small requests.
- #1008
- #issue
> Adding an SFTP send file option to the CheckFunction

- prime-router/build.gradle.kts
- prime-router/src/test/kotlin/CsvFileTests.kt
- prime-router/src/test/kotlin/DocumentationTests.kt
- prime-router/src/test/kotlin/ElementTests.kt
- prime-router/src/test/kotlin/FakeReportTests.kt
- prime-router/src/test/kotlin/FileSettingsTests.kt
- prime-router/src/test/kotlin/JurisdictionalFilterTests.kt
- prime-router/src/test/kotlin/MetadataTests.kt
- prime-router/src/test/kotlin/SimpleReportTests.kt
- prime-router/src/test/kotlin/TranslatorTests.kt
This PR adds a reference to the assertk fluent assertions library, and converts some tests to use the assertk library as examples.
Fluent assertions are easier to read and are chainable, so you're able to more clearly express the intent of your checks in your tests. An example from our own code is:
```kotlin
// this checks to see if the schema is not null, and if it has an element named "c"
assertThat(three).isNotNull().hasElement("c")
```
```kotlin
// this checks to see if the schema is not null, it has an element named "a" and the element has two csvFields attached
assertThat(schema).isNotNull().hasElement("a").csvFieldsHasSize(2)
```
In both of the cases above, I've not only made use of the built-in assertions provided by assertk, but I also added extension methods that let us build …
> Add fluent assertions to Project

- .github/workflows/build_hub.yml
- .github/workflows/release.yml
This PR uses a Github Actions plugin to publish the unit tests results to the Github Actions results, so we can see any errors that may pop up.  I encountered an issue that tests were failing only in Github due to environment differences and I needed to see what the problem was.  I wish you could see the STDOUT of the tests, but you can only see the assertion failure.  The results show in the jobs summary of the build and a comment is added to a PR if there are errors.  More details about the plugin at https://github.com/marketplace/actions/publish-unit-test-results
When there are errors ([Click here to see real errors](https://github.com/CDCgov/prime-data-hub/runs/2632215149?check_suite_focus=true)):
This is what the comment in the PR looks like.  It keeps updating the same comment with …
> Added publishing of unit test results to builds

- prime-router/src/main/kotlin/Report.kt
- prime-router/src/main/kotlin/Sender.kt
This PR updates the mime type for HL7 messages.
First, there is no HL7 mime type specified in the IANA list. There is an [old 2008 proposal by HL7](https://wiki.hl7.org/Media-types_for_various_message_formats) on what mime types to use, but it mentions registering them with IANA and that has not happened. The best source I can find is the HAPI library, which is already using some similar mime types as [documented here](https://hapifhir.github.io/hapi-hl7v2/hapi-hl7overhttp/specification.html). Based on that information and HAPI's implementation, I will recommend using application/hl7-v2 per their implementation in https://hapifhir.github.io/hapi-hl7v2/hapi-hl7overhttp/xref/ca/uhn/hl7v2/hoh/encoder/EncodingStyle.html#16
- Update the mime type
- #1068
> Updated mime type for HL7 messages

- prime-router/src/main/kotlin/Element.kt
- prime-router/src/main/kotlin/serializers/CsvSerializer.kt
This PR address issue #1061 where warning messages were suppressed in the Json response to the sender on submissions to /api/reports. 
- standardized the case on some error messages
- added any messages to the warnings collection if the checkForError failed regardless of the cardinality of the element
- #1061
- #issue
> Added warning messages on formatting/code failures

- .gitignore
- operations/app/src/environments/common/.terraform.lock.hcl
- operations/app/src/environments/dev/.terraform.lock.hcl
- operations/app/src/environments/dev/main.tf
- operations/app/src/environments/prod/.terraform.lock.hcl
- operations/app/src/environments/prod/main.tf
- operations/app/src/environments/staging/.terraform.lock.hcl
- operations/app/src/environments/staging/main.tf
- operations/app/src/environments/test/.terraform.lock.hcl
- operations/app/src/environments/test/main.tf
- operations/app/src/modules/front_door/main.tf
This PR redirects the old download site (`prime.cdc.gov`) to the new download site (`reportstream.cdc.gov`). Resolves #1179.
This change has been deployed to `staging.prime.cdc.gov` and can be reviewed in that environment.
- Redirects the path `/` and `/download` on `*prime.cdc.gov` to `reportstream.cdc.gov`
- This preserves API functionality on `prime.cdc.gov`
- Adds some logic to handle the dev environment, which does not have an HTTPS cert
- Migrates the Terraform Azure provider to `v.2.61.0` due to a breaking change Microsoft made on April 9th
- Followed the migration guide provided by Terraform here: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/2.58.0-frontdoor-upgrade-guide
- Remove the terraform lock file from `.gitignore` so we can more easily …
> Redirect to the new download site

- prime-router/docs/releases/2021-06-01-release-notes.md
- prime-router/src/main/kotlin/JurisdictionalFilters.kt
- prime-router/src/main/kotlin/Metadata.kt
- prime-router/src/test/kotlin/JurisdictionalFilterTests.kt
This PR changes the default quality filter to add CLIA validation.  Previously I had assumed the code in Element.kt was validating CLIAs, but it does not.
The other option would be to put the validation code on CLIAs into Element.kt, and zero-out an invalid CLIA to empty string.   I was reluctant to do that, as I wasn't sure whether there would be strange downstream confusion/errors if empty CLIAs started leaking into state data. 
So currently, nothing in our code ever change or zeros-out a CLIA, ever.   However, we will refuse to send data to the States if the CLIA is invalid.  That's this PR.
- [N] Does logging contain sensitive data?  
- [Y] Includes a summary of what a code reviewer should verify?
- [Y] Updated the release notes?
no known issues
> added CLIA validation to the quality filter

- prime-router/docs/schema_documentation/hhsprotect-hhsprotect-covid-19.md
- prime-router/docs/schema_documentation/waters-cue-covid-19.md
- prime-router/docs/schema_documentation/waters-direct-covid-19.md
- prime-router/docs/schema_documentation/waters-safehealth-covid-19.md
- prime-router/docs/schema_documentation/waters-waters-covid-19.md
- prime-router/metadata/schemas/WATERS/cue-covid-19.schema
- prime-router/metadata/schemas/WATERS/direct-covid-19.schema
- prime-router/metadata/schemas/WATERS/safehealth-covid-19.schema
- prime-router/metadata/schemas/WATERS/waters-covid-19.schema
- prime-router/metadata/schemas/hhsprotect/hhsprotect-covid-19.schema
- prime-router/metadata/valuesets/covid-19.valuesets
- prime-router/settings/organizations-local.yml
- prime-router/settings/organizations.yml
- prime-router/settings/prod/0026-hhsprotect.yml
- prime-router/settings/staging/0020-hhsprotect.yml
- prime-router/src/main/kotlin/DocumentationFactory.kt
- prime-router/src/main/kotlin/JurisdictionalFilters.kt
- prime-router/src/main/kotlin/Mappers.kt
- prime-router/src/main/kotlin/Metadata.kt
- prime-router/src/main/kotlin/Translator.kt
- prime-router/src/test/kotlin/JurisdictionalFilterTests.kt
- prime-router/src/test/kotlin/MapperTests.kt
- Wrote a new `hhsprotect/hhsprotect-covid-19` schema, that generally mimics what Waters sends.  Does not send redundant text versions of code columns.  Added a couple columns.  See that schema for details.
- Wrote new `hash(column-name1, column-name2) `mapper, which generates a sha-256 digest of the concatenation table values.
- This is now used generate hashes identical to Waters, so that HHSProtect can detect duplicates.   Only doing this for patient_id right now - the patient_id we send to HHSProtect is the hashed version, not the real one.
- For incoming waters, direct data, and outgoing HHSProtect, use YES,NO,UNK instead of Y,N,UNK
- Delivery codes for ethnicity are done per HHS standard (TODO: fix this in covid-19.schema globally)
- Added detailed logging to the qualityFilters. …
> changes to support direct submission to ReportStream, etc

- operations/app/src/environments/prod/main.tf
- operations/app/src/environments/staging/main.tf
- operations/app/src/modules/database/main.tf
- operations/app/src/modules/database/variables.tf
- operations/app/src/modules/front_door/main.tf
- operations/app/src/modules/front_door/variables.tf
- operations/app/src/modules/prime_data_hub/main.tf
- operations/app/src/modules/prime_data_hub/variables.tf
This PR deploys Metabase to our staging environment, per request from @jimduff-usds.
- Flips the switch to enable a Metabase deploy in staging.
- Refactors the Metabase deployment configuration so there is only one boolean that controls the entire Metabase deployment.
- The initial deployment will leave Metabase in an un-configured state. We’ll need to quickly configure Metabase after deployment and add authentication.
- Configure Metabase after deployment. Not sure what goes into this. Perhaps we can restore the production Metabase database into staging to preserve our configuration?
- Due to the Palo Alto test, I don’t have a working Azure development environment, so I’m unable to experiment prior to deployment to staging.
> Deploy Metabase to staging

- operations/app/src/modules/database/main.tf
This PR resolves an issue where Terraform tries to scale down the database size after the `auto_grow` setting increases our database.
- Adds the the `storage_mb` field to the ignored changes list
- This prevents Terraform from attempting to scale down the database after its grown
- #issue
- #issue
> Ignore Database Size in Terraform

- prime-router/metadata/file_name_templates/file-name-templates.yml
- prime-router/src/main/kotlin/Report.kt
This PR changes the default file name format back to the classic style until we can communicate the change to states
- updates the name formats yaml to use the old style
- updates the default style in the `Report` class to match the old style
> Changes the default file name format back to the classic style until we can communicate the change to states

- prime-router/build.gradle.kts
This PR correctly sets the environment variables when running the CLI from Gradle.  The previous way completely replaced the environment provided by the process.  This new way just adds more variables.
To test:
Run the following commands and verify that the output is using the HashicorpVaultCredentialService and not the MemoryService.
`export $(cat ./.vault/env/.env.local | xargs)`
`./gradlew primeCLI --args='create-credential --type=UserPass --persist=IGNORE--CSV --user foo --pass pass'`
The output will look like:
10:13:12.888 [main][1] INFO  gov.cdc.prime.router.credentials.**HashicorpVaultCredentialService** - CREDENTIAL UPDATE: ...
- Set environment variables correctly in Gradle.
- #1282
> 1282 Fixed CLI environment overwrite issue when using Gradle

- operations/app/src/modules/storage/main.tf
This PR resolves #1287.
- Require TLS 1.2 on the main storage account
- Other storage accounts had this setting enabled, but we never enabled it for the main storage account
- Disallow public containers to be created in our storage account containing PHI/PII
- This setting prevents any storage container in the future created under this storage account from being granted public access
- We currently have no containers within this storage account with public access; we have a separate public-facing storage account
- This will ensure we can't accidentally make our PHI/PII container public
- [N/A] Tested locally?
- [N/A] Ran `quickTest all`?
- [N/A] Ran `./prime test` against local Docker ReportStream container?
- [N/A] Downloaded a file from `http://localhost:7071/api/download`?
- [N/A] …
> Enforce TLS 1.2 and disable public access on main storage account

- prime-router/src/main/kotlin/azure/HistoryFunctions.kt
This PR changes the ID token validator back to an access token validator because we're currently not passing the client ID in to the jwt token.
> Reverts the id token validator to be an access token validator

- prime-router/settings/prod/0031-oh-la-la.yml
- prime-router/settings/prod/0031-vt-la.yml
- prime-router/settings/staging/0028-tn-mi.yml
This PR submits setting changes for new receivers for secondary data to OH, LA, and VT.
- No code changes
- The new receivers were created by doing a `get` of the existing `elr` receivers in Prod and only these changes were made:
-- the name of the new receiver is `elr-secondary`
-- changed the `reverseTheQualityFilter` flag to `true`
-- the sftp directory is changed.
MUST tell LA, VT, and OH we are doing this before the command is run in PROD.
I did not run any tests below because there are no code changes.   however, I uploaded the receivers into my local reportstreeam just to make sure there were no syntax errors.  It worked.
- no issues known
- 
- #issue
- #issue
> Secondary feeds for OH, LA, VT

- prime-router/src/main/kotlin/azure/ReportFunction.kt
This PR validates in the SendReport function if the associated schema of the sender is valid, and returns an error in the canonical json payload if necessary.
@jimduff-usds I've talked with Tom about adding extra tests for this based on the works he's doing, but he isn't planning to push anything related to that anytime soon, so maybe it's preferable to send this wo tests.
- prime-router/src/main/kotlin/azure/ReportFunction.kt -> schema validation
- #issue
- #issue
> add schema existence validation to SendReport

- prime-router/settings/prod/0033-ca-quality-filter.yml
- prime-router/settings/staging/0030-ca-quality-filter.yml
This PR adds yamlitos that update the quality filter for CA and Santa Clara that removes the CLIA quality filter check
- Adds a yamlito for production that removes the CLIA format check from the default quality filter
- Adds a yamlito for staging that removes the CLIA format check from the default quality filter
- #1380 
- #1381
> Adds yamlitos for CA quality filter change

- operations/README.md
- prime-router/docs/playbooks/shutdown.md
This PR adds a playbook detailing various options to stop traffic to PRIME resources.
- Adds playbooks/shutdown.md
N/A
N/A
N/A
- #issue
- #issue
> Add playbook for shutting down resources

- prime-router/docker-compose.yml
- prime-router/src/main/kotlin/azure/BlobAccess.kt
This PR ignores an error that the Blob already exists.  This is not really an error for us, but can occur when concurrent calls are made to the API and those calls all try to create the Blob store at the same time.
- ignore blob already created error
#1471
> 1471 Ignore errors that the blob already exists

- prime-router/docs/schema_documentation/direct-cue-covid-19.md
- prime-router/docs/schema_documentation/direct-direct-covid-19.md
- prime-router/docs/schema_documentation/direct-imagemover-covid-19.md
- prime-router/docs/schema_documentation/direct-inbios-covid-19.md
- prime-router/docs/schema_documentation/direct-safehealth-covid-19.md
- prime-router/docs/schema_documentation/hhsprotect-hhsprotect-covid-19.md
- prime-router/metadata/schemas/direct/direct-covid-19.schema
This PR adds a missing testId header into the `direct` family of schemas.
> made testId (internally as message_id) visible in all direct schemas

- prime-router/build.gradle.kts
- prime-router/gradle.properties
This PR adds the smoke test to the Gradle script.  I also refactored the CLI portion a bit to be able to create other tasks to call the CLI without having to copy the full CLI task code.  I tried once again to split the gradle script, so it is not a large file, but Gradle does not have the ability to do that.  :( 
To test:
Run `./gradlew testSmoke'
- Added testSmoke task
- A bit of refactor to make future CLI tasks simpler to make.
#1384
> 1384 Added smoke test to gradle script

- prime-router/docker-compose.yml
This PR removes an invalid and expired key from the development docker-compose file.
- Comment out `SENDGRID_API_KEY` from `./prime-router/docker-compose.yml`; the value for this variable was invalid (not usable) anyway. We are leaving the environment variable in place (albeit commented out) to indicate that this is a value that can/should be set in running environments.
Note: there are some whitespace fixed included here as well (in accordance with editorconfig)
> Remove invalid/expired key from docker-compose

- prime-router/docs/signing-commits.md
This PR adds a documentation file on how to set up your machine to sign commits, since that's a thing we do now.
> Documenting how to set up your device to sign commits

- prime-router/build.gradle.kts
- prime-router/prime
- prime-router/quick-test.sh
This PR reverts the invocation of gradlew in quick-test.sh instead of using build.sh
> Fix quicktest to no longer use the build.sh script

- prime-router/src/main/kotlin/Report.kt
- prime-router/src/main/kotlin/azure/BlobAccess.kt
- prime-router/src/test/kotlin/azure/BlobAccessTests.kt
This PR fixes the filenames uploaded via SFTP to not have the blob folders.  I searched all the code for any other places that the blob URL was being used besides SFTP and found the BlobTransport was affected too.
To test:
1. Build and run the API.
2. Run `./gradlew testend2end` and verify in the build/sftp folder that the filenames for the received data do not contain the blob folders.
- Fixed SFTP so filenames do not have the blob folders
- Updated blob copy method to use proper filename.  This affects the BlobTransport.
- #1678
> 1678 Fixed SFTP filenames to not have blob folders

- .github/workflows/build_hub.yml
- .github/workflows/release.yml
This PR disables the publishing of test results for PRs that are not within the context of this repo (e.g. dependabot).  The issue is [described in this article](https://github.blog/changelog/2021-02-19-github-actions-workflows-triggered-by-dependabot-prs-will-run-with-read-only-permissions/) and it results in dependabot not being able to publish the test results for the build to the PR and breaking the build.  This change implements the [recommended check as described here](https://github.com/EnricoMi/publish-unit-test-result-action#support-fork-repositories-and-dependabot-branches) since the publishing is really an optional thing.
Test: 
1. Verify the build completes successfully and that the unit and integration tests are published.
Note that we will need to merge this change in to …
> 1686 Only publish test results when in our repo context

- prime-router/build.gradle.kts
- prime-router/src/main/kotlin/azure/BlobAccess.kt
This PR fixes a bug in the BlobCopy method that was introduced as part of #1678.  It was using the incorrect call to get the filename.
Test:
1. Run the waters test `gradle primecli --args="test --run waters"` and verify the test passes.
2. Look at the container output and verify the filename of the blob copy shows as expected.
- Use correct URL to get the filename
- Minor updates to gradle file to not show usage of primeCLI.
#1678
> 1676 Fixed incorrect filename for blob copy

- .github/workflows/build_frontend.yaml
- .github/workflows/build_hub.yml
This PR allows our CI GitHub Action to run for forks.
Originally we had disabled this because our CI build required the use of some secrets, but those limitations have since been removed.
> Enable CI for Forks

- prime-router/prime
This PR changes the prime script to build the fatjar that is required to run the tool if gradlew is detected.  Note that the slim jar does not work locally as the Azure functions lib folder does not include certain runtimes.
To test:
1. Delete the jars from build/libs
2. From the CLI like `./prime test --run waters` and verify the fatjar is generated before running the CLI.
3. Run `./prime test --run waters` again and verify the fatjar is not generated again.
- Updated the prime script to generate the fatjar IF gradlew is available.
-
Not related to an issue
> Enhanced prime script to build fatjar if possible

- prime-router/src/main/kotlin/FileNameTemplate.kt
- prime-router/src/main/kotlin/Report.kt
- prime-router/src/test/kotlin/FileNameTemplateTests.kt
This PR fixes an issue where the `uuid` file name element was always returning a random UUID instead of the report ID
- Adds logic to pass in the report Id 
- Adds logic to output the report's ID from the element
- Adds a test
- #1419 
- #issue
> Mo/report UUID mismatch

- prime-router/build.sh
This hotfix makes sure that the result (i.e. Return Code/RC) returned by the `build.sh` script is the return code from the invocation of the docker run.
As return code of the `build.sh` script, we (erroneously) used the return code (`$?` is the return code from the immediately preceding command in bash) as returned by the invocation of the call to `ensure_build_dir` whereas we _should_ have picked up the RC immediately after the call to the `docker run` invocation.
Thus the script erroneously reported success (i.e. a return code of `0` instead of non-zero, and `1` in specific) because while the `docker run` invocation correctly reported failure, the value we picked up was the return code of `ensure_build_dir` which is always `0` (i.e. success). This meant that the build pipelines sees …
> Fixing the build not picking up build failures from build.sh

- .github/workflows/release.yml
This PR adds a concurrency flag to each deployment environment, to ensure that additional deployments are queued while an active deployment is in progress.
See: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idconcurrency
> Prevent multiple deployments occurring at the same time

- .environment/gitleaks/gitleaks-config.toml
- .environment/gitleaks/run-gitleaks.sh
- .github/workflows/run_gitleaks.yaml
This PR changes how we run gitleaks on a schedule and fixes #1760 (linked issue for auto-close).
Scanning between commits is not reliable (yet) when there are multiple branches involved. When it's all in a single branch, then the tool can easily figure things out, but as soon as you have multiple, the tool ends up scanning an undeterministic subset of the entire history.
The fix for this is to scan since an LKG (Last Known Good) that is a date instead.
This PR introduces 2 new runmodes to the run-gitleaks script:
- `--since <datespec>`: scans commits that are created on or after this date
- `--depth <int>`: scans the last <int> commits from `HEAD` backwards
The `run_gitleaks.yml` GitHub action has been modified to use the `--since` version which now records an LKG date of the last time we …
> GitHub run_gitleaks Action Fix

- frontend/src/_includes/details_report.liquid
- frontend/src/js/prime-web-receiver-pre.js
- prime-router/src/main/kotlin/Report.kt
- prime-router/src/main/kotlin/azure/DatabaseAccess.kt
- prime-router/src/main/kotlin/azure/HistoryFunctions.kt
This PR removes the call to get the file header when listing the files for an organization to speed up the performance of the UI.
- Removes the call to get the file header in order to speed up the listing of downloadable files in the UI
- #issue
- #issue
> Speed improvements for files in UI

- prime-router/docs/azure_database_login.md
This PR updates our DB access docs.
- Example uses read-only connection
- Add to example a one-liner for setting and parsing the access token
- Adds notes about session expiration
- Fixes script syntax highlighting
> Improved DB access docs

- .environment/gitleaks/gitleaks-config.toml
Adding a gitleaks exclusion for a commit (efb0f02fce90cd7117ff1b9e092afdd6c2a06de0 - not yet pushed up, will modify this code when it is) that is coming up... The gitleaks documentation contains some "stuff not to do" examples which obviously trip a gitleaks rule
Note that the file referenced in the exclusion is added by the commit, so it's not yet there...
> gitleaks: adding exclusion for commit that is about to come

- .environment/gitleaks/gitleaks-config.toml
This PR fixes the 2021-08-10 gitleaks run using a robust pattern that tripped for `aad_object_keyvault_admin` due to the presence of `key` in the name.
> gitleaks: fix 2021-08-10 run

- .github/workflows/run_gitleaks.yaml
This PR adds outputting of the `gitleaks.log` that is generated by the gitleaks to the nightly `run_gitleaks.yaml` workflow. This log file does **NOT** contain the violations themselves, but it does contain metrics about the violations, thus telling us how _bad_ the run was:
- scan duration
- commits scanned
- violation count
> gitleaks workflow: output the non-sensitive log after a gitleaks run

- .gitignore
- prime-router/docker-compose.yml
- prime-router/docs/getting-started/java-profiling.md
- prime-router/docs/getting_started.md
- prime-router/local.settings.json
This PR enables JMX in the local report stream and exposes the JMX port 9090 to be used by JConsole or Mission Control.  Also added some documentation about profiling.  Note this only works locally and will not open ports in staging or prod.
Test:
1. Use Mission Control or JConsole to connect to the JVM's JMX port.
- Enabled JMX locally to allow for profiling.
> Enabled local JMX port and documented use of Mission Control

- prime-router/docs/schema_documentation/direct-cue-covid-19.md
- prime-router/metadata/schemas/direct/cue-covid-19.schema
- prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
This PR moves Cue out of Training mode.  Also fixed a minor bug in TestReportStream
**None apply.**
- Threat _T_, which could be achieved by …
> Move cue out of Training mode

- prime-router/docs/getting_started.md
This PR changes `docker compose` to `docker-compose` in the getting started document.  This is relates to PR https://github.com/CDCgov/prime-reportstream/pull/1843, but it was merged before completing all requested changes.
> Changed to use docker-compose

- prime-router/settings/organizations.yml
- prime-router/src/main/kotlin/TranslatorConfiguration.kt
- prime-router/src/main/kotlin/azure/WorkflowEngine.kt
- prime-router/src/main/kotlin/cli/FileUtilities.kt
- prime-router/src/main/kotlin/cli/ProcessDataCommands.kt
- prime-router/src/main/kotlin/cli/tests/Hl7Tests.kt
- prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
- prime-router/src/main/kotlin/cli/tests/WatersAuthTests.kt
- prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
- prime-router/src/test/kotlin/azure/WorkflowEngineTests.kt
- prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
- prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
This PR adds a property to the translation configuration to chance the CLIA number for testing completed outside the state of the receiver.
- Property added to HL7 Configuration (cliaForOutOfStateTesting) accepting a string value
- Reviews the StateCode set in the organizations.yml for the receiver against the Performing Organization State (OBX-24.4) value. When those values are different, the replacement CLIA is set only in MSH-4.2.
- Set the property for California's primary feed and secondary feed
- #1828 
- #1788
> Bg 1828 ca onboarding

- operations/app/src/modules/metabase/main.tf
This PR enables AppInsights for Metabase. It turns out we had tried to enable it before, but we were missing some environment variables to make it happen.
There has also been Terraform formatting applied to the file.
> Enable AppInsights for Metabase

- .github/workflows/prepare_deployment_branch.yaml
This PR introduces a GitHub Action that prepares some logistics in anticipation of the scheduled deployments; these deployments happen on Tuesdays and Thursdays. The GitHub Action runs ahead of these days on the following schedule:
- Monday at 16:00 UTC (noon ET)
- Wednesday at 16:00 UTC (noon ET)
When the Action runs, it does the following:
1. A new branch called `deployment/<DEPLOYMENT_DATE>` is spun off from `master` (note that the deployment date is the date of the deployment, not the date of the branching)
2. A new PR (using the [k3rnels/pr-update](https://github.com/marketplace/actions/pr-update) action) is created and tagged with `chore`, `deployment`, `devops` to go from `deployment/<DEPLOYMENT_DATE>` (and thus effectively that snapshot from `master`@noon on the snapshot day) into …
> Add GitHub Actions for automatic deployment branches (closes #1851)

- prime-router/settings/organizations.yml
- prime-router/settings/prod/0040-hhsprotect.yml
- prime-router/settings/staging/0039-hhsprotect.yml
This PR adds Reddy Family Medical Clinic in the jurisdictional filter for HHSProtect.
Modified filter in organizations.yml
Added yamlitos for staging and prod
- #1708 Onboarding of Reddy Family Medical Clinic sender
> Add Reddy FMC to the HHSProtect jurisdictional filter

- prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
- prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
This PR makes sure the HL7 serializer is not generating a false warning about processing an empty message for batch payloads.  The problem was that the serializer would loop through the initial batch segments and generate a string with "\r\r" due to the appending of \r to the nextMessage variable.  The serializer would then generate a warning that it could not parse an empty message when it encountered the first true HL7 message of the batch message.  
- Not parse a blank string.
- #1902
> 1902 Do not process blank strings generated from batch submission headers

- .environment/terraform-fmt/run-terraform-fmt.sh
This fixes #1977 by only running the terraform hook if `git status --porcelain` reports files with `.tf` extension. If no such files come back from that command, then the hook tells you that it will skip the check (and reports success). If such files _were_ changed then the script will report the return code from the (containerized) `terraform fmt` invocation as it did before.
This closes #1977
> Fix for #1977: Only run terraform format check hook when there are terraform changes

- operations/app/src/modules/function_app/main.tf
- prime-router/host.json
This PR flips some Function App settings to enable App Insights profiling.
Reference:
* https://docs.microsoft.com/en-us/azure/azure-monitor/app/monitor-functions#how-to-enable-distributed-tracing-for-java-function-apps
* https://docs.microsoft.com/en-us/azure/azure-monitor/app/java-in-process-agent
* https://docs.microsoft.com/en-us/azure/azure-functions/functions-host-json#applicationinsights
Related to #1827
> 1827 Turn on App Insights profiling

- prime-router/metadata/tables/LIVD-SARS-CoV-2-2021-04-28.csv
This PR adds an alias for the QuickVue Rapids test kit that doesn't currently exist in the LIVD table but SimpleReport is using as a test type.
> Adds an alias for the QuickVue Rapids test kit

- frontend-react/public/index.html
A quick fix to get staging working again (and to see if there are other URLs that break once this is fixed).
Always allows access to https://staging.prime.reportstream.cdc.gov/api even in production. 
This needs to be fixed in a better way, but having it be runtime based versus configuration based is problematic.
see `getBaseUrl()`
related to: #2051
> Quick fix to get staging working with `Content-Security-Policy`

- frontend-react/.env
- frontend-react/.env.development
- frontend-react/.env.production
- frontend-react/.env.staging
- frontend-react/public/index.html
`https://prime.cdc.gov/api` ONLY matches the `api` page... just that page. 
`https://prime.cdc.gov/api/` matches the api path and all pages under that path.
Right now the `https://staging.reportstream.cdc.gov/api/` and `https://staging.prime.cdc.gov/api/` are hard coded in the "Content-Security-Policy" because `.env.staging` isn't being used. 
```html
<meta
http-equiv="Content-Security-Policy"
content="default-src 'self';
script-src 'self'
https://hss-prime-okta.com
https://global.oktacdn.com
https://www.google-analytics.com
https://*.in.applicationinsights.azure.com;
style-src 'self' 'unsafe-inline'
https://global.oktacdn.com
https://cdnjs.cloudflare.com;
frame-src 'self' https://hhs-prime.okta.com;
img-src 'self' https://hhs-prime.okta.com https://reportstream.cdc.gov data: ; …
```
> "content security policy" Path change from `/api` to `/api/`

- prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
This PR fixes a bug that occurs when when cliaForOutOfStateTesting is set to true. The codes checked the value for testing lab state. But that value can be blank. In that case the ordering facility state should be used.
- Checks if testing lab state is blank
- if testing lab state is blank the ordering facility state is retrieved
> Fix bug with out of State CLIA translation property

- operations/app/src/modules/common/private_endpoint/main.tf
- operations/app/src/modules/network/old-vnet.tf
This PR fixes our VNET peering between East and West locations. The West VNET was missing a return peering to the East VNET. In addition, the West VNET needed registered DNS records on private endpoints to support DNS lookups.
> Fix VNET peering

- prime-router/src/main/kotlin/cli/CredentialsCli.kt
- prime-router/src/main/kotlin/credentials/Credential.kt
- prime-router/src/main/kotlin/transport/SftpTransport.kt
This PR adds the ability for our PEM and PPK file auth to also accept a user password in addition to the file password. This is used by DE as part of what is called "partial authentication," where you need to authenticate with both a key file AND a password. Authenticating with either individually is not supported. Our existing code base did not support this.
- Adds a user pass property for both the PEM and PPK file types and logic to chain the auth 
- #issue
- #2175
> Adds user password option for the two key file auths

- prime-router/src/main/resources/db/migration/V17__add_sender_and_testkit_data_to_metadata_table.sql
This PR adds sender ID and testkit information to the metadata table.
Test steps:
1. Update your database by running `./gradlew package`. This will update the DB and regenerate the Java database files.
2. Run ReportStream
3. Run the smoke tests to generate data - `./gradlew testsmoke`
4. Inspect the covid_result_metadata table and verify the sender_id, test_kit_name_id and test_performed_loinc_code columns are present.
5. Inspect the sender_id data and verify that the sender ID is populated. 
I tested this further as follows:
1. Database in V16, ran data, updated to V17, verified SQL populates existing rows with sender ID.
2. Database in V16, no data, updated to V17, ran data and verified data inserted to table and sender ID added when running with code for #1913
- Added sender_id, …
> 1913 Added sender and testkit data to metadata table

- operations/app/src/modules/common/private_endpoint/main.tf
- operations/app/src/modules/container_registry/data.tf
- operations/app/src/modules/container_registry/main.tf
- operations/app/src/modules/database/data.tf
- operations/app/src/modules/database/main.tf
- operations/app/src/modules/function_app/candidate_slot.tf
- operations/app/src/modules/function_app/data.tf
- operations/app/src/modules/function_app/main.tf
- operations/app/src/modules/key_vault/data.tf
- operations/app/src/modules/key_vault/main.tf
- operations/app/src/modules/metabase/data.tf
- operations/app/src/modules/metabase/main.tf
- operations/app/src/modules/sftp_container/data.tf
- operations/app/src/modules/sftp_container/main.tf
- operations/app/src/modules/storage/candidate_slot.tf
- operations/app/src/modules/storage/data.tf
- operations/app/src/modules/storage/main.tf
This PR rolls out the Palo Alto egress firewall in all environments outside of production.
- Adds private endpoints to the Palo Alto VNET for the database, storage accounts, and Key Vaults
- These private endpoints are in addition to our existing private endpoints
- This ensures that the resources are connected to both VNETs
- Adds firewall rules to the container registry and storage accounts to allow connections from the Palo Alto VNET
- This is in addition to our existing VNET firewall rules, so both VNETs can connect
- Switches the Function App to the Palo Alto VNET in non-production environments
- This will restart the Function App when deployed
- Switches Metabase to the Palo Alto VNET in non-production environments
- This will restart Metabase when deployed
- Switch the SFTP …
> Palo Alto: Lower Environments

- prime-router/metadata/tables/zip-code-data.csv
> rhood/2240 Add zip codes

- prime-router/docs/playbooks/db_flyway_repair.md
- prime-router/src/main/resources/db/migration/V17__add_sender_and_testkit_data_to_metadata_table.sql
This PR removes an update statement that was running too slowly to run inside flyway.
Users must run `./gradlew flywayRepair` before doing a build.
Test Steps:
1. Run run `./gradlew flywayRepair` before doing a build.
2. Then run run `./gradlew clean package`
3. You should get a clean build.
- #2263 
- Don't forget to run `./gradlew flywayRepair` before attempting a build.
> modified V17 to remove slow update sql

- prime-router/src/main/kotlin/azure/HistoryFunctions.kt
- prime-router/src/main/kotlin/azure/WorkflowEngine.kt
- prime-router/src/main/kotlin/cli/tests/WatersAuthTests.kt
- prime-router/src/main/kotlin/transport/RedoxTransport.kt
This PR adds flag that stops the history functions from downloading the blob body.
- Adds flag to remove the call to download the blob body
-
- #issue
> Remove call to get blob body

- operations/app/src/modules/common/private_endpoint/main.tf
- operations/app/src/modules/common/private_endpoint/variables.tf
- operations/app/src/modules/database/main.tf
- operations/app/src/modules/function_app/candidate_slot.tf
- operations/app/src/modules/function_app/main.tf
- operations/app/src/modules/key_vault/main.tf
- operations/app/src/modules/metabase/main.tf
- operations/app/src/modules/network/main.tf
- operations/app/src/modules/sftp_container/main.tf
- operations/app/src/modules/storage/candidate_slot.tf
- operations/app/src/modules/storage/main.tf
This PR fixes multiple private endpoints overwriting DNS records within the same resource group.
Azure [only allows one private DNS zone per resource group](https://dev.to/kaiwalter/using-azure-private-links-and-private-dns-zones-with-globally-distributed-resources-4ce3), so when using multiple private endpoints in the same resource group, only one can register a DNS record against a private DNS zone. Allowing them all to registered a DNS record creates unpredictable results.
> fix: DNS records cannot be registered against multiple private endpoints

- frontend-react/.env.development
The `REACT_APP_PUBLIC_URL` variable is used to build the path the manifest file. It needs to be set to empty for local dev setup.
This small PR also tests my setup for signing git commits.
> Add missing `REACT_APP_PUBLIC_URL`

- prime-router/docs/schema_documentation/az-pima-az-covid-19.md
- prime-router/metadata/schemas/AZ/pima-az-covid-19-csv.schema
This PR adds a couple values to the alt value set for device_type in Pima schema.
Tested by running similar data thru and did not see the exception.
Test Steps:
1. Generate fake pdi data for AZ, and set the equipment_model_name to both unknown (not in Pima alt valueset) and good values.
- The rest of #2354 - this is only a partial fix for 2354.
> added two new equipment_model_name to Pima Schema as temp fix

- prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
- prime-router/docs/schema_documentation/experity-experity-covid-19.md
- prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
- prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
- prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema
- prime-router/metadata/tables/zip-code-data.csv
- prime-router/metadata/valuesets/sender-automation.valuesets
- prime-router/settings/organizations.yml
- prime-router/settings/prod/0046-all-in-one-health-ca.yml
- prime-router/settings/staging/0046-all-in-one-health-ca.yml
This PR adds a Schema for All-In-One-Health onboarding.  Note, there is no parent/child schema setup for this Sender, so this Schema is stored in a new folder for non-standard one-off schemas under /non-standard/.
Test Steps:
1. This is still in testing, so testing will continue in Staging.
- Adds the Schema for the Sender All-In-One-Health.
- Added All-In-One-Health to the …
> rhood/2350 Onboarding All-In-One-Health

- frontend-react/src/components/ReportStreamHeader.tsx
In `ReportStreamHeader` the `PrimaryNav` was missing expand/collapse functionality
| Collapsed | Expanded |
|-----|-----|
| ![image](https://user-images.githubusercontent.com/87096393/135007532-7f3baf61-7dd5-4303-a875-eb50fbdf2aea.png) | ![image](https://user-images.githubusercontent.com/87096393/135007551-2a1d6332-e54f-44ce-9cc8-999851634acc.png)|
> Fix nav on mobile 

- frontend-react/src/webreceiver-utils.ts
This PR retrieve sender organization information when sender name is 'default'
Test Steps:
pre-req: be part of a sender group in Okta that has a sender name of "default", i.e. "DHSender_all-in-one-health-ca"
1. log in to ReportStream
2. browse to /upload
3. that's it! you should see organization data coming through and the page shouldn't be blank
4. bonus: join a group in Okta like …
> sender-tools/2384: retrieve sender organization information when sender name is 'default'

- .github/workflows/build_hub.yml
- prime-router/src/main/kotlin/Translator.kt
- prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
This PR ...
Adds linting and other checks to the CI checks and moves some checks into parallel jobs.
Test Steps:
1. Check jobs run in this PR e.g. https://github.com/CDCgov/prime-reportstream/pull/2220/checks?check_run_id=3624351115
- Adds klint linting check to CI checks
- Moves docs check and linting into parallel jobs (results in longest check running in roughly 11min instead of 16min, and failing much faster)
- Adds Smoke tests
> Running more in CI

- frontend-react/src/pages/Upload.tsx
- prime-router/src/main/kotlin/ElementErrors.kt
- prime-router/src/main/kotlin/ResultDetail.kt
- prime-router/src/main/kotlin/azure/ReportFunction.kt
- prime-router/src/main/kotlin/serializers/CsvSerializer.kt
When there are error and/or warning during CSV uploading, each one is listed in the UI. This can become verbose and unfriendly to the end user. The solution is to consolidate these messages as shown in [these mocks](https://www.figma.com/file/ctpYEoOBWGkUnk9cmXzVp2/ReportStream-Submitter-Front-End?node-id=980%3A3216)
Tech specs proposal detailed here: https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/1966
- Introduces a `ResponseMessage` interface that `ResultDetail` uses instead of a `String` for the message
- Creates data classes for each error type that implement `ResponseMessage`
- Creates a generic `ResponseMsgType` all HL7 serialization warnings/errors since these do not need consolidation
- Adds new fields …
> Consolidate error and warning messages for the CSV uploader

- prime-router/metadata/tables/zip-code-data.csv
> rhood/2382-Add Zip Codes

- frontend-react/public/index.html
It really should be in the header anyways.
What it was in case we want to use this as a starting point for http header cors:
```html
<meta
http-equiv="Content-Security-Policy"
content="default-src 'self';
script-src 'self'
https://hss-prime-okta.com
https://global.oktacdn.com
https://www.google-analytics.com
https://*.in.applicationinsights.azure.com;
style-src 'self' 'unsafe-inline'
https://global.oktacdn.com
https://cdnjs.cloudflare.com;
frame-src 'self' https://hhs-prime.okta.com;
img-src 'self' https://hhs-prime.okta.com https://reportstream.cdc.gov data: ;
connect-src 'self'
https://www.google-analytics.com
https://*.in.applicationinsights.azure.com
https://hhs-prime.okta.com
https://staging.reportstream.cdc.gov/api/
https://staging.prime.cdc.gov/api/
%REACT_APP_BACKEND_URL%
;"
/> …
```
> remove Content-Security-Policy for now

- prime-router/src/main/kotlin/azure/SendFunction.kt
- prime-router/src/main/kotlin/transport/AS2Transport.kt
- prime-router/src/main/kotlin/transport/BlobStoreTransport.kt
- prime-router/src/main/kotlin/transport/RedoxTransport.kt
- prime-router/src/main/kotlin/transport/SftpTransport.kt
- prime-router/src/main/resources/db/migration/V18__add_send_info_to_action_type.sql
- prime-router/src/test/kotlin/azure/SendFunctionTests.kt
This PR ...
- Migrate `task_action` type to include a `send_warning` value
- Use `send_warning` for action history in the case where a receiver has no transports defined.
- #1973 
Open review questions:
- Any better name suggestions than `send_info`?
- Is the migration kosher?
---
To explore this locally, change the ignore.CSV transport to have a bogus `host`. Update the `maxRetries = 2` in SendFunction.kt and run end to end tests. You may also have to `@Ignore` a couple of unit tests to pass `gradlew package`. This will populate the action table with a series of `send_warning` and then `send_error` pairs.
> Adding send_info action type

- prime-router/src/main/kotlin/azure/ReportFunction.kt
The hyphen characters are not coming through correctly in the rolled up error messages for the csv uploader:
This problem only happens on staging, I am not able to repro locally. Switching to using the unicodes for these characters may solve the problem. I'll have to see what it looks like in staging.
> Use utf-8 chars

- frontend-react/src/pages/Login.tsx
On staging, when navigating to /daily-data the log in screen flashes. This cannot be reproduced locally. It seems like it could be an 11ty artifact. This PR adds a console log and a subtle UI change to make it clear which login page is being flashed.
> Sanity check which login page is being used

- prime-router/src/main/kotlin/azure/ReportFunction.kt
The hyphen characters are not coming through correctly in the rolled up error messages for the csv uploader. I've tried both the literal character, and the encoding for the hyphen and both result in the question mark character showing:
This problem only happens on staging, I am not able to repro locally. Switching to just use " to " since I've already spent too much time trying to debug!
> Use "to" instead of hyphen

- frontend-react/src/components/ReportStreamHeader.tsx
This PR changs the /daily-data page to function as part of the single page app. Previously we've been making page requests to load this page. 
This has 2 benefits
- Load speeds will be faster
- This will hopefully solve the bug where the log in screen flashes on navigation. There is a change this is flashing since while the app waits for the server request to be made, temporarily it seems like the user is not logged in. This bug is not reproducible locally so we won't know until it is in staging
> Switch /daily-data to a NavLink

- frontend-react/src/pages/daily/Table/TableReportsData.tsx
Switch the link to /report-details to instead be handled within the single page app so that a page request is not required.
> Use NavLink for report details

- frontend-react/src/components/header/ReportStreamHeader.tsx
Use NavLink for the RS logo in header so that a page request isn't made
> NavLink for home page

- prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
- prime-router/docs/schema_documentation/experity-experity-covid-19.md
- prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
- prime-router/metadata/schemas/Experity/CUC-AL-covid-19.schema
- prime-router/metadata/schemas/Experity/GUC-LA-covid-19.schema
- prime-router/metadata/schemas/Experity/experity-covid-19.schema
This PR contains modifications to the Compass Urgent Care Schema to add the RightSign Anitbody Test.  It also includes changes to the remove the unused Default value from the test_kit_name_id.
- Populate the OBX.3.1 with LOINC Code: 94507-1 for the IgG result.
- Populate the OBX3.1 with LOINC Code: 94508-9 for the IgM result.
- Populate the OBX.17.1 with "RightSign COVID-19 IgG/IgM Rapid Test Cassette_Hangzhou Biotest Biotech Co., Ltd._EUA" for both the IgG and IgM results.
**If you are suggesting a fix for a currently exploitable issue, please disclose the issue to the prime-reportstream team directly outside of GitHub instead of filing a PR, so we may immediately patch the affected systems before a disclosure. See [SECURITY.md/Reporting a …
> rhood/2607 CUC - Add RightSign Antibody Test

- prime-router/metadata/tables/zip-code-data.csv
> rhood/2626 Add Zip Codes

- frontend-react/package.json
- frontend-react/yarn.lock
react-snap is used to generate static html as a `postbuild` step using Puppeteer to crawl the site.
Ran `yarn remove react-snap` to update yarn.lock
Fixes #2514
> Remove dependency on `react-snap`

- frontend-react/src/pages/home/Home.test.tsx
- frontend-react/src/pages/home/Sections/Section.test.tsx
This #2916. (My change #2837 broke the unit tests.
This PR fixes the tests by removing the jest mock for the removed component.
Opened another issue https://github.com/CDCgov/prime-reportstream/issues/2920 to have tests run as github action so it gets caught automatically.
> Remove jest mocks for unused CdcMap component

- .github/workflows/release.yml
- .github/workflows/validate_terraform.yml
* Something (not sure what) changed recently in the `azure/login`action
where the credentials are not passed properly to the `azure/CLI`
action
Test Steps:
1. Run the `release` and `validate_terraform` actions
- Remove use of `azure/CLI` action
> Remove use of azure/CLI action, run commands directly

- operations/app/src/environments/configurations/prod.tfvars
- operations/app/src/modules/function_app/main.tf
- prime-router/docs/dns.md
This PR flips the switch to enable the Palo Alto in production. (A retry from https://github.com/CDCgov/prime-reportstream/pull/2828)
> Turn Palo Alto on for production

- prime-router/docs/schema_documentation/direct-cue-covid-19.md
- prime-router/metadata/schemas/direct/cue-covid-19.schema
- prime-router/src/main/kotlin/ElementErrors.kt
- prime-router/src/main/kotlin/azure/ReportFunction.kt
- This makes the CLIA number optional in the cue schema
- Also fixes a missing error message problem
- Also fixes our line numbering so that the first row of data is "row 1", to fit with how we number HL7 files.
Tested locally, and smoke tested.
> Fix to Cue schema

- .github/workflows/release.yml
* This is to see if any intervening step is mucking with the current working directory, or is cleaning up files/directories behind the scenes.
> Move the download-artifact step to just before the upload one

- .github/workflows/release.yml
* Toward the top of the `release.yml` there's a default setting for  `run | working-directory`, which is why this wasn't working, and also why this was succeeding previously with the `azure/CLI` action (that default didn't apply).
> Setting the working directory should do the trick

- prime-router/docs/schema_documentation/az-az-covid-19.md
- prime-router/docs/schema_documentation/az-az-ihs-covid-19.md
- prime-router/metadata/schemas/AZ/az-covid-19-csv.schema
This PR fixes the issue where OBX-23-1 was not populated. This is for AZ and their display field name is Lab_Name. Lab_Name was only being populated by test results from Simple Report and not from any other sender. At the same time, this PR fixes the issue of specimen id not being populated as well.
Test Steps:
1. Run gradle
- test
- integration
- testSmoke
2. Generate fake data from Simple Report for AZ
3. Submit to api
4. Verify that Lab_Name and Speciment_ID fields are populated
5. Do steps 2 through 4 with fake data from imagemover for AZ
- Edited az-covid-19-csv.schema
- organization_name
- testing_lab_specimen_id
- #2631
> AZ Missing Lab Name and Specimen ID

- prime-router/docs/schema_documentation/direct-directlite-covid-19.md
- prime-router/metadata/schemas/direct/abbott-covid-19.schema
- prime-router/metadata/schemas/direct/directlite-covid-19.schema
- prime-router/settings/prod/0049-abbott-lifepoint.yml
- prime-router/settings/staging/0050-abbott-lifepoint.yml
This PR adds Abbott and Lifepoint sender settings, and adds a Direct Lite base schema for Abbott.
Test Steps:
1. Execute `./prime multiple-settings` against yamlitos as described in line 1 of the files.
2. Create and submit fake Abbott data
- abbott-covid-19.schema - change base to directlite-covid-19
- adds directlite-covid-19.schema
- adds settings/prod/0049-abbott-lifepoint.yml
- adds settings/staging/0050-abbott-lifepoint.yml
- #2950
> Adding Abbott and Lifepoint senders, directlite schema

- prime-router/settings/organizations.yml
- prime-router/settings/prod/0049-update-vt-doh.yml
- prime-router/settings/staging/0049-update-vt-doh.yml
This PR suppresses HL7 field OBX-18 for VT. 
Test Steps:
1. Make sure your docker containers are running and type this command: 
- `./prime multiple-settings set --input settings/organizations.yml`
2. Generate fake test data for VT
- `./prime data --input-fake 5 --input-schema primedatainput/pdi-covid-19 --output-format CSV --output <FILE PATH> --target-states VT`
3. Submit fake data to api
- `curl -X POST -H 'client: simple_report' -H 'Content-Type: text/csv' --data-binary '@<FILE PATH>' localhost:7071/api/reports`
4. Verify that OBX-18 is blank
- Go to build/sftp folder 
- Open the newly generated HL7 file and verify that OBX-18 is blank
- Edits org file for vt-doh by adding `suppressHl7Fields: OBX-18-1, OBX-18-2, OBX-18-3, OBX-18-4` to the translation property
- adds …
> Suppress OBX-18 For VT

- frontend-react/package.json
see https://github.com/CDCgov/prime-reportstream/issues/2952
Fix is to simply duplicate the index.html page (which hosts the SPA) to 404.html. Any 404 result should just load this page.
> Trying experiment to handle missing paths for a SPA

- prime-router/src/main/kotlin/cli/OktaCommands.kt
- prime-router/src/main/kotlin/cli/SenderUtilsCommand.kt
- prime-router/src/main/kotlin/cli/SettingCommands.kt
This PR fixes the PRIME CLI's `--env` option. This option was broken in the recent environment consolidation work. 
Test Steps:
1. Try `./prime login --env prod` 
2. Other commands that have an `--env` option
- The PRIME CLI's environment was hardcoded to the local environment. Now use the value in the --env option to select the environment. 
- #2996 
-
- #issue
- Does this PR include or remove any sensitive …
> Bug Fix 2996: Broken env option on the PRIME CLI

- frontend-react/src/oktaConfig.ts
- frontend-react/src/utils/UserUtils.ts
This PR fixes the CDC logo img path for the Okta login widget
Test Steps:
1. pull branch
2. `yarn` and `yarn start` (also have prime-router running)
3. click login and observe the OktaSigninWidget
- CDC logo now appears on login widget
- Fixed build error thrown by TS in `UserUtils`
- What are …
> Okta widget img path now reflects React release image path

- prime-router/docs/schema_documentation/strac-strac-covid-19.md
- prime-router/metadata/schemas/STRAC/strac-covid-19.schema
This PR populates OBR-22 in messages coming from STRAC
Test Steps:
1. Generate fake data from strac
2. Run Docker
3. Submit fake data file to api
4. Verify that OBR-22 is populated
- Added date_result_released to STRAC schema
- generatedocs
- #3022
> MA Missing OBR-22 In Messages From STRAC

- prime-router/settings/organizations.yml
- prime-router/settings/prod/0050-update-mn-doh.yml
- prime-router/settings/staging/0050-update-mn-doh.yml
This PR suppresses SPM-2-1 field for MN.
1. Generate fake data for MN
2. Start Docker
3. Run this command: `./prime multiple-settings set --input settings/organizations.yml`
4. Submit the fake data to the api
5. Verify that SPM-2-1 is blank  
- Added settings/prod/0050-update-mn-doh.yml
- Added settings/staging/0050-update-mn-doh.yml
- gradle test --> passed
- gradle testIntegration --> passed
- gradle testSmoke --> passed
- #3003
> MN - Suppresses SPM-2-1

- prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
- prime-router/metadata/schemas/HL7/prescryptive-covid-19.schema
- prime-router/settings/organizations.yml
- prime-router/settings/prod/0051-prescryptive.yml
- prime-router/settings/staging/0051-prescryptive.yml
This PR adds an HL7 schema for Prescryptive Health and yamlitos for staging and production.
Test Steps:
1. Send an HL7 message to ReportStream using client=prescryptive
- Adds HL7 schema, prescryptive-covid-19.schema
- Adds configuration to organizations.yml, plus staging and production yamlitos
- #2126
> Onboard prescryptive

- prime-router/src/main/kotlin/azure/ReportFunction.kt
This PR fixes tracking of sending_org and sending_org_client which was missed during the Async/split work.
> add missed tracking of sender information

- prime-router/src/main/kotlin/azure/ActionHistory.kt
This PR changes the download action history so it no longer stores the verbose response.
Test Steps:
1. Do a download, then confirm that just the brief http status string (eg, "OK") appears in the action.action_response field in the database.
> Removed the entire response body from the data stored in action history

- .github/workflows/build_hub.yml
Before this a required check would not run when changes weren't made to router files. GitHub Actions isn't fully ready for mono-repos: https://github.community/t/status-check-with-path-filter/18049
This PR moves back to using https://github.com/dorny/paths-filter
Test Steps:
1. See that the check still runs
2. after this is merged the router check should pass but no heavy weight tasks should run if no router files were changed.
- re-implement https://github.com/dorny/paths-filter
> Revert move to gh actions path filter

- frontend-react/package.json
- frontend-react/src/components/header/OrgDropdown.tsx
- frontend-react/src/pages/daily/Table/ReportLink.tsx
- frontend-react/src/pages/details/Details.tsx
- frontend-react/src/pages/details/FacilitiesTable.tsx
- frontend-react/yarn.lock
- prime-router/src/main/kotlin/azure/HistoryFunctions.kt
This PR fixes the error(s?) created by refreshing the `/daily-data` page. Firstly, the `facilities` call receives the reportId due to a parameter change in the `Details` component. Next, the `getReportById` call accessed via the `/history/report/{reportId}` endpoint now returns the full report (sans facilities) to match our front-end needs.
Test Steps:
1. pull most recent 
2. `cd prime-router; docker-compose down; ./gradlew clean build; docker-compose up`
`cd ../frontend-react; yarn; yarn start`
3. Login and navigate to a details page for a report (note: You may need to add a new report to your local db since rebuilding seems to erase blob storage. It does not erase the result from showing up on your `/daily-data` page, however, so be weary of impending `404`s)
4. Refresh the page and …
> Fixes the /report-details page refresh bug

- frontend-react/src/App.tsx
- frontend-react/src/components/header/ReportStreamHeader.tsx
- frontend-react/src/pages/Submissions.tsx
As a first step towards building out Submission history, we are going to show this data to admins only. This is just the initial set up so we can get a sense of these feature before rolling it out. Few things to note:
- Table design matches /daily-data page
- Columns not finalized 
- File name is not included in the server response yet so it is left blank here
Issue: https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3365
Test Steps:
1. Generate submissions from a specific sender
2. Log into the web app as admin
3. Switch the org drop down to the sender from 1.
4. See submission history tab and results
- #issue
- Does this PR introduce …
> Admins can view submission history

- prime-router/src/main/kotlin/Metadata.kt
- prime-router/src/main/kotlin/Organization.kt
- prime-router/src/main/kotlin/Translator.kt
- prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
- prime-router/src/test/kotlin/MetadataTests.kt
This PR fixes a bug that a new filter didn't appear in the filter list.  Also added a unit test for this.
Test Steps:
1. Run the unit tests.
- Also fixed a bug in the 'sandaclaus' test in TestReportStream that was preventing it from running on staging.
- Added logging in the case where the allowNone() filter is actually applied.   This could mean that someone forgot to override it.  Its not necessarily an error - someone might (rarely, I'm guessing) do that on purpose. …
> Fixed bug that allowNone was missing from metadata list.

- prime-router/settings/organizations.yml
- prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
- prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
This PR fixes an issue where the new truncation logic inadvertently truncates other fields it should not.
See case #3411 for more details about what caused the bug. In short the `truncateHl7Fields` was treated as a string, when it should have been a list.
Closes #3411 
Test Steps:
1. Run the application in docker
2. Update the settings for a state to truncate `OBX-23-1`
3. Submit a new file for that state
4. View the created HL7 file for the test state
5. Verify that OBX-2 was not affected
- Adds a test for a compound type for truncation
- Updates the logic to convert `truncateHl7Fields` to a list
- Updates the settings for VT to include `OBX-23-1` for truncation
- #3411 
| …
> Fixes issue with the new truncation logic truncating fields it should not be

- prime-router/src/main/kotlin/cli/LookupTableCommands.kt
- prime-router/src/main/kotlin/cli/SettingCommands.kt
- prime-router/src/main/kotlin/cli/SettingsUtilities.kt
This PR increases the read timeout for the settings CLI operations from the default 15 sec timeout.  After looking at the logs for different build failures, one can see that the amount of time that the system takes from initializing a function to providing a response can be 15+ secs, which exceeds the default read timeout for Fuel. This lag tends to happen when a new function is being invoked and the Hikari pool needs to be initialized.  This does not happen all the time, and a rerun of the build tends to be successful, but I am thinking that this is due to loads in GitHub. Increasing the read timeout can help with this issue.
Test Steps:
1. Verify the GitHub Actions build success for this branch.
- increased the read timeout for the settings CLI operations to 30 sec timeout
- #3527
- …
> 3527 Increased read timeouts for Settings CLI operations

- prime-router/src/main/kotlin/serializers/CsvSerializer.kt
This PR adds a snippet of logging to help diagnose what's going on in Staging right now. …
> Added logging to help find serialization error

- prime-router/src/main/kotlin/azure/BatchFunction.kt
- prime-router/src/main/kotlin/azure/DatabaseAccess.kt
- prime-router/src/main/kotlin/azure/WorkflowEngine.kt
Current Exceptions in Staging are caused by new Batch being over-eager -- reaching back to try to run reports from August.   For sanity, we had a "backstopTime" oldest-time-to-look-for built into the BatchDecider, but it was missing from the BatchFunction query itself.   I added it there.
Note that the actual exception thrown in Staging was a date parse formatting exception -- caused by attempting to process very old data with the current schema.     A bizarre case of our old "WIP" bug.  This further emphasizes @mauricereeves 's point that we need schema versioning.    Regardless of that, we shouldn't be regularly running data from last August.  ;) 
It can be very hard to tell which original data has caused merged data to fail.   The particular error in Staging occurred after the batch …
> Added a backstop time to batch queries, to prevent it processing very old data

- prime-router/src/main/kotlin/azure/BatchDeciderFunction.kt
- prime-router/src/main/kotlin/azure/BatchFunction.kt
- prime-router/src/main/kotlin/azure/DatabaseAccess.kt
- prime-router/src/main/kotlin/azure/WorkflowEngine.kt
- prime-router/src/test/kotlin/azure/WorkflowEngineTests.kt
This PR enables a fairly robust retry mechanism for BatchFunction, by using a backstopTime that is set per-receiver, based on that receiver's frequency of batching.
Test Steps:
1. Run smokes.  Pay attention to the logs showing the `backstopTime`
2. I tested by hacking in a thrown Exception into BatchFunction, then removing it.
- This fixes the problem that frequent batchings that fail in unrecoverable ways would give us days of grief.
> BackstopTime set per receiver, based on next_action_at

- prime-router/build.gradle.kts
This PR prevents any logback library from coming in. If it does slf4j may pick it up before log4j and our logging configuration gets ignored.
Test Steps:
1. Deploy the app
2. Check logging amounts, hopefully it's much less.
- Exclude logback libraries from being brought in by gradle, no matter who declares the dependency …
> Prevent logback from getting pulled in

- prime-router/src/main/kotlin/Metadata.kt
This PR allows fields that can be blank to have mappers.
Test Steps:
1. Add a mapper to a field that can be blank in any schema.  E.g. ordering_facility_street2 
2. Rebuild and restart your local RS.
3. Verify that no schema error is thrown.
- Allow fields that can be blank to have mappers.
- #3728
If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at …
> 3728 Allow fields that can be blank to have mappers

- prime-router/src/main/kotlin/azure/DatabaseAccess.kt
This PR orders the Batch tasks by oldest first to ensure that old batch tasks are not missed if new ones come in during the run.
Test Steps:
1. Run a batch
- add orderBy created_at to the task select statement for batch …
> add orderBy created_at to batch task selection

- prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
This PR ...
Fixed bug NET.1 is blank.
Test Steps:
1. docker-compose down
2. ./gradlew clean package
3. docker-compose up 
4. Copy the file below to ./junk directory:
[StandardCSV-Test.csv](https://github.com/CDCgov/prime-reportstream/files/7846982/StandardCSV-Test.csv)
5.  Run prime cli command below:
**./prime data --input ./junk/StandardCSV-Test.csv --input-schema manualupload/csvuploadertest-covid-19 --output ./junk/StandarHL7-Test.hl7 --output-dir junk --route**
6. Verify the file ./junk/StandardHL7-Test.hl7 to see NTE|1| as below:
**NTE|1|L^Ancillary (filler) department is source of comment^HL70105|Test Comment|RE^Remark^HL70364^^^^2.5.1**
- #issue - List GitHub issues …
> 3325: Fixed Bug NET.1 is blank

- prime-router/settings/organizations.yml
- prime-router/settings/prod/0062-suppress-pid-20-ma.yml
- prime-router/settings/staging/0062-suppress-pid-20.yml
This PR adds PID-20 suppression for MA
Test Steps:
1. Create a test file for MA
2. Run docker
3. Submit your test file to Docker
4. Verify PID-20 is blank
- Adds suppression of PID-20 for MA
- Closes #3287 …
> Adds PID-20 suppression for MA

- prime-router/metadata/file_name_templates/file-name-templates.yml
- prime-router/settings/organizations.yml
- prime-router/settings/prod/0063-change-tx-name-format.yml
- prime-router/settings/staging/0063-change-tx-name-format.yml
This PR updates the name format for TX until we have the ability to batch by sending facility.
Test Steps:
1. Create a test file for TX
2. Run Docker
3. Submit the file to your local docker container
4. Verify the created file in your SFTP folder has the new name format
- Changes the name format for Texas to an interim format until we add the ability to batch by the sending facility.
- Closes #2189  …
> Adds new name format for TX

- prime-router/settings.gradle.kts
This PR removes jcenter from gradle plugin manager.  Note we still need the previous change to force the use of the correct json-smart library.
Test Steps:
1. Verify the build works in Github Actions
2. Verify the build works bypassing the gradle dep cache by running `gradle package --refresh-dependencies`
- Force gradle to not use jcenter
- #issue
- Does this PR …
> Remove jcenter from gradle plugin manager

- prime-router/local.settings.json
- prime-router/src/main/kotlin/azure/DatabaseLookupTableAccess.kt
- prime-router/src/main/kotlin/cli/LookupTableCommands.kt
This PR fixes the lookup tables CLI diff working with the LIVD table.  Previously, the new lines and unordered table was creating a huge incorrect diff.
Test Steps:
1. Store the current LIVD table in the database by running `./prime lookuptables create -n LIVD-test -i ./metadata/tables/LIVD-SARS-CoV-2-latest.csv`
2. Store a modified LIVD table, so the diff shows up.  You can use the command `./prime lookuptables create -n LIVD-test -i ./metadata/tables/LIVD-SARS-CoV-2-2021-04-28.csv`.  
3. Verify the diff looks clean and shows the correct differences in the tables.
- Fixed diff working with the LIVD table
- Force add the azure extension bundle as sometimes running Dockerless does not work.
*Create GitHub issues to track the work remaining, if …
> 2887 Fixed diff working with the LIVD table

- frontend-react/src/components/header/ReportStreamHeader.tsx
- frontend-react/src/webreceiver-utils.ts
This PR rolls back the permission check refactor and shows upload nav item to admins and senders.
Test Steps:
- #issue
If you answered '_yes_' …
> Fix for upload nav item and sender permission check

- prime-router/src/main/kotlin/metadata/LivdMappers.kt
This PR fixes a big issue with our LOINC lookup logic where every multiplex test was failing lookups in the LIVD table because they have multiple rows in the table and the lookup logic expects only a single matching row before returning a value. This has caused numerous data quality issues for us, and it is a high priority it get reviewed and released ASAP.
Test Steps:
1. Run Docker
2. Send the attached test file to your local container. Note that all the multiplex tests do return a value because they're now matching on both model name AND test performed code. File: 
[sample-livd-test.csv](https://github.com/CDCgov/prime-reportstream/files/7967239/sample-livd-test.csv)
- Updates the logic to make the lookup more strict by searching on two columns instead of one when both model name and …
> Fixes issue with LOINC multiplex look up logic

- prime-router/src/main/kotlin/azure/BatchDeciderFunction.kt
- prime-router/src/test/kotlin/azure/BatchDeciderTests.kt
This PR fixes a problem with the batch decider tests failing due to missing mock.  This was due to the batch decider function swallowing all exceptions including missing mock exceptions.
Test Steps:
1. Run the build locally and verify the tests pass.
2. Verify the Github build passes.
- Fixed missing mock responses
- #issue …
> Fix batch decider unit test

- frontend-react/src/components/header/ReportStreamHeader.tsx
To test:
1. Point your client to your localdev API server.
2. Shut down your localdev API server so it generates network errors
3. Log in and let the navbar render.
Result: you should still see the top navbar and "network error" where the Organization dropdown would normally be.
Fixes #4209 …
> Bugfix: Show topnav even if there's a network error or server is down.

- frontend-react/src/pages/submissions/SubmissionsTable.tsx
- frontend-react/src/resources/SubmissionsResource.ts
- prime-router/docs/release-notes.md
- prime-router/src/main/kotlin/azure/DatabaseSubmissionsAccess.kt
- prime-router/src/main/kotlin/azure/SubmissionFunction.kt
- prime-router/src/main/kotlin/azure/SubmissionsFacade.kt
- prime-router/src/test/kotlin/azure/SubmissionFunctionTests.kt
This PR moves filtering of failed submissions to back-end. The default behavior is still to show all results. This was decided in a chat with @drew-usds so that API senders can still see failed results if needed. The SubmissionsList has been updated, though, to call for only successful submissions.
BEFORE
AFTER
- #issue …
> Filter out failed submissions in list on backend

- prime-router/src/main/kotlin/Report.kt
- prime-router/src/main/kotlin/Translator.kt
- prime-router/src/test/kotlin/ReportTests.kt
resolves #4283 
This PR adds the `"filterType": "<FILTER_TYPE>"` to the `action_log` detail json.
Test Steps:
1. Follow the steps outlined in this PR's readme file: https://github.com/CDCgov/prime-reportstream/pull/4638/files
2. (or create submission data with filters ran on it)
3. Check the database's `action_log` table for this report's detail information
4. The JSON should include what …
> experience/4283: Add the filter type (eg 'qualityFilter') to the ReportStreamFilterResult

- operations/app/terraform/modules/application_insights/alert_availability.tf
- operations/app/terraform/modules/application_insights/main.tf
Tiny change - updates the name of one of the alerts & changes the format in one of the TF files to match the output from `terraform format`
#4595  …
> changing availibility alert to use correct naming convention

- prime-router/src/main/kotlin/credentials/Credential.kt
- prime-router/src/test/kotlin/credentials/CredentialTests.kt
This PR removed certain data from our logging when a jackson exception occurs.
Test Steps:
- The code is all unit tested, so you can test by just running the unit tests
- Have you ensured logging does not contain sensitive data?  Yes. …
> Added ectomy code

- frontend-react/src/contexts/SessionStorageTools.ts
- frontend-react/src/utils/OrganizationUtils.test.ts
- frontend-react/src/utils/OrganizationUtils.ts
- frontend-react/src/webreceiver-utils.ts
This PR refactors `groupToOrg` to handle non-standard names (i.e. names that don't follow our okta group naming convention)
Test Steps:
1. Pull branch
2. Observe the `OrganizationUtils.test.ts` file for example input/output
3. Run tests
4. Alter tests to check some stress cases that might need to be considered.
- Refactor: `groupToOrg()`
- Added: `OrganizationUtils.test.ts`
- #issue
- Does logging …
> Fix okta group name parsing

- prime-router/src/main/kotlin/azure/ReportFunction.kt
- prime-router/src/main/kotlin/tokens/AuthenticationStrategy.kt
- prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
This PR fixes a bug where the authentication code was being passed the fully dotted sender name (eg simple_report.myspecialsender) instead of just simple_report.
We had no tests for this, so tests were added as well.
Test Steps:
1. Run unit tests.
**None apply**
- #4655 - partial. …
> Fix in waters endpoint to just send the org name, not full client name, to OktaAuth

- prime-router/src/main/kotlin/Report.kt
- prime-router/src/main/kotlin/azure/Event.kt
- prime-router/src/main/kotlin/azure/ReportFunction.kt
- prime-router/src/test/kotlin/azure/EventTest.kt
This PR makes it so that when an invalid option (anything we don't support) is passed to the /reports endpoint or is included in an event message for process (which can happen when an invalid option is passed to /reports or when we are updating code), it will simply ignore the invalid option and progress without erroring out.
Test Steps:
1. POST to /reports with an invalid options
- add companion object to enum Options with function getValueOrNone
- update all locations Options.valueOf was used to instead use the new function
- add unit tests
|                                                                                                                                                                            | User               | Total reviews | Time to …
> add valueOfOrNone function to Options to handle invalid incoming options

- prime-router/settings/organizations.yml
- prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
- prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
This PR added a feature to allow users to be able to set a default, hardcoded value for a field and have it populate that way for all receivers.
Another example where this is needed is for testing in production. When we onboard an HL7 sender to testing in production, we rely on them to set MSH-11 to "T" or "D" so their messages aren't routed downstream. If they forget to do this and send "P" instead (which happened this week with WA), their messages will route to HHS+STLTs before they've been approved for full production.
Test Steps:
2. ./prime data --input junk/prescryptive-sample1a.hl7 --input-schema HL7/prescryptive-covid-19 --output-dir junk/output --route
3. Verify the HL7 output file contains the field below:
MSH-3:  Sending Application: …
> 4879: Need ability to override hl7 field with a hardcode value

- prime-router/src/main/kotlin/azure/CovidResultMetaDataFunction.kt
- prime-router/src/main/kotlin/azure/WorkflowEngine.kt
- prime-router/src/main/kotlin/cli/ProcessDataCommands.kt
- prime-router/src/main/kotlin/serializers/CsvSerializer.kt
- prime-router/src/test/kotlin/serializers/CsvSerializerTests.kt
- prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
This PR fixes a bug that occurs during deployment when a schema is changed in the middle of a report being processed.  See #5200 for details. The result is that:
1. The processing fails if fields were added to the schema
2. The wrong data is assigned to a field if a field is removed from the schema (I do not think this has happened yet as we normally add fields) 
Test Steps:
I think the unit tests cover this, but here are steps to test locally:
1. Submit a report and stop the processing of the report, so the queue message is not pulled.  This may be easier to do by adding code in the ProcessFunction to just return a fail status then removing the code later.
2. Stop ReportStream.
3. Change the covid-19 schema to add a field somewhere in the middle of the schema.
4. Restart ReportStream …
> 5200 Allow processing of reports after a schema change

- frontend-react/src/components/Admin/CompareJsonModal.tsx
- frontend-react/src/components/Admin/EditReceiverSettings.tsx
- frontend-react/src/components/Admin/EditSenderSettings.tsx
- frontend-react/src/components/EditableCompare.tsx
- frontend-react/src/hooks/UseOrgName.ts
- frontend-react/src/pages/admin/AdminOrgEdit.tsx
- frontend-react/src/styles/_reportstream.scss
- frontend-react/src/utils/misc.test.ts
- frontend-react/src/utils/misc.ts
This PR prevents the user from saving changes to any setting if the setting they're trying to edit has been modified by another user at the same time.
Test Steps (happy path 1):
1. Login to ReportStream as an admin and choose Admin->Organization Settings (or click on the top right org picker)
2. Click Edit on a particular org (i.e. abbott)
3. Launch a Chrome tab in Incognito mode
4. Login to ReportStream as an admin and choose Admin->Organization Settings (or click on the top right org picker)
5. Click Edit on the org you chose for step 2
6. Make a change, click on "Preview save...", then click Save on the resulting compare dialog
7. In your _original_ browser tab (without refreshing anything), make a change and click "Preview save..."
8. The modal will popup with a big scary warning all …
> Experience/4325: guard against simultaneous setting edits

- operations/app/terraform/modules/log_analytics_workspace/data.tf
- operations/app/terraform/modules/storage/main.tf
This PR adds azure diagnostic settings for blob-level actions (read/write/delete) and enables storage account access to Azure services, which is required to [support lifecycle management](https://docs.microsoft.com/en-us/answers/questions/107954/lifecycle-mangement-isn39t-doing-anything.html?childToView=154361#answer-154361)
Test Steps:
1. Validate blobs are deleted according to the desired lifecycle by checking the logs:
* `StorageBlobLogs` 
- Add blob-level diagnostics
- Enabled Azure service access to storage account
- Fixes #5566  …
> add blob level diag and permit lifecycle management access

- frontend-react/src/components/Table/Table.tsx
- frontend-react/src/resources/AuthResource.ts
- Sanity check for empty data in Table
- Turn the schema mismatch errors coming from `rest-hooks` into warnings so I can get work done. …
> Tomn usds/fix empty table bug

- frontend-react/package.json
- frontend-react/src/components/Table/Pagination.test.tsx
- frontend-react/src/components/Table/Pagination.tsx
- frontend-react/src/components/Table/__snapshots__/Pagination.test.tsx.snap
- frontend-react/src/pages/submissions/SubmissionTable.tsx
- frontend-react/src/styles/_reportstream.scss
- frontend-react/yarn.lock
This PR adds the UI component to render the pagination values produced by the `usePaginationHook` added in #5575. When the `numbered-pagination` feature flag is on, the submission table renders the new component with static props while this feature is still in development.
Test Steps:
1. Create a feature flag called `numbered-pagination`.
2. Go to the submissions page and see the rendered pagination component.
3. Modify the [static list of slots](https://github.com/CDCgov/prime-reportstream/pull/5627/files#diff-49bba1f24f8c082ab6d04fb65f3fd2e9ea5d3e4639716282aca973084ded93a9R152) to test different rendering conditions.
4. Clicking any of the page options will log the selected page number to the console.
- The pagination component determines whether to show previous and next links by …
> Add numbered pagination UI

- prime-router/src/test/kotlin/azure/LookupTableFunctionsTests.kt
This PR mocks the Okta authentication instead of relying on the underlaying code that mocks the response for local use.
Test Steps:
1. Verify the unit tests and smoke tests pass on the build.
- Mock the Okta authentication for the tests
- N/A …
> Fix Lookup Table tests after a change to a library broke them

- prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
- prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
This PR Fixed the Hl7Serializer.setTelephoneComponent Error out On Blank Value
Test Steps:
2. ./gradlew test --tests "gov.cdc.prime.router.serializers.Hl7SerializerTests.test setTelephoneComponents for facility"
3. Verify the test SUCCESS
- Fixes #issue
- https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4877
- 
- #issue
- Does this change introduce new …
> Fixed the Hl7Serializer.setTelephoneComponent Error out On Blank Value

- prime-router/src/test/kotlin/fhirengine/utils/FhirTranscoderTests.kt
After feedback on a better more kotlin style way of testing, this commit changes == into .equals and assertTrue into .isTrue.
Test Steps:
1. Ran unit test locally
- changes == into .equals
- assertTrue into .isTrue
- Fixes #issue
- #issue …
> Update FHIR Transcoder tests to kotlin style assertions

- operations/app/terraform/modules/application_insights/alert_exception.tf
- operations/app/terraform/modules/application_insights/main.tf
This PR disables the "One or More Exceptions Raised in the Last Hour" for non-production (staging) environments. Non-production will still receive the actual alert, just not alerts about alerts.
- disables the "One or More Exceptions Raised in the Last Hour" for non-production environments
- Fixes #5624 …
> for non-prod, do not enable an alert about alerts

- frontend-react/src/components/Table/TableRows.tsx
a bug exists on the current 5442 branch ([dws/value-set-edit-rebase](https://github.com/CDCgov/prime-reportstream/tree/dws/value-set-edit-rebase) where the api will throw an error when trying to save a new where all fields are not filled in with values by the user. With this change the client can send valid empty fields to the api to avoid this behavior.
1. start servers on master with `yarn run start:localdev` from `frontend-react` and `./gradlew run` from `prime-router`
2. visit http://localhost:3000/admin/value-sets/gender and log in as necessary
3. click `add item` to add a new row, and fill in the `display` field
4. click save
5. _VERIFY_: row is not added to table
6. repeat steps 2 - 4 on this branch
7. _VERIFY_: row is added
- …
> fix: allow adding rows with empty fields [experience-5442]

- frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
This PR fixes the update and activate axios calls for saving a Valueset in the UI. It was discovered upon deploying to Staging and identified as the probably culprit by @doug-s-nava thanks Doug!
Test Steps:
1. Login as Admin to ReportStream on **_Staging_**
2. Navigate manually to /admin/value-sets in the URL (or add the "value-sets" feature flag to navigate from the menu itself)
3. Click on any particular valueset name link
4. Click the Edit button on any particular row --> cells become editable
5. Change any or all values and click the Save button --> was an **ERROR**! This PR should fix this and save it properly.
> Experience/5442: fix to update/activate calls

- frontend-react/src/components/StaticAlert.test.tsx
- frontend-react/src/components/StaticAlert.tsx
- frontend-react/src/hooks/UseLookupTable.test.ts
- frontend-react/src/hooks/UseLookupTable.ts
- frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.test.tsx
- frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
- frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.tsx
- frontend-react/src/utils/ErrorUtils.tsx
Adds messaging for users to display success or error results after editing or adding rows to the value sets table.
Also:
* creates a StaticAlert component based on the alert currently used on the Upload page for use here, and across the app where this sort of messaging is called for
* creates an ErrorUtils file to hold functionality and types related to common error handling
Open question: do we want these alerts to disappear at a particular time? At this point they will stay on the page until:
* they are replaced by a new alert
* the page reloads, or user navigates away
Some options:
* message disappears after a certain length of time
* message disappears when a new update operation is performed (and is likely quickly replaced by a new message)
* message disappears when a new row is open …
> feat: error and success messaging for value sets edits [experience-5443]

- operations/dnsmasq/Dockerfile
This PR forces the dns alpine image to 3.14.2, as there is a potential failure running 3.16
- Set dns image to alpine 3.14.2
- Fixes #5952
> set dns image alpine:3.14.2

- operations/dnsmasq/Dockerfile
This PR updates the dns container to 3.15.4, after testing confirmed 3.16.0 breaks dns
> updating dns container to 3.15.4

- prime-router/src/main/kotlin/SubmissionReceiver.kt
This PR ensures the correct error message is returned for incorrect HL7 message types when submitted to the full ELR pipeline.
Test Steps:
1. Submit an HL7 message with a type other than OR_R01 to the full ELR pipeline
2. Verify the error message returned specifies that the type submitted is not supported.
- Update item logger to include index
> add index for item-scoped error message for invalid message type

- prime-router/settings/organizations.yml
- prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
This PR adds truncation limits for CE fields. This is needed particularly for OBX-17.
Test Steps:
1. pull branch and package then run  `./gradlew reloadSettings`
2. `./prime data --input <PATH TO TEST FILE> --input-schema primedatainput/pdi-covid-19 --output-dir <PATH TO OUTPUT FOLDER> --route`
- TEST FILE:  [sr-test-file-CA.csv](https://github.com/CDCgov/prime-reportstream/files/9049918/sr-test-file-CA.csv)
3. Check OBX-17.1 and ensure it is less than 20 characters
- add truncation list for CE to HL7_COMPONENT_MAX_LENGTH
- fixed some typos
> Add CE truncation limits

- operations/app/terraform/modules/function_app/candidate_slot.tf
- operations/app/terraform/modules/function_app/main.tf
- operations/app/terraform/modules/function_app/~inputs.tf
- operations/app/terraform/vars/prod/locals.tf
- operations/app/terraform/vars/prod/main.tf
- operations/app/terraform/vars/staging/locals.tf
- operations/app/terraform/vars/staging/main.tf
- operations/app/terraform/vars/test/locals.tf
- operations/app/terraform/vars/test/main.tf
This PR upgrades the function app runtime to version ~4 in the test environment, as support for lower versions will soon end.
The function app runtime version is parameterized to allow easy updates for staging and prod when we are ready.
Test Steps:
1. Confirm all function app functionality remains after the update
- Parameterize function app runtime version
- Change version in test environment from ~3 to ~4
- Fixes #6070
> set function app runtime as parameter and set test env to ~4

- frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx
This PR truncates an error message if it has the token "Exception:" and the newline character ("\n") - truncating at the first occurrence of the newline character
Since it's a very minor change and based on your refactor branch, I thought it made sense to just do a PR to it instead of going against master and then refactoring again to make it play nice with this branch. If there are any objections to this, I can redo vs master instead.
Test Steps:
1. Via the "/verify" admin page, upload a test file that normally produces a long unsightly stack trace
2. Observe its abbreviated form
- Added smol helper method to FileHandlerMessaging.tsx, to be called on each error row rendered
- *before*
*after*
- Addresses #6091
> experience/6091-human-readable: truncate an error message if stack trace

- prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
- prime-router/metadata/schemas/PrimeDataInput/pdi-covid-19.schema
This PR adds test_kit_name_id and equipment_model_id to the simple report schema. These fields are needed to uniquely identify test types in the LIVD table.
Test Steps:
1. Run test file through system locally
- ```./prime data --input /PATH/TO/FILE/SR-test-2.csv --input-schema primedatainput/pdi-covid-19 --output-dir /PATH/TO/DIR --route```
2. Ensure OBR-4 and OBX-3 fields are complete in output HL7
Test file: [SR-test-2.csv](https://github.com/CDCgov/prime-reportstream/files/9169604/SR-test-2.csv)
- test_kit_name_id and equipment_model_id to the simple report schema
- Fixes #5798 
- inform SR of new fields and coordinate sending based on LIVD table
> Onboarding ops/5798/testkit and equip uid for sr

- prime-router/docs/api/waters-submissions.yml
- prime-router/src/main/kotlin/Sender.kt
- prime-router/src/main/kotlin/history/SubmissionHistory.kt
- prime-router/src/main/kotlin/history/azure/DatabaseSubmissionsAccess.kt
- prime-router/src/main/kotlin/history/azure/HistoryDatabaseAccess.kt
- prime-router/src/main/kotlin/history/azure/SubmissionsFacade.kt
- prime-router/src/test/kotlin/history/SubmissionHistoryTests.kt
- prime-router/src/test/kotlin/history/azure/SubmissionFunctionTests.kt
This PR fixes the submissions list returning multiple entries for one submission.  I also got together with the UI team to verify all the fields they are using and updated the OpenAPI to match what is in the response.
Test Steps:
1. Check out this branch and run report stream.
2. Submit a report using your favorite sender.  Include the header `payloadname` with a custom report name, so you can see it in the response.
3. Do a GET on `api/waters/org/{{senderOrg}}/submissions` for the sender you used and verify 
a. `reporItemCount` has the correct number of items
b. `externalName` has your custom payloadname
c. `sender` has the complete sender name as in <org>.<service>
d. There is only one report per submission ID
4. Verify the OpenAPI spec matches this output.
Sample new API response:
``` …
```
> 6233 Fix submissions list returning multiple entries for one submission

- prime-router/src/main/kotlin/azure/HistoryFunctions.kt
- prime-router/src/test/kotlin/azure/HistoryFunctionsTests.kt
Many of our DHxxxxx group names in Okta are wrong, because they don't match the organization names in settings.   The problem is that the group names in Okta mostly use `_` where the settings mostly use `-`.  This has a been a continuing source of confusion, messy fixes, and bugs.
I've been experimenting with simply changing all the group names in Okta to be correct, to exactly match the settings names.  (eg, change from DHmd_phd to DHmd-phd)
This lovely fix appears to work (yay!), with one exception:  the old deprecated HistoryFunctions.kt has strange code in it that depends on the group name being wrong, that is, having a `_`.  (eg, DHmd_phd)  
This PR fixes that code, so that HistoryFunctions.kt will succeed even with good correct group names (eg, DHmd-phd) and also still work with …
> Enable HistoryFunction to accept both dashes and underscores

- prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
- prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
- prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
This PR allows the FHIR to HL7 library to use primitives in resource schema properties.
Test Steps:
1. Check out this branch.
2. Start the FHIR Path tool.  E.g. `./prime fhirpath -i src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir`
3. Set the resource to a primitive value (e.g. `resource = Bundle.id`)
4. Verify that just typing `%resource` returns the proper value for the resource.
5. Run the FHIR to HL7 conversion to verify that the conversion still works.  E.g., `./prime fhirdata --input-file src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir -s metadata/hl7_mapping/ORU_R01/ORU_R01-base.yml`
- FHIR to HL7 library allows use of primitives in resource schema property
- FHIR path CLI tool uses the same rule
- N/A
> FHIR to HL7 library allows use of primitives in resource schema property

- prime-router/docs/schema_documentation/dcipher-dcipher-monkeypox.md
- prime-router/docs/schema_documentation/monkeypox.md
- prime-router/metadata/schemas/dcipher/dcipher-monkeypox.schema
- prime-router/metadata/schemas/monkeypox.schema
- prime-router/metadata/valuesets/monkeypox.valuesets
- prime-router/src/main/kotlin/Report.kt
- prime-router/src/main/kotlin/azure/DatabaseAccess.kt
- prime-router/src/main/resources/db/migration/V55__add_normalized_code_values_elr_metadata.sql
This PR adds additional metadata columns for ELR and fixes bug with test performed fields. In specific we are looking to normalize some fields that are coming in with different values from the senders. For example, the test result text field (`OBX-5-2`) has different values per sender, even if they're using the correct code value in `OBX-5-1`. This causes some challenges and discrepancies in reading the data. To that end I've added in a column that normalizes the sender's value to the preferred values for the SNOMED code.
This has also been done for ordered test and performed test data, and I've added a column to collect the long name for the test based on the test code being used.
It also adds the specimen type code, specimen source site code, specimen collection method code, and …
> Adds additional metadata columns for ELR and fixes bug with test performed fields

- prime-router/metadata/fhir_mapping/hl7/resource/MessageSender.yml
- prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
- prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir
This PR fixes an issue in primeCLI that prevents processing of hl7 files with 5 delimiter characters, and updates messageSender config to fix a bug there.
Test Steps:
1. run fhirdata comment on a source hl7 with 5 delimiters, see it doesn't break
- replace 5 delimiters with 4 on hl7
- update messageSender hl7 source
> bugfixes from 5745

- prime-router/docs/getting-started/getting-started.md
This PR ...
Adds a section explaining how to use the prime CLI and the example use case of the HL7 -> FHIR data command.
It also removes the misleading sentence about documentation existing for the CLI in the README.
- This is a documentation change and needs to be read for clarity of communication. No unit tests needed
> Add PRIME CLI to getting started doc

- prime-router/src/test/kotlin/fhirengine/utils/CompareFhirDataTests.kt
Convert the `\t` characters to `  ` so the `ktlintFormat` will run for pre-commit git hooks.
> Remove tabs from CompareFhirDataTests.kt to keep linter happy

- frontend-react/src/content/live.json
- frontend-react/src/content/usa_w_territories.svg
This PR adds New York to the "where we're live" map and list
> Adds NY to the "where we're live" map and list

- prime-router/src/main/kotlin/cli/SenderFilesCommand.kt
This PR fixes a bug introduced via dependabot. A library was updated that deprecated a function being used by the sender-files tool. The echo function started failing. 
Test Steps:
1. docker down
2. ./gradlew clean package
3. docker up
4. query local database
- `select *
from covid_result_metadata`
5. Select message ID for a result
6. run sender-files command
- `./prime sender-files --message-id <messageID> -o /path/to/folder`
7. check that file was provided
- changed echo function
- Fixes #6705
> Sender-files tool fix

- frontend-react/docs/rs-error-boundary-and-suspense.md
- frontend-react/src/components/RSErrorBoundary.test.tsx
- frontend-react/src/components/RSErrorBoundary.tsx
- frontend-react/src/hooks/UseCreateFetch.ts
- frontend-react/src/pages/error/ErrorPage.tsx
- frontend-react/src/utils/RSNetworkError.ts
This PR creates and tests the new `RSErrorBoundary` (set to replace `NetworkErrorBoundary` from `rest-hooks`) and `RSNetworkError`, the first custom error type for our app that allows us to parse incoming network errors and (later) determine what content to display.
Test Steps:
1. `yarn test` to ensure no tests are broken
2. No integrations to test in the UI
- Adds new ErrorBoundary
- Adds new error type
- UseCreateFetch's axios call now will throw RSNetworkError instead of a normal error
- #issue
- …
> Fetch Refactor: New RSErrorBoundary and RSNetworkError

- prime-router/build.gradle.kts
- prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
- prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt
- prime-router/src/testIntegration/kotlin/FileNameTemplateIntegrationTests.kt
This PR addresses an issue where the AOE processing for the monkeypox messages was missing any OBX segments placed under the SPM segment which is legal and valid HL7, but does not match the assumptions we made using the terser.
This logic now converts the message we're working with to an `ORU_R01` message and then walks both areas where OBX's could live and looks at OBX-3 to see if they match the AOE question code we're looking for. Then the code actually attempts to coerce the OBX-5 value into its correct datatype (e.g. `DT`, `NM`, etc) and extract the identifier value we want.
Test Steps:
1. Pass a message through that has AOE OBX segments under the SPM value and see if they are correctly parsed.
2. Run the unit tests and integration tests
- Moved the AOE processing into the companion …
> Better AOE Processing

- frontend-react/src/components/AuthElement.test.tsx
- frontend-react/src/components/SenderModeBanner.test.tsx
- frontend-react/src/components/header/ReportStreamHeader.test.tsx
- frontend-react/src/contexts/AuthorizedFetchContext.test.tsx
- frontend-react/src/contexts/AuthorizedFetchContext.tsx
- frontend-react/src/contexts/SessionContext.test.tsx
- frontend-react/src/contexts/SessionContext.tsx
- frontend-react/src/hooks/UseValueSets.ts
- frontend-react/src/hooks/network/History/DeliveryHooks.test.ts
- frontend-react/src/hooks/network/Organizations/ReceiversHooks.test.ts
- frontend-react/src/pages/submissions/SubmissionTable.test.tsx
- frontend-react/src/utils/CustomRenderUtils.tsx
Currently there exists the possibility of making a request using the function output by `useAuthorizedFetch` before the js okta library has fully initialized. This means that requests can go out without an auth headers if made quickly enough after page load.
This change fixes this bug by:
* adding an `initialized` flag to tell the `useAuthorizedFetch` internals whether okta is ready to be used yet
* based on the value of this flag, telling useQuery whether or not it should be `enabled` (if an `enabled: false` option is passed to a `useQuery` invocation the hook will not run)
* outputting from `useAuthorizedFetch` an `rsUseQuery` function that is basically just `useQuery` with the `initialized / enabled` state management mentioned above folded into it
* using `rsUseQuery` instead of …
> fix: do not make useQuery requests with uninitialized okta [experience-unticketed]

- prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
- prime-router/docs/schema_documentation/direct-hca-covid-19.md
- prime-router/docs/schema_documentation/hl7-detect-covid-19.md
- prime-router/docs/schema_documentation/hl7-hcintegrations-covid-19.md
- prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19-prod.md
- prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19-training.md
- prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
- prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
- prime-router/docs/schema_documentation/hl7-mns-covid-19.md
- prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
- prime-router/docs/schema_documentation/hl7-primary-covid-19.md
- prime-router/docs/schema_documentation/hl7-signetic-covid-19.md
- prime-router/docs/schema_documentation/hl7-test-covid-19.md
- prime-router/metadata/schemas/HL7/hl7-ingest-covid-19.schema
- prime-router/metadata/schemas/covid-19.schema
This PR addresses the issue where OTC data came without ORC-22-4 (ordering_facility_state) and this was causing our api filters to exclude these OTC messages, coming from intrivo. The solution was to use the zip code lookup mapper to display the state.
Test Steps:
1. Create fake data for intrivo
2. Blank out ORC-22-4
3. Fire up docker
4. reloadtables and reloadsettings
5. Send to api and verify generated files have the state in ORC-22-4
6. Repeat with fake data having ORC-22-4 populated
- added new entry to hl7-ingest-covid-19.schema: `-name: ordering_facility_zip_lookup` and `-name: ordering_facility_state`
- Fixes #6780
> Intrivo - ORC-22-4 Blank

- frontend-react/src/components/AuthElement.test.tsx
- frontend-react/src/components/AuthElement.tsx
- frontend-react/src/contexts/SessionContext.test.tsx
- frontend-react/src/contexts/SessionContext.tsx
- frontend-react/src/hooks/__mocks__/UseOktaMemberships.ts
This PR removes the need for Admins to closely manage their Okta groups. Previously, if you okta groups claim contained anything other than PrimeAdmins, it would mess up admin auth depending on the order of claims. Now, instead, we hard check where hard admin requirements are required by looking at the `memberships` map and seeing if you have an admin membership anywhere, not just in your `activeMembership` slot.
Test Steps:
1. Go onto OktaPreview and change your user's Groups to include a receiver (DHxx_phd) and DHPrimeAdmins (in that order)
2. Login to your local on this branch
3. Try to navigate to an admin-only page like `/admin/settings`
You should be redirected back home.
- AuthElement now hard checks for admin permissions
- SessionContext now provides a memoized hard check for …
> Adds a hard check for admin auth in memberships map

- frontend-react/src/components/MessageTracker/MessageDetails.test.tsx
- frontend-react/src/components/MessageTracker/MessageDetails.tsx
- frontend-react/src/components/MessageTracker/MessageTracker.tsx
This PR 
Changed messageId to id
Removed inaccurate text
Test Steps:
1. rebuild RS
2. login as an admin to the front-end
3. place in the feature flag "message-tracker" if not there already
4. navigate to the Message id Search page
5. search for a message id that you think is in the database, case insensitive (i.e. Ohio11)
6. Select a message Id from the list
7. View Message Details
> Experience/7190 Patch

- frontend-react/src/components/MessageTracker/MessageDetails.tsx
Update to title when calling WarningsErrors component
Test Steps:
1. rebuild RS
2. login as an admin to the front-end
3. place in the feature flag "message-tracker" if not there already
4. navigate to the Message id Search page
5. search for a message id that you think is in the database, case insensitive (i.e. Ohio11)
6. Select a message Id from the list
7. View Message Details
- Fixes #7190
> Experience/7190 Update to title when calling WarningsErrors component

- prime-router/src/main/kotlin/azure/WorkflowEngine.kt
- prime-router/src/test/kotlin/azure/WorkflowEngineTests.kt
We track work-waiting-to-be-done in two places:    It gets queued in an Azure queue, and it gets a row in the TASK table in the database.
There appears to be an issue wherein in rare cases queued items are picked up and processed twice.    Examples of this are documented in #7404.  
The first successful run will update the TASK table, and change the "next_action" to NONE.    So, this double-procesing can be prevented by having the ProcessFunction check that the TASK table next_action value is PROCESS -- that is, the expected next_action in the TASK table matches the expected action found in the queue.   It was probably just an oversight that we were not checking this already - its just a basic assertion / sanity check.
This PR adds a check in ProcessFunction that the next_action in the …
> Abort ProcessFunction if the TASK table and queue entry don't match

- frontend-react/src/content/resources/index.ts
Removed out dated CSV related resources
Test Steps:
1. Go to [resources](https://reportstream.cdc.gov/resources)
2. Do not see the CSV schema documentation guide Card and the CSV upload guide card
> 7280 - fixed removed out dated CSV related resources

- frontend-react/src/pages/support/legacy-page-content/Contact.tsx
This changeset is a simple removal of the 'CSV upload' link on the ReportStream support page.  Pretty simple, but let me know if I'm missing something!
Test Steps:
1. Navigate to /support/contact
2. Verify that the "Read our guides for sending data" no longer includes the "CSV upload upload" link
Before:
After:
- <strike>[ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?</strike>
- <strike>[ ] Added tests?</strike>
- Fixes #7541
> Experience 7541: Remove CSV upload from Contact/Support page on RS Website

- frontend-react/src/hooks/network/History/DeliveryHooks.ts
- frontend-react/src/pages/submissions/SubmissionTable.test.tsx
- frontend-react/src/pages/submissions/SubmissionTable.tsx
- frontend-react/src/resources/SubmissionsResource.ts
Reverts CDCgov/prime-reportstream#7635
Currently this sorting fix causes a new issue: The if a user navigates past the 5th page the pages stop updating with values. This is because I messed up the calculation of the "cursor" value. Will revert this PR so we don't introduce this issue to production and will work on a fix.
> Revert "Experience/7358"

- .github/workflows/prepare_deployment_branch.yaml
So we can click a button to cut 'production' from 'master', not just rely on the cron jobs.
> adding ability to manually trigger the production branch creation action

- frontend-react/src/components/Admin/CompareJsonModal.test.tsx
- frontend-react/src/components/Admin/CompareJsonModal.tsx
- frontend-react/src/components/EditableCompare.tsx
This changeset updates the Organization settings highlighting UX flow to:
- Disable highlighting while the user is updating the textarea
- Add a 'Check syntax' button to reformat + highlight errors/changes
- Update the blur listener to reformat + highlight
It also includes a few minor/refactory updates to the code, which I'll point out in comments.
Test Steps:
1. Log in as a PrimeAdmin
2. …
> Experience 7448: Fix highlighting UX

- frontend-react/src/TelemetryService.test.ts
- frontend-react/src/TelemetryService.ts
- frontend-react/src/index.tsx
This PR ...
This changeset reverts the revert in https://github.com/CDCgov/prime-reportstream/pull/7740.  There are two main changes from that revert:
1) Always pass an instance of Error to `trackException`
Originally, we were passing in either an Error or a string depending on the arguments `console.error` was called with.  However, `exception` should be an instance of [Error or IAutoExceptionTelemetry](https://github.com/microsoft/ApplicationInsights-JS/blob/master/shared/AppInsightsCommon/src/Interfaces/IExceptionTelemetry.ts#L31) or we'll end up with a `not_specified` for the exception message.
2) Only tracking error-level messages
This is a deviation from SimpleReport so I'm happy to discuss and update if needed, but my feeling is that we don't have to track warnings just yet until …
> Experience-7607: Capture FE exceptions in Azure

- frontend-react/package.json
- frontend-react/src/components/AppWrapper.tsx
- frontend-react/yarn.lock
This PR ...
This changeset adds the ReactQueryDevtools utility to our codebase to let us more easily debug query/mutation statuses in development mode.  When the devtools are open, you can see the statuses of queries and mutations ("mountedness" and staleness), and you can retrigger them or even delete them from the cache entirely.
There's also a possibility of lazy-loading the devtools in production mode if we need that, but I think we can just include it in development for now.
Test Steps:
1. Start up the local Webpack dev server: `yarn run start:localdev`
2. Load up any page
3. Look for the devtools icon on the lower-left corner
4. Start making requests through react-query and see the devtools populate
<strike>- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker …
> Experience-7857: Add ReactQueryDevtools for query/mutation debugging

- prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
This PR doubles the polling time for smoke test steps, since staging is inconsistent.
> double polling time for smoke test step checking

- prime-router/metadata/fhir_mapping/hl7/resource/DiagnosticReport.yml
- prime-router/metadata/fhir_mapping/hl7/resource/ServiceRequest.yml
- prime-router/metadata/fhir_mapping/hl7/secondary/Collection.yml
- prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir
- prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0006.fhir
- prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0014.fhir
- prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_2_20220803-0001.fhir
This PR updates the Service Request and Diagnostic Report resources from the HL7 v2 OBR segment using the latest HL7 v2 to FHIR mapping documents. It also added some mapping between OBR and the Specimen resource.
[Updated mapping documents for OBR](https://cdc.sharepoint.com/:x:/r/teams/USDSatCDC/_layouts/15/Doc.aspx?sourcedoc=%7B3FE6736B-8FD5-48D0-8908-F2D2E323B952%7D&file=HL7%20to%20FHIR%20-%20OBR%20Segment.xlsx&action=default&mobileredirect=true&cid=e4c27b8f-bd2e-43f6-a5c5-877a9941c36a), copy of file attached:
[HL7 to FHIR - OBR Segment.xlsx](https://github.com/CDCgov/prime-reportstream/files/10460810/HL7.to.FHIR.-.OBR.Segment.xlsx)
Test Steps:
1. Build this branch and run the unit and integration tests. Verify they all pass. Alternatively you can verify the Github Actions build …
> OBR hl7v2 to fhir mapping updates

- operations/dnsmasq/config/staging/hosts.local
Quick change so VPN users will resolve the _old_ DB's FQDN to restore2. This should allow them to run prime test without changing scripts etc.
> change staging to look at restore2 when using old FQDN

- frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx
- frontend-react/src/components/StaticAlert.test.tsx
- frontend-react/src/components/StaticAlert.tsx
- frontend-react/src/components/alerts/AdminFetchAlert.tsx
- frontend-react/src/components/alerts/NoServicesAlert.tsx
- frontend-react/src/hooks/UseOrganizationReceivers.ts
- frontend-react/src/hooks/UseOrganizationReceiversFeed.test.ts
- frontend-react/src/hooks/UseOrganizationReceiversFeed.ts
- frontend-react/src/hooks/UseOrganizationSettings.test.ts
- frontend-react/src/hooks/UseOrganizationSettings.ts
- frontend-react/src/hooks/network/History/DeliveryHooks.test.ts
- frontend-react/src/hooks/network/History/DeliveryHooks.ts
- frontend-react/src/network/QueryClients.ts
- frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
- frontend-react/src/pages/deliveries/Table/DeliveriesTable.test.tsx
- frontend-react/src/pages/deliveries/Table/DeliveriesTable.tsx
- frontend-react/src/pages/submissions/SubmissionTable.test.tsx
- frontend-react/src/pages/submissions/SubmissionTable.tsx
This changeset disables a few Organization-specific requests to mitigate the number of 404s we're getting as admins try to fetch Organization resources:
- Organization settings
- Deliveries
- Submissions
There's not a one-size-fits-all solution here given the different fetch mechanisms we already have and how the data is rendered, so I tried to add minimal changes to prevent disrupting anything down the line.  I think going forward, we can make a generic `useOrganizationQuery` hook (or whatever) that'll automatically be disabled if the user is logged in as an admin without impersonating an Organization.  There are a lot of layers with our fetching that in my opinion should be untangled, but that's out of the scope of this pull request.
Test Steps:
2. Open the network …
> Experience-7891: Disable organization-specific fetches as admin

- frontend-react/src/content/live.json
- frontend-react/src/content/usa_w_territories.svg
This PR ...
Turns Utah Blue on the public map
Test Steps:
1. In RS, navigate to Product -> Where we're live
2. See that Utah is listed and the state is blue on the map
> 8129 Turn Utah Blue on the public map

- prime-router/examples/generate-jwt-python/generate-jwt.py
Modified python script to allow for variable Sender, instead of just 'default'
This PR changes an example script, not used in our code.  The change is to allow both the Organization name and the Sender name to be variables set by the user.  Previously the Sender was hardcoded to 'default'.
> Modified example to allow for variable Sender

- frontend-react/src/components/FileHandlers/FileHandler.test.tsx
- frontend-react/src/components/FileHandlers/FileHandler.tsx
- frontend-react/src/components/FileHandlers/FileHandlerForm.test.tsx
- frontend-react/src/components/FileHandlers/FileHandlerForm.tsx
- frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx
- frontend-react/src/hooks/UseCreateFetch.ts
- frontend-react/src/hooks/UseFileHandler.test.ts
- frontend-react/src/hooks/UseFileHandler.ts
- frontend-react/src/hooks/UseSenderResource.ts
- frontend-react/src/hooks/network/WatersHooks.test.ts
- frontend-react/src/hooks/network/WatersHooks.ts
- frontend-react/src/pages/Validate.tsx
- frontend-react/src/senders/hooks/UseSenderSchemaOptions/UseSenderSchemaOptions.test.ts
- frontend-react/src/senders/hooks/UseSenderSchemaOptions/index.ts
This PR ...
This changeset adds a dropdown to the validator page to allow the user to select between schema options to validate against.  To accommodate this, I've added a `useSenderSchemaOptions` hook that always returns the three "master" schemas" in addition to the designated Sender schema if the current user is logged is as a Sender.
This also includes a decent amount of cleanup/rewrites because the logic in useFileHandler, FileHandler, and FileHandlerForm is oddly coupled together.  Will comment below!
To generate test files to validate against different schemas, you can use the CLI tool:
```
./prime data --input-fake <item_count> --input-schema <schema> --output <output_destination>
```
like:
```
./prime data --input-fake 10 --input-schema hl7/hcintegrations-covid-19 --output …
```
> Experience-7773: Add schema dropdown on validator page

- frontend-react/src/App.tsx
- frontend-react/src/components/AppWrapper.tsx
- frontend-react/src/components/SenderModeBanner.test.tsx
- frontend-react/src/contexts/SessionContext.tsx
- frontend-react/src/utils/CustomRenderUtils.tsx
This changeset removes the makeOktaHook logic that's fed into SessionProvider and a few test utilities.  There's a temporary workaround to fall back on an empty object in SessionProvider from the `useOktaAuth` call -- this is to account for components being rendered outside of Okta's Security Provider, in which case `useOktaAuth` calls return `null`.  This will be fixed as part of [#8292](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/8292); it'd just be easier to remove this logic beforehand.
Ultimately, there's no reason for us to have to pass a stand-in for `useOktaAuth` as a prop when we could just mock it if we really need to.
Test Steps:
N/A
<strike>- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker …
> Experience-8161: Remove makeOktaHook logic

- frontend-react/cypress.config.ts
- frontend-react/cypress/support/commands/auth.ts
- frontend-react/cypress/support/pages/Base.ts
- frontend-react/package.json
- frontend-react/yarn.lock
Fixes #8055
This PR updates cypress to v12 and updates related dependencies to their latest versions. ESLint rules were modified (as suggested here: **https://github.com/testing-library/eslint-plugin-testing-library/discussions/533#discussioncomment-1949661**) to not use testing-library rules on cypress files to fix false-positives. ESLint plugin chai-friendly was added to cypress ruleset to allow unused-expressions on chai method chains.
> Upgrade to Cypress v12

- .environment/yarn/run-yarnCheck.sh
Fixes #8363
This PR fixes a bug from my yarn integrity check addition whereas developers making changes outside of frontend-react are forced to install node/yarn due to the script not verifying if a yarn integrity check is necessary. The script will now check if package.json and/or yarn.lock has been changed before trying to call the integrity check which should return pre-commit back to previous expected behavior.
> Only run yarn integrity check when package.json/yarn.lock changed

- prime-router/docs/schema_documentation/csv-otc-covid-19.md
- prime-router/docs/schema_documentation/direct-abbott-covid-19.md
- prime-router/docs/schema_documentation/direct-anavasidx-covid-19.md
- prime-router/docs/schema_documentation/direct-cue-covid-19.md
- prime-router/docs/schema_documentation/direct-direct-covid-19.md
- prime-router/docs/schema_documentation/direct-direct-otc-covid-19.md
- prime-router/docs/schema_documentation/direct-directlite-covid-19.md
- prime-router/docs/schema_documentation/direct-genabio-covid-19.md
- prime-router/docs/schema_documentation/direct-ihealthlabs-covid-19.md
- prime-router/docs/schema_documentation/direct-imagemover-covid-19.md
- prime-router/docs/schema_documentation/direct-inbios-covid-19.md
- prime-router/docs/schema_documentation/direct-pmg-covid-19.md
- prime-router/docs/schema_documentation/direct-safehealth-covid-19.md
- prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
- prime-router/docs/schema_documentation/experity-experity-covid-19.md
- prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
- prime-router/docs/schema_documentation/hhsprotect-hhsprotect-covid-19.md
- prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
- prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
- prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
- prime-router/docs/schema_documentation/upload-covid-19.md
- prime-router/metadata/schemas/Experity/experity-covid-19.schema
- prime-router/metadata/schemas/csv-otc-covid-19.schema
- prime-router/metadata/schemas/direct/direct-covid-19.schema
- prime-router/metadata/schemas/direct/direct-otc-covid-19.schema
- prime-router/metadata/schemas/direct/directlite-covid-19.schema
- prime-router/metadata/schemas/iPatientCare/iPatientCare-covid-19.schema
- prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema
- prime-router/metadata/schemas/upload-covid-19.schema
This PR add abnormal_flag to sender CSV schemas so it can be used in receiver filtering.
Test Steps:
1. Copy settings from attached file for il into local organizations.yml file
2. Run ./prime data command with attached test file for organization with csv-upload-covid-19 schema
3. Expected output from test file:
- For receiver il-phd.elr-antigen - produce 1 output HL7 message with a positive result for an antigen test
- For receiver il-phd.elr-molecular - produce 2 output HL7 messages (1 positive, 1 negative) for a molecular test
IL wants to receive all molecular test results +positive results for antigen tests, all other tests should be filtered out.
- adds abnormal_flag to 
- [ x] Tested locally?
- [x ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream …
> Add abnormal_flag to sender CSV schemas

- frontend-react/yarn.lock
Just noticed this smallllllll update to the yarn.lock when installing on Node v16.19.1
> chore: update yarn.lock

- frontend-react/src/components/Table/TableFilters.test.tsx
- frontend-react/src/components/Table/TableFilters.tsx
- frontend-react/src/hooks/filters/UseDateRange.test.ts
- frontend-react/src/hooks/filters/UseDateRange.ts
- frontend-react/src/hooks/filters/mocks/MockFilterManager.ts
This PR ...
Fixes bug - Typing non-numeric characters into date range filter fields errors out
Test Steps:
1. Log into RS
2. Select a State(For Daily Data) or a Federal(For Submissions) organization
3. Go to Daily Data and enter in a non-numeric character into the start range and/or end range
4. Click Filter
5. Notice that an error is not thrown and the table lists the default result set
Added check for valid date before calling toISOString.
Added startDateHint to DateRangePicker
- #7998
> 7998 date range filter bug fix

- frontend-react/src/senders/hooks/UseSenderSchemaOptions/index.ts
This changeset updates the HL7 schema option for the validator. Incorrect: `standard/standard-covid-19`
Correct: `hl7/hl7-ingest-covid-19-prod`
Test Steps:
2. Go to /file-handler/validate
3. Click on the "Select a schema" dropdown and choose `hl7/hl7-ingest-covid-19-prod`
4. Ensure validation works with an HL7 file with the selected schema
<strike>- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?</strike>
<strike>- [ ] Added tests?</strike>
- Fixes #8565
> Experience-8565: Fix incorrect HL7 schema for validator options

- frontend-react/docs/test-conventions.md
This changeset adds an initial doc for test conventions we want to maintain in frontend-react.
Still some todos, which will be broken out into a separate ticket or two:
- Mocking and tautological tests
- Different types of tests (unit, integration, end-to-end) and when to use them
- Jest tips
- Cypress tips
> Experience-6693: Add doc for front-end test patterns

- frontend-react/src/hooks/UseFileHandler.ts
- frontend-react/src/utils/TemporarySettingsAPITypes.test.ts
- frontend-react/src/utils/TemporarySettingsAPITypes.ts
Pretty simple change!  Just adding FHIR as an available format in addition to CSV and HL7.  This'll allow us to update Sender formats through the admin Organization settings view.
Test Steps:
2. Go to the Organization settings page
3. Choose an Organization with a Sender service and click 'Edit'
4. Click the Format dropdown --> ensure that `FHIR` shows up as an option and that it can be saved as such
<strike>- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?</strike>
<strike>- [ ] Added tests?</strike>
- Fixes #8602
> Experience-8602: Add FHIR format to list of options

- frontend-react/src/network/api/Organizations/SettingRevisions.ts
This changeset updates the setting revision query key to be cached on the Organization and setting type (Sender|Receiver).  Originally, it was being cached on the strings "org" and "settingType" verbatim, which means that all revision histories would get the same response that's in the query cache.  This just updates the query key to be more dynamic.
Test Steps:
2. Choose an Organization with multiple Sender/Receiver channels to edit
3. Click on the different "History" links (using the back button/without refreshing the page) and verify that only the correct revision histories are shown for the specific setting type (Organization|Sender|Receiver)
<strike>- [ ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?</strike>
- Fixes …
> Experience-8549: Fix incorrect setting type history

- frontend-react/docs/best-practices.md
This changeset is just introducing an initial "best practices" doc for working within the frontend-react side of things.  I'm hoping our team can keep adding to it as we encounter and build out new patterns.
There are still lots and lots of things to write about, and I'll split those up into separate tickets:
- More styleguide conventions
- Using react-query: our approach to resources/collections, our treatment of the query cache (and mocking it in the test conventions doc)
- React patterns and optimizations (hooks versus HOCs, references)
- A billion other things
> Experience-8433: Add initial best practices doc

- frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
- frontend-react/src/components/Admin/AdminReceiverDashboard.tsx
- frontend-react/src/components/Admin/OrgsTable.tsx
- frontend-react/src/components/Content/PageGenerationTools.tsx
- frontend-react/src/components/Content/Templates/IACardGridTemplate.tsx
- frontend-react/src/components/Crumbs.tsx
- frontend-react/src/components/FileHandlers/FileHandler.tsx
- frontend-react/src/components/HipaaNotice.tsx
- frontend-react/src/components/MessageTracker/MessageDetails.tsx
- frontend-react/src/components/MessageTracker/MessageTracker.tsx
- frontend-react/src/components/Table/Table.tsx
- frontend-react/src/components/Table/TableFilters.tsx
- frontend-react/src/pages/admin/AdminLastMileFailures.tsx
- frontend-react/src/pages/admin/AdminMain.tsx
- frontend-react/src/pages/admin/AdminMessageTracker.tsx
- frontend-react/src/pages/admin/AdminReceiverDashPage.tsx
- frontend-react/src/pages/deliveries/Deliveries.tsx
- frontend-react/src/pages/deliveries/Table/DeliveriesTable.tsx
- frontend-react/src/pages/deliveries/details/DeliveryDetail.tsx
- frontend-react/src/pages/deliveries/details/DeliveryFacilitiesTable.tsx
- frontend-react/src/pages/deliveries/details/DeliveryInfo.tsx
- frontend-react/src/pages/deliveries/details/Summary.tsx
- frontend-react/src/pages/resources/Resources.tsx
- frontend-react/src/pages/submissions/SubmissionDetails.tsx
- frontend-react/src/pages/submissions/Submissions.tsx
- frontend-react/src/pages/support/Support.tsx
- frontend-react/src/styles/_uswds_overrides.scss
This changeset updates the follow pages' containers to be widescreen (up to 1400px) since they're the most data-heavy:
- Daily Data
- Submissions
- Message Tracker
The Public Validator page will continue to be on 1024px to align with the rest of the public pages.
Additionally, there's some cleanup regarding containers in the codebase across several different pages, and I've updated `grid-container` modifier classes to use the GridContainer component instead.  There are a lot of `grid-container` modifier classes used around the codebase, and it really shouldn't be used this much; it should be used at the highest ancestor node of common width, and all descendants should naturally expand to their own widths inside of that.  The grid container sets a maximum width, yes, but it also includes …
> Experience-8026: Widen grid container

- frontend-react/src/components/Admin/EditSenderSettings.test.tsx
- frontend-react/src/components/Admin/EditSenderSettings.tsx
- frontend-react/src/components/Admin/NewSetting.tsx
- frontend-react/src/utils/misc.test.ts
- frontend-react/src/utils/misc.ts
This changeset relaxes the Organization/service name validation to allow letters, numbers, hyphens, and underscores, and it removes the reserved word restrictions we had previously.  This was causing issues with current Sender/Receiver settings, and as far as I know, we haven't run into issues with them in production anyway.  I think it'd probably be best to run this validation on the back end instead of the front end since the user can make the PUT themselves with invalid names, but this is just a helpful reminder to admins to stay in line with our naming conventions.  Tests have been updated as well.
Test Steps:
2. Go to /admin/settings and choose an Organization
3. Add a new service with only letters/numbers/hyphens/underscores --> verify success + saved
4. Add a …
> Experience 8616: Relax Organization/service name validation

- prime-router/docs/api/validate.yml
- prime-router/src/main/kotlin/azure/ValidateFunction.kt
- prime-router/src/test/kotlin/azure/ValidateFunctionTests.kt
This changeset updates the validation endpoint to still return 200 if there are only validation errors.  We should still continue to return 4xx/5xx for _real_ errors, but catching validation errors is unexceptional logic for the validator -- that's working as expected.
Test Steps:
1. Submit a file with only errors to the /validate endpoint, expect:
- 200 response code is received
- `overallStatus` to equal `Error`
- `errors` to be populated with expected errors
- `warnings` to be empty
2. Submit a file with only warnings to the /validate endpoint, expect:
- 200 response code is received
- `overallStatus` to equal `Valid`
- `errors` to be empty
- `warnings` to be populated with expected warnings
3. Submit a file with both errors and warnings to the /validate endpoint, expect:
- 200 …
> Experience-8170: Update validate endpoint to return 200 for strictly validation errors

- prime-router/build.gradle.kts
This PR updates `JaCoCo` from 0.8.8 to 0.8.9. This adds support for JDK 19 and 20.
This PR does *not* change the project to use JDK 19. See also #8206 
Changelog: https://www.jacoco.org/jacoco/trunk/doc/changes.html
Test Steps:
1. Build the branch using JDK 17 or 18 and verify it is successful.
2. Verify the Github build is successful.
- Update `JaCoCo` from 0.8.8 to 0.8.9.
> Bump jacoco from 0.8.8 to 0.8.9

- prime-router/src/test/kotlin/azure/ApiKeysFunctionsTest.kt
This PR updates a test case to not mock System
Test Steps:
1. Run the tests
- Mocks `JwkSet.Companion` rather than System for testing the JwkSet key limit
- Fixes #8981 
- …
> 8981: mock JwkSet companion rather than System.get

- prime-router/src/main/kotlin/azure/ApiKeysFunctions.kt
- prime-router/src/test/kotlin/azure/ApiKeysFunctionsTest.kt
This PR fixes the bug where the api key is not persisted via the POST endpoint due to a typo in the `putSetting` call
Test Steps:
1. Add an api key
```sh
curl --location 'http://localhost:7071/api/settings/organizations/simple_report/public-keys?scope=simple_report.*.report&kid=simple_report' \
--header 'Authorization: Bearer dummy' \
--header 'Content-Type: text/plain' \
--data '-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu/iNl3p3b0G4a5AbhycX
0gnzszqSjMP7NJygno4UfF8HA+jLKqKXbG93ywyvbau+Rm1J7wbVb5hYWx3jvXt2
7LfQea1XgMF67O2Xo7bJ7U5NSceVVrtAA/IIq5sqolrxcVQ5LbGkuVqVTKwMtgs2
pe+sj6GcgdjhRnxLCN0Ex4xB7RtsieIvqwqEi4ds+sbLAs9fHMumcGzvyDLQpNGW
avOMqpXM1WqNauzOn4mgECu4BJuHPu7gXIPAkrVwLRF0LcSs7Js37uWtg04FxTz8
6sv0kYwqYXDJNcrCd+3S5cbQTGvdLAbUvvZ3vassfrxbQGFKJEt51iiHW7U/CaX8 …
```
> 8991: use correct name for putSetting and add test for api-key persist failure

- frontend-react/config/webpack.config.js
Fixes #9000
This PR updates the mdx loader config for webpack to target only mdx files and not md so they can be consumed by react-markdown as normal.
> Update MDX loader to ignore md files

- frontend-react/package.json
In https://github.com/CDCgov/prime-reportstream/pull/9019, we removed the `storybook:start` command, but it was being used for the base `storybook` command.  This changeset just restores the command so everything works again.
> Experience-9235: Fix storybook command

- prime-router/src/main/kotlin/cli/tests/LivdApiTest.kt
- prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
This PR increases some of the timeouts in the smoketests as they were occasionally failing.
Test Steps:
n/a
- Sets the livdapi timeout in smoke tests to 75000ms
- Sets the polling timeout for testing submissions to 480 seconds
- Fixes #issue
- #issue …
> 9233: increase livdapi and reportstream poll smoketest timeouts

- .gitignore
This PR ...
adds **/.bin to .gitignore
** Testing **
```
prime-reportstream % touch test.bin
prime-reportstream % git status
On branch devops/jmp/gitignore
Your branch is up to date with 'origin/devops/jmp/gitignore'.
nothing to commit, working tree clean
```
> add .bin files to gitignore

- .github/workflows/dependency_review.yml
This PR is to make the Dependency review action to run only on Pull requests, Currently it is set to run on pushes to master and production branches and causing failures while running the action as both a base ref and head ref must be provided, either via the `base_ref`/`head_ref` config options
> Dependency review update to run only on PRs

- frontend-react/src/AppRouter.tsx
- frontend-react/src/content/resources/api-programmers-guide/Sidenav.mdx
- frontend-react/src/content/resources/api-programmers-guide/getting-started/GettingStarted.mdx
- frontend-react/src/pages/resources/api-programmers-guide/documentation/DataModel.stories.tsx
- frontend-react/src/pages/resources/api-programmers-guide/documentation/Documentation.stories.tsx
- frontend-react/src/pages/resources/api-programmers-guide/documentation/ResponsesFromReportStream.stories.tsx
- frontend-react/src/pages/resources/api-programmers-guide/documentation/SamplePayloadsAndOutput.stories.tsx
Fixes #9613
This PR updates the api programmer's guide url structure to be pages under /resources/api.
> Route Resource Page Link to the new API Programmer's Guide

- prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
This PR attempts to fix an issue causing smoke tests to fail on the staging environment.
Test Steps:
1. Run smoke tests and check for failures.
- Alter logic to allow the test to wait for query results longer
> Attempt to fix failing smoke test

- frontend-react/.env.preview
- frontend-react/package.json
- frontend-react/vite.config.ts
Fixes #10715
This PR:
- adds a new `preview` script that builds and runs `vite preview` under the `preview` environment
- adds a new `.env.preview` file
- adds the current CSP header given on the live site to the preview server
- hhs-prime.okta.com swapped to hhs-prime.oktapreview.com
> Experience: vite preview

- frontend-react/package.json
- frontend-react/postcss.config.cjs
- frontend-react/yarn.lock
Fixes #10717
This PR adds the missing `autoprefixer` dev dependency that was lost during vite migration (for browser autoprefixing on CSS).
> Missing autoprefixer

- .github/dependabot.yml
This PR fixes `@typescript-eslint` so that it is grouped inside the typescript group.
> Include typescript-eslint in typescript group

- prime-router/build.gradle.kts
- prime-router/gradle.properties
- prime-router/src/main/kotlin/azure/DatabaseAccess.kt
This PR bumps flyway and flyway-core to 9.21.1 and makes a change to Gradle properties to support new configuration options.
Building on #10512, the configuration changes to set flyway to use session locks has already been added to the code, but at the time the flyway 9.8.3 and 9.9.0 updates were previously tested in RS there was [an issue with flyway](https://github.com/flyway/flyway/issues/3682) not obeying the configuration flag. This has since been corrected upstream as of flyway 9.19.4.
Test Steps:
1. Ensure all smoke tests pass.
- Bumps flyway and flyway-core to 9.21.1.
- Change Gradle properties to configure flyway to run without transactional locks.
- #10865
- Supercedes #9090 and #10650.
- #10526
> Bump flyway and flyway-core to 9.21.1

- prime-router/settings/organizations.yml
This PR Fixes an issue where ORM messages would get routed to Ignore.ETOR-TI receiver and would fail translation
Test Steps:
1. run `./prime multiple-settings set --input /Users/arnej/Projects/prime-reportstream/prime-router/settings/organizations.yml `
2. Configure and run "Send HL7v2 Message" from the Postman collection: 
[CDC.postman_collection.json.zip](https://github.com/CDCgov/prime-reportstream/files/12432257/CDC.postman_collection.json.zip)
3. Verify no translation error occurs and Ignore.ETOR-TI was not a receiver
> Fix filter for ignore.etor-ti receiver

- frontend-react/src/utils/UserUtils.ts
Fixes #9609
This PR changes the order of operations on logout so that localstorage is cleared BEFORE initiating the okta library's signOut function. This ensures that the okta library doesn't prevent the clearage.
> [SPIKE] Org/Status not being cleared after logging out of site

- prime-router/build.gradle.kts
This PR updates `JaCoCo` from 0.8.9 to 0.8.10. This addresses a regression introduced in 0.8.9.
Changelog: https://www.jacoco.org/jacoco/trunk/doc/changes.html
Test Steps:
1. Verify the build is successful.
- Update `JaCoCo` from 0.8.9 to 0.8.10.
> Bump jacoco from 0.8.9 to 0.8.10

- frontend-react/src/shared/LiveMap/LiveMap.tsx
Remove testimonials on homepage based on this Slack comment: 
**Note:** leaving the content itself as-is since we may use it in the future.
Screenshot:
> Remove Homepage Testimonials

- .github/ISSUE_TEMPLATE/platform-user-story.md
This PR removes the pipeline label from being automatically added when the Platform User Story issue template is used.
- Remove pipeline label from default labels in Platform User Story template
> Remove pipeline label from Platform User Story template

- operations/app/terraform/modules/application_insights/alert_response_time.tf
This PR is to Configure pdhprod-504-alert via Terraform code
Terraform detected the following changes made outside of Terraform since the last "terraform apply":
```
~ resource "azurerm_postgresql_server" "postgres_server" {
id                                = "/subscriptions/7d1e3999-6577-4cd5-b296-f518e5c8e677/resourceGroups/prime-data-hub-prod/providers/Microsoft.DBforPostgreSQL/servers/pdhprod-pgsql"
name                              = "pdhprod-pgsql"
~ sku_name                          = "GP_Gen5_16" -> "MO_Gen5_32"
~ storage_mb                        = 342016 -> 1048576
tags                              = {
"environment" = "prod"
}
~ storage_profile {
~ storage_mb            = 342016 -> 1048576
}
}
~ resource "azurerm_log_analytics_workspace" "law" {
id                         = …
```
> update terraform code with 504 FA alert

- operations/app/terraform/vars/demo/main.tf
Added missing OKTA variable references in the `function_app `module in DEMO environment.
Test Steps:
1. `terraform plan -var-file=$env/env.tfvars.json` should now pass.
> Added missing OKTA variable references in function_app module in DEMO env

- prime-router/docs/design/design/mapping-schemas.md
This PR adds documentation on mapping schema organization.
The intention is to slowly update to the new file structure as mapping work is completed.
- Add mapping schema organization documentation.
- #11472
> 11472 add mapping schema organization document

- prime-router/src/main/kotlin/azure/CheckFunction.kt
- prime-router/src/main/kotlin/transport/RESTTransport.kt
This PR This PR fixed the alive checking function for flexion REST endpoint.
Test Steps:
1.) Setup flexion in the localhost.
2.) Run curl command below
curl "http://localhost:7071/api/check?sftpcheck=flexion.etor-service-receiver"
3.) Output screenshot:
- Fixes #issue
- #issue
- Does this PR …
> Fixed Flexion REST Alive Check rebased

- .environment/sftp/get_ssh_list.sh
Fixed `get_ssh_list.sh` to work on Bash versions prior to v4.
Test Steps:
1. Run Terraform _or_ `get_ssh_list.sh` separately
- This PR fixes `get_ssh_list.sh` to work on Bash versions prior to v4. `^^` case transformation does not work in Bash prior to v4, which is what comes with MacOS by default. I.e. this does not work: `upper_env=${environment^^}`
> Fixed get_ssh_list.sh to work on Bash versions prior to v4.

- operations/app/terraform/modules/application_insights/alert_availability.tf
Reverted the SFTP availability test from `alert_availability.tf` because there is unresolved connectivity issue from the admin app to SFTP containers.
Test Steps:
1. `terraform apply` should not create a new availability check in App Insights. 
- Reverted the SFTP availability test from `alert_availability.tf` because there is unresolved connectivity issue from the admin app to SFTP containers.
> Removing app insights availability check for the sftp container

- frontend-react/src/hooks/network/DataDashboard/UseReceiverDeliveries.ts
- frontend-react/yarn.lock
This PR ...
Fixes the issue where the Data dashboard will not load if the reciever does not have a service defined in their active membership
Test Steps:
1. Log into RS as a receiver i.e. Alaska
2. Navigate to Data dashboard
- removed the activeMembership.service enabled check when calling the endpoint.
- Fixes #12352
> 12352 - removed activeMembership.service check since not all receiver have a service defined i.e."default"

- prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
- prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/ConstantResolverTests.kt
This PR stops an attempted integer cast that is resulting in an overflow error in production.
Test Steps:
1. Run tests
- Do not cast values to Integer in `ConstantResolver.kt`
- Adjust related tests to expect String
- Fixes #12609
- Decide what the path forward is (will we try again to cast? maybe fallback to string?)
> Fix overflow during integer parse of constants

- prime-router/build.gradle.kts
This PR fixes the log4j dependency so that it's pinned to a specific version.
Test Steps:
CI is enough
- Fixes the dependency declaration for log4j so it's pinned to 2.22.0
> Pin log4j version to 2.22.0

- frontend-react/src/content/developer-resources/reportstream-api/documentation/SamplePayloadsAndOutput.mdx
This PR ...
Removed the Example Data Models from API Guide
Test Steps:
1. Go to RS
2. Click on the Developers tab
3. Click on the API guide
4. Click on Sample payloads and output
5. Notice the section has been removed
- Fixes #12347
> 12347 - Removed the Example Data Models from API Guide

- prime-router/docs/getting-started/standard-operating-procedures/observation-mapping-table.md
This PR adds documentation that covers retrieving source bundles with unmappable conditions.
Test Steps:
1. Submit `valid.fhir` to the receiver `development.dev-elims` (may have to change topic/format)
```zsh
curl --location 'http://localhost:7071/api/reports' --header 'client: development.dev-elims' --header 'Content-Type:application/fhir+ndjson' --data-binary @/Users/gabriel/dev/focus/prime-reportstream/prime-router/src/test/resources/fhirengine/engine/routing/valid.fhir
```
2. Run the query and verify the output matches what is expected
- Added SOP for retrieving unmappable conditions
- Fixes #12283
> Added documentation for retrieving unmapped bundles

- .github/workflows/alert_PD_schedule_Slack.yml
This PR is to change the on call schedule PD alert to go to prime-reportstream-engineering instead of going to pagerduty-alert-dump
> change PD Alert to prime-reportstream-engineering

- prime-router/docs/design/proposals/0024-original-message-passthrough.md
This PR updates the original passthrough design to reflect findings around the existing `payloadname` API header. There are no code changes.
- Update original passthrough feature design with findings on existing `payloadname` parameter.
- #12813
> Update original passthrough design with payloadname finding

- prime-router/src/main/resources/db/migration/V67__update_list_send_failure.sql
This PR corrects an issue with the Last Mile Failures API.
A known caveat with this change is that send failures that predate the message format change will now return an error. In production, the last instance of a send error using the deprecated message format occurred on December 6, 2023.
Test Steps:
1. Create the test data:
```
INSERT INTO public.action(
action_name, action_params, action_result, created_at, receiving_org, receiving_org_svc)
VALUES ('send_error', '{"type":"report","eventAction":"SEND","emptyBatch":false,"reportId":"d0e999c6-d819-41f1-bf08-083f0e8e091c","at":""}', '"FAILED Sftp upload of inputReportId d0e999c6-d819-41f1-bf08-083f0e8e091c to SFTPTransportType(host=sftp, port=22, filePath=./upload, credentialName=DEFAULT-SFTP-PPK) (orgService = ignore.HL7_BATCH_PPK), …
```
> 13073 fix last mile failures api

- prime-router/src/main/kotlin/fhirengine/utils/FHIRBundleHelpers.kt
This PR removes exception handlers from the coding lookup extension function intended to swallow specific exceptions thrown during testing. There are no other changes.
Test Steps:
1. Ensure all smoke tests pass.
- Removed exception handlers from the coding lookup extension function.
- #12750
> 12750 remove exception handling from coding extension function

- prime-router/src/main/kotlin/tokens/OktaAuthentication.kt
This PR quiets down JWT exception logging. This should solve the issue of constant PagerDuty alerting.
Test Steps:
1. Attempt to authenticate without a valid JWT
2. Check the exceptions table to ensure no `JWTVerificationException` shows up
- Move exception out of parameters and add the message directly to the string
- Fixes #13825
> 13825: quiet JWT exception logging

- prime-router/src/main/kotlin/fhirengine/utils/HL7Reader.kt
This PR stops logging the expected exception during HL7 parsing to reduce PagerDuty alerts.
I also took the liberty of cleaning up the logging logic to use the log4j `Level` class rather than depending on some logging class found in an SSH library.
Test Steps:
1. See that parsing errors are no longer ending up in the exceptions table in Azure
- Remove exception from logger call
- Use `Level` class from log4j
- Fixes #13315
> 14415: clean up exception logging for hl7 parsing

- prime-router/build.gradle.kts
- prime-router/metadata/test_fhir_mapping/config.properties
- prime-router/metadata/test_fhir_mapping/hl7/message/ORM_O01.yml
- prime-router/metadata/test_fhir_mapping/hl7/message/ORU_R01.yml
- prime-router/metadata/test_fhir_mapping/hl7/segments/MSH/MessageHeader.yml
- prime-router/src/main/kotlin/azure/BlobAccess.kt
- prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
- prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
- prime-router/src/main/kotlin/fhirengine/translation/HL7toFhirTranslator.kt
- prime-router/src/main/kotlin/fhirengine/utils/HL7Reader.kt
- prime-router/src/test/kotlin/fhirengine/engine/FhirConverterTests.kt
- prime-router/src/test/kotlin/fhirengine/translation/HL7toFhirTranslatorTests.kt
- prime-router/src/test/kotlin/fhirengine/utils/HL7ReaderTests.kt
- prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt
This PR introduces the ability to dynamically configure the location of HL7 to FHIR conversion schemas based on the message type and profile.
This should be reviewed with https://github.com/CDCgov/hl7v2-fhir-converter/pull/8
Test Steps:
1. Run Integration tests and confirm they pass.
- Added data structures to support dynamic schema mapping by MSH9/MSH21
- Refactored HL7toFhirTranslator to not rely on a singleton instance
- HL7toFhirTranslator instances can now be constructed with a configuration file path
- #13020
> 13020 load schema mapping support

- prime-router/src/main/kotlin/history/azure/DatabaseDeliveryAccess.kt
- prime-router/src/test/kotlin/history/azure/HistoryDatabaseAccessTests.kt
This PR ...
Fix to Daily Data API to include ELIMS files
Test Steps:
1. Log into RS
2. All ELIMS sent items appear in the Daily Data table alongside other data in accordance with existing logic
Added additional logic to the organizationFilter method
- Fixes #13578
> 13578 - Fix to Daily Data API to include ELIMS files

- prime-router/src/main/kotlin/azure/BlobAccess.kt
- prime-router/src/test/kotlin/azure/BlobAccessTests.kt
This PR accounts for the the fact that azure connection strings have a different shape local vs. the higher environments. 
Test Steps:
1. CI should cover this
- Updates the `getBlobEndpoint` method to look for account name and endpointsuffix in the higher environments
> Bug: create blob endpoint from suffix and account name

- prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirTransformer.kt
This PR uses the correct default container for loading fhir transform schemas from azure
Test Steps:
n/a
- Changes the default azure blob info to use metadata container
> Bug: use the metadata container for loading fhir transform schemas

- prime-router/build.gradle.kts
This PR updates `JaCoCo` from 0.8.10 to 0.8.12.
Changelog: https://www.jacoco.org/jacoco/trunk/doc/changes.html
Test Steps:
1. Verify the build is successful.
- Update `JaCoCo` from 0.8.10 to 0.8.12.
> Bump jacoco from 0.8.10 to 0.8.12

- .github/actions/build-backend/action.yml
This PR increases the delay before running `reloadTables` from 30 to 90s.
Test Steps:
1. Run Build Hub GHA
It appears the 30 seconds delay between containers startup and subsequent reloadTables is too small to prevent a race condition. In rare circumstances, ./gradlew reloadTables is refreshing the observation-mapping table at the same instant the API container is loading the metadata. 
NA
- Fixes #13961
- Watch GHA to ensure the issue does not re-occur.
NA
> Build Hub intermittent failure

- operations/app/terraform/modules/function_app/~inputs.tf
- operations/app/terraform/vars/demo/main.tf
- operations/app/terraform/vars/prod/main.tf
- operations/app/terraform/vars/staging/main.tf
- operations/app/terraform/vars/test/main.tf
This PR fixes the build by pumping the TI ETOR base URL into the function application in the `function_app` Terraform module.
Test Steps:
1. Do a Terraform apply.
- Updated Terraform.
- IntelliJ with the Terraform plugin seems happy.
https://github.com/CDCgov/trusted-intermediary/issues/690
> Pump the TI ETOR Base URL Values into the Function Application

- prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
This PR provides a temporary fix for underlying issue in the HAPI Fhir library (See the comment in the code for more details
Test Steps:
[large-bulk-fhir.txt](https://github.com/CDCgov/prime-reportstream/files/15200407/large-bulk-fhir.txt)
1. On master, send the above bulk JSON through, verify that the exceptions occur (look for HAPI-2200)
2. Check out this branch, do the same and no errors should occur
- FhirConverter will not initialize FhirPathUtils before running any of the converting
- https://github.com/CDCgov/prime-reportstream/issues/14287
> Bug: eagerly intialize FhirPathUtils in the convert step

- frontend-react/src/hooks/api/UseReceiversConnectionStatus/UseReceiversConnectionStatus.ts
Fixes #14658
This PR fixes a bug in the useReceiversConnectionStatus hook with param names.
> BUG: UseReceiverConnectionStatus incorrect params

- prime-router/src/main/kotlin/fhirengine/translation/TranslationSchemaManager.kt
This PR fixes a bug while running the command `./prime validateSchemas`. The FhirToHl7Converter was missing a context parameter that is used to translate messages.
Test Steps:
1. Run `./prime validateSchemas` against staging and verify that schemas are valid
- Fixed a bug while running the command `./prime validateSchemas`.
> Fixed a bug while running the validate schemas command

- .github/workflows/frontend_ci.yml
Fixes #14966
This PR prevents the chromatic analysis step from running on frontend PRs from dependabot, as dependabot does not have access to secrets.
> BUG: Chromatic Analysis step running for dependabot

- frontend-react/src/AppRouter.tsx
- frontend-react/src/components/header/ReportStreamHeader.tsx
- frontend-react/src/pages/Login.tsx
Fixes #15018 #14701
This PR (hopefully) fixes magiclinks so that state is properly passed to the okta auth client. It also fixes the nav bar so that it will appear for all authenticated users (regardless of groups). The bar only shows the email and logout buttons for users that do not have the necessary groups for anything else.
> BUG: Login state param initialization of state for widget isn't passed to auth client

- .environment/gitleaks/gitleaks-config.toml
- prime-router/settings/STLTs/Flexion/flexion.yml
No updates were made to the Flexion org file. Just copying it from `prime-router/settings/staging/0166-flexion-staging-results-handling.yml` to the new location in the project: `prime-router/settings/STLTs/Flexion/flexion.yml`
**Note**: we had to make some minor changes to the yaml file to pass the org validation test:
- Removed `externalName` from senders
- Changed `qualityFilter: true` to `qualityFilter: "true"`
> ETOR: Move Flexion org settings to new location

- .github/workflows/frontend_ci.yml
Fixes #15160
This PR adds a dummy proxy job after e2e_tests that will always run and provide a status that can be used as a requirement for PRs.
> BUG: e2e_tests job of frontend_ci workflow doesn't properly reflect skip status when required

- prime-router/settings/STLTs/LA/la-ochsner.yml
- prime-router/settings/STLTs/Oracle/oracle-rln.yml
We currently don't have the receiver identifier information for the Ochsner and Oracle recivers. In the meantime, we need to add a dummy filter so all ETOR ORUs are not routed to them
> Add dummy filters to avoid routing all ETOR ORUs to these receivers

- prime-router/src/main/kotlin/fhirengine/translation/hl7/HL7Truncator.kt
- prime-router/src/test/kotlin/fhirengine/engine/CustomTranslationFunctionsTest.kt
- prime-router/src/test/kotlin/fhirengine/translation/hl7/HL7TrucatorTests.kt
This PR fixes truncating sub-components for HL7 fields.
Test Steps:
1. add fields and subcomponents to a receiver's `truncateHl7Fields` setting. For example: 
```     
translation: !<HL7>
schemaName: "classpath:/metadata/hl7_mapping/ORU_R01/ORU_R01-base.yml"
truncateHl7Fields: "ORC-12-3, SPM-2-2-2"
```
2. Note each field's maximum length. Use https://hl7-definition.caristix.com/v2/HL7v2.5/Segments as a reference.
3. Use a sample HL7 report and replace values for the fields that were specified in the `truncateHl7Fields` setting with strings that are the size of each field's maximum length. Add "TRUNCATE THIS" at the end of each of these strings.
4. Use http://localhost:7071/api/reports to send a report to the receiver
5. Verify that the HL7 file that was created contains the original …
> Fix for truncating sub-components

- prime-router/src/main/kotlin/fhirengine/engine/FHIRDestinationFilter.kt
- prime-router/src/test/kotlin/fhirengine/azure/FHIRDestinationFilterIntegrationTests.kt
- prime-router/src/test/kotlin/fhirengine/engine/FhirDestinationFilterTests.kt
This PR adds some more data to the ITEM_ROUTED event that was missed during the initial implementation.
Test Steps:
1. Run the end2end_up smoketest
2. Verify the emitted ITEM_ROUTED event in the logs includes the receiver name and a bundle digest
- Adds receiver and bundle digest to the ITEM_ROUTED event
If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses …
> Bug: add receiver and bundle digest to item routed

- prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventBuilder.kt
This PR disables sending events outside of local environment as the query is taking a very long time in staging.
Test Steps:
Covered by CI
- Adds a check to only build and send events in a local environment
> Disable sending events except for local environments

- prime-router/src/main/kotlin/fhirengine/engine/LookupTableValueSet.kt
- prime-router/src/test/kotlin/fhirengine/engine/LookupTableValueSetTests.kt
This PR reverts the previously merged fix to an issue with multiple valuesets using the same source table and implements a new fix.
Test Steps:
1. Covered by tests, but another reproduction of the issue is detailed in #14901
- Reverted #14933
- A copy of the lookup table is now made instead of processing the lookup table in metadata directly
- Updated tests
- #15397
> 15397 valueset loading fix

- prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventBuilder.kt
- prime-router/src/main/kotlin/history/db/ReportGraph.kt
This PR adjusts the item lineage recursive query to get postgres to use the index after the table has been vacuumed and analyzed
Test Steps:
CI covers it
- Re-enables sending events 
- Updates the item lineage recursive query to that postgres will optimize it correctly
> Fix item graph recursive query and re-enable event sending

- prime-router/src/main/resources/metadata/hl7_mapping/receivers/STLTs/CA/ca-observation-result.yml
This PR fixes an issue CA identified when OBX-23-1  is longer than 50 characters and the NPI was being truncated. The facility name needs to be truncated and not the NPI.
> Fixes a bug while truncating OBX-23-1.

- .environment/frontend/run-frontend.sh
Fixes #15786
This PR updates the monorepo frontend hook to only check for the existance of the internal hook after passing the modified check.
> monorepo frontend hook: check for internal hook after modified

- frontend-react/e2e/spec/chromium-only/authenticated/daily-data-page-user-flow.spec.ts
- frontend-react/e2e/spec/chromium-only/authenticated/receiver-status-page-user-flow.spec.ts
This PR disables smoke tests for receiver status temporarily to investigate errors.
> disable smoke tests for receiver status temporarily

- prime-router/src/main/kotlin/common/BaseEngine.kt
- prime-router/src/main/kotlin/fhirengine/azure/FHIRFunctions.kt
This PR moves initializeQueueMessages to companion object in BaseEngine
Test Steps:
1. run integration and unit tests
> move initializeQueueMessages to companion object

- frontend-react/e2e/spec/chromium-only/authenticated/organization-settings-edit-page-user-flow.spec.ts
This PR ...
Implement user flow for e2e smoke test for Sender Settings Page
Test Steps:
1. Run e2e
- Fixes #15905
> 15905 - Implement user flow for e2e smoke test for Sender Settings Page

- prime-router/src/main/kotlin/azure/ActionHistory.kt
- prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
- prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
- prime-router/src/test/kotlin/fhirengine/azure/FHIRConverterIntegrationTests.kt
- prime-router/src/test/kotlin/fhirengine/azure/FHIRDestinationFilterIntegrationTests.kt
This PR updates the code so that when an empty report (or any situation where the number of items cannot be determined) makes it to the convert step.
Test Steps:
There are a integration tests that covers this, but as the pipeline is currently structured this is hard to test manually as the report function will synchronously fail. 
- Adds a new `trackEmptyReport` that can be used anywhere in the pipeline
- Updates the convert step to use it if it cannot determine the number of items
- #15223
> 15223: generate empty in convert

- prime-router/src/main/kotlin/history/DeliveryHistory.kt
- prime-router/src/main/kotlin/history/azure/DeliveryFacade.kt
- prime-router/src/main/kotlin/history/azure/DeliveryFunction.kt
- prime-router/src/test/kotlin/history/azure/DeliveryFacadeTests.kt
- prime-router/src/test/kotlin/history/azure/DeliveryFunctionTests.kt
This PR updates fetching detailed delivery to count for actions that produce more than on report
Test Steps:
Follow these steps on main and they'll error, but on this branch they'll pass
1. Send a report through with at least two times from `ignore.ignore-fhir-e2e`
2. Wait for the items to get delivered
3. Find a report ID from the batch step going to the `ignore.FULL_ELR_FHIR` receiver
4. Run
```sh
curl --location 'http://localhost:7071/api/waters/report/afbeca26-8b1a-4a57-9749-8000c731e473/delivery' \
--header 'Authorization: Bearer dummy' \
```
For the success case, you should get back a single delivered item
- Updates the findDetailedDeliveryHistory to individually retrieve the report and action if the requested id is a report id
- [Fixes …
> 14609: findDetailedDeliveryHistory handles actions that produce multiple reports

- operations/app/functions/admin/host.json
This PR adds UTF-8 encoding to the JAVA_OPTS in operations/app/functions/admin/host.json
> Add java_opts with UTF-8 encoding

- .github/workflows/deploy_terraform.yml
- operations/app/terraform/modules/storage/main.tf
- operations/app/terraform/modules/storage/~inputs.tf
This PR 
- adds terraform timeouts for `azurerm_storage_account` resource
- adds additional terraform sanity checks before running `terraform apply` in deploy action
Test Steps:
1. Run deployment via automation
- Fixes #16241
> add tf storage timeouts

- operations/app/terraform/modules/storage/main.tf
- operations/app/terraform/modules/storage/~inputs.tf
This PR 
- fixes timeout for read, setting it to 60m
- adds timeouts to other `azurerm_storage_account` resources
> bump GET timeout to 60m

- .github/actions/build-backend/action.yml
This PR always removes runner IP from storage account regardless of build validation status
- Fixes #14639
> add remove sa runner ip

- frontend-react/package.json
- frontend-react/yarn.lock
Fixes #16317
This PR manually resolves dependencies to safe versions temporarily until their parent dependencies do so.
> Manually resolve send and cookie dependencies to safe versions

- frontend-react/src/components/FileHandlers/FileHandler.tsx
- frontend-react/src/content/about/security.mdx
- frontend-react/src/content/support/index.mdx
This PR removes the dead link across the site of: `https://reportstream.cdc.gov/developer-resources/api/documentation/data-model`
Fixes #15728
> remove dead link

- .github/CODEOWNERS
Flexion team members have requested code owner privileges for their configuration files in the RS repo.
> Give CDC flexion team codeowner access to Flexion related folders

- prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/CustomFHIRFunctions.kt
- prime-router/src/main/resources/metadata/fhir_transforms/common/datetime-to-local-mtz.yml
This PR adds a fhir to fhir transform to convert datetimes using changeTimeZone function
Test Steps:
- Fixes #issue
- #issue
If you answered '_yes_' to any of the questions above, …
> Added transform for converting datetimes to mountain time

- prime-router/src/main/kotlin/fhirengine/engine/FHIRConverter.kt
- prime-router/src/main/kotlin/history/db/ReportGraph.kt
- prime-router/src/test/kotlin/common/UniversalPipelineTestUtils.kt
- prime-router/src/test/kotlin/fhirengine/azure/FHIRTranslatorIntegrationTests.kt
The query changes introduced by this PR was flagged as a potential cause for high CPU utilization.
Reverts CDCgov/prime-reportstream#16723
> Revert "16409 do not use receive step to determine root report"

- prime-router/src/main/kotlin/history/azure/DatabaseDeliveryAccess.kt
- prime-router/src/test/kotlin/history/azure/HistoryDatabaseAccessTests.kt
Quick followup to #17120 which is for ticket #16865 
This PR fixes a small error with the deliveries query that was affecting the daily data page when filtered by "ELR_ELIMS"
Test Steps:
- Fixes #16865
- #issue …
> quick fix for deliveries query for ELIMS reports

- frontend-react/e2e/spec/chromium-only/authenticated/daily-data-page-user-flow.spec.ts
Fixes #17206
This PR adds an additional await for the table to load before the rest of the actual checks in order to be more flexible on load time.
> Add time flexibility to Daily Data "onLoad / table has correct headers" Smoke Test

- prime-router/docs/design/proposals/0023-condition-to-code-mapping/0023-condition-to-code-mapping.md
Correcting path to diagram for _code-to-condtion-overview.png_ that was pointing to a local location (C:\...)
This PR **only** updates documentation 
Test Steps:
N/A
-change to readme file
> Update 0023-condition-to-code-mapping.md to correct broken Diagram

- prime-router/src/main/kotlin/azure/BlobAccess.kt
This PR amends a missing item from the main PR for this [receiver enrichment PR](https://github.com/CDCgov/prime-reportstream/pull/16854).  The utility class that facilitates the uploading of BLOBs maps event actions to folder structure inside of Azure.  This simple change updates that mapping for "receiver-enrichment" (see attached screenshot of the updated report folder/directory structure in Azure Storage Explorer).
> [16141] Amending new folder name.

- frontend-react/e2e/spec/chromium-only/authenticated/receiver-status-page-user-flow.spec.ts
Fixes #17262
This PR adds a wait for proof of rendering on page before moving forward with a smoke test for receiver status.
> Add wait for status dashboard container visibility for Receiver Status Page / functions correctly / filters / result message

- frontend-react/e2e/spec/chromium-only/authenticated/receiver-status-page-user-flow.spec.ts
Fixes #17268
This PR temporarily disables the Admin Receiver Status Page › functions correctly › filters › result message smoke test until a solution is found.
> Disable Admin Receiver Status Page / functions correctly / filters / result message @smoke test

- frontend-react/package.json
- frontend-react/vite.config.ts
This PR adds a local dev mode that removes the TS error/warning overlays which can get quite annoying when early development is riddled with TS errors.
> add dev mode that removes browser overlays

- frontend-react/nginx.conf
Fixes #17435
This PR adds proxying to the staging api through the /api url for the docker nginx server. This is for internal use only (running locally), as in deployed environments this redirection is handled at a higher level so our nginx server is never queried at this url in practice.
> Finish validation of the new dockerization of FE to eliminate 404 error

- prime-router/src/main/kotlin/azure/observability/event/AzureEventUtils.kt
- prime-router/src/main/kotlin/azure/observability/event/ObservationSummary.kt
- prime-router/src/test/kotlin/azure/observability/bundleDigest/FhirPathBundleDigestExtractorStrategyTests.kt
- prime-router/src/test/kotlin/azure/observability/event/AzureEventUtilsTest.kt
- prime-router/src/test/kotlin/fhirengine/engine/FhirDestinationFilterTests.kt
This PR adds Observation.interpretation information to the bundle digest information logged in Azure Events.
Test Steps:
1. Submit a Report (e.g., c2sense in staging has some HL7 messages that would work) that has lab interpretation information (i.e., information in OBX8 segment) and observe the event(s) that are logged (either in your local console if you're running the app or via [appinsights](https://github.com/CDCgov/prime-reportstream/blob/73f12902351ef0968231e6039cca2336a71672ee/prime-router/docs/observability/local-dev-setup.md)).
- See [this](https://github.com/CDCgov/prime-reportstream/pull/17534/files).
- N/A
- N/A
- N/A
> [17330] Log test result interpretations in Azure Event.

- .github/workflows/sonarcloud.yml
This PR comments out the sections in the SonarCloud workflow that use tj-actions
> Update sonarcloud.yml - remove refs to tj-actions

- prime-router/src/main/kotlin/history/SubmissionHistory.kt
- prime-router/src/test/kotlin/history/SubmissionHistoryTests.kt
This PR addresses a bug where information did not appear in the history API response.
From the user story in [Zenhub](https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/17603):
The bug is not limited to multiple receiving organizations. It occurs for any number of receivers in the DetailedSubmissionHistory initializer (init) when it is looping through reports (List of DetailedReport). filterLogs is the result of filtering logs (List of DetailedActionLog) based on the filter type of filter and the reportIds matching. filterReportRows and filterReportItems are constructed from that result. In the event that the list of destinations does not already contain an entry for the receiving organization then a new destination (including the …
> [17603] Fix incomplete History API response.

- .github/workflows/alert_PD_schedule_Slack.yml
This PR updates the PagerDuty slack notification workflow to match the slack URL with the team to fix the "404 not found" error.
Test Steps:
1. I had Nava generate a new Slack URL that is tied to the following Nava owned channel: `cdc-reportstream-engineering-new`
2. I installed ACT locally and ran the following simplified version of the workflow from the root of the repo via `act -j PDAlert_WeekDays`
```
name: Find next person on call
on:
schedule:
- cron: "7 13 * * Tue-Fri"  #UTC-5
- cron: "7 13 * * Mon"  #UTC-5
env:
channel: cdc-reportstream-devsecops-new
jobs:
PDAlert_WeekDays:
name: PD Alert for WeekDays
runs-on: ubuntu-latest
steps:
- name: Check Out Changes
uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938
with:
fetch-depth: 0
- name: Slack Notification
uses: …
```
> Update GH Action Slack URL

- .github/workflows/release_to_azure.yml
- Added `permissions` block to `.github/workflows/release_to_azure.yml` with:
- `checks: write` - Allows creating and updating check runs
- `contents: read` - Allows reading repository contents
- `pull-requests: write` - Allows updating pull requests
The workflow was encountering a 403 Forbidden error when trying to create check runs for test results. This was happening because the workflow didn't have the necessary permissions to create check runs. By default, GitHub Actions workflows have limited permissions, and we need to explicitly grant the required permissions.
> Add GitHub workflow permissions for check runs

- .github/workflows/release_to_github.yml
This PR ...
adds the `contents: write` permission to the `release_to_github.yml` workflow to allow the `delete-older-releases` action to delete releases and tags. The workflow now has:
- `checks: write` - for test results
- `contents: read` - for reading files
- `contents: write` - for deleting releases
- `pull-requests: write` - for PR status
This change should resolve the "Resource not accessible by integration" error when the workflow tries to delete older releases.
> Add contents: write permission for deleting releases

- .github/workflows/release_to_github.yml
This PR ...
- Removed duplicate `contents: read` permission
- Kept `contents: write` permission  needed for deleting releases
- Fixes workflow error in commit 6f8fd9b4f
>  remove duplicate contents permission in release_to_github workflow

- .github/actions/build-backend/action.yml
This PR ...
Added `skip-schema-validation` input parameter to the build-backend action with a default value of true, which:
1. Adds explicit control over schema validation in the build-backend action
2. Removes redundant skip-schema-validation settings from release_to_github.yml
Both workflows will skip schema validation by default since they use the action's default value of true.
- The parameter is set to `true` by default in all workflows to unblock deployments
- Schema validation can be re-enabled by setting `skip-schema-validation: false` once the underlying issue is resolved
- This change is a temporary workaround to unblock deployments while investigating the schema validation error
- A separate investigation is needed to resolve the root cause of the schema validation failure
> add skip-schema-validation option to build-backend action

- frontend-react/e2e/spec/chromium-only/authenticated/daily-data-page-user-flow.spec.ts
Reverts CDCgov/prime-reportstream #17950 since they are breaking on staging.
> Revert "Experience/16349/unskip e2e test"

- frontend-react/e2e/spec/chromium-only/authenticated/last-mile-failures-page-user-flow.spec.ts
Reverts CDCgov/prime-reportstream#17975.
Seems like a timing issue happening on the staging server that needs to be revisited.
> Revert "16059 Removed skip from last mile failure test"

- frontend-react/e2e/spec/chromium-only/authenticated/last-mile-failures-page-user-flow.spec.ts
This PR ...
Unskips a last mile failures page user flow test 
Test Steps:
1. When running locally
`yarn run test:e2e-smoke e2e/spec/chromium-only/authenticated/last-mile-failures-page-user-flow.spec.ts`
- unskipped a skipped test
- Fixes #16059
> 16059 -Unskips a last mile failures page user flow/smoke test

- operations/dnsmasq/Dockerfile
This PR resolves CVEs baked into ubuntu
> DOCKER_HOST=unix:///Users/matts/.docker/run/docker.sock trivy image --severity=HIGH,CRITICAL,MEDIUM,LOW --ignore-unfixed dnsmasq:matts-3
> 
> 2025-05-07T15:08:26-07:00       INFO    [vuln] Vulnerability scanning is enabled
> 2025-05-07T15:08:26-07:00       INFO    [secret] Secret scanning is enabled
> 2025-05-07T15:08:26-07:00       INFO    [secret] If your scanning is slow, please try '--scanners vuln' to disable secret scanning
> 2025-05-07T15:08:26-07:00       INFO    [secret] Please see also https://trivy.dev/v0.61/docs/scanner/secret#recommendation for faster secret detection
> 2025-05-07T15:08:26-07:00       INFO    Detected OS     family="wolfi" version="20230201"
> 2025-05-07T15:08:26-07:00       INFO    [wolfi] Detecting …
> switch dnsmasq Dockerfile to wolfi to resolve cves

- prime-router/src/test/kotlin/fhirengine/azure/SubmissionTableServiceIntegrationTests.kt
This PR disables a test related to submission table services that does not appear to be functioning. This may be due to resources in Okta being disabled; we should disable this test anyway if there are no immediate plans to deploy the submissions microservice.
- Disables `SubmissionTableServiceIntegrationTests`
> ignore submission table integration test

- prime-router/src/main/kotlin/azure/ActionHistory.kt
- prime-router/src/main/kotlin/common/AzureHttpUtils.kt
- prime-router/src/main/resources/db/migration/V75__extend_character_limits.sql
- prime-router/src/test/kotlin/azure/ActionHistoryTests.kt
This PR extends the length of the `report_file`.`schema_name` column so longer strings can be stored and removes temporary code that truncates the data to be stored in this column. It additionally extends the length of many other varchar columns throughout the database.
Test Steps:
1. Run `clean` followed by `package` to apply db migrations and run tests.
2. Confirm the database has been updated by running the following query and verifying the value is null:
```
SELECT character_maximum_length 
FROM information_schema.columns 
WHERE table_schema = 'public' 
AND table_name  = 'report_file' 
AND column_name  = 'schema_name';
```
- Add migration to alter size of `report_file`.`schema_name` and many other varchar database columns
- Remove temporary code to truncate schema name prior to …
> 13598 address database varchar size limits

- .editorconfig
This PR disables the ktlint rule while requires that no newline be present at the end of a file. This is an issue because the github code editor automatically adds a trailing new line to files it touches. 
Test Steps:
1. Build passes
> Disabled end of file newline rule
