prime-router/README.md
prime-router/prime

- Documentation update for running locally on Ubuntu install
- Update prime shell script as artifact version was not in sync with pom.xml file

Add Ubuntu packages and update artifact version in prime shell script

---

prime-router/pom.xml
prime-router/src/main/kotlin/azure/IngestFunction.kt
prime-router/src/main/kotlin/azure/IngestedFile.kt

- Added the new Report ingest Azure function
- added a few dependencies to pom.xml
- [X ] Tested locally?
- [X ] Added new dependencies?
- [ X] Did you check for sensitive data, and remove any?

Added Azure Function to ingest data reports via http

---

prime-router/metadata/organizations.yml

This PR does moves the AZ service to use CSV
- Organizational

Move AZ back to CSV files

---

prime-router/setup_resource_group.sh

Add Azure Front Door - Access Restrictions Coming Soon

---

prime-router/metadata/organizations.yml
prime-router/metadata/schemas/AZ/pima-az-covid-19-csv.schema
prime-router/src/main/kotlin/Element.kt

This PR now includes generation of data for Pima County.  
- Tweaked Element so that it processes an element with a set of local altValues but no Value Set.
- Added Pima Schema, 95% same as input PDI schema.
- [N] Added new dependencies?
See above change to Element.kt
- Need to get the rest of the Devices from James.

Added Pima Schema. 

---

prime-router/src/main/kotlin/Element.kt

This PR fixes a bug in the altValue code.
Yesterday I put in a bug fix, which prioritized altValue even when no value set was present.  I found today I also had to fix the reverse flow, from formatted value to normalized value.   Turns out this is used in the Batch function.  now fixed.
- Element.kt
-

Bug fix:  

---

prime-router/metadata/organizations-prod.yml
prime-router/metadata/organizations-test.yml

This PR adds the new county organization-service to -test.yml and -prod.yml

Added the new county organization-service to -test.yml and -prod.yml

---

.github/workflows/build_test.yml
.github/workflows/release_test.yml
README.md

Testing PR

---

prime-router/assets/email-templates/css/custom.css
prime-router/assets/email-templates/css/foundation-emails.css
prime-router/assets/email-templates/readme.md
prime-router/assets/email-templates/test-results-ready.html
prime-router/assets/email-templates/test-results-ready__inline.html

- Adds email templates & CSS to `/assets`
- Partly fixes #91 
- Engineering portion of #91

Responsive email template for CSV download notification

---

prime-router/setup_database.sh
prime-router/setup_resource_group.sh

This PR rebrands `prime-data-hub-prod` as `prime-data-hub` for standing up the Azure resources.  It also changes naming consistency for now so that names are consistent among different resources.
- #issue
- #issue

Environment consistency updates

---

.github/workflows/release.yml

This PR restarts the function app instead of updating it upon deployment.

Restart function app instead of update

---

.github/workflows/release.yml

Forgot to add snippet for working directory to the release workflow.

Update Working Directory

---

.github/workflows/release.yml

This PR adds a key for the SimpleReport client to communicate with the `reports` endpoint.

Add key for SimpleReport

---

prime-router/metadata/schemas/AZ/az-covid-19-hl7.schema
prime-router/metadata/schemas/covid-19.schema
prime-router/metadata/valuesets/common.valuesets
prime-router/metadata/valuesets/covid-19.valuesets
prime-router/src/main/kotlin/CsvConverter.kt
prime-router/src/main/kotlin/Element.kt
prime-router/src/main/kotlin/FakeReport.kt
prime-router/src/main/kotlin/Hl7Converter.kt
prime-router/src/main/kotlin/Mappers.kt
prime-router/src/main/kotlin/Metadata.kt
prime-router/src/test/kotlin/ElementTests.kt

This PR improves the HL7 processing, in general, and improves the HL7 message for AZ. 
- A new type: Entity Identifier (EI) to represent the `message_profile_id`
- A new mapper, obx8, to calculate the `abnormal_flag` from the `test_result`
- `message_profile_id` now matches AZ spec
- HL70078 valueset for abnormal flag

AZ HL7 changes

---

prime-router/metadata/organizations-test.yml

This PR fixes an incorrect sftp IP.

Fixed wrong ip in test

---

prime-router/metadata/organizations-test.yml

Another fix for az hl7

---

prime-router/docs/releases/2021-01-12-release-notes.md
prime-router/quick-test.sh
prime-router/src/main/kotlin/FakeReport.kt
prime-router/src/main/kotlin/cli/main.kt

This PR has these changes
- Added a --target-county option to ./prime cli
- Added the --merge file1,file2,file3 option to ./prime cli
- Added tests of merging and of STRAC to quick-test
- #165

Adding --merge operations to the cli, & other fixes

---

.github/workflows/build.yml

Check full repo name from the PR request agains the base.  If it is from a fork, skip the build workflow.

CI/CD Update

---

prime-router/metadata/organizations-local.yml
prime-router/metadata/organizations-prod.yml
prime-router/metadata/organizations-test.yml
prime-router/metadata/organizations.yml
prime-router/metadata/schemas/STRAC/strac-covid-19.schema
prime-router/metadata/schemas/covid-19-redox.schema

This PR adds an ordering_facility_county field to the STRAC field and routes to counties based on this field. 
STRAC asked for this county field to be added, so we could route based on the school location. 
- STRAC schema
- PA-PHD receivers

PA and STRAC Ordering_Facility_County field

---

prime-router/quick-test.sh

- The `quick-test.sh` fails after merging in the CLI improvements. Had to make changes to correct.
- #377

Fixes bug with ND test after CLI improvements

---

prime-router/assets/csv-download-site/index__inline.html
prime-router/src/main/kotlin/azure/DatabaseAccess.kt
prime-router/src/main/kotlin/azure/DownloadFunction.kt

-  Add date, location in front of filename test-results.csv -> maybe YYYYMMDD-[state]-[county name]-test-results.csv
- Typo: remove trailing "`" at the end of the no data available message.
- Added SENT_AT != NULL to query to avoid duplicates
- Moved orgName/userName to local to avoid threading issues

MVP Download page #3

---

prime-router/metadata/organizations-prod.yml

This PR fixes a messed-up organizations-prod.yml.
Not possible to test locally.
- #issue

Fix to az data in organizations-prod.yml

---

prime-router/docs/azure-logs-audit.md
prime-router/docs/azure-logs.md

As part of our security review, we have to send our logs to Splunk (#358). This is the first pass at making a list of all available logs in our system, which we will need to send over to Splunk.
- Lists out all known logs in Azure.
- Once we have a list of all the logs, comb through them and verify no PII/PHI.

Audit of Available Logs

---

prime-router/pom.xml

This PR upgrades Log4j because of a security vulnerability found by DependaBot. 
- Log4j upgrade to 2.13+

Upgrade Log4j for Security

---

prime-router/docs/azure-logs.md

This supports organizing the Splunk work in #359 
- Update the list of logs
- Organizes them
- Prioritizes them
- Adds the actual resource names
- #issue
- #issue

Update Splunk logging priorities

---

prime-router/docs/schema_documentation/la-la-covid-19-hl7.md
prime-router/docs/schema_documentation/la-la-covid-19.md
prime-router/pom.xml
prime-router/src/main/kotlin/CsvComparer.kt
prime-router/src/main/kotlin/Element.kt
prime-router/src/main/kotlin/JurisdictionalFilters.kt
prime-router/src/main/kotlin/Translator.kt
prime-router/src/main/kotlin/azure/ActionHistory.kt
prime-router/src/main/kotlin/azure/DatabaseAccess.kt
prime-router/src/main/kotlin/azure/DownloadFunction.kt
prime-router/src/main/kotlin/azure/Event.kt
prime-router/src/main/kotlin/azure/ReportFunction.kt
prime-router/src/main/kotlin/azure/SendFunction.kt
prime-router/src/main/kotlin/cli/main.kt
prime-router/src/main/kotlin/serializers/CsvSerializer.kt
prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
prime-router/src/main/kotlin/transport/EmailTransport.kt
prime-router/src/main/kotlin/transport/RedoxTransport.kt
prime-router/src/main/kotlin/transport/SftpTransport.kt
prime-router/src/test/kotlin/JurisdictionalFilterTests.kt
prime-router/src/test/kotlin/MetadataTests.kt
prime-router/src/test/kotlin/ReportTests.kt
prime-router/src/test/kotlin/SimpleReportTests.kt
prime-router/src/test/kotlin/azure/SendFunctionTests.kt

This PR turns on KTLint checking during the Maven build
- KTLint check is now part of the build process. 
- Much reformatting to make our build pass

Fix KTLint Errors

---

.gitignore
frontend/README.md
frontend/eleventy.config.js
frontend/mock/_api_utils.mjs
frontend/mock/demo.openapi.yml
frontend/mock/main.mjs
frontend/package-lock.json
frontend/package.json
frontend/src/_data/env.js
frontend/src/_includes/app_topbar.liquid
frontend/src/_includes/footer_cdc_website.liquid
frontend/src/_includes/header_gov_website.liquid
frontend/src/_includes/prime_page.liquid
frontend/src/css/prime.css
frontend/src/csv-download.html
frontend/src/index.html
frontend/src/login.html
frontend/src/settings.html

Status: Review & feedback with Matt & Drew on 2021-02-10. Suggested shipping PR as-is and starting the next one.
JAMStack frontend skeleton for PRIME Data Hub.
- USWDS via CDN with integrity on style and script tags
- Uses Eleventy static site generator
- NPM based build tooling
- Mock OpenAPI server
- Adds top level `/frontend` artifact
- Adds build dependencies: `node`, `npm`, various npm packages in `package-lock.json`
- Adds development dependencies: `watchexec`

Frontend JAMStack skeleton

---

prime-router/docs/dependency-graph-full/dependency-graph-full.txt
prime-router/docs/dependency-graph-full/generate.sh

- Adds a script to generate our maven dependency tree
- Generate the tree in the docs folder
- #issue
- #issue

Dependency tree script

---

prime-router/docs/schema_documentation/la-la-covid-19-hl7.md
prime-router/docs/schema_documentation/nd-nd-covid-19.md
prime-router/docs/schema_documentation/standard-standard-covid-19.md
prime-router/metadata/schemas/LA/la-covid-19-hl7.schema
prime-router/metadata/schemas/ND/nd-covid-19.schema
prime-router/metadata/schemas/standard/standard-covid-19.schema
prime-router/quick-test.sh

- Updates `quick-test` to use the COVID-19 schema for LA and ND
- Fixes issue with `sending_facility` not being needed anymore
- #488

Fixes bug with sending_facility

---

prime-router/metadata/organizations-test.yml

This PR adds a `pentest-pima-az-phd` for pen testers to hit. 
- #issue
- #issue

Add a pentest org to the test deployment 

---

prime-router/metadata/organizations-local.yml
prime-router/metadata/organizations-prod.yml
prime-router/metadata/organizations-test.yml
prime-router/metadata/organizations.yml

This PR adds Delaware county to the Chester county's feed. This PR fixes a data leak that is missing from PA's feeds.

Chester get Delaware data as well

---

operations/Dockerfile
operations/README.md
operations/app/src/environments/dev/main.tf
operations/app/src/environments/prod/main.tf
operations/app/src/environments/staging/main.tf
operations/app/src/environments/staging/variables.tf
operations/app/src/environments/test/main.tf
operations/app/src/modules/function_app/main.tf
operations/app/src/modules/function_app/variables.tf
operations/app/src/modules/prime_data_hub/main.tf
operations/app/src/modules/prime_data_hub/variables.tf
operations/docker-compose.yml

An additional environment module has been added to terraform for a `staging` environment.  It will essentially mimic the behaviors of the `test` environment, yet it will be isolated within the `prime-data-hub-staging` resource group in Azure.

Updates to support staging environment

---

operations/app/src/modules/database/main.tf
operations/app/src/modules/front_door/main.tf
operations/app/src/modules/function_app/main.tf
operations/app/src/modules/prime_data_hub/main.tf

- Add new app settings for test/staging environments.  I will create a future PR for merging app settings as opposed to all of the conditionals.  
- Remove metabase resources for non-test environments.

Terraform Updates For App Settings and Metabase

---

operations/app/src/modules/database/main.tf

This PR enables Advanced Threat Protection for our PostgreSQL servers.

Enable PostgreSQL Advanced Threat Protection

---

operations/app/src/modules/front_door/main.tf

This PR keeps the metabase-specific configurations within the Front Door in the production environment.

Keep Metabase Front Door configuration for prod environment

---

.github/workflows/build_frontend.yaml
.github/workflows/build_hub.yml

Fixes GitHub not marking PRs as ready when steps are skipped

---

operations/app/src/modules/function_app/main.tf

Update to the name for internal PRIME environment variables.

Update internal PRIME env var names

---

prime-router/docker-compose.yml
prime-router/metadata/schemas/TCP/tcp-covid-19.schema
prime-router/quick-test.sh
prime-router/settings/organizations-local.yml
prime-router/settings/organizations-prod.yml
prime-router/settings/organizations-test.yml
prime-router/settings/organizations.yml
prime-router/src/main/kotlin/Mappers.kt
prime-router/src/main/kotlin/Metadata.kt
prime-router/src/main/kotlin/Report.kt
prime-router/src/main/kotlin/TranslatorConfiguration.kt
prime-router/src/main/kotlin/azure/BlobAccess.kt
prime-router/src/main/kotlin/cli/main.kt
prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
prime-router/src/test/kotlin/MapperTests.kt

This PR updates the organizations and adds the HL7 translator config to the HL7 serializer writing.

Adds translator config to the HL7 serializer 

---

prime-router/src/main/kotlin/transport/SftpTransport.kt

Replace underscore with dash

---

frontend/src/_data/content/index.yaml

This PR ... 
- Made a title change because it was confusing before
- #issue
- #issue

Header update

---

operations/app/src/modules/database/main.tf
operations/app/src/modules/storage/main.tf

This PR enables globally redundant storage for the storage account as part of disaster recovery planning efforts.

Storage Account - Enable Globally Redundant Storage

---

prime-router/docs/schema_documentation/empty.md
prime-router/metadata/schemas/empty.schema
prime-router/src/main/kotlin/azure/ReportFunction.kt

This PR includes a missing schema file.
- #issue
- #issue

Added missing schema

---

operations/app/src/modules/function_app/main.tf

Adds and sets the feature flag for settings to `false`.

Set settings feature flag

---

operations/app/src/modules/storage/main.tf

This PR configures data protection and lifecycle management policies for our storage accounts.  Specifically, it adds point-in-time restore snapshots, versioning for data within blob storage, soft delete, and a 30-day lifecycle retention policy for the aforementioned features.

Add data restore, versioning, soft delete, and lifecycle policy

---

operations/app/src/modules/function_app/main.tf

This PR turns on the use of settings from the database, rather than from the .yml files.

Turning on database settings

---

prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
prime-router/docs/schema_documentation/ca-ca-scc-covid-19.md
prime-router/docs/schema_documentation/co-co-covid-19-redox.md
prime-router/docs/schema_documentation/covid-19-redox.md
prime-router/docs/schema_documentation/covid-19.md
prime-router/docs/schema_documentation/fl-fl-covid-19.md
prime-router/docs/schema_documentation/gu-gu-covid-19.md
prime-router/docs/schema_documentation/la-la-covid-19.md
prime-router/docs/schema_documentation/mt-mt-covid-19-csv.md
prime-router/docs/schema_documentation/mt-mt-covid-19.md
prime-router/docs/schema_documentation/nd-nd-covid-19.md
prime-router/docs/schema_documentation/nm-nm-covid-19.md
prime-router/docs/schema_documentation/oh-oh-covid-19.md
prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
prime-router/docs/schema_documentation/pa-pa-covid-19-redox.md
prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
prime-router/docs/schema_documentation/standard-standard-covid-19.md
prime-router/docs/schema_documentation/strac-strac-covid-19.md
prime-router/docs/schema_documentation/tx-tx-covid-19.md
prime-router/docs/schema_documentation/vt-vt-covid-19.md
prime-router/metadata/schemas/CA/ca-scc-covid-19.schema
prime-router/metadata/schemas/covid-19.schema
prime-router/quick-test.sh
prime-router/settings/organizations-local.yml
prime-router/settings/organizations.yml
prime-router/settings/prod/0001-ca-scc-phd.yml

This PR adds a schema for Santa Clara, CA.
- SCC schema
- SCC org files
- #issue
- #issue

Schema for Santa Clara, CA

---

frontend/ci_build.bash
frontend/eleventy.config.js
prime-router/docker-compose.yml

This PR ... 
- 
- 
- #issue
- #issue

changing build

---

frontend/package-lock.json
frontend/package.json
frontend/src/_includes/actions.liquid
frontend/src/_includes/navbar.liquid
frontend/src/_includes/table_facilities.liquid
frontend/src/_includes/table_reports.liquid
frontend/src/data-index.html
frontend/src/js/cards.js
frontend/src/js/checkjwt.js
frontend/src/js/reports.js
prime-router/src/main/kotlin/azure/HistoryFunctions.kt

This PR ... 
- #issue
- #issue

mry-frontend-bugfix

---

frontend/src/login.html

This PR ... 
- 
- 
- #issue
- #issue

set redirect url

---

operations/app/src/modules/function_app/main.tf
operations/app/src/modules/function_app/variables.tf
operations/app/src/modules/prime_data_hub/main.tf
operations/app/src/modules/storage/main.tf

This PR adds the setting for the partner store.
- 
- 
- #issue
- #issue

Partner Store Setting

---

prime-router/quick-test.sh
prime-router/settings/organizations-local.yml
prime-router/settings/organizations.yml
prime-router/settings/prod/0012-nh-ma-organizations.yml
prime-router/settings/staging/0005-nh-ma-organizations.yml

This PR adds NH, MA, AL, and MI to the organizations

Adds MA, NH, AL, and MI to the organizations

---

prime-router/src/main/kotlin/azure/BlobAccess.kt

This PR fixes a glitch in the code getting the connection string

blob store fix

---

prime-router/src/main/kotlin/azure/BlobAccess.kt

More logging related to env var

---

prime-router/src/main/kotlin/azure/BlobAccess.kt

This PR changes the way we're writing to partner storage - first pull in the bytes, then write out to the new store.

Changes to pull in the bytes, then write out to parterstorage

---

operations/app/src/modules/function_app/main.tf
operations/app/src/modules/network/main.tf
operations/app/src/modules/storage/main.tf

This PR tweaks a few Azure configurations to enable the HHS Protect integration.
- Opens the firewall between the partner storage and general storage accounts.
- Fixes the environment variables name on the function app.
- Changes the IP rules for Ron (he has two public IPs 😮 )
- #issue
- #issue

Partner Storage Fixes

---

frontend/package-lock.json
frontend/package.json
frontend/src/_includes/details_report.liquid
frontend/src/_includes/grid_charts.liquid
frontend/src/_includes/navbar.liquid
frontend/src/_includes/table_facilities.liquid
frontend/src/_includes/table_reports.liquid
frontend/src/_layouts/protected.liquid
frontend/src/index.html
prime-router/src/main/kotlin/azure/HistoryFunctions.kt

This PR ... 
- 
- 
- #issue
- #issue

mry-bug-bash

---

frontend/src/_includes/details_report.liquid
frontend/src/_includes/grid_charts.liquid
prime-router/src/main/kotlin/azure/HistoryFunctions.kt

This PR ... 
- 
- 
- #issue
- #issue

Mry bug bash

---

frontend/src/_data/content/index.yaml
frontend/src/_data/site.yaml
frontend/src/_includes/details_report.liquid
frontend/src/_includes/head_tags_universal.liquid
frontend/src/_includes/menu_documentation.liquid
frontend/src/_includes/menu_settings.liquid
frontend/src/_includes/navbar.liquid
frontend/src/_includes/table_reports.liquid
frontend/src/_layouts/protected.liquid
frontend/src/assets/stylesheets/prime.css
frontend/src/data-index.html
frontend/src/data-retention.html
frontend/src/data-show.html
frontend/src/documentation.html
frontend/src/elr-guide.html
frontend/src/error-unsupported-browser.html
frontend/src/index.html
frontend/src/js/checkjwt.js
frontend/src/login.html
frontend/src/terms-conditions.html
frontend/src/web-receiver-guide.html

This PR ... 
Further updates rom #744 . Biggest change is edits to permalinks for clean URLs and new /documentation content
- Edits permalinks for clean URLs
- Edits nav partials with new URLs
- Edits JWT JS check to account for new URLs
- Adds full content to /documentation pages
- Edits to layouts and CSS for new documentation content
- #issue
- #issue

Further bug fixes

---

prime-router/src/main/kotlin/serializers/Hl7Serializer.kt

This PR expands on the HD truncation logic for VT. In some HL7 segments, components are of type `HD` which has a max length of 20 for the namespace ID: (`MSH-4`, `ORC-2`, `OBR-2`, etc). Some jurisdictions want to make sure that the first subcomponent for the HD fields is truncated to 20 char. While some of our fields in our schemas are encoded as type `HD`, some are not, and therefore it was necessary to flag some `TEXT` fields as actually `HD` fields that need to be truncated.
- Adds an `HD_FIELDS` list to the companion object of the `Hl7Serializer`
- Adds logic to truncate the fields if their length is greater than the 20 char limit and the truncation flag is true.

Improves HD truncation logic for VT

---

.github/pull_request_template.md

This PR improves our PR checklist. Yes, a PR for a PR. Ironically, this PR will not use the new checklist. 😱 
Resolves CDCGov/prime-devops#8
- Organizes the checklist into categories
- Adds some ops process items to the checklist
- #issue
- #issue

PR template checklist improvements

---

prime-router/docs/schema_documentation/waters-waters-covid-19.md
prime-router/metadata/schemas/WATERS/waters-covid-19.schema

This PR updates the waters schema based on the example received from Waters team on Friday Apr 24.
@joemeree

updated waters schema to match latest example from waters

---

prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
prime-router/docs/schema_documentation/az-pima-az-covid-19.md
prime-router/docs/schema_documentation/ca-ca-scc-covid-19.md
prime-router/docs/schema_documentation/covid-19.md
prime-router/docs/schema_documentation/fl-fl-covid-19.md
prime-router/docs/schema_documentation/gu-gu-covid-19.md
prime-router/docs/schema_documentation/la-la-covid-19.md
prime-router/docs/schema_documentation/mt-mt-covid-19-csv.md
prime-router/docs/schema_documentation/mt-mt-covid-19.md
prime-router/docs/schema_documentation/nd-nd-covid-19.md
prime-router/docs/schema_documentation/nm-nm-covid-19-csv.md
prime-router/docs/schema_documentation/nm-nm-covid-19.md
prime-router/docs/schema_documentation/oh-oh-covid-19.md
prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
prime-router/docs/schema_documentation/standard-standard-covid-19.md
prime-router/docs/schema_documentation/strac-strac-covid-19.md
prime-router/docs/schema_documentation/tpca-tpca-covid-19.md
prime-router/docs/schema_documentation/tx-tx-covid-19.md
prime-router/docs/schema_documentation/vt-vt-covid-19.md
prime-router/metadata/schemas/covid-19.schema
prime-router/src/main/kotlin/azure/BlobAccess.kt

This PR change ordering_facility_phone_number to optional in the base schema
- 
- 
none known

change ordering_facility_phone_number to optional in the base schema

---

prime-router/build.gradle.kts
prime-router/src/main/kotlin/azure/HttpUtilities.kt

This PR fixes an error with the null error stream on posting Http requests from RS 
- Adds logic to return a null error stream issue
- Fixes formatting in build.gradle.kts
- #issue
- #issue

Fixes error with null errorStream

---

frontend/src/_includes/table_facilities.liquid
frontend/src/_includes/table_reports.liquid
frontend/src/data-index.html
frontend/src/index.html
frontend/src/js/prime-web-receiver-pre.js
frontend/src/web-receiver-guide.html

This PR ... 
More content edits from today's look at staging
- Changes text of "7 days" of data retention to "30 days"
- Hanges download index h1 to just be "Test results"
- Tweaks Okta language slightly, adds HHS link
- removes duplicate `mailto:` link on index
- Edits font weights and colors for labels/breadcrumbs
- #issue
- #issue

Content edits

---

prime-router/settings/organizations-local.yml
prime-router/settings/organizations-prod.yml
prime-router/settings/organizations-test.yml
prime-router/settings/organizations.yml
prime-router/settings/prod/0020-update-ma-translation.yml
prime-router/settings/staging/0013-update-ma-translation.yml

This PR updates the translation settings for the MA ELR receiver 
- Adds yamiltos for ma-phd.elr
- Updates the org files

Update receiver for Massachusetts 

---

operations/app/src/modules/key_vault/main.tf

This PR changes Azure Key Vault access.
- Removes Chris Glodosky
- Adds Rick Hawes
- #issue
- #issue

Remove Chris, add Rick to Key Vault

---

operations/README.md

This PR improves our documentation for how to apply infrastructure changes via Terraform.
- Indicates what commands need to be run once or on every deployment
- Fixes a typo on a command
- Adds a section on caveats and how to work around them
- #issue
- #issue

Improve Terraform docs after session with Rick

---

prime-router/settings/prod/0025-update-pa-allegheny.yml

This PR adds the Allegheny county destination to the settings in PROD. 
- Allegheny county yml file
- Misconfiguration can lead to data leaks. 
#1097

Add Allegheny county destination

---

prime-router/docs/releases/2021-05-27-release-notes.md

This PR ... 
- 
- 
- #issue
- #issue

release notes update

---

prime-router/docs/getting_started.md

This PR ... 
- Updates documentation with a Troubleshooting section 
This does explicitly lists the values for the env variables used to run locally. If these are used outside of local development we should think of a better way to store them. 
- #1169 
- #issue

#1169 - updates documentation with a Troubleshooting section

---

prime-router/docs/jurisdiction-connection-status.md

Updating jurisdiction outreach

---

prime-router/docs/schema_documentation/waters-direct-covid-19.md
prime-router/metadata/schemas/WATERS/direct-covid-19.schema
prime-router/metadata/valuesets/covid-19.valuesets
prime-router/settings/organizations-local.yml
prime-router/settings/organizations.yml
prime-router/settings/staging/0019-direct.yml
prime-router/src/main/kotlin/azure/QueueAccess.kt

This PR does some minor tweaks to prepare for some direct senders into ReportStream.
- HHS standard calls for YES and NO for AOE questions, instead of hl70136 which we use with other senders.
- 
none known

updates for safe

---

prime-router/docs/releases/2021-06-07-release-notes.md
prime-router/settings/organizations-local.yml
prime-router/settings/organizations.yml
prime-router/settings/prod/0029-direct.yml
prime-router/settings/staging/0022-direct.yml
prime-router/settings/staging/0023-giang.yml
prime-router/settings/staging/0024-ignore.yml

This PR ... 
- changed hhsprotect in PROD to take processing_mode_code = 'T', in support of waters comparison test
- tweaked the release notes to say that the filename changes are not here yet.
- fixed a typo in staging settings.
- #issue
- #issue

Last minute tweaks

---

operations/Makefile

This PR ... 
- rename `TF_ENV_MODULE` to `TF_STAGE` which more accurately reflects what it is (and avoids confusion with `TF_ENV`)
- Adds more information to `make help` output
- Adds more build steps to the `.PHONY` list

Enhancements to the operations' Makefile

---

prime-router/src/main/kotlin/azure/ActionHistory.kt
prime-router/src/main/kotlin/azure/ReportFunction.kt
prime-router/src/test/kotlin/azure/ActionHistoryTests.kt

This PR makes the **report** endpoint to write back the **sending_at** field with the value **never - skipSend specified** when the SkipSend flag is set.
**curl -X POST -H "client:simple_report" -H "content-type:text/csv" --data-binary "@c:\users\pablo\pdi-covid-19-20210610115239-5cf8f0e5-5109-467b-8557-ba60f906a021.csv" "http://localhost:7071/api/reports?option=SkipSend"**
RESPONSE
```
{
"id" : "675135a0-a308-4027-a0b7-9790cbcf94ff",
"timestamp" : "2021-06-10T20:12:20.038694Z",
"topic" : "covid-19",
"reportItemCount" : 1,
"destinations" : [ {
"organization" : "Public Health Department - Santa Clara, California",
"organization_id" : "ca-scc-phd",
"service" : "elr-download",
"sending_at" : "never - skipSend specified",
"itemCount" : 1
}, {
"organization" : "California Department of Public …
```

1234 - Change sending_at response on SkipSend=on

---

prime-router/metadata/valuesets/covid-19.valuesets
prime-router/src/main/kotlin/Mappers.kt

This PR adds the following valueset to covid-19
**- code: 373121007
display: Test not done**
- covid-19.valuesets
- #issue
- #issue

added the new valueset, still need to implement tests

---

prime-router/src/main/kotlin/azure/HistoryFunctions.kt

This PR fixes the security hole identified previously
- 
- 
- #issue
- #issue

Fixes to security hole

---

prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
prime-router/metadata/schemas/direct/careevolution-covid-19.schema
prime-router/settings/organizations-local.yml
prime-router/settings/organizations-test.yml
prime-router/settings/organizations.yml
prime-router/settings/staging/0027-direct.yml

This PR adds Care Evolution as a sender.
- Added Care Evolution as a sender
- Create schema for Care Evolution
- #issue
- #issue

1349 Added Care Evolution sender and schema

---

prime-router/src/main/kotlin/azure/HistoryFunctions.kt
prime-router/src/main/kotlin/azure/ReportFunction.kt

This PR fixes issues the linter found with code format. These are just formatting changes. 
- Removes wildcard import
- Fixes line-length exception
- Removes redundant braces
There's *NO* logic changes here, just code formatting fixes

Fixes ktlint exceptions

---

prime-router/docs/getting_started.md

remove sftp since the docker-compose.yml provides an sftp container and update postgreSQL docker-compose command
-
-
- n/a (readme change)
- Does this PR include changes in authentication and/or authorization of existing endpoints? n/a (readme change)
- Does this change introduce new dependencies that need vetting? n/a (readme change)
- Does this …

README: remove sftp and update postgreSQL docker-compose command

---

frontend/src/js/prime-web-receiver-post.js
frontend/src/js/prime-web-receiver-pre.js

This PR fixes the idle timer (15min timeout)
- created isLoggedIn function
- called idle timeout in pre-functions
- #issue
- #issue

Fixed idle timer

---

prime-router/src/main/kotlin/Report.kt

This PR fixes an issue where the `qualityFilter` test reported a warning on value set lookup for null ethnicity code. Nothing was actually breaking, it reported an error, so I added an `if` check around the value set lookups to stop the warning from being reported. …

Fixes error on saving metadata with null value sets

---

prime-router/docs/releases/2021-06-25-release-notes.md

This PR adds release notes for the production release of 6-25-2021

Release notes for 6-25-2021

---

prime-router/docs/proposals/0008-cdc-ip-space.md

This is a proposal for the IP CIDR request we need to submit to the CDC, which is a prerequisite to peering with the Palo Alto firewall. Items to discuss are listed within the proposal.

Proposal: IP Address CIDR Request

---

prime-router/metadata/valuesets/common.valuesets
prime-router/src/testIntegration/resources/datatests/CSV_to_HL7/sample-batch-pdi-20210608-0001.hl7

This PR fixes the bug with the incorrect coding system in PID-22 (Patient Ethnicity). 
-Old: NULLFL
-New: HL70189
- Deleted coding system in common.valuesets
- Updated HL7 batch file in datasets
- #1432

Bg 1432 remove nullfl from hl70189

---

prime-router/docs/getting_started.md
prime-router/docs/how-to-onboard-a-receiver.md
prime-router/docs/how-to-run-static-site.md

Some of the docs have not kept up with the times. They needed updated. They are now.

Updates docs to reflect the current reality

---

prime-router/src/main/kotlin/azure/DatabaseAccess.kt

This PR converts the async inserts for the COVID result metadata into a batch insert.
- Threat _T_, which could be achieved by _A_, is …

Converts the async insert into a batch insert

---

frontend/package-lock.json

This PR updates the devDependencies in the package lock file to clear four security vulnerabilities currently present in our ReportStream website. Given the fact that there was a transitive dependency I tested this by running the static site locally. If you want to do the same to verify functionality (and you should), you need to follow these steps:
- Open a terminal into the `frontend` folder
- Run `npx eleventy --config eleventy.config.js` to generate the files
- Run `npx eleventy --serve --config eleventy.config.js` to launch the site
- You will see two URLs presented to you, one labeled `local` and the other `ui`. The local is a copy of our static site running on a port like `localhost:8091`. Your port may be different. The `ui` link is to browsersync which lets you live reload the …

Updates node packages to clear dependabot security vulnerabilities

---

prime-router/settings/organizations.yml
prime-router/src/main/kotlin/cli/FileUtilities.kt
prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
prime-router/src/test/csv_test_files/input/otc-template.csv

https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/1488
To run the test
a) ./gradlew primeCLI --args='test --run otcproctored'
This PR ...
-
-
- Does this change …

add otc/proctored tests

---

prime-router/src/main/kotlin/cli/tests/TestReportStream.kt

The new OTC receivers needs to be filtered out from allGoodReceivers which is used by
the end2end test
- This PR adds OTC on the exclude filter for allGoodReceivers
Test plan
a) verify `./gradlew primeCLI --args='test'` has no failures
b) ./quick-test.sh
- What are the potential security threats …

fix end2end test: exclude OTC receiver from allGoodReceivers

---

CONTRIBUTING.md
LICENSE
README.md

This PR updates the licensing in the project to match SimpleReport and provide clarity about whether or not contributions would violate the Anti-Deficiency Act. There's no code changed here. Just doc updates.
- Updates LICENSE
- Updates contributing.md
- Updates README.md
- #270

Updating licensing

---

frontend/src/_includes/identifier.liquid
frontend/src/_layouts/protected.liquid

This PR ...
- Deletes rogue `npm` text following a CDN link in `_layouts/protected.liquid`. Was breaking build process on my localhost.
- Adds required HHS vulnerability disclosure policy link to the footer.
- Does this …

Add HHS vulnerability disclosure policy link to footer

---

prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
prime-router/metadata/schemas/OR/or-covid-19-hl7.schema
prime-router/quick-test.sh

This PR creates a folder for Oregon (metadata/schems/OR) with an HL7 schema. Additionally, OR was added to quick-test.sh. Data can now be created for Oregon to fit their HL7 spec.
- added OR folder with HL7 schema extending the covid-19 schema
- added OR to quick-test.sh
- What are the potential …

Bg 1364 oregon hl7 schema

---

operations/app/src/environments/02-config/main.tf
operations/app/src/modules/container_registry/main.tf
operations/app/src/modules/container_registry/variables.tf
operations/app/src/modules/function_app/main.tf

This PR enables the Trust Policy (i.e. notary service) on our Azure Container Registry. This is step on towards making sure we run signed containers in our environment. (The second step is actual signing in the CI/CD pipeline - with validation - and the final step being enforcing it).
See https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/docker-content-trust.md for more information. 
NOTE: this should be validated in a developer resource group first, but due to logistical issues, I cannot do that (yet).
- The main terraform code that manages the container registry (see `02-config/main.tf`) sets the value for `enable_content_trust` to `true` (note: the other highlighted changed lines are due to indentation)
- The terraform container_registry now accepts a boolean …

Signed Container Images: enable trust policy in the registry and prepare for enforcement

---

.github/workflows/build_frontend.yaml
.github/workflows/build_hub.yml

This PR runs our PR GitHub Action suite on merge to master. This will send an email to the commit author if the build breaks after a merge and provides traceability when a build breaks.
- Adds a push to master trigger on the router and frontend GitHub Actions
- What are the potential security …

Run tests when merging into master

---

prime-router/docs/schema_documentation/or-or-covid-19-hl7.md

This PR updates schema doc that broke build.  Looks like e0081d0f0fd35ae497173dd28f7929a7e8b67368 is the first bad commit in master
Test:
1. Verify the build for this branch is successful.
- updated schema doc that broke build

Updated schema doc that broke build

---

prime-router/cleanslate.sh

This PR ...
-
-
- Does this PR include or remove any sensitive …

Updated script to use ownership flag

---

prime-router/settings/put-local-settings.py
prime-router/src/main/kotlin/azure/DownloadFunction.kt
prime-router/src/main/kotlin/azure/HistoryFunctions.kt
prime-router/src/main/kotlin/azure/ReportFunction.kt
prime-router/src/main/kotlin/azure/SettingsFunctions.kt
prime-router/src/main/kotlin/tokens/AuthenticationStrategy.kt
prime-router/src/main/kotlin/tokens/OktaAuthentication.kt

Hey @jimduff-usds || @RickHawesUSDS , maybe @pablocaviglia as well,  this is a draft PR to see if I am on the right track for using the Okta authentication service in a reusable way.
I took the code from the SettingsFunctions class and placed it into its own class to be reusable.
The plan is to move it over to the HistoryFunctions next.
Please review this to see if I am on the right track with what you all were thinking.
I am definitely open to feedback!
Thank you :)
-----------
This PR refactors the token auth into a reusable class
**If you are suggesting a fix for a currently exploitable issue, please disclose the issue to the prime-reportstream team directly outside of GitHub instead of filing a PR, so we may immediately patch the affected systems before a disclosure. See …

1390 - Refactor Bearer token authentication into reusable class

---

prime-router/metadata/schemas/iPatientCare/ReddyFMC-LA-covid-19.schema
prime-router/settings/prod/0036-reddyfmc-la.yml
prime-router/settings/staging/0034-reddyfmc-la.yml

Changed capitalization of schema folder name.

tweaked capitalization of schema folder

---

.environment/gitleaks/gitleaks-config.toml

This PR adds GItLeaks exceptions for:
- 7b71499581297fc7f8b807afa8cf37d518f00205
- Doc update with a reference to `USERNAME`
- 6b04ad2134d44008a2f7bdb1fc10976830ed20ff
- Upcoming commit containing Azure AD group IDs

Whitelist expected non-secrets

---

.environment/gitleaks/gitleaks-config.toml

This PR fixes some false positives found in the Gitleaks GitHub Action run

gitleaks: fixing false positives

---

.environment/gitleaks/gitleaks-config.toml

Some additional suppressions and sorting of gitleaks rules

gitleaks: further suppressions

---

prime-router/settings/prod/0037-wa-uat.yml
prime-router/settings/staging/0037-wa-uat.yml

Connect both staging and prod to WA UAT
This PR contains the settings for connecting staging and prod to WA UAT
- Prod YML
- Staging YML
- …

Connect WA-PHD to WA UAT (test)

---

prime-router/docs/vpn.md

This PR add documentation for connecting to the staging/production VPN from Linux.

docs: Adding instructions on how to activate the OpenVPN tunnel on Linux

---

prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
prime-router/metadata/schemas/iPatientCare/ReddyFMC-LA-covid-19.schema
prime-router/metadata/schemas/iPatientCare/iPatientCare-covid-19.schema

This PR updates multiple schema columns to adjust for data differences found in Reddy production data.  
iPatientCare-covid-19.schema
ReddyFMC-LA-covid-19.schema
- #1708 Onboarding of Reddy Family Medical Clinic sender

Updating Reddy sender for differences found in production data

---

prime-router/settings/prod/0038-primary.yml
prime-router/settings/staging/0038-primary.yml

Adding configs for review for primary health.

primary configs for staging and prod

---

prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
prime-router/metadata/schemas/iPatientCare/ReddyFMC-LA-covid-19.schema

This PR is the third update for Reddy Medical Clinic.  Changing the processing_mode_code from T to P, in order to start sending data to LA DOH
ReddyFMC-LA-covid-19.schema - change processing_mode_code
- #1708 Onboarding of Reddy Family Medical Clinic sender

Onboarding of Reddy Family Medical Clinic sender

---

prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
prime-router/metadata/schemas/iPatientCare/ReddyFMC-LA-covid-19.schema

This PR contains a cherry-picked PR for a prod deploy. The PR that has been cherry-picked is: #1838

Prod Deploy 2021-08-13

---

prime-router/build.gradle.kts
prime-router/docs/getting_started.md

This PR updates the getting started doc for developers to add a few more details and tried to make some sections a bit simpler for new developers.  I also rearranged a few topics to try to make the document flow in order from building to running.  I did not go through the entire document, just a few sections. 
It is easier to read the file at this link: https://github.com/CDCgov/prime-reportstream/blob/0bf60a1c730bee9f765da074aa7bec7cda572ee4/prime-router/docs/getting_started.md
- updates the getting started doc 
- Added new Gradle task to reset/reload the database

Updated getting_started.md document with a few more details

---

prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
prime-router/metadata/schemas/iPatientCare/ReddyFMC-LA-covid-19.schema
prime-router/metadata/schemas/iPatientCare/iPatientCare-covid-19.schema

This PR updates the iPatientCare base schema and Reddy schema based on input from LADOH.
- #1708 Onboarding of Reddy Family Medical Clinic sender

Updates to Reddy schema based on input from LADOH

---

prime-router/docs/releases/2021-08-17-release-notes.md

This PR adds the release notes for the 2021-08-17 release

Adds release notes for 2021-08-17 production deploy

---

prime-router/settings/organizations.yml
prime-router/src/main/kotlin/azure/BlobAccess.kt

This PR adds minor bits of logging to blobstore upload, a possible slow point in our code.
Also fixes a problem in local organizations.yml - an erroneous sftp site for our 'giang' load test receiver.
- [] Ran `quickTest all`?
**None apply.** …

Fixed issue in local load test receiver; minor logging addition

---

prime-router/docs/vpn.md

This PR adds more Windows related info on connecting to the VPN.

Updated VPN doc with more Windows information

---

.github/vpn/test.ovpn
.github/workflows/release.yml
operations/Makefile
operations/app/src/environments/01-network/variables.tf
operations/app/src/environments/03-persistent/variables.tf
operations/app/src/environments/04-app/variables.tf
operations/app/src/environments/tf

This PR reclaims our `test` environment (deploying out our latest Terraform to it) and set `test` to be deployed alongside `staging`.
- Adds `test` to the Makefile environments
- Adds VPN profile (sans secrets) for test
- Updates release pipeline to deploy to `test` on merge to `master`
- `tf` script needed a wildcard on import to accept parameters …

Reclaim TEST environment

---

prime-router/docs/schema_documentation/direct-imagemover-covid-19.md
prime-router/metadata/schemas/direct/imagemover-covid-19.schema

This PR moves ImageMover from Training mode to Production mode
- Threat _T_, which could be achieved by _A_, is mitigated by _M_
- …

moved Imagemover from Training mode

---

prime-router/src/main/kotlin/azure/EmailEngineFunction.kt

This PR adds dual template function,
- by supplying a template set separated by : (i.e. d-1234:d-1235) this will identify a template to use for having reports in the past 24hrs (d-1234) and for not having any (d-1235).
-
- …

added dual template function

---

frontend/src/login.html
frontend/src/public-terms-of-service.html

This PR addresses the changes to support #1890 AC-8 Compliance for ReportStream Login
- added banner to login page
- added banner to terms of service
- Does …

changes to support POAM

---

.environment/gitleaks/run-gitleaks.sh

This PR fixes gitleaks to run within the Windows environment.
- fixed /repo vs. repo
-
- Does logging …

changes to support windows

---

prime-router/settings/prod/0039-wa-prod.yml

This PR only has one setting change that points WA to the WA prod environment
- Setting change 39 to point to prod
-
- Threat _T_, which …

Point WA to Prod

---

prime-router/docs/vpn.md

This PR adds info on how to fix the Windows DNS issue with OpenVPN

Update VPN doc with Windows DNS issue

---

prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
prime-router/metadata/schemas/PrimeDataInput/pdi-covid-19.schema

This PR ...
- patient_tribal_citizenship field has been added to the SimpleReport schema
- [N/A] Added tests?
None
- [N/A] Are there licensing issues with any new dependencies introduced?
- #1746 
- #issue

Add patient_tribal_citizenship to pdi schema

---

prime-router/build.gradle.kts
prime-router/docs/getting-started/faster-development.md
prime-router/docs/getting_started.md

This PR adds documentation and a gradle task to run the Azure functions locally instead of in a Docker container.  This allows for faster redeploys of changes without the need to tear down all the Docker containers.  See the included document for more information.  In my performance tests I was getting better performance (>2x) and lower CPU usage running without a container.
- Added documentation on how to run the functions locally
- Added gradle task to make it easier to run the functions locally
None

Document how to run the Azure functions locally

---

prime-router/docs/releases/2021-08-24-release-notes.md
prime-router/settings/staging/0039-hhsprotect.yml
prime-router/src/main/kotlin/cli/tests/Hl7Tests.kt
prime-router/src/main/kotlin/cli/tests/TestReportStream.kt
prime-router/src/main/kotlin/cli/tests/WatersAuthTests.kt

This PR makes small tweaks to our standard smoke test so it works in Staging.
- Removed watersauth test from the smoke test suite, since it currently requires a human in the loop to login.  The test is still available and can always be run manually, eg, `./prime --run watersauth`
- Redox tests no longer run in staging.   They always failed in staging, because we don't have a mock redox running there.  So I just removed them.  Redox tests still run locally.
_no new risks._
- Does logging contain sensitive …

Modified Smoke Test so it works in Staging

---

DEPLOYMENTS.md

This PR adds a `DEPLOYMENTS.md` to the root directory of our repository, documenting our deployment process. Resolves #1850.

Document Deployment Process

---

prime-router/docs/schema_documentation/hhsprotect-hhsprotect-covid-19.md
prime-router/metadata/schemas/hhsprotect/hhsprotect-covid-19.schema
prime-router/settings/prod/0040-hhsprotect.yml

This PR stops sending test data (data with processing_mode_code = 'T') to HHSProtect in production.   When we first turned on this stream, we allowed test data to flow so that we could ensure it was working.   This is no longer needed, as we have lots of processing_mode_code = 'P' data now flowing to Protect. …

We had been sending test data to HHSProtect -  Turning that off

---

prime-router/metadata/tables/zip-code-data.csv

This PR adds 10 additional zip codes to the zip-code-data table.
**Local RS Testing:**
Copied zip-code-data.csv to an existing branch and processed a test file with zip codes containing those added to the .CSV file.  The Error messages for 'patient_county' null are now gone.  The HL7 message produced now includes the FIPS code in PID.11.9.
I attached a document supporting the two Local RS testing.
[Pull-Request 1945 - Zip Code Update.docx](https://github.com/CDCgov/prime-reportstream/files/7040632/Pull-Request.1945.-.Zip.Code.Update.docx)
Updated metadata/tables/zip-code-data.csv
-
- #1939 Add zip codes to zip-code-data.csv

Reddy zip code update

---

.environment/gitleaks/gitleaks-config.toml

This PR fixes the GitLeaks runs of 2021-08-[28..30].

gitleaks: fix 2021-08-{28-30} runs

---

prime-router/src/main/kotlin/azure/DatabaseAccess.kt
prime-router/src/main/kotlin/azure/HistoryFunctions.kt
prime-router/src/main/kotlin/cli/tests/Hl7Tests.kt
prime-router/src/main/kotlin/serializers/Hl7Serializer.kt

This PR fixes an issue for MD where the `patient_age` AOE is being passed as CWE instead of NM or ST.
- Adds switch on element type
- Fixes ktlint errors
- #1987

Fix patient age encoding in HL7

---

prime-router/docs/playbooks/dependabot-updates.md

This PR adds a playbook for the dependabot PRs.

Adds depbot check playbook

---

frontend-react/src/pages/Daily.tsx
frontend-react/src/pages/Upload.tsx
frontend-react/src/resources/AuthResource.ts
prime-router/src/main/kotlin/azure/HistoryFunctions.kt

This PR updates how the client header for sender is retrieved.
- get client header value to look like "<orgname>.<sendername>" to match ReportStream schema definitions
- update /daily page to dynamically get organization name based on if they are a receiver
- update history/report endpoint to get a non-sender organization from user claims
no
- Does …

1390 CSV Uploader Tool - update how client header value is retrieved

---

frontend-react/src/pages/Daily.tsx

This PR adds the HIPAA data aggregation notice at the bottom of the Test Results list on the Daily Data page.
- Addition of code to `Daily.tsx`
No
No
No
- Does this change require changes to our …

Addition of HIPAA notice at bottom of test results list

---

frontend-react/src/App.tsx
frontend-react/src/index.css

This PR prepositions the footer in the DOM to make it populate at the bottom of the page properly both when the page is shorter and taller than the view-port height.
- Updated `App.tsx` to render `<Footer>` outside of the main content in the DOM
- Updated `index.css` to accomodate for proper footer height when calculating `min-height` for `.content` …

Footer moved to bottom of pages that are shorter than VH/don't scroll

---

prime-router/src/main/kotlin/cli/tests/TestReportStream.kt

This PR changes the staging timing by 10 secs

tweaked code to force a rebuild in staging

---

frontend-react/src/components/ReportStreamHeader.tsx

This PR adjusts the `<Link>` markup position to envelop the entire Login button so it can be clicked anywhere, not just on the text inside the button.
- Adjusted `<Link>` position in `ReportStreamHeader.tsx`
- Auto formatting adjusted spacing in `ReportStreamHeader.tsx`
No
No
No
No
No
No
- What are the potential security threats …

Make entire login button the clickable link

---

operations/app/src/environments/04-app/main.tf
operations/app/src/modules/application_insights/metabase.tf
operations/app/src/modules/application_insights/outputs.tf
operations/app/src/modules/application_insights/variables.tf

This PR moves App Insights for Metabase to a dedicated instance. We do not want to pollute our regular App Insights instance, but we still want the logging of Metabase to track down why Metabase keeps dying. This is a happy middle ground.
- Deploys dedicated App Insights for Metabase, only if Metabase is deployed in the environment …

Dedicated metabase App Insights

---

frontend-react/src/components/ReportStreamFooter.tsx

This PR adds the Vulnerability Disclosure Policy link to the footer
- Added `<IdentifierLinkItem>` to `ReportStreamFooter.tsx`
No
No
No
No
No
No
- Threat _T_, which could be …

Added vulnerability disclosure policy link to footer

---

prime-router/src/main/kotlin/azure/ReportFunction.kt

This PR fixes an issue where the client id simple_report was changed to simple-report, and so couldn't be found in the settings.   The dash is needed by Okta, so I just pushed the char replacement down into the if (Okta)... code.
@ahay-agile6 can you check whether  the csv uploader is OK?
I've tested locally with simple_report, and I've tried other sad paths eg missing client header.  Also sending the client as a query parameter works too.
- Does this PR include or …

fixed issue where simple_report could not submit

---

prime-router/docs/jurisdiction-connection-status.md
prime-router/src/main/kotlin/azure/ReportFunction.kt

master-> production

---

frontend-react/src/pages/Upload.tsx
frontend-react/src/resources/SenderAuthResource.ts
frontend-react/src/resources/SenderOrganizationResource.ts
frontend-react/src/webreceiver-utils.ts
prime-router/src/main/kotlin/azure/Authentication.kt
prime-router/src/main/kotlin/azure/ReportFunction.kt
prime-router/src/main/kotlin/azure/SettingsFunctions.kt

This PR separates the sender permission from the receiver permission on the ReportStream side when retrieving organization data.
- the /api/settings/organizations/{organame} endpoint now checks the headers for the authentication-type
- if the auth type is okta, it passes that information to the api functions and gets the correct claims check from the okta verifier
- added react hooks when …

1390 - independent okta sender permissions

---

frontend-react/src/App.css
frontend-react/src/App.tsx
frontend-react/src/pages/Daily.tsx

This PR re-styles the `<Suspense>` spinner and adds indication of no results returning rather than showing an empty table.
- Updated `App.tsx` where the spinner was in a nested `div` to now a single `div` housing the spinner, ID changed to `#spinner`
- Updated `App.css` to remove old `#div` and `#spinner` attributes no longer needed, and address the ID change
- Updated `Daily.tsx` where reports are pulled from back-end from `TableData` to `TableReports` component and pass results in as `props` to `TableData` (This was done for the ease of checking `results.length` and showing the "No results" message. If kept in `TableData` and checked there, a DOM error appears in console regarding a `<p>` not being able to be the child of `<table>` despite still rendering properly.)
- Does this PR …

Updated spinner styling and "no results" text for empty table

---

frontend-react/src/content/live.json

This PR updates the `CDCMap` component by adding the missing states to `src/content/live.json` (list of active sites updated Sept. 3)
- Addition of missing states to `live.json`
No
No
No
No
No
No
- **S**poofing …

Updated live map based on jurisdiction-connection-status.md update

---

prime-router/src/main/kotlin/tokens/TokenAuthentication.kt
prime-router/src/test/kotlin/azure/TokenFunctionTests.kt

This PR ...
- Tests that a bad request will fail with an UNAUTHORIZED response.
- Sets up a pattern for controlled testing of the Azure functions.
- #1766
- General style, are there changes to make this more idiomatic Kotlin?
- Are there any cases where input/output cases that you can think of that aren't covered? (or aren't covered clearly?)
- Are any of the Mocks too aggressive reducing the meaningfulness of the tests.

FHIR Auth Unit Tests

---

frontend-react/src/pages/Daily.tsx

This PR removes an unused frontend-react import
-
-
- Does this …

remove unused SpinnerCircular import

---

frontend-react/src/content/live.json

This PR updates states to reflect were we are currently.
-
-
- …

reflect new states

---

prime-router/metadata/tables/zip-code-data.csv

**Local RS Testing:**
Copied zip-code-data.csv to an existing branch and processed a test file with zip codes containing those added to the .CSV file.  The Error messages for 'patient_county' null are now gone.  The HL7 message produced now includes the FIPS code in PID.11.9.
- #2113

Update zip codes

---

prime-router/metadata/tables/zip-code-data.csv

**Local RS Testing:**
Copied zip-code-data.csv to an existing branch and processed a test file with zip codes containing those added to the .CSV file.  The Error messages for 'patient_county' null are now gone.  The HL7 message produced now includes the FIPS code in PID.11.9.
- #2165

rhood/2165 Add zip codes

---

frontend-react/src/App.tsx
frontend-react/src/components/ReportStreamHeader.tsx
frontend-react/src/resources/PermissionsResource.ts
frontend-react/src/webreceiver-utils.ts

This PR adds the `DHPrimeAdmins` permission label to `PermissionsResource.ts` and converts the file to an enumerated class file.
- Converts `PermissionsResource.ts` to `enum` class
- Adds `PRIME_ADMIN` to class
No
No
No
No
No
No
- What are the potential security threats and mitigations? Please list the _STRIDE_ threats and how …

Added DHPrimeAdmins to PERMISSIONS enum

---

frontend-react/src/pages/TermsOfService.tsx

This PR adds the POAM based instructions on top of the terms of service page
-
-
- Does logging …

added message to terms of service

---

frontend-react/src/components/ReportStreamFooter.tsx
frontend-react/src/pages/Login.tsx
frontend-react/src/pages/how-it-works/SystemsAndSettings.tsx
frontend-react/src/pages/how-it-works/WebReceiverGuide.tsx

This PR fixes content discrepancies 
Test Steps:
1. Navigate to the pages outlined in the Issues and ensure changes are presented.
- Updated content with fixes required by Issues
- #2208 
- #2209 
- #issue
- What are the potential …

React content fixes

---

frontend-react/src/content/live.json

This PR updates the map to not show currently-onboarding states; only fully onboarded and live states.
Test Steps:
1. Navigate to "Where we're live!" and check the map/list for errors
-  Updated content in `live.json`
- #2210 
No
No
No
No
No
No
- What are the potential security threats and mitigations? Please list the _STRIDE_ …

Updated map to remove states who are onboarding

---

frontend-react/src/pages/how-it-works/ElrChecklist.tsx
frontend-react/src/pages/how-it-works/GettingStarted.tsx
frontend-react/src/pages/how-it-works/SecurityPractices.tsx
frontend-react/src/pages/how-it-works/SystemsAndSettings.tsx
frontend-react/src/pages/how-it-works/WebReceiverGuide.tsx

This PR fixes content in the new React site to match the content from our source of truth (production site)
Test Steps:
1. Check each page under How It Works for any grammatical or wording errors.
- Updates to most files in `/src/pages/how-it-works`
- 
- #2205 
No
No
No
No
No
No …

React site content fixes under "How it works"

---

prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
prime-router/docs/schema_documentation/experity-experity-covid-19.md
prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
prime-router/metadata/schemas/Experity/CUC-AL-covid-19.schema
prime-router/metadata/schemas/Experity/GUC-LA-covid-19.schema
prime-router/metadata/schemas/Experity/experity-covid-19.schema
prime-router/metadata/valuesets/sender-automation.valuesets

This PR contains all modifications necessary to add the Healgen IgG/IgM Rapid Test to the  Experity parent schema, and child schema Compass Urgent Care.  Greenlight Urgent Care is an Experity client, so it was re-tested to insure changes didn't break it.
Also multiple other fixes/changes were made as listed under "Changes" and "Fixes" below.
Test Steps:
1. If requested, I've saved the …

rhood/2166-CUC-Add Healgen Antibody test

---

frontend-react/src/pages/Upload.tsx

This PR updates the wording for buttons and alert boxes in the CSV Uploader tool according to this ticket: https://app.zenhub.com/workspaces/prime-data-hub-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/2124
Test Steps:
1. in the ReportStream front-end, browse to `/upload`
2. upload a file that has known warning issues
3. check the wording for the "Alert" box that pops up. …

2124 Change Wording for Sender Submission Alert for Warnings

---

frontend-react/src/App.css
frontend-react/src/App.tsx
frontend-react/src/components/Spinner.tsx
frontend-react/src/controllers/OrganizationController.ts
frontend-react/src/pages/daily/Daily.tsx
frontend-react/src/pages/details/Details.tsx
frontend-react/src/pages/details/Summary.tsx
frontend-react/src/pages/how-it-works/WebReceiverGuide.tsx

This PR addresses some of the blocker bugs from the React Bug Bash
- Fixed breadcrumb on the Details page to link back to `/daily-data` rather than `/data`
- Breadcrumb link also now uses the org name instead of "Covid-19"
- Extrapolated the functionality to get an org name as string and created the `useOrgName()` hook
- Added HIPAA notice to Details page
- Removed PDF downlaod link from Data Download Website Guide page
- Added `<Suspense>` wrapper to give `/details` loading spinner 
- Updated the `<Spinner>` component with props, prop types, and `React.CSSProperties` variables for styling (removed from `App.css`)
- Added typing for most files touched (please leave comments where you see the need for typing to be added!)
- #2301 
- #2310 
- #2291 
- #2294  …

Squashing react bugs

---

frontend-react/src/components/ReportStreamHeader.tsx

This PR adjusts the dropdown menu for How It Works so clicking off of it or clicking the menu button again will close the menu. 
- Refactored the dropdown to its own component (from standard JSX element) to contain state and menu data
- Added event listeners to the `DropdownHowItWorks` component to listen for clicks elsewhere
- #2288 
No
No
No
No
No
No
If you answered '_yes_' to any of the questions above, conduct a detailed Review …

Clicking off of dropdown menu now closes the menu

---

prime-router/src/main/kotlin/azure/HistoryFunctions.kt

This PR removes the call to get the facilities from `getReports`

Removes the call to get the facilities from getReports

---

frontend-react/src/pages/how-it-works/SystemsAndSettings.tsx

This PR fixes a link from `/how-it-works/where-were-live` and opens it in a new tab
- Link changed for standard data schema MD file on GitHub
- #2302 
No
No
No
No
No
No
- …

Link fix and target change

---

frontend-react/src/pages/details/Details.tsx
frontend-react/src/pages/details/FacilitiesTable.tsx
frontend-react/src/resources/FacilityResource.ts
frontend-react/src/resources/ReportResource.ts
frontend-react/src/webreceiver-utils.ts
prime-router/src/main/kotlin/azure/DatabaseAccess.kt
prime-router/src/main/kotlin/azure/HistoryFunctions.kt
prime-router/src/main/resources/db/migration/V19__add_report_facilities_function.sql

This PR pulls facilities for reports on the `report-details` page through a temporary `fetch()` solution. This will later be changed over to a `useResource` call from `rest-hooks`.
Test Steps:
1. Pull `kevinhaube/details-facilities-fix`
2. Run `npm install` for good measure, then `npm start`
3. Spin up your backend, too
4. Navigate to the details page of a report
5. You should see a spinner while the table loads, then facilities listed in the table!
- Added temporary facilities call, `useState()`, and `Facility` type
- #2343 
- #2365
- #2368 
No
No
- Does this change introduce new dependencies that …

Details page pulls report facilities 

---

frontend-react/package-lock.json
frontend-react/src/pages/details/FacilitiesTable.tsx

This PR removes the empty dependency array for `useEffect` in the `<FacilitiesTable>` component. To fix this, I've added the `getFacilities` function and `facilitiesURL` variable as dependencies to `useEffect`. This resulted in infinite calls to the API due to the facilities function being "remade" endlessly. This is why you'll now find `getFacilities` wrapped in the `useCallback` hook with a dependency that does not change. This means the function will ONLY be recreated if that dependency changes, thus `useEffect` is not calling this function endlessly.
Test Steps:
1. pull `kevinhaube/react-build-errors`
2. `npm run build`
3. Ensure the following warning isn't present: `React Hook useEffect has a missing dependency: 'getFacilities'. Either include it or remove the dependency array`
4. …

Fixed empty dependency array in useEffect

---

frontend-react/src/index.css
frontend-react/src/pages/Login.tsx

This PR addresses styling discrepancies between prod and staging on the `/login` page
- `Alert` changed to `SiteAlert`
- Padding added to `<main>` in `app.css` to compensate for USWDS style library not having proper padding (see images)
Prod using USWDS SCSS
Local (after fix) using `trussworks/react-uswds/lib/uswds.css`
- #2283 
no
no
no
no
no
no …

Login page style fixes

---

frontend-react/src/pages/Upload.tsx
frontend-react/src/pages/daily/Daily.tsx

- Network errors include okta permissions issues and cors errors.
- I keep hitting (and having to fix locally) typescript errors in Upload.tsx

Fix blank page when there's a network error the loading the table

---

frontend-react/package-lock.json
frontend-react/package.json
frontend-react/src/App.tsx
frontend-react/src/oktaConfig.ts

This PR includes the 15 minute idle timeout for the React app
Test Steps:
1. pull `kevinhaube/timeout-in-react`
2. Open `App.tsx` and change the `timeout` value in `useIdleTimer()` to a shorter period of time (change `15` to like `.25` for 0:15 timeouts)
3. `npm start`
4. Log in
5. Wait...
6. ....
7. Did it log you out? Did you get redirrected to `http://localhost:3000/`??
- Adds `useIdleTimer()` to `App.tsx` with settings for a 15m timeout
- Adds `signOutRedirectURI` to `oktaConfig`
- #2381 
No
No
No
No
- Does logging contain sensitive …

React app timeout

---

prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
prime-router/docs/schema_documentation/experity-experity-covid-19.md
prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema
prime-router/metadata/valuesets/sender-automation.valuesets

This PR contains all modifications to the All-In-One-Health Schema to:
- Populate the SPM.2.1.1 with the OBR.2.1 instead of the MSH.10.1.
- Added values to the sender-automation.valuesets to translate the specimen type SNOMED code received to the appropriate Specimen Source Site SNOMED code and insert it into the SPM.8.
- The client will send the equipment_model_name instead of the test_kit_id_name to be used in the LIVDLookup.
**If you are suggesting a fix for a currently exploitable issue, please disclose the issue to the prime-reportstream team directly outside of GitHub instead of filing a PR, so we may immediately patch the affected systems before a disclosure. See [SECURITY.md/Reporting a Vulnerability](https://github.com/CDCgov/prime-reportstream/blob/master/SECURITY.md#reporting-a- …

Rhood/2398 Changes to All-In-One-Health schema

---

frontend-react/package-lock.json
frontend-react/package.json
frontend-react/src/App.tsx
frontend-react/src/components/AuthorizedRoute.tsx
frontend-react/src/controllers/OrganizationController.ts
frontend-react/src/pages/Login.tsx
frontend-react/src/pages/daily/Table/TableButtonGroup.tsx
frontend-react/src/pages/daily/Table/TableReports.tsx
frontend-react/src/pages/details/Details.tsx
frontend-react/src/pages/error/ErrorPage.tsx
frontend-react/src/pages/home/Home.tsx
frontend-react/src/pages/home/Sections/LiveMapSection.tsx
frontend-react/src/pages/how-it-works/WhereWereLive.tsx
frontend-react/src/resources/AuthResource.ts
frontend-react/src/webreceiver-utils.ts
frontend-react/tsconfig.json

- Set `noImplicitAny: true`
- Fix types where solution is simple/obvoius
- Add `// @ts-nocheck // TODO: fix types in this file` to top of the file where further changes are needed

Turn on noImplicitAny in typescript config

---

prime-router/src/main/kotlin/azure/ReportFunction.kt

One more guess and check to fix this problem:
Not reproing locally so just have to push changes to staging and see

Fix hyphen character not displaying correctly

---

prime-router/metadata/schemas/covid-19.schema

This PR adds the `equiptment_model_name` to the OBX 17.2 component which is the text component. This component is currently blank, but other components are filled. So for BinaxNow, the OBX 17 field will read: 
```
10811877011290_DIT^BinaxNOW COVID-19 Ag Card^99ELR
```
Instead of the current
```
10811877011290_DIT^^99ELR
```
##Background
The OBX 17 field is a Coded Element field for the Observation Method. 
> OBX-17 Observation Method (CE) 00936
>
> Components:  <Identifier (ST)> ^ <Text (ST)> ^ <Name of Coding System (ID)> ^
<Alternate Identifier (ST)> ^ <Alternate Text (ST)> ^ <Name of Alternate
Coding System (ID)>
The reference [HHS guidance page](https://confluence.hl7.org/display/OO/Proposed+HHS+ELR+Submission+Guidance+using+HL7+v2+Messages#ProposedHHSELRSubmissionGuidanceusingHL7v2Mes …

Fix #2347: Fill the OBX-17.2 field with equipment model

---

frontend-react/src/components/ReportStreamHeader.tsx

This PR makes /upload path NavLink.
Test Steps:
-
- #issue
- Does this PR include changes in authentication and/or …

CSV Uploader: make /upload path NavLink

---

frontend-react/src/components/header/ReportStreamHeader.tsx
frontend-react/src/pages/details/Summary.tsx
frontend-react/src/pages/how-it-works/WebReceiverGuide.tsx
frontend-react/yarn.lock

- NavLink for going back to /daily-data from report page
- NavLink for going to /about
- NavLinks in the /how-it-works/data-download-guide page
This will keep all navigation within the single page app and prevent unnecessary page requests

Use a NavLink where possible

---

.github/workflows/build_frontend.yaml

This PR fixes the frontend GitHub Actions not running and removes an unused upload step.

fix: Frontend CI not running

---

frontend-react/src/components/header/HowItWorksDropdown.tsx
frontend-react/src/components/header/ReportStreamHeader.tsx

All header links should use NavLink to take advantage of the benefits of a single page app

Nav links in header

---

frontend-react/src/components/header/ReportStreamHeader.tsx

As titled. This is breaking out build https://github.com/CDCgov/prime-reportstream/runs/3797624533?check_suite_focus=true

Remove unused link import

---

operations/app/src/modules/database/main.tf

https://docs.microsoft.com/en-us/azure/postgresql/concepts-limits#maximum-connections

Increase database instance size

---

prime-router/src/main/kotlin/serializers/CsvSerializer.kt

Simple typo fix in an error message use in csv parsing
Test Steps:
1. Verify error now says "found" instead of "founder"
- #issue …

Typo fix: founder -> found

---

frontend-react/package.json
frontend-react/yarn.lock

This PR removes chart.js from frontend-react. It's not presently in use
Test Steps:
1. frontend-react builds
- #issue …

Remove chart.js

---

frontend-react/src/App.tsx
frontend-react/src/pages/details/Details.tsx
frontend-react/src/pages/error/ErrorPage.test.tsx
frontend-react/src/pages/error/ErrorPage.tsx
frontend-react/src/pages/home/Sections/LiveMapSection.tsx
frontend-react/src/pages/how-it-works/WhereWereLive.tsx

- Fix ts errors and tighten up types in general.
- Add unit tests ErrorPage.

Fix ts erros for ErrorPage

---

.github/workflows/release.yml

This PR modifies the release github flow to build and deploy the React site, removing the same for the 11ty site. The actual process is already working in staging.

Modify the production flow to build/release React site

---

prime-router/build.gradle.kts
prime-router/src/main/kotlin/transport/SftpTransport.kt

This PR rolls the SSHJ library version back to fix issues we're seeing with delivery of files

Rollsback SSHJ version bump

---

frontend-react/package.json
frontend-react/yarn.lock

This PR ...
Test Steps:
- #issue
- Does this PR include …

Move react-scripts to dev dep

---

frontend-react/src/resources/AuthResource.ts

This PR ...
Test Steps:
- #issue
- Does this PR include …

Update prod base url

---

frontend-react/src/resources/AuthResource.ts

This PR ...
Test Steps:
- #issue
- Does this PR include …

Revert back to prime.cdc.gov for react api calls

---

.environment/eslint/run-eslintCheck.sh
.environment/pre-commit.runner.sh
frontend-react/package.json
frontend-react/src/App.tsx
frontend-react/src/components/ReportStreamFooter.tsx
frontend-react/src/pages/TermsOfService.tsx
frontend-react/src/pages/home/Home.tsx
frontend-react/src/pages/home/Sections/LiveMapSection.tsx

This PR ...
- Creates a shell script pre-commit hook that will run if there are any changes to .tsx or .js files to look for lint errors
Test Steps:
1. Make a format change in a .tsx file that breaks lint convensions
2. Commit the change
3. See that there is a warning 
4. Repeat for .js files
- #issue
- Does this PR include or remove any sensitive information …

Create eslint pre-commit hook

---

prime-router/build.gradle.kts
prime-router/build.sh
prime-router/cleanslate.sh
prime-router/devenv-infrastructure.sh
prime-router/docker-compose.yml
prime-router/docs/getting-started/Using-an-apple-silicon-mac.md
prime-router/docs/getting_started.md

This PR helps developers with an M1 Mac by giving them an M1 specific getting started doc and by putting checks into our dev scripts that handle M1 Mac. The M1 Mac has to be a special case because Microsoft doesn't produce a docker image that runs on the M1 Mac. 
This PR is a redo of #2625 which had a few unverifiable commits in it. It was simpler to just redo the changes in a fresh branch. 
Test Steps:
On your local dev-box, either Windows or Mac)
- Run cleanslate.sh
- Run devenv-infrastructure.sh
- A new getting started doc for the M1 mac
- devenv-infrastructure.sh has a m1 mac check
- cleanslate.sh has a m1 check
Could look at combining `getting started.md` and this M1 mac. 
- new …

Fix our dev scripts to run on Apple Silicon Macs

---

.github/workflows/stats.yml

This creates the config to generate PR stats. 
Source: https://github.com/marketplace/actions/pull-request-stats …

Create GH Action to generate PR stats

---

frontend-react/package.json
frontend-react/yarn.lock

We pre-maturely bumped the version https://github.com/CDCgov/prime-reportstream/pull/3061/files There are some breaking changes we'll need to address with this version increase
- #issue
- What …

Revert react-router back to v5

---

frontend-react/.env.staging

This PR is testing to see if staging uses `.env.staging` properly
Test Steps:
- #issue
If you answered '_yes_' to any of the questions above, …

Test to see if Staging uses this env

---

prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
prime-router/docs/schema_documentation/covid-19.md
prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
prime-router/docs/schema_documentation/direct-hca-covid-19.md
prime-router/docs/schema_documentation/fl-fl-covid-19.md
prime-router/docs/schema_documentation/gu-gu-covid-19.md
prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
prime-router/docs/schema_documentation/hl7-primary-covid-19.md
prime-router/docs/schema_documentation/hl7-test-covid-19.md
prime-router/docs/schema_documentation/la-la-covid-19.md
prime-router/docs/schema_documentation/mt-mt-covid-19.md
prime-router/docs/schema_documentation/nd-nd-covid-19.md
prime-router/docs/schema_documentation/nm-nm-covid-19-csv.md
prime-router/docs/schema_documentation/nm-nm-covid-19.md
prime-router/docs/schema_documentation/oh-oh-covid-19.md
prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
prime-router/docs/schema_documentation/standard-standard-covid-19.md
prime-router/docs/schema_documentation/tx-tx-covid-19.md
prime-router/docs/schema_documentation/vt-vt-covid-19.md
prime-router/metadata/schemas/covid-19.schema
prime-router/metadata/valuesets/tribal.valuesets

This PR sets PID-39.2 and PID-39.3 when `tribal_citizenship` is received from Simple Report and other CSV senders. 
Test Steps:
1. Generate a simple report CSV. 
2. Add a tribal affiliation value for a patient. Value 448 is one that was sent recently. 
3. Look the resulting PID-39. 
=> PID-39.1,2,3 should be filled in. `448^Native Village of Kotzebue^HL70171` in this case. 
- The tribal citizenship value set is now labeled as an HL7 valueset instead of meaningless FHIR. 
- #3235 
- #issue
- Does this …

Improve Tribal reporting

---

prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema

This PR contains modifications to the All-In-One-Health Schema to resolve the issue outline in #3224 .  Those issue are:
- Receiving warning that column "Ok to Contact Patient".
- Initial testing indicates that the County text received is more accurate that using the zip code to lookup the FIPS County code.
Test Steps:
1. Re-run the AI1 test file and:
- Validate all FIPS County codes are …

rhood/3224 A1H Changes based on Testing

---

operations/app/src/modules/function_app/autoscale.tf

* This is being done in preparation for additional load from Abbott;
once we have the async report submission API ready to go we may dial
it back down.
This PR increases the default number of hosts available for function apps from 2 to 3.
Once the PR is accepted and merged we'll need to apply the changes with terraform. …

Set the default number of hosts to 3 (from 2)

---

prime-router/metadata/tables/zip-code-data.csv

rhood/3275-Add Zip Codes

---

frontend-react/package.json
frontend-react/yarn.lock

Dependabot tried to bump this but we're not using it
Test Steps:
1. Front end builds and runs fine
- #issue
- What are the potential security threats and mitigations? Please list the _STRIDE_ …

Remove user-event npm module

---

frontend-react/package.json
frontend-react/yarn.lock

Cypress deeper dependencies are pulling in an older version of json-schema.
cypress@^9.0.0 -> cypress@^9.1.0 fixes.
`yarn list` was used to track down. …

json-schema package upgrade

---

frontend-react/src/content/live.json
frontend-react/src/content/usa_w_territories.svg

issue https://github.com/CDCgov/prime-reportstream/issues/2740
Test Steps:
1. Launch the RS front end and verify that TN and OR are shaded
- #issue …

Add TN and OR to map

---

.github/workflows/release.yml

Pass different argument to yarn based on whether we're building staging or prod

---

.github/workflows/release.yml

This PR updates the gradle invocations in the `release` workflow to match those in the `build_hub` flow. @carlosfelix2 pointed out the differences in https://github.com/CDCgov/prime-reportstream/pull/3276
Test Steps:
1. Run the release flow (which this will do when merged to master.
- Use `gradlew` to startup gradle …

Update gradle invocations in release flow to match build_hub flow

---

.github/workflows/release.yml

Do not execute tests yet

---

.github/workflows/release.yml

Also copy over the docker compose invocation

---

prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema

This PR contains modifications to the All-In-One-Health Schema outlined in Ticket #3310 which is "Users sometimes do not enter the Ordering Provider ID/NPI, but most States want a Provider Id, so we need to populate the Ordering Provider ID and Name with default Provider information for this Sender."
Test Steps:
1. Clear the Provider ID/ NPI column in the A1H test file.
2. Re-run the AI1 …

rhood/3310-A1H Add Default Provider

---

prime-router/metadata/tables/zip-code-data.csv

rhood/3333-CUC Zip Code Updates

---

prime-router/docs/azure-dashboard-faq.md

Notes about how to use azure dashboard

azure faq creation and notes, from meeting with ops 12/7/2021

---

frontend-react/src/pages/Upload.tsx

Issue: https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3305
Errors and warnings were flipped
Test Steps:
1. Upload a csv that has expected errors and warnings
2. Verify that the errors and warnings are in the correct place
- Correct how errors and warnings are set
- Check array length instead of `warningCount` and `errorCount` since this just feels more reliable 
- #issue
- Does this change require changes …

Correct reversed upload errors and warnings

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0054-update-vt-doh.yml
prime-router/settings/staging/0054-update-vt-doh.yml
prime-router/src/main/kotlin/serializers/Hl7Serializer.kt
prime-router/src/test/kotlin/serializers/Hl7SerializerTests.kt

This PR replaces the value of MSH-3-1 with the value of "CDC PRIME - Atlanta,"
Test Steps:
1. Generate test data for VT
2. Run docker
3. Import settings to docker
4. Generate HL7 file through the api
5. verify that MSH-3-1 has a value of "CDC PRIME - Atlanta,"
- Edits to org file 
- Addition of yamlito file to prod and staging folder
- #3363  …

VT - replaceValue for MSH-3-1

---

.environment/gitleaks/run-gitleaks.sh

This PR ...
Fixes the issues with the 8.x version of gitleaks. New commands as well as new flags were needed to use the latest version. Local log file creation was also removed as this seemed unnecessary.
Test Steps:
1. Run pre-commit hooks and verify gitleaks runs as expected.
- Updated the command for gitleaks to protect
- Updated flags to account for gitleaks changes
- Removed local log file creation in lieu of terminal output …

Updated gitleaks version, commands, and flags

---

.environment/gitleaks/run-gitleaks.sh

This PR fixes a cosmetic issue from the gitleaks fix on the previous commit. …

Remove the comment I accidentally kept in with previous

---

prime-router/build.gradle.kts

* More about vulnerability: https://www.lunasec.io/docs/blog/log4j-zero-day/
Test Steps:
1. Normal operation, and logs are emitted as normal. …

Update log4j due to public security vulnerability (log4shell)

---

.environment/gitleaks/gitleaks-config.toml

This PR ...
Fixes an error we had with a scan giving us a false positive. After discussing with the team, it was decided to remove it as opposed to possibly fixing it.
Test Steps:
1. Run commit hooks and verify no errors are generated.
- Removed the entry for the test. …

Removed entropy scan

---

prime-router/src/main/kotlin/azure/TokenFunction.kt
prime-router/src/main/kotlin/tokens/SenderUtils.kt

This PR fixes 2 bugs that occur when a sender requests a token.
Test Steps:
1. Do steps 1a, 1b, and 2 in https://github.com/CDCgov/prime-reportstream/blob/master/prime-router/docs/playbooks/how-to-use-token-auth.md
Previously, step 2 failed with a 404 error, and then a 500 error after the 404 was resolved.  When successful, it returns a token as described under step 2.
- URL fixed in SenderUtils.kt
- Default value added for metadata parameter in TokenFunction constructor
- #3430 …

Fixing 2 bugs with token request

---

frontend-react/src/pages/Submissions.tsx

The react component was getting stuck in a loop since every time submissions was set it would fire the fetch again. `useEffect` here will only trigger the fetch if organization or authState update.
Test Steps:
1. Go to submissions page
2. Open network console
3. Verify api call to submissions only happens once
This also removed an unnecessary JSON.parse
- #issue
- …

Add useEffect to prevent unnecessary submission fetches

---

.environment/pre-commit.runner.sh

This PR ...
Temporarily removes the gitleaks hook until we can determine the issues we are having with the current rules.
Test Steps:
1. Commit and verify that gitleaks does not run.
- Commented out gitleaks from the pre-commit runner script. …

Temporarily removed gitleaks commit hoook

---

prime-router/build.gradle.kts

* See https://logging.apache.org/log4j/2.x/security.html for discussion …

Update log4j dependency (again) due to refined handling of security vuln

---

prime-router/build.gradle.kts
prime-router/docs/schema_documentation/direct-pmg-covid-19.md
prime-router/metadata/schemas/direct/pmg-covid-19.schema
prime-router/settings/organizations.yml
prime-router/settings/prod/0055-pmg.yml
prime-router/settings/staging/0055-pmg.yml

This PR onboards PMG (Premier Medical Group USA).  It includes a new direct schema for the sender and associated settings changes.
Note when modifying HHSProtect in staging and production, the included configuration is a copy as of the most recent yamlito and may not exactly represent the current configuration. As usual, 'get' the latest receiver configuration from that environment, make the associated change, and 'set' it back.
Test Steps:
1. Send a sample csv file for sender "pmg"
- Adds new direct child schema pmg-covid-19.schema
- Adds PMG to organizations.yml as a new sender
- Adds staging and prod yamlitos for PMG
- #3427 
| …

Onboarding sender PMG

---

prime-router/src/main/kotlin/azure/EmailSenderFunction.kt

This PR sets emails in-code for TOS agreement endpoint
Test Steps:
- #issue …

Emails no longer rely on env vars

---

prime-router/src/test/resources/metadata/tables/testkit-lookup.csv

This PR contains the table needed to use `lookup()` to find testkit information
Test Steps:
- #issue
If you answered '_yes_' to any of the …

Add testkit lookup table

---

.github/changelog_config.json
.github/workflows/github_release.yaml

This PR updates the GitHub actions workflow file that will generate a GitHub release with artifacts for every push to production to include the a configuration file that properly finds PRs submitted between release tags
Test Steps:
1. Push (merge PR) to production branch
- Update `.github/workflows/github_release.yml` to use a configuration file that properly sorts release tags.
- #1048  …

fixes #1048 add config file to github release

---

prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema

This PR contains modifications to the All-In-One-Health Schema outlined in Ticket #3507.  This modification allow results with blank or invalid Patient County to flow to CA PHD.
Test Steps:
1. Clear or enter an invalid value in the Patient County column in the A1H test file.
2. Re-run the AI1 test file and verify that the file doesn't fail, and the PID.11.9 is blank.
*List GitHub issues …

OO/3507/A1H Make Patient County Optional

---

.github/actions/build-frontend/action.yml
.github/workflows/build_frontend.yaml

This PR fixes https://github.com/CDCgov/prime-reportstream/pull/3532 because I forgot we can't use secrets directly in local actions. 
Test Steps:
1. App builds and deploys properly on Github
- Define inputs for the local front-end build action, and pass values for all inputs from the release workflow
- [-] Tested locally?
- [-] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [-] Are there licensing issues with any new dependencies introduced?
- [-] DevOps team has been notified if PR requires ops support?
| …

Fix how we pass in keys for AppInsights to the local action

---

prime-router/build.gradle.kts

This PR updates log4j from 2.16 to 2.17 to deal with a recently discovered Denial of Service attack.
Test Steps:
1. Ensure the app builds as normal
- Updates log4j to 2.17 …

Bump log4j to 2.17 to deal with discovered DoS attack

---

.github/actions/build-frontend/action.yml
.github/workflows/release.yml

This PR adds an empty line to the relevant .env file before adding the app insights key. Otherwise we run the risk of running the text into the previous setting, which happened in the 2021-12-21 deploy.
Test Steps:
1. Run the Github Action and verify the site is working
- Update build for frontend .env files
- [-] Tested locally?
- [-] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- [-] Are there licensing issues with any new dependencies introduced?
- [-] Includes a summary of what a code reviewer should test/verify?
- [-] DevOps team has been notified if PR requires ops …

Add empty line to appropriate .env file before adding the app insights key

---

prime-router/build.gradle.kts

This PR removes the fuzzy cdv library from the application because it is no longer in use
Test Steps:
1. Run `gradle build test testIntegration`
2. Run docker and do a local smoke test
- Removes fuzzy-csv from the application …

Removing the fuzzy csv library from the application

---

prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema

This PR contains modifications to the Experity Parent Schema outlined in Ticket #3590  .  The changes in the PR will force an error message to be given if the equipment model name is blank.  Also, CAPHD is ready to receive these results into Production, so the processing mode is now "P" instead of "T".
Test Steps:
1. Clear the field Equipment Model Name in the A1H test file.
2. Re-run the …

OO/3590- A1H Equipment Model Required

---

.environment/terraform-fmt/run-terraform-fmt.sh

This PR fixes the pre-commit terraform hook that scans terraform files on change.
Test Steps:
1. Run the pre-commit hooks against the repo.
2. You will get the message that it's skipping tf formatting checks as no tf files were edited.
- Changed the bash conditional to correctly check against the git response.
-  #3027 …

Removed incorrect brackets for terraform eval

---

frontend-react/src/pages/tos-sign/SuccessPage.tsx
prime-router/src/main/kotlin/azure/EmailSenderFunction.kt

This PR updates the TOS email to be sent from a non-CDC email as CDC emails are not allowed to be used as `From` addresses in SendGrid.
- From email changed to non-CDC email
- Reply-to email set as RS email
- #issue
If you answered '_yes_' to any of the questions above, conduct a detailed Review …

TOS Email Bug Fix

---

prime-router/build.gradle.kts

* This PR updates log4j to latest. See https://nvd.nist.gov/vuln/detail/CVE-2021-44832
Test Steps:
1. Application builds and passes tests
- Update log4j dependency from 2.17.0 to 2.17.1 …

Update log4j to 2.17.1 for latest issue found

---

prime-router/src/main/kotlin/azure/BatchDeciderFunction.kt

This PR points BatchDecider at the receivers list in WorkflowEngine.
Test Steps:
1. A regular smoke test should show that its reading in the receivers.
2.  Simply change a timing setting in the database (an easy one to change is maxReportCount) and look in the batchDecider logs to see that that new value appears. …

Fixed issue where BatchDecider was using TestReportStream settings

---

prime-router/src/main/resources/log4j2.xml

This PR sets "additivity=false" for the root log4j logger in hopes that this curbs the flood of logging happening in production.
Test Steps:
1. Deploy the app
2. Look at the log messages getting sent to AppInsights and Log Analysis Workbench
- Turn off additivity for the root log4j logger …

Turn additivity off for the root logger

---

.github/workflows/github_release.yaml

This PR updates the GitHub actions workflow file that will generate a GitHub release with artifacts for every push to production to include a well formatted body of release notes
Test Steps:
1. Push (merge PR) to production branch
- Update `.github/workflows/github_release.yml` to publish the release with a well formatted body of release notes
- #1048  …

fixes #1048 replace release body

---

.github/workflows/github_release.yaml

This PR prevents the error of release body containing too many characters by disabling auto-generated release notes from the ncipollo/release-action, as release notes are generated via mikepenz/release-changelog-builder-action
Test Steps:
1. Publish to production branch
- Removed creation of release notes from ncipollo/release-action,
- #1048  …

fix #1048 body content length exception

---

prime-router/docs/playbooks/how-retry-mechanisms-work.md
prime-router/docs/schema_documentation/direct-ihealthlabs-covid-19.md
prime-router/metadata/schemas/direct/ihealthlabs-covid-19.schema
prime-router/settings/staging/0061-ihealthlabs.yml

This PR creates a schema for iHealthLabs. …

setup for iHealthLabs

---

prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
prime-router/docs/schema_documentation/experity-experity-covid-19.md
prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
prime-router/docs/schema_documentation/manualupload-csvuploadertest-covid-19.md
prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
prime-router/docs/schema_documentation/upload-covid-19.md
prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema
prime-router/metadata/valuesets/sender-automation.valuesets

This PR contains modifications outlined in ticket #3740 to fix  errors during fake data generation,  set the trackingElement on the schema, and add Race Code: 1002-5 to sender-automation.valueset
Test Steps:
1. To test fake data errors, run "./prime data --input-fake 100 --input-schema non-standard/all-in-one-health-ca-covid-19 --output junk/all-in-one-health-ca-fake.csv"
2. Run  ./prime …

OO/rhood/3740 - A1H - Errors Generating Fake Test

---

prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
prime-router/docs/schema_documentation/experity-experity-covid-19.md
prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
prime-router/metadata/schemas/Experity/CUC-AL-covid-19.schema
prime-router/metadata/schemas/Experity/GUC-LA-covid-19.schema
prime-router/metadata/schemas/Experity/experity-covid-19.schema
prime-router/metadata/schemas/iPatientCare/ReddyFMC-LA-covid-19.schema
prime-router/metadata/schemas/iPatientCare/iPatientCare-covid-19.schema

This PR contains modifications outlined ticket #3764 to fix errors during fake data generation, clear invalid Illness Onset Date and set the trackingElement on all schemas.
Test Steps:
1. To test fake data errors, run the CLI below.
- ./prime data --input-fake 100 --input-schema Experity/GUC-la-covid-19 --output junk/GUC-la-fake.csv
- ./prime data --input-fake 100 --input-schema …

OO/rhood/3764-ReddyFMC and Experity Error Generating Fake Data

---

prime-router/docs/schema_documentation/manualupload-csvuploadertest-covid-19.md
prime-router/docs/schema_documentation/upload-covid-19.md
prime-router/metadata/schemas/manualupload/csvuploadertest-covid-19.schema
prime-router/metadata/schemas/upload-covid-19.schema

This PR contains modifications outlined ticket #3780  to fix errors during fake data generation, clear invalid Illness Onset Date, set the trackingElement on all schemas, and re-implement IfNotPresent on ordering_facility_street2.
Test Steps:
1. To test fake data errors, run the CLI ""./prime data --input-fake 100 --input-schema manualupload/csvuploadertest-covid-19 --output …

OO/rhood/3780 Std CSV - Fix Fake Data Error

---

frontend-react/package.json
frontend-react/yarn.lock

- `react-scripts` depends on an old version of `postcss`. I tried upgrading `react-scripts` but it breaks backwards compatibility. After a couple of days of trying to get `react-scripts` 5.0.0 to work, but I gave up. I'm just forcing react-scripts to use the latest version of `postcss` (using yarn's `"resolution"` feature).
- Also updated `uswds` and `@trussworks/react-uswds` to the latest. …

Upgrade postcss

---

prime-router/build.gradle.kts
prime-router/src/main/kotlin/azure/EmailEngineFunction.kt

This PR removed JCenter from the dependency repo list as it has been permanently shutdown.
Test Steps:
1. Build the baseline using `gradle package`
2. Run RS locally using Dockerless by running `gradle run`
3. Run the smoke tests against your Dockerless instance.  If the json-smart dependency is not included as part of the gradle plugin then requests will fail.
- Removed JCenter
- Removed khttp library, which only exists in JCenter
- Force the use of the json-smart library by gradle.
- #issue
- Does this change introduce …

Removed JCenter from dependency repo list

---

frontend-react/src/pages/submissions/SubmissionsTable.tsx
frontend-react/src/resources/SubmissionsResource.ts
frontend-react/src/webreceiver-utils.ts

Paginate Submission History#3497
https://app.zenhub.com/workspaces/prime-reportstream-5ff4833beb3e08001a4cacae/issues/cdcgov/prime-reportstream/3497
This PR adds pagination to the submission history page.
Test Steps:
You need records for the sending facility you are affiliated with.
For testing purposes, you can set the `paginationPageSize` in …

Experience #3497: Paginate Submission History

---

frontend-react/.env.production
frontend-react/src/components/GlobalContextProvider.tsx
frontend-react/src/pages/Upload.tsx
frontend-react/src/resources/SenderAuthResource.ts
frontend-react/src/utils/UserUtils.ts
frontend-react/src/webreceiver-utils.ts

When logged in as admin, we noticed the Upload page was making a request with `https://prime.cdc.gov/api/settings/organizations/ignore.ignore-waters ` for the request.
Test Steps:
1. Log in as admin into production.
2. Go to the Upload page.
Result: blank page page is the result.
- Fix string (that's only used for console.log) from "staging" to "production"
- Load the current Organization from the session vars to make sure it's correct.
- Fix logout flow. It wasn't always calling okta to revoke and some of the session vars were sticking around.
|                                                                                                                                                                            | User               | Total reviews | Median …

Fix production issues when going to Upload as Admin

---

prime-router/docs/schema_documentation/manualupload-sourcebioscience_ca-covid-19.md
prime-router/metadata/schemas/manualupload/sourcebioscience_ca-covid-19.schema
prime-router/settings/organizations.yml
prime-router/settings/prod/0064-sourcebioscience_ca.yml
prime-router/settings/staging/0064-sourcebioscience_ca.yml

This PR contains modifications need to add Source BioScience to the CSV Uploader Pilot.  See ticket #3847 
Test Steps:
1. Process the attached standard CSV Test file using the CLI command "./prime data --input result_files/StandardCSV-Test.csv --input-schema manualupload/sourcebioscience_ca-covid-19 --output-dir junk --route"
- #3847 
*Create GitHub …

OO/rhood/3847 Source BioScience sub-schema for CSV Uploader Pilot

---

frontend-react/src/content/live.json
frontend-react/src/content/usa_w_territories.svg

This PR updates the SVG map for Sprint 33
Test Steps:
1. Pull and serve
2. Navigate to `How it works -> where we're live` and ensure the map properly represents our coverage.
- Removed `Arkansas` since it's listed as `not engaged` on the spreadsheet
- Fixes #3255
- #issue …

Updated svg to match PHD onboarding tracker

---

prime-router/docs/schema_documentation/manualupload-cadph-csvuploadertest-covid-19.md
prime-router/docs/schema_documentation/manualupload-sourcebioscience_ca-covid-19.md
prime-router/docs/schema_documentation/upload-covid-19.md
prime-router/metadata/schemas/manualupload/cadph-csvuploadertest-covid-19.schema
prime-router/metadata/schemas/upload-covid-19.schema
prime-router/settings/organizations.yml
prime-router/settings/prod/0065-cadph-csvuploadertest.yml
prime-router/settings/staging/0065-cadph-csvuploadertest.yml

This PR contains modifications need to add CA-PHD to the CSV Uploader Pilot.  See ticket #3854 
Test Steps:
1. Process the attached standard CSV Test file using the CLI command "./prime data --input result_files/StandardCSV-Test.csv --input-schema manualupload/caphd-csvuploadertest-covid-19 --output-dir junk --route"
- #3854  
*Create GitHub issues to …

OO/rhood/3854 CA-PHD CSV Uploader Test

---

.github/actions/build-frontend/action.yml
.github/actions/deploy-frontend/action.yml
.github/changelog_config.json
.github/workflows/github_release.yaml

This PR corrects the time range used to generate release notes.
Test Steps:
1. Push to production branch to generate a new release
- Release notes are now generated after new tag is created instead of before.
- #1048  …

close #1048 build release notes after creating tag

---

.github/actions/build-vars/action.yml

This PR removes a hardcoded version tag that was left in for testing.
Test Steps:
1.  Run release pipeline from master
- Removes hardcoded version tag …

removed hardcoded version tag set for testing

---

frontend-react/src/App.tsx

This tab isn't quite ready yet
Test Steps:
1. Verify admins can see submissions tab
2. Verify senders cannot
- Hide submissions tab from senders (only viewable to admins)
- #issue
- What are the …

Hide submissions tab from senders until ready

---

.github/ISSUE_TEMPLATE/research.md

This PR ...
Adds a research issue template.
Test Steps:
- Adds a research issue template.
- #issue …

Add research issue template (with signed commit this time)

---

frontend-react/src/pages/Upload.tsx

This PR removes the "warning" alert box from the CSV Upload page.
references: https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/3892
Test Steps:
1. log in to reportstream
2. upload a file that has warnings for a sender's schema
3. there should be no warning alert box that pops up
- removes warning alert box from the CSV upload response
- …

Experience #3892: Remove Warnings from Display to the Sender on CSV Upload

---

.github/actions/build-vars/action.yml

This PR forces change trigger if prod deploy …

force change trigger if prod deploy

---

.gitignore
operations/app/src/modules/storage/main.tf

This PR expands data retention in the storage account from 30 to 60 days.
Test Steps:
1. Check that files older than 30 days are in the storage account
- Modifies the retention policy to keep data in the storage account for an additional 30 days.
- #3879  …

Expand data retention policy from 30 to 60 days (closes #3879)

---

prime-router/src/main/kotlin/FileSettings.kt
prime-router/src/main/kotlin/azure/Event.kt

This PR addresses two minor issues found in the most recent Fortify code scan.
Test Steps:
1. Run tests and ensure they pass
1. Add `hashCode()` implementation for few small objects that implemented `equals()` without it
2. Do not include the full filesystem path in the message of an exception, just the filename.
- [-] DevOps team has been notified if PR requires ops support?
|                                                                                                                                                                            | User               | Total reviews | …

Address a couple minor code scanning issues

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0068-add-lemoore-naval-clinic.yml
prime-router/settings/staging/0068-add-lemoore-naval-clinic.yml

This PR adds Lemoore Naval Clinic as a CSV uploader sender
Test Steps:
- Adds Lemoore Naval Clinic as a CSV uploader sender
- Closes #3910  …

Add Lemoore Naval Clinic as a Sender

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0067-sourcebioscience_ca.yml
prime-router/settings/prod/0068-cadph-csvuploadertest.yml
prime-router/settings/prod/0069-vivature-tx.yml
prime-router/settings/staging/0069-vivature-tx.yml

This PR adds Vivature as a CSV Uploader Sender
Test Steps:
curl -X POST -H "client:vivature-tx" -H "content-type:text/csv" --data-binary "@./result_files/StandardCSV-Test-v2.csv"  "http://localhost:7071/api/reports"
[StandardCSV-Test-v2.csv](https://github.com/CDCgov/prime-reportstream/files/7937531/StandardCSV-Test-v2. …

OO/rhood/4025 Add vivature-tx as a CSV Sender

---

prime-router/docs/releases/2022-01-28-release-notes.md

This PR just add a release notes document. …

Added 2022-01-28 release notes

---

prime-router/src/main/kotlin/azure/ActionHistory.kt

Before this the grouping for item type errors would not fire. It checks
the value based on a hard coded string, which needed to be updated to
match the scope it comes from.
This PR corrects the capitalization of the grouping string `item`
Test Steps:
1. Ensure that `itemNums` is present in responses with item level error values
- #3986  …

#3986 Correct grouping check for new scope ENUM

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0070-vt-aoe.yml
prime-router/settings/staging/0070-vt-aoe.yml

This PR provides an update to the Vermont receivers to filter AOE questions from all results.
Test Steps:
1. update local settings
2. create fake data with AOE questions:
`./prime data --input-fake 1 --input-schema primedatainput/pdi-covid-19 --output <FILEPATH> --target-states VT`
2. curl created test file and ensure AOE questions are not included in the HL7 output
- update organizations.yml
- add yamilitos for prod and staging
- #3954  …

Onboarding ops/3954/filter aoe for vt

---

prime-router/docs/schema_documentation/upload-covid-19.md
prime-router/metadata/schemas/upload-covid-19.schema

This PR sets processing_mode_code to "T" for all Senders until the routine to set it from the settings table is debugged.
Test Steps:
curl -X POST -H "client:cadph-csvuploadertest" -H "content-type:text/csv" --data-binary "@./result_files/StandardCSV-Test-AL.csv"  "http://localhost:7071/api/reports"
- #issue - List …

OO/rhood/4082 CSV Uploader - Temporarily Set Processing Mode to T

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0071-cdphe-csvuploader.yml
prime-router/settings/staging/0071-cdphe-csvuploader.yml

This PR adds CDPHE (Colorado) as a CSV Uploader Sender
Test Steps:
curl -X POST -H "client:cdphe-csvuploader" -H "content-type:text/csv" --data-binary "@./result_files/StandardCSV-Test-AL.csv"  "http://localhost:7071/api/reports"
[StandardCSV-Test-AL.csv](https://github.com/CDCgov/prime-reportstream/files/7970494/Standa …

OO/rhood/4088 Add CSV Sender - CDPHE (CO)

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0068-cadph-csvuploadertest.yml
prime-router/settings/prod/0070-sdilabs-ca.yml
prime-router/settings/staging/0068-cadph-csvuploadertest.yml
prime-router/settings/staging/0070-sdilabs-ca.yml

This PR adds Vivature as a CSV Uploader Sender
Test Steps:
curl -X POST -H "client:sdilabs-ca" -H "content-type:text/csv" --data-binary "@./result_files/StandardCSV-Test-AL.csv"  "http://localhost:7071/api/reports"
[StandardCSV-Test-AL.csv](https://github.com/CDCgov/prime-reportstream/files/7970494/StandardCSV-Test-AL.c …

OO/rhood/4056 YML for SDI Labs

---

frontend-react/src/pages/Upload.tsx

This PR fixes errors on the upload page not showing what rows the error occurs in
Test Steps:
1. Upload a file using the CSV uploader
2. Ensure errors with Scope `item` are given row numbers in the proper column
- #issue …

Updated field name to represent back-end change

---

frontend-react/src/pages/details/FacilitiesTable.tsx
prime-router/docs/releases/2022-01-28-release-notes.md
prime-router/metadata/schemas/upload-covid-19.schema

This PR works around a rest-hooks bug that was causing the facilities results to render as duplicated and unsorted, even though the JSON response was solid. This is all @kevinhaube and @TomNUSDS 's work, btw, i'm just taking the credit. Thanks, guys!
Test Steps:
1. Login as admin
2. On the Daily Data page, click on a report that has multiple tests from multiple facilities
3. Facilities reporting table is always ordered by Organization with no duplicated rows
Some examples of pages this is fixing:
- on staging: [ca-dph](https://staging.reportstream.cdc.gov/report-details?reportId=8a0e1095-9318-4e38-9c71-c5325edebc92)
- on prod: [il-phd](https://reportstream.cdc.gov/report-details?reportId=0c202dbc-2229-4b4b-a4f4-baa4df2f0124)
- FacilitiesTable.tsx only
- before
- after
- #issue - List …

experience/3794: fixed rendering of (seemingly) duplicated items

---

prime-router/src/main/kotlin/azure/HistoryFunctions.kt

This PR sets the logging of an exception in the history API to the debug level, so a normal bad token or authorization does not show as an exception in Azure.  This matches what the other functions do.  Not sure why the History API has its own OKTA validation code.
Test Steps:
1. Send a request to `http://localhost:7071/api/history/report` with the following headers:
a. `Authrorization` to `Authorization : Bearer dummy`
b. `organization` to `ignore`
2. Verify that only a warning is shown in the logs about an invalid token.  E.g.,  ` WARN  gov.cdc.prime.router.azure.GetReports - Unable authenticate user: Token did not contain signature:`
- set the logging of an exception in the history API to the debug level
- Closes #4064
- new …

4064 History function token validation errors not log exceptions

---

prime-router/src/main/resources/db/migration/V32__action_time_and_sender_indexes.sql
prime-router/src/main/resources/db/migration/V33__report_file_created_sender_index.sql

This PR tracks indexes created manually (using `CREATE INDEX CONCURRENTLY...`) in both production and staging. The `IF NOT EXISTS` clause should make Flyway's application of the migration a no-op, but we'll have it tracked for database builds.
We ran these with `CONCURRENTLY` during off-hours to minimize the I/O impact on production traffic. Doing it this way also ensures that future deployments don't block on the index being created.
Test Steps:
1. Run the application (tests) with a fresh database.
2. Run the application (tests) with an existing database.
- Add three indexes; two to the `action` table and one to the `report_file` table.
- [-] Are there licensing issues with any new dependencies …

Backfill indexes created for action and report file

---

.github/ISSUE_TEMPLATE/devops_request.md

Proposing a template to be used for requests to PRIME-devops, initially used primarily by the PHDI team.

Create DevOps Request issue template

---

prime-router/src/main/kotlin/azure/BatchDeciderFunction.kt
prime-router/src/main/kotlin/azure/DatabaseAccess.kt
prime-router/src/test/kotlin/azure/BatchDeciderTests.kt

Small update - separate out logic for calculating batch message count, update batch decider tests to verify functionality …

fixing empty batch tests

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0073-ocrapidtest-ca.yml
prime-router/settings/staging/0073-ocrapidtest-ca.yml

This PR adds OC Rapid Test in CA as a CSV Sender (Issue #4175 )
Test Steps:
curl -X POST -H "ocrapidtest-ca" -H "content-type:text/csv" --data-binary "@./result_files/StandardCSV-Test-AL.csv"  "http://localhost:7071/api/reports"
[StandardCSV-Test-AL.csv](https://github.com/CDCgov/prime-reportstream/files/7970494/Standar …

OC Rapid Test in CA - Add as a new CSV Sender

---

prime-router/src/main/kotlin/cli/tests/BasicTests.kt
prime-router/src/main/kotlin/cli/tests/TestReportStream.kt

This PR ...
Fixed Bug-Qualityfilter Smoke Test Fails when runs in --async mode
Test Steps:
1. docker-compose down
2. ./gradlew package
3. docker-compose up
4. run the following commands:
prime test --sequential --async --run qualityfilter
5. User should see the following screen output:
6. 
- https://app.zenhub.com/workspaces/pipeline-6182b02547c1130010f459db/issues/cdcgov/prime-reportstream/3974
- #issue
- …

3974: Fixed Bug-Qualityfilter Smoke Test Fails when runs in async mode

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0074-warrior-dx-co.yml
prime-router/settings/staging/0074-warrior-dx-co.yml

This PR adds Warrior Diagnostics as a CSV Sender (Issue #4205  )
Test Steps:
curl -X POST -H "warrior-dx-co" -H "content-type:text/csv" --data-binary "@./result_files/StandardCSV-Test-AL.csv"  "http://localhost:7071/api/reports"
[StandardCSV-Test-AL.csv](https://github.com/CDCgov/prime-reportstream/files/7970494/Standar …

OO/rhood/4205 - Warrior Diagnostics - Add as new CSV User

---

prime-router/build.gradle.kts

* Originally done as part of PR #3679
This PR updates cron-utils with a minor version.
Test Steps:
1. Build and test
- Updates the cron-utils dependency
- N/A
N/A …

Re-apply cron-utils update

---

prime-router/docs/api/lookup-tables-openapi.yaml
prime-router/docs/openapi.yml

This PR replaces https://github.com/CDCgov/prime-reportstream/pull/4043
Test Steps:
- #issue …

api spec updates

---

prime-router/docs/schema_documentation/upload-covid-19.md
prime-router/metadata/schemas/upload-covid-19.schema

This PR contains modifications needed to add Reporting Facility Name and Reporting Facility CLIA to the CSV Schema.  Patient Primary Language was also added even though it is not saved and reported yet.  See Ticket #4219 
**Test Steps:**
1. In your local RS environment, run "./prime multiple-settings set --input ./result_files/settings/local/al-phd-local.yml" after you rename the attached …

OO/rhood/4219-Update CSV Schema with Reporting Facility and Patient Primary Language.

---

frontend-react/src/pages/getting-started/testing-facilities/Overview.tsx

This PR ...
Adds a link to our [Programmer's Guide for Testing Facilities and Senders](https://view.officeapps.live.com/op/view.aspx?src=https%3A%2F%2Fraw.githubusercontent.com%2FCDCgov%2Fprime-reportstream%2Fmaster%2Fprime-router%2Fdocs%2FReportStream-Programmers-Guide-for-Senders.docx&wdOrigin=BROWSELINK)
Test Steps:
- Adds link to external Programmer's Guide .docx
- #4100 
- #issue
- Does logging …

Add link to RS programmers guide .doc

---

prime-router/src/main/resources/db/migration/V35__indexes_for_action_id.sql

This PR adds indexes on `action_id` for three tables: `action_log`, `report_file`, and `report_lineage`. These indexes have already been added to staging and will be added shortly (evening of 9-Feb) to production, so a deployment of this migration will be a no-op.
Test Steps:
1. Run tests
- Adds three btree indexes: `action_log(action_id)`, `report_file(action_id)`, and `report_lineage(action_id)`
- #3722 …

Add indexes to three tables on action_id

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0077-covidclinic-org.yml
prime-router/settings/prod/0078-stemexpress-ca.yml
prime-router/settings/prod/0079-hollywoodsmiles-ca.yml
prime-router/settings/staging/0077-covidclinic-org.yml
prime-router/settings/staging/0078-stemexpress-ca.yml
prime-router/settings/staging/0079-hollywoodsmiles-ca.yml

This PR adds Covid Clinic (sending to CO only), Stemexpress in CA and Hollywood Smiles in CA as CSV Senders.  PR #4277 
Test Steps:
1. Add Covid Clinic to your local RS settings table by executing "./prime multiple-settings set --input ./settings/staging/0077-covidclinic-org.yml"
2. Add Stemexpress to your local RS settings table by executing "./prime multiple-settings set --input …

OO/rhood/4277-Add Covid Clinic and Stemexpress as New CSV Senders

---

.vscode/settings.json
operations/app/terraform/modules/container_registry/~outputs.tf
operations/app/terraform/modules/front_door/~outputs.tf
operations/app/terraform/modules/function_app/~inputs.tf
operations/app/terraform/modules/function_app/~outputs.tf
operations/app/terraform/modules/key_vault/main.tf
operations/app/terraform/modules/key_vault/~inputs.tf
operations/app/terraform/modules/key_vault/~outputs.tf
operations/app/terraform/modules/log_analytics_workspace/data.tf
operations/app/terraform/modules/log_analytics_workspace/main.tf
operations/app/terraform/modules/log_analytics_workspace/~inputs.tf
operations/app/terraform/modules/log_analytics_workspace/~outputs.tf
operations/app/terraform/modules/nat_gateway/~outputs.tf
operations/app/terraform/modules/storage/candidate_slot.tf
operations/app/terraform/modules/storage/main.tf
operations/app/terraform/modules/storage/~inputs.tf
operations/app/terraform/modules/storage/~outputs.tf
operations/app/terraform/modules/vnet/data.tf
operations/app/terraform/modules/vnet/~outputs.tf
operations/app/terraform/vars/test/main.tf
operations/app/terraform/vars/test/variables.tf

This PR updates the Log Analytics Workspace to use TF wiring between resources instead of data sources where possible. ~A few resources will remain as data sources until they are available (un-commented) in `main.tf` for the test environment.~ (data sources no longer needed)
Test Steps:
1. `terraform plan --target='module.log_analytics_workspace'`
-  updates the Log Analytics Workspace to use TF wiring between resources instead of data sources where possible …

replaced LAW data sources with resource wiring where possible

---

.github/workflows/github_release.yaml

This PR increases the retention threshold for GitHub releases from previous 5 to previous 24 (~3 months)
Test Steps:
1. Push to production branch (generates release)
- increased retained GitHub releases from previous 5 to previous 24
Fixes #4369  …

fixes #4369 increase release retention

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0080-newport-childrens-hospital-ca.yml
prime-router/settings/prod/0081-elitemedlabs-co.yml
prime-router/settings/prod/0082-youthclinic-co.yml
prime-router/settings/staging/0080-newport-childrens-hospital-ca.yml
prime-router/settings/staging/0081-elitemedlabs-co.yml
prime-router/settings/staging/0082-youthclinic-co.yml

This PR changes the name of ocrapidtest-ca to newport-childrens-hospital-ca.  It also adds EliteMed Laboratories (sending to CO only) and The Youth Clinic in CO as CSV Senders.  PR #4374 
Test Steps:
1. Add The Youth Clinic to your local RS settings table by executing "./prime multiple-settings set --input ./settings/staging/0082-youthclinic-co.yml"
2. Add EliteMed Laboratories to your …

OO/rhood/4374 - Change ocrapidtest-ca to newport-childrens-hospital-ca.  Add 2 new Senders

---

prime-router/metadata/tables/livd/LIVD-Supplemental.csv

This PR add three new entries (flowflex, binax, and cue) to the supplemental LIVD table.
Per our conversion with STRAC:
---
STRAC reached out to us to let us know that starting Monday 2/14, PA will be adding the following values to their data:
PA will be rolling out a new rapid test on Monday (02/14/2022). We wish to advice ReportStream that we will be adding the following values to our data:
equipment_model_name
Previous valid values: "binax", "cue".
New values: "binax", "cue", "flowflex"
The LIVD values STRAC has for other applications are as follows:
Device identifier: Flowflex COVID-19 Antigen Home Test*
Ordered test name: SARS-CoV-2 (COVID-19) Ag [Presence] in Upper respiratory specimen by Rapid immunoassay
Ordered test LOINC code: 97097-0
Describe the solution you'd like
Don't …

new entries to supp. livd table

---

frontend-react/src/components/Admin/OrgsTable.tsx

Prime admin bug fix.

---

prime-router/docs/schema_documentation/non-standard-all-in-one-health-ca-covid-19.md
prime-router/metadata/schemas/non-standard/all-in-one-health-ca-covid-19.schema

This PR contains modifications outlined in Ticket #4439 .  cardinality: ONE was added to multiple fields to insure they are populated and populated with the correct data.
**If you are suggesting a fix for a currently exploitable issue, please disclose the issue to the prime-reportstream team directly outside of GitHub instead of filing a PR, so we may immediately patch the affected systems before a disclosure. See [SECURITY.md/Reporting a Vulnerability](https://github.com/CDCgov/prime-reportstream/blob/master/SECURITY.md#reporting-a-vulnerability) for more …

OO/rhood/4439 - Add cardinality: ONE to multiple fields in the A1H schema

---

prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
prime-router/docs/schema_documentation/covid-19.md
prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
prime-router/docs/schema_documentation/direct-hca-covid-19.md
prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
prime-router/docs/schema_documentation/hl7-mns-covid-19.md
prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
prime-router/docs/schema_documentation/hl7-primary-covid-19.md
prime-router/docs/schema_documentation/hl7-test-covid-19.md
prime-router/docs/schema_documentation/la-la-covid-19.md
prime-router/docs/schema_documentation/mt-mt-covid-19.md
prime-router/docs/schema_documentation/nm-nm-covid-19.md
prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
prime-router/docs/schema_documentation/primedatainput-pdi-covid-19.md
prime-router/docs/schema_documentation/standard-standard-covid-19.md
prime-router/docs/schema_documentation/tx-tx-covid-19.md
prime-router/docs/schema_documentation/vt-vt-covid-19.md
prime-router/metadata/valuesets/iso.valuesets

This PR adds additional languages to the ISO639 value set, expanding our ability handle more patient preferred languages. This value set is no longer a direct copy of the ISO-639, but is a superset that includes additional languages. It also duplicates the same language multiple times for different spellings. This is on purpose, and makes our value set more useful.
As it stands we get the display value from SimpleReport, so we could receive one display value and output a different one.
- Adds new languages to the value set 
- Updates the documentation
- Closes #4445 
|                                                                                                                                                                            | User               | …

Onboarding ops/4445/add additional languages to iso639

---

operations/dnsmasq/Dockerfile

This PR just anchors the dnsmasq container to Alpine v3 rather than the latest Alpine. (This is at the encouragement of the latest Fortify code scan.)
Test Steps:
1. Ensure the `dnsmasq` image still builds:
```
$ cd operations/dnsmasq
$ docker build -t azure-dnsmasq .
```
* Change `FROM` from `alpine:latest` to `alpine:3`
- [-] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container? …

Use the latest alpine v3, vs latest overall, to make Fortify happy

---

frontend-react/src/components/Admin/AdminFormEdit.tsx
frontend-react/src/components/Admin/EditReceiverSettings.tsx
frontend-react/src/components/Admin/NewSetting.tsx
frontend-react/src/pages/admin/AdminOrgEdit.tsx

This PR works around some inconsistencies in the API when trying to write blank JSON fields (or display them). See comments on #4293 for more information. Stories will be created and assigned to the pipeline team to address them
Test Steps:
1. Login as admin to ReportStream
2. Select an org to edit
3. For top-level org settings, and verify that 
- the Filters field can be blanked out and saved without error, and 
- blank values display as blank, and not as "[]" or "{}"
4. Edit a receiver setting, and verify that
- the Jurisdictional Filter, Quality Filter, Routing Filter, Processing Mode Filter, Timing and Transport fields can be blanked out and saved without error, and 
- blank values display as blank, and not as "[]" or "{}"
- **note**: the Translation field can NOT be blanked out, but …

experience/4293: workaround inconsistencies in API for writing blank JSON settings

---

prime-router/docs/schema_documentation/upload-covid-19.md
prime-router/metadata/valuesets/sender-automation.valuesets

This PR contains modifications outlined in Ticket #4467 which are the changes required to update sender-automation.valuesets with the latest ISO639 table.
**Test …

OO/rhood/4467/Add the latest ISO639 updates to sender-automation.valuesets

---

prime-router/settings/prod/0070-sdilabs-ca.yml

This PR contains modifications outlined in Ticket #4490 required to move the CSV Sender SDI Labs into production. 
**Test Steps:**
No testing needed.  The PROD YML …

OO/rhood/4490 - Move CSV Sender SDI Labs to PROD

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0084-update-nj-doh.yml
prime-router/settings/staging/0084-update-nj-doh.yml
prime-router/src/main/kotlin/serializers/Hl7Serializer.kt

This PR edits the org file by adding OBX-23-1 in the truncateHl7Fields property for nj-doh.
NJ requested for OBX-23-1 to be truncated to the spec limit of 50 characters. While testing the output file, it was noticed that the OBX-23-1 iterations where not being truncated. 
To address this issue, truncation logic was added to the setAOE function in the hl7Serializer file.
This included the following fields:
- OBX-23-1
- OBX-24-1
- OBX-24-2
- OBX-24-3
- OBX-24-4
The logic was only added to the above fields as these are the fields with the highest chances of going over their limit.
Test Steps:
1. Generate test data for NJ
2. Edit the performing organization name to exceed 50 characters
3. Run docker
4. Load org settings to container
5. Submit test file to the api
6. Check to see the newly …

Onboarding ops/4197/nj obx.23.1 truncation/jorge

---

frontend-react/package.json
frontend-react/src/pages/submissions/SubmissionDetails.test.tsx
frontend-react/src/pages/submissions/SubmissionDetails.tsx
frontend-react/src/utils/DateTimeUtils.test.ts
frontend-react/src/utils/DateTimeUtils.ts
frontend-react/yarn.lock

This PR fixes date-time parse errors caused by mismatched date formats from API. 
Test Steps:
1. Pull and `yarn test` to ensure tests still pass.
2. Spin up and ensure the submissions detail page shows the date instead of "parsing error" where dates are meant to be.
- [] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container? …

Fixing date parsing for Submissions pages

---

prime-router/metadata/tables/local/LIVD-SARS-CoV-2.csv

This PR updates LIVD table with the latest from production.  No code changes. …

Updated LIVD table with the latest from production

---

prime-router/src/main/kotlin/azure/DatabaseSubmissionsAccess.kt
prime-router/src/main/kotlin/azure/SubmissionFunction.kt
prime-router/src/main/kotlin/azure/SubmissionsFacade.kt
prime-router/src/test/kotlin/azure/SubmissionFunctionTests.kt

This PR adds an optional `sortCol` query param for the `/api/history/{org}/submissions` endpoint. Sorting column defaults  to `CREATED_AT` (i.e. the prior default action) if an invalid or no `sortCol` is provided.
Test Steps:
1. Pull and set breakpoints where needed to track the piping of `qSortCol` from the azure function trigger to the db access layer.
- optional query param added to `/api/history/{org}/submissions`
- #4270 
- #4362 
- …

Submissions API: sortCol query param

---

frontend-react/src/pages/submissions/SubmissionDetails.tsx
frontend-react/src/resources/ActionDetailsResource.ts
frontend-react/src/resources/TestResponse.ts
frontend-react/src/utils/DateTimeUtils.test.ts

This PR makes necessary field name changes outlined in #4241 
Test Steps:
1. Pull and run `yarn test`
2. Spin up and observe the title component on `/submissions/:taskId` page to ensure values are properly set.
- What are the potential security threats and mitigations? Please list the _STRIDE_ …

Updated to match work done in #4241

---

prime-router/docs/schema_documentation/direct-cue-covid-19.md
prime-router/metadata/schemas/direct/cue-covid-19.schema

This PR modifies the Cue schema to accommodate an HHS request that Cue include an additional identifier for tests being conducted by Eurofins.  For these tests, Cue is sending the value "OpET – CEI" in patientHomeAddress2.  
HHS Protect data is deidentified, so patientHomeAddress2 is not sent.  This PR modifies the mapping so that patientHomeAddress2 is sent to performingFacility if it contains the value "OpET – CEI". Eurofins data do not have a performingFacility.
Test Steps:
Submit Cue tests and observe the following behavior:
-patientHomeAddress2 is populated as received from Cue (provided the receiver data are not deidentified)
-performingFacility is populated as received from Cue
-if performingFacility is not populated by Cue, it is populated with "OpET – CEI" if patientHomeAddress2 …

Updating Cue schema for Eurofins data

---

prime-router/src/main/resources/db/migration/V40__report_lineage_report_id_indexes.sql

* Note that these indexes already exist in both staging and production,
so the migration will be a no-op.
Test Steps:
1. Run the migration
- Adds indexes to the `parent_report_id` and `child_report_id` fields in `report_lineage`
- [o] Added tests?
- #4528  …

Add indexes on parent/child report fields in report_lineage

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0084-update-nj-doh.yml
prime-router/settings/staging/0084-update-nj-doh.yml
prime-router/settings/staging/0085-update-ca-dph-truncate-obr-16-3-orc-12-3.yml

This PR address the issue where OBX-11 and OBR-25 have code of 'W'. NJ has reached out to us letting us know to filter out all test results with an observation result status code of 'W'.
To filter out these test results, a routing filter needs to be added to the settings file for NJ, that would only accept codes of P, C, and F.
Test Steps:
1. Generate test data for NJ
2. Change observation result status to 'W'
3. Start your docker containers
4. Load settings to docker
5. Submit test data to api
6. verify that test result gets filtered out and is not in your sftp folder.
- adds routing filter of `matches(test_result_status, F, C, P)` to NJ settings file
- Note: the two YML files, one for prod, and one for staging, where never pushed as I did them to have them ready for this PR.
- #4429 …

Filter Code of W in OBX-11 for NJ

---

prime-router/src/main/kotlin/Sender.kt
prime-router/src/main/kotlin/azure/SettingsFacade.kt

ticket [3526](https://github.com/CDCgov/prime-reportstream/issues/3526)
added SenderType enum class
This PR modifies the Sender Class by adding a SenderType enumeration.  The SenderType provides additional data about the type of sender who is sending the data. …

add sender attributes

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0086-update-nj-truncate-orc-12-3-and-obr-16-3.yml
prime-router/settings/staging/0086-update-nj-truncate-orc-12-3-and-obr-16-3.yml

This PR truncates ORC-12.3 and OBR-16.3 for NJ.
Test Steps:
1. ./gradlew package
2. run: ./prime data --input junk/nj-fake-20220302.csv --input-schema primedatainput/pdi-covid-19 --output-format HL7 --output-dir junk --route
3. In the HL7 files verify OBR-16.3 and ORC-12.3 are truncated to 30 characters.
Test file: 
[nj-fake-20220302.csv](https://github.com/CDCgov/prime-reportstream/files/8173233/nj-fake-20220302.csv)
HL7 output:
- #issue
- Does this PR include changes in authentication and/or …

4428: NJ ORC-12.3 and OBR-16.3 truncation

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0086-update-wa-doh-suppressed-tribal.yml
prime-router/settings/staging/0086-update-wa-doh-suppressed-tribal.yml

This PR suppressed the PID-39-1, PID-39-2, PID-39-3 Tribal Affiliation Transmitted 
Test Steps:
1. ./gradlew package
2. .prime data --input junk/pdi-covid-19-wa.csv --input-schema PrimeDataInput/pdi-covid-19 --output-dir junk --route
3. Verify the PID-39 is blank
Test File:
[pdi-covid-19-wa.csv](https://github.com/CDCgov/prime-reportstream/files/8163494/pdi-covid-19-wa.csv)
- https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/3555
- #issue
- new endpoint …

3555: WA Do Not Need Tribal Affiliation Transmitted

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0087-update-il-not-receiving-observation-status.yml
prime-router/settings/staging/0087-update-il-not-receiving-observation-status.yml

This PR suppresses the Observation Status for IL.
Test Steps:
1. /gradlew package
2. /.prime data --input junk/pdi-covid-19-il.csv --input-schema PrimeDataInput/pdi-covid-19 --output-dir junk --route
3. Verify the HL7 output file "Observation Result Status" doesn't contain 'W'
Test File: 
[pdi-covid-19-il.csv](https://github.com/CDCgov/prime-reportstream/files/8179407/pdi-covid-19-il.csv)
- #issue
- Does this …

4465: IL Not receiving Observation Status

---

frontend-react/.env.staging
frontend-react/.env.test
frontend-react/package.json
frontend-react/src/__mocks__/HistoryMockServer.ts

Like "staging" site but for more testing oriented.
- fixed icon reference from staging->production. Should just be staging.
- Added command to serve out of build directory to verify builds locally `run:build-dir`
FYI @cwinters-usds . The ci/cd will need to do a `build:test` …

Frontend build support for a test site

---

prime-router/src/main/kotlin/azure/ReportFunction.kt

This PR updates the `payloadName` header name constant to lowercase since Azure Function `request` items capture headers in lowercase.
Test Steps:
- #issue
If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at …

Payload Name header extraction fix

---

prime-router/settings/prod/0088-update-il-orc-21-1-truncation.yml
prime-router/settings/staging/0088-update-il-orc-21-1-truncation.yml

This PR adds IL ORC-21-1 truncation to prod and staging settings.
Test Steps:
1. ./gradlew package
2. run ./prime data --input junk/pdi-covid-19-il.csv --input-schema primedatainput/pdi-covid-19 --output-dir junk --route
3. Verify the ORC-21-1 is as below:
Test file: 
[pdi-covid-19-il.csv](https://github.com/CDCgov/prime-reportstream/files/8188327/pdi-covid-19-il.csv)
- https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/4020
- #issue
- …

4042: IL ORC-21-1 Truncate org name to 50 chars

---

prime-router/settings/staging/0089-update-ca-dph-truncate-ORC-21-1-and-OBX-23-1.yml

This PR Update staging setting for CA-DPH
Test Steps:
- #issue …

4360: Update staging setting for CA-DPH

---

prime-router/src/main/kotlin/azure/ActionHistory.kt
prime-router/src/main/kotlin/cli/LivdTableDownload.kt
prime-router/src/main/kotlin/cli/tests/CompareData.kt
prime-router/src/main/kotlin/transport/FTPSTransport.kt
prime-router/src/main/kotlin/transport/SftpTransport.kt
prime-router/src/testIntegration/kotlin/FakeReportIntegrationTests.kt
prime-router/src/testIntegration/kotlin/SimpleReportIntegrationTests.kt
prime-router/src/testIntegration/kotlin/datatests/TranslationTests.kt

This PR takes care of some small issues found by the Fortify code scanning process.
Test Steps:
1. Compile and run tests
* Removing unneeded print statements
* main/kotlin/azure/ActionHistory
* main/kotlin/transport/FTPSTransport
* test/kotlin/transport/RedoxTransportTests
* testIntegration/kotlin/FakeReportInstegrationTests
* testIntegration/kotlin/SimpleReportIntegrationTests
* Explicitly closing readers/streams
* main/kotlin/cli/LivdTableDownload
* main/kotlin/cli/tests/CompareData
* testIntegration/kotlin/datatests/TranslationTests
- [-] DevOps team has been notified if PR requires ops support?
Stats for the …

Bunch of small fixes found by code scanning process

---

operations/app/terraform/modules/function_app/main.tf
operations/app/terraform/vars/dev/main.tf
operations/app/terraform/vars/dev/variables.tf
operations/app/terraform/vars/staging/main.tf
operations/app/terraform/vars/staging/variables.tf
operations/app/terraform/vars/test/main.tf
operations/app/terraform/vars/test/variables.tf

Needs to vary based on env:
* Prod: hhs-prime.okta.com
* Everything else: hhs-prime.oktapreview.com …

Make the OKTA_baseUrl functionapp config a variable

---

prime-router/docs/release-notes.md

This PR removes a release note related to the unreleased submissions API. 
Test Steps:
None
- To release notes
- Threat _T_, which could be …

Removed notes for unreleased submissions API

---

frontend-react/src/components/Admin/DiffEditorComponent.tsx
frontend-react/src/components/Admin/EditReceiverSettings.tsx
frontend-react/src/components/Admin/EditSenderSettings.tsx
frontend-react/src/pages/admin/AdminOrgEdit.tsx

This PR fixes issues found in Staging with the new diff editor component. This allows users to be able to continue to save changes while the larger issues are ironed out
Test Steps:
1. Login to ReportStream as an admin
2. Navigate to Admin->Organization Settings
3. Choose an org from the list and click Edit
4. Make edits to the top-level org fields and click Save
5. A dialog pops up informing the user that the diff window is under maintenance, and to just hit Save
6. Clicking Save updates the setting(s) accordingly.
7. Repeat steps 4-6 for senders and receivers, both edit and clone operations
- added feature flag to disable diff window in compare dialog, so that update operations can continue
*Create GitHub issues to track the work remaining, if …

experience/4264-repair: added showDiffEditor feature flag to fix breaking diff editor

---

frontend-react/src/components/Admin/EditReceiverSettings.tsx
frontend-react/src/components/Admin/EditSenderSettings.tsx

This PR fixes issues found in Staging with the new diff editor component. This allows users to be able to continue to save changes while the larger issues are ironed out
NOTE: this is a continuance of [this PR](https://github.com/CDCgov/prime-reportstream/pull/4691), but for the Clone workflows …

experience/4264-repair: added showDiffEditor feature flag to clone workflow

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0090-pcl-ca.yml
prime-router/settings/staging/0090-pcl-ca.yml

This PR adds Precision Clinical Laboratories as aCSV Sender.  PR #4696 
Test Steps:
1. Add PCL to your local RS settings table by executing "./prime multiple-settings set --input ./settings/staging/0090-pcl-ca.yml"
2. Process the attached standard CSV Test file using the CURL commands:
curl -X POST -H "pcl-ca" -H "content-type:text/csv" --data-binary …

OO/rhood/4696-Add new CSV Sender - Precision Clinical Laboratories, CA

---

prime-router/src/main/kotlin/Sender.kt
prime-router/src/main/kotlin/azure/SettingsFacade.kt

This PR adds doc changes to sender.kt and settingsfacade.kt
also manages unverified commits by creating a single new verified commit.
No code changes.
- #3526
- #issue
- What are the potential security threats and mitigations? Please list …

added kdoc to sender.kt and settingsfacade.kt

---

prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
prime-router/metadata/schemas/iPatientCare/ReddyFMC-LA-covid-19.schema
prime-router/metadata/schemas/iPatientCare/iPatientCare-covid-19.schema
prime-router/settings/organizations.yml
prime-router/settings/prod/0091-jrslab-ca.yml
prime-router/settings/staging/0090-pcl-ca.yml
prime-router/settings/staging/0091-jrslab-ca.yml

This PR contains modifications outlined in Ticket #4698.  cardinality: ONE was added to multiple fields to insure they are populated and populated with the correct data.  Also, the Reddy schema was changed to use the equipment_model_name instead of the test_kit_name_id to fix a problem found with missing OBX.17.2 for the Binax Ag Card.
**If you are suggesting a fix for a currently exploitable issue, please disclose the issue to the prime-reportstream team directly outside of GitHub instead of filing a PR, so we may immediately patch the affected systems before a …

OO/rhood/4698- ReddyFMC - Add cardinality: ONE to multiple fields

---

prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
prime-router/metadata/schemas/iPatientCare/ReddyFMC-LA-covid-19.schema
prime-router/metadata/schemas/iPatientCare/iPatientCare-covid-19.schema
prime-router/settings/organizations.yml
prime-router/settings/prod/0091-jrslab-ca.yml
prime-router/settings/staging/0090-pcl-ca.yml
prime-router/settings/staging/0091-jrslab-ca.yml

Emergency deployment for 3/11/2022 requested by @rhood23699  …

Deployment 2022-03-11

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0092-touroedu-ca.yml
prime-router/settings/prod/0093-rollinghillsclinic-ca.yml
prime-router/settings/prod/0094-quantgene-ca.yml
prime-router/settings/staging/0092-touroedu-ca.yml
prime-router/settings/staging/0093-rollinghillsclinic-ca.yml
prime-router/settings/staging/0094-quantgene-ca.yml

This PR adds three new CSV Senders.  Ticket #4727.  They are:
- Add Touro University in CA - sender_id: touroedu-ca
- Add Rolling Hills Clinic in CA - sender_id: rollinghillsclinic-ca
- Add Quantgene in CA - sender_id: quantgene-ca
Test Steps:
1. Add each Sender to your local RS settings table by executing
"./prime multiple-settings set --input ./settings/staging/0092-touroedu-ca.yml" …

OO/rhood/4727 - Add three new CSV Senders

---

prime-router/src/main/kotlin/Translator.kt
prime-router/src/main/kotlin/azure/BatchFunction.kt
prime-router/src/main/kotlin/azure/ProcessFunction.kt
prime-router/src/main/kotlin/azure/ReportFunction.kt
prime-router/src/main/kotlin/azure/SendFunction.kt
prime-router/src/main/kotlin/azure/WorkflowEngine.kt
prime-router/src/main/resources/log4j2.xml
prime-router/src/test/kotlin/azure/BatchFunctionTests.kt
prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
prime-router/src/test/kotlin/azure/SendFunctionTests.kt
prime-router/src/test/kotlin/azure/WorkflowEngineTests.kt

This PR creates the hooks for Azure and PagerDuty to pick up certain errors and ping humans to deal with it.
Test Steps:
1. If you can stand it:   Send data to a site with a screwed up sftp info or bad creds.   Wait like 3 hours for the four rounds of failures.  The final round of logging should include the new super secret magic keyword.
- [N] Are there licensing issues with any new dependencies introduced?
- [S] Includes a summary of what a code reviewer should test/verify?
- [N] Updated the release notes?
- [N/A] Database changes are submitted as a separate PR?
- [N/A] DevOps team has been notified if PR requires ops support?
- #3736 
| …

Hooks to trigger pagerduty on SendFunction and ProcessFunction failures (Ticket 3736)

---

prime-router/docs/schema_documentation/direct-cue-covid-19.md
prime-router/metadata/schemas/direct/cue-covid-19.schema

This PR adds another alt value to handle translating the `OpET - CEI` flag regardless if it contains a dash `-` or en-dash `–`. Both are converted to a dash.
Test Steps:
1. Run Cue results through containing `OpET - CEI` and `OpET – CEI` in patientHomeAddress2. HHS output will place `OpET - CEI` in performingFacility for both cases.
- Adds a code/display pair to the Cue alt values …

Add handling for Cue Eurofins flag containing a regular dash or en-dash

---

prime-router/src/main/kotlin/azure/TokenFunction.kt

The Token endpoint now adds some response data to the Action entry.
Test Steps:
1. Follow the steps [here](https://github.com/CDCgov/prime-reportstream/blob/6f755d307c5e4b892c6fdcb4d7ba8b6efbc9439b/prime-router/docs/playbooks/how-to-use-token-auth.md) to run Token authentication.
2. Run token auth on master and then do it again on this branch.
3. Check the `action` table and compare the last few entries. The `action_response` and `http_status` columns should be populated on the new entries.
- The `Token` endpoint now adds some basic response data prior to saving to the db.
- #issue
- Does this PR include changes in …

3950 Token action log Http Status

---

frontend-react/src/pages/submissions/SubmissionDetails.test.tsx
frontend-react/src/pages/submissions/SubmissionDetails.tsx
frontend-react/src/resources/TestResponse.ts

Adds service name to organization title on the Submission Details page for a report
Test Steps:
1. `yarn && yarn start:localdev`
2. As an admin, navigate to a sender org in your dropdown
3. Load their Submissions page and ensure the timestamps are hyperlinks to the details pages for each
4. Load a details page and ensure the organization title includes the service in parentheses
5. Run yarn test and ensure unit tests pass.
Add service (ELR) to Organization title on Submission Details page for a report
- #4628 
[#4590 Expose aggregate numbers for submission history](https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/4590)
- Does this PR include changes in …

Add service to organization title for submission history

---

prime-router/docs/schema_documentation/experity-cuc-al-covid-19.md
prime-router/docs/schema_documentation/experity-experity-covid-19.md
prime-router/docs/schema_documentation/experity-guc-la-covid-19.md
prime-router/docs/schema_documentation/ipatientcare-ipatientcare-covid-19.md
prime-router/docs/schema_documentation/ipatientcare-reddyfmc-la-covid-19.md
prime-router/metadata/schemas/Experity/CUC-AL-covid-19.schema
prime-router/metadata/schemas/Experity/GUC-LA-covid-19.schema
prime-router/metadata/schemas/Experity/experity-covid-19.schema
prime-router/metadata/schemas/iPatientCare/iPatientCare-covid-19.schema

This PR contains modifications outlined in Ticket #4744 .  cardinality: ONE was added to multiple fields to insure they are populated and populated with the correct data.  Also, the CUC-AL and GUC-AL schemas were changed to use the equipment_model_name instead of the test_kit_name_id.
**Test Steps:**
1. Process the attached CSV Test file using the command "curl -X POST -H …

OO/rhood/4744/Change Experity Schemas to use equipment model name and add cardinality: ONE

---

frontend-react/src/components/Admin/AdminFormEdit.tsx

- Fixes #4735
- Fires when text area unfocused
- Don't break the site when someone makes a typo. …

Warn and highlight json mistakes

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0096-update-wa-phd-obx11.yml
prime-router/settings/staging/0096-update-wa-phd-obx11.yml

This PR edits the settings file for WA. WA reached out to us and pointed out that they only wanted to accept codes of "F", "S", "P", "C", "X", and "I" for OBX-11-1.
- Add routing filter to WA's settings file that matches codes of "F", "S", "P", "C", "X", and "I" for `test_result_status`
Test Steps:
1. Generate fake data for WA, 7 count
2. Edit fake data file by changing result status to the accepted codes of  "F", "S", "P", "C", "X", and "I", also include code of "W"
3. Fire up docker
4. Run `./gradlew reloadsettings' to upload the local org file 
5. Send the fake data file to the api
6. Check that the generated files have all the accepted codes and that code of "W" was filtered out
- Added routing filter of `- matches(test_result_status, F, S, P, C, X, I)` to WA's settings file (Local …

WA Settings Change - Routing Filter for OBX11 Only F, S, P, C, X, and I

---

frontend-react/src/components/Admin/CompareJsonModal.tsx

No CSP or CORs errors, so mainstream the feature. …

Remove featureflag for diff editor since it works

---

prime-router/src/main/kotlin/azure/SubmissionFunction.kt

Resolves #4707 
Correct permissions for accessing organization's submission history
Test Steps:
1. Have admin access in OktaPreview removed and add self to `DHSender_elitemedlabs-co`
2. Log into ReportStream
3. Navigate to "Submissions"
4. Verify that submissions table loads
1. Change minimum access level from admin to user for submission history  
- #4707 
N/A
If you answered '_yes_' to any of the …

Change minimum access level for SubmissionFunction

---

frontend-react/src/components/Admin/AdminFormEdit.tsx
frontend-react/src/components/AlertNotifications.tsx
frontend-react/src/components/EditableCompare.tsx
frontend-react/src/utils/misc.ts

Refactor the json validator that works on other TextArea fields and move code into somewhere common. Then use it in the Diff Editor. …

Make json validator work fo diff editor

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0099-update-nv-phd-drop-obr-16-1.yml
prime-router/settings/staging/0099-update-nv-phd-drop-obr-16-1.yml

This PR NV Update to drop OBR-16-1
Test Steps:
./gradlew clean package
./prime data --input junk/pdi-covid-19-nv-no-orc-12-2n3.csv --input-schema primedatainput/pdi-covid-19 --output-dir junk/output --route
Verify the HL7 output as below.  There should NO OBR-16-1
- #issue
- Does logging …

4710: NV Update to drop OBR-16-1

---

prime-router/build.gradle.kts
prime-router/docs/schema_documentation/az-az-covid-19-hl7.md
prime-router/docs/schema_documentation/covid-19.md
prime-router/docs/schema_documentation/direct-careevolution-covid-19.md
prime-router/docs/schema_documentation/direct-hca-covid-19.md
prime-router/docs/schema_documentation/fl-fl-covid-19.md
prime-router/docs/schema_documentation/gu-gu-covid-19.md
prime-router/docs/schema_documentation/hl7-hl7-ingest-covid-19.md
prime-router/docs/schema_documentation/hl7-lifepoint-covid-19.md
prime-router/docs/schema_documentation/hl7-mns-covid-19.md
prime-router/docs/schema_documentation/hl7-prescryptive-covid-19.md
prime-router/docs/schema_documentation/hl7-primary-covid-19.md
prime-router/docs/schema_documentation/hl7-test-covid-19.md
prime-router/docs/schema_documentation/la-la-covid-19.md
prime-router/docs/schema_documentation/mt-mt-covid-19.md
prime-router/docs/schema_documentation/nd-nd-covid-19.md
prime-router/docs/schema_documentation/nm-nm-covid-19.md
prime-router/docs/schema_documentation/oh-oh-covid-19.md
prime-router/docs/schema_documentation/or-or-covid-19-hl7.md
prime-router/docs/schema_documentation/pa-pa-covid-19-hl7.md
prime-router/docs/schema_documentation/standard-standard-covid-19.md
prime-router/docs/schema_documentation/tx-tx-covid-19.md
prime-router/docs/schema_documentation/vt-vt-covid-19.md
prime-router/metadata/schemas/covid-19.schema
prime-router/settings/organizations.yml
prime-router/src/main/kotlin/FakeReport.kt

This PR is a follow-on to the latter half of [#4793](https://github.com/CDCgov/prime-reportstream/issues/4793), which has been resolved for the state of WA in PR [#4807](https://github.com/CDCgov/prime-reportstream/issues/4807). When we receive HL7 results from senders, ID fields such as OBR-25, OBX-2, and OBX-11 are expanded from standard ID values (e.g. "F", "CWE") to fully expanded values such as
Test Steps:
1. ./gradlew package
2. ./prime data --input junk/prescryptive-sample1a.hl7 --input-schema HL7/prescryptive-covid-19 --output-dir junk/output --route
3. Verify the HL7 output file:
OBR-25: Result Status +:                                F
Suppressed OBR-25-2, 3
OBX-2:  Value Type:                                        CWE
Suppressed OBX-2-2, 3
OBX-11: Observation Result Status: …

4878: Fixed Undesired expansion of HL7 field with type ID

---

frontend-react/src/components/EditableCompare.tsx

Without end-to-end unit tests, some of these features are fragile. I broke the ability to edit content with #4936
I'm opening an issue (#4966) to figure out some way to create unit tests for this component. It might require cypress.

Fix EditableCompare bug introduced by #4936

---

prime-router/src/main/kotlin/Element.kt
prime-router/src/main/kotlin/serializers/Hl7Serializer.kt

Reverts CDCgov/prime-reportstream#4835 …

Revert "3869: Accept Internatinal Phone Number"

---

operations/app/terraform/modules/function_app/main.tf
operations/app/terraform/vars/dev/azure.tf
operations/app/terraform/vars/staging/azure.tf
operations/app/terraform/vars/test/azure.tf

This PR: 
* Enforces Terraform azure provider < 3.0.0, as any higher introduces breaking changes.
* Disables function app FTP/FTPS via Terraform …

Enforce TF < 3.0 and disabled function FTP

---

frontend-react/src/content/live.json
frontend-react/src/content/usa_w_territories.svg

This PR adds Nevada to the "where we're live" map and list. …

Add Nevada to where we're live

---

frontend-react/src/App.tsx
frontend-react/src/index.tsx

This PR fixes the `401` error on the sender settings network call when logging in.
Test Steps:
1. Set OktaPreview orgs to `DHSender_ignore.ignore-waters` and `DHSender_ignore`
2. Start the React dev env
3. Log in and watch the network calls
- Wraps app in `SessionProvider`
- Uses session to control when `SenderModeBanner` is rendered
- #4980 
If you answered '_yes_' to any of the questions above, …

Fixes the sender settings call on login

---

frontend-react/package.json
frontend-react/src/components/OktaSignInWidget.jsx
frontend-react/yarn.lock

- Also put placeholders back into `package.json` for `peerDependencies` and `resolutions` since we'll probably need to use them again in the future
To test: …

Latest updates and fix some backwards compatibility issues

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0106-desertoasishealthcare-ca.yml
prime-router/settings/prod/0107-toprankdx-ca.yml
prime-router/settings/prod/0108-bi2technologies.yml
prime-router/settings/staging/0106-desertoasishealthcare-ca.yml
prime-router/settings/staging/0107-toprankdx-ca.yml
prime-router/settings/staging/0108-bi2technologies.yml

This PR contains modifications outlined in Ticket #5066 required to add the new senders:
- Add Oasis Healthcare Immediate Care - sender_id: oasishealthcare-ca
- Add Top Rank Diagnostic Lab - sender_id: toprankdx-ca
- Add BI2 Technologies - sender_id: bi2technologies
**If you are suggesting a fix for a currently exploitable issue, please disclose the issue to the prime-reportstream team directly outside of GitHub instead of filing a PR, so we may immediately patch the affected systems before a disclosure. See [SECURITY.md/Reporting a …

OO/rhood/5066/Add new Senders

---

prime-router/src/main/resources/db/migration/V45__fixed_delivery_statistics.sql

This PR fixes a flaw in the previous special_delivery_statistics query, where it wasn't properly filtering out old/deleted receivers from the settings table.
No kotlin code changes.
The updated query is already on Staging, so you can test this by going to this dashboard, and enter dates from April 10 to April 12 in the "End to End Delivery Statistics" query.  
https://staging.prime.cdc.gov/metabase/dashboard/11-delivery-statistics
Look in the results for the rows for `simple_report`.   I have submitted the `simple_report_example` file to Staging.   It sends data to four States, so you should see four rows of `simple_report` data. (Previously, with the bug, there were 8 rows of simple_report data)
- Adds checks for deleted data in the settings table subquery.
- Further improvements to …

Delivery Statistics:  bug fix

---

.github/dependabot.yml

This PR removes the old "frontend/" directory from dependabot scanning.
- #5115  …

Remove "/frontend" from dependabot directories (fixes #5115)

---

operations/README.md

Cosmetic change to do a deploy

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0109-navushealth.yml
prime-router/settings/staging/0109-navushealth.yml

This PR contains modifications outlined in Ticket #5166  required to add the new senders:
- Add Navus Health, LLC - sender_id: navushealth
**Test Steps:**
No testing …

OO/rhood/5166 - Add new CSV Sender (Navus Health)

---

operations/app/terraform/modules/container_registry/main.tf
operations/app/terraform/modules/log_analytics_workspace/main.tf
operations/app/terraform/modules/network/security_groups.tf
operations/app/terraform/modules/network/subnets.tf
operations/app/terraform/modules/network/~outputs.tf
operations/app/terraform/modules/storage/~outputs.tf
operations/app/terraform/vars/dev/main.tf
operations/app/terraform/vars/dev/secrets.tf
operations/app/terraform/vars/dev/variables.tf
operations/app/terraform/vars/dev/~outputs.tf
operations/app/terraform/vars/staging/main.tf
operations/app/terraform/vars/staging/secrets.tf
operations/app/terraform/vars/staging/variables.tf

This PR ran `terraform fmt -recursive` to help reduce future PR whitespace changes. …

ran terraform fmt -recursive

---

frontend-react/src/components/Admin/CompareJsonModal.tsx

This PR fixes a minor bug caught by Tom post-merge, thanks @TomNUSDS  …

experience/4325-fix: small bug fix with getOriginalText()

---

frontend-react/src/components/Table/readme.md

This PR adds docs for the new `Table` component
- #5212 
- #issue
- Threat _T_, …

Table readme with basic and advanced implementations

---

operations/README.md
operations/app/terraform/modules/storage/candidate_slot.tf
operations/app/terraform/modules/storage/main.tf
operations/app/terraform/modules/storage/~inputs.tf
operations/app/terraform/vars/prod/main.tf
operations/app/terraform/vars/prod/variables.tf
operations/app/terraform/vars/staging/main.tf
operations/app/terraform/vars/staging/variables.tf
operations/app/terraform/vars/test/main.tf
operations/app/terraform/vars/test/variables.tf

This PR pulls into a variable the number of days to keep PII blobs in the storage account, then uses that in the different envs as appropriate (60 for prod/staging, 30 for test) …

Ensure the storage retention time is 60 days in prod/staging

---

prime-router/docs/vpn.md

This doc-only PR adds a pointer about a common issue getting OpenVPN working on Linux. …

Some tips on fixing a non-working OpenVPN on Linux

---

prime-router/docs/getting-started/Using-an-apple-silicon-mac.md

This PR adds a missing step to the Apple Silicon setup instructions. It also clarifies some of the explanation and fixes the step numbering.
- #issue
If you answered '_yes_' to any of …

Update Apple Silicon setup instructions

---

.environment/terraform-fmt/run-terraform-fmt.sh
operations/app/terraform/modules/application_insights/alert_response_time.tf

This PR updates terraform alert rules to match what is in production. A parameter `metric_column` was required in the terraform, although it did not match what was specified in prod. Will continue to monitor.
Also fixed Terraform hook not referencing repo root. …

Updated rule alert to match prod. metric_column required

---

prime-router/Makefile

This PR adds the ability to prune and delete local branches into the `makefile`. …

Adds pruning and deleting of pruned branches into makefile

---

prime-router/docs/schema_documentation/hl7-signetic-covid-19.md
prime-router/metadata/schemas/HL7/signetic-covid-19.schema
prime-router/settings/organizations.yml
prime-router/settings/prod/0110-signetic.yml
prime-router/settings/staging/0110-signetic.yml

This PR onboards Signetic as a new HL7 sender.
Test Steps:
1. Fire docker
2. reloadsettings
3. send test file to api (test file: [signetic-03v2.txt](https://github.com/CDCgov/prime-reportstream/files/8586826/signetic-03v2.txt))
4. verify there is a HL7 message
NOTE: You need to change the extension of the test file to ".hl7" before sending it to the api. Git does not accept hl7 extension format for attachments
- Added schema for signetic
- Added org settings for signetic
- Added prod yamalitos  (will excecute once PR is approved)
- Added staging yaalitos (will excecute once PR is approved)
- test passed
- testIntegration passed
- #5296 
| …

Onboarding Signetic

---

.github/actions/deploy-backend/action.yml

Tiny PR that reverts the change for the functions-container-action so it's using the tag instead of hash. …

reverting to v1 tag for functions-container-action

---

prime-router/src/main/kotlin/azure/SendFunction.kt

This PR fixes an issue where PagerDuty was alerting on sftp failures for Receivers in Testing or Inactive modes.
With this change it only triggers the highest level "FATAL-ALERT" on Active receivers.
Test Steps:
1. This test is simple but unpleasant:   Run `./prime test --run end2end`.   Wait 3 or 4 hours.  It just so happens that there are a couple misconfigured receivers (` ignore.HL7_BATCH_PPK ` and ` ignore.HL7_BATCH_PEM`) that always fail SFTP.   So watch for nice red final error messages for those two receivers after several hours.  Since neither one is `customerStatus=Active`, when they do finally error out, they should NOT print out the a `FATAL-ALERT` message.  (The bug in the previous code is that it _was_ printing FATAL-ALERT)
Here is an example of the error message, sans …

Only trigger PagerDuty alerts on sftp failures of Active receivers

---

prime-router/docs/api/waters-delivery-detail.yml
prime-router/src/main/kotlin/TranslatorConfiguration.kt

This PR provides the documentation for a new Waters endpoint for delivery details (also known as report-details).
(Epic: #5158 Issue: #5333)
Test Steps:
Use an OpenAPI linter (https://github.com/Redocly/openapi-cli) to verify the new file (docs/api/waters-delivery-detail.yml).
- Built spec for new endpoint at waters-delivery-detail.yml, based on waters-delivery.yml
- #5333
If you answered '_yes_' to …

OpenAPI (Report) Delivery Detail. Jh765/5333

---

frontend-react/src/components/Admin/EditReceiverSettings.tsx
frontend-react/src/components/Admin/EditSenderSettings.tsx

Add spacing above form buttons

---

.github/workflows/run_sonarcloud_scan.yaml

This PR ...
Adds manual Sonarcloud scans which allows us to get code coverage information as well.
Test Steps:
- Create a PR and check sonarcloud.io
- Added new GHA that will trigger on master pushes as well as PRs. …

Filename change to match action name

---

.github/pull_request_template.md

Updates the section for issues fixed by the PR to demonstrate the format for linking issues in pull requests. GitHub markdown will hyperlink an issues written as `#1234` but to formally link it to the PR you need to preface it with a supported keyword. 
See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword …

Update PR template for linked issues

---

frontend-react/src/components/Table/Table.test.tsx
frontend-react/src/components/Table/Table.tsx
frontend-react/src/components/Table/TableFilters.test.tsx
frontend-react/src/components/Table/TableFilters.tsx
frontend-react/src/components/Table/TestTable.tsx
frontend-react/src/hooks/filters/UseDateRange.test.ts
frontend-react/src/hooks/filters/UseDateRange.ts
frontend-react/src/hooks/filters/UseFilterManager.test.ts
frontend-react/src/hooks/filters/UseFilterManager.ts
frontend-react/src/hooks/filters/mocks/MockFilterManager.ts
frontend-react/src/pages/submissions/SubmissionPages.css
frontend-react/src/pages/submissions/SubmissionTable.tsx

Swaps out two DatePickers for a DateRangePicker, and adjusts logic to account for the component change.
Test Steps:
1. Navigate to `/submissions`
2. Ensure the range picker behaves as intended: From should be a historic date and To should be a more present date.
- DatePickers changed to DateRangePicker
- Start/End range logic swapped to match range picker's labels (From [Start Range] and Until [End Range])
- #5180  …

Fix date range filter pickers to use range instead of individual dates

---

frontend-react/src/content/getting_started_csv_upload.json
frontend-react/src/pages/getting-started/testing-facilities/CsvSchemaDocumentation.tsx

This PR updates the CSV schema documentation to indicate that Patient ID is requested. Also updates the guidance for requested fields at the top of the page.
| Before | After |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2730338/167650567-2f3b8527-d2c1-40cf-90aa-27a18850a60e.png) | ![image](https://user-images.githubusercontent.com/2730338/167651137-05c981bf-b114-410e-bbf0-a3f1d57c86bb.png) |
- Fixes #4854  …

Update Patient ID and Requested field guidance

---

frontend-react/src/pages/submissions/SubmissionTable.tsx

This PR is a quick fix for the submission table config
- Config has default sort settings so arrow now appears next to sorted column
- Config removed `enableEditableRows` since no fields are marked editable
BEFORE:
AFTER: …

Fixes config for SubmissionsTable

---

.github/workflows/run_sonarcloud_scan.yaml

This PR adds `mocks` folders to the ignore pattern for sonar cloud coverage exclusions. …

Adjust pattern for coverage report ignore

---

prime-router/docs/vpn.md

Fixed the DNS server shown in the docs to be 10.0.2.4 (instead of 10.0.2.5 which does not work). …

update the vpn.md with correct DNS server

---

frontend-react/package.json

This PR clears jest cache before CI tests run …

Clear cache before test CI

---

.github/dependabot.yml

This PR updates the dependably settings to explicitly ignore sshj updates so we don't inadvertently bump to an incompatible version. …

Updates dependabot ignore settings to exclude SSHJ from update notifications

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0118-NH-replace-msh-4.yml
prime-router/settings/staging/0118-NH-replace-msh-4.yml

This PR replaces MSH-4 with CDC PRIME^11D2030855^CLIA for NH ELR.
Test Steps:
- Fixes #issue
- #issue
If you answered '_yes_' to any of the questions above, conduct a detailed Review …

NH ELR Replace MSH-4 with CDC PRIME^11D2030855^CLIA

---

prime-router/src/main/kotlin/Element.kt

This is an emergency fix to back out the cardinality one change from PR 5648.
- Removes one else condition from Element.kt
- Fixes #5648 …

Backing out cardinality one fix

---

frontend-react/src/hooks/UseLookupTable.test.ts
frontend-react/src/hooks/UseLookupTable.ts
frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.tsx

This PR changes the way we proxy the `useLookupTable` hook
Test Steps:
1. Ensure new code makes sense and suits needs
2. Ensure nothing in UI is affected negatively by this change
- Removes `generateUseLookupTable`
- Adds `useValueSetTable` and `useValueSetRowTable`
- Fixes #issue
- #issue …

React hook conventions implemented

---

frontend-react/src/pages/Upload.tsx

This PR adds the transition banner to the upload page of ReportStream.
Test Steps:
1. Load RS localhost
2. Login and navigate to `/upload`
- Fixes #5190
- **S**poofing (faking …

Adds transition banner to upload page

---

frontend-react/src/components/Admin/OrgsTable.tsx
frontend-react/src/pages/Upload.tsx

Currently, when setting yourself as a sender and choosing an organization as an admin, the `sender name` of the chosen sender is not set in session storage, and subsequently not supplied to the client header in relevant requests. With this change, when selecting an organization from the admin view as a sender, the sender name will be set as `default`.
Note: as, in non-admin scenarios, where actual senders are logging in with their own credentials, the sender name is sourced directly from the user's okta account. As such, it is not believed that this bug exists in a non-admin context.
Future work: allow for specific selection of different senders within each organization from the admin view, rather than forcing `default`.
1. start servers on this branch with `yarn run start:localdev` from …

fix: default admin defined sender names [experience-5938]

---

frontend-react/src/pages/daily/Table/ReportsTable.tsx

This PR fixes a layout issue on the daily data page.
|Before|After|
|------|-----|
|<img width="1532" alt="Screen Shot 2022-06-29 at 11 41 57 AM" src="https://user-images.githubusercontent.com/640182/176478668-5788b75e-c064-44e4-82a8-cd28a9724046.png">|<img width="1532" alt="Screen Shot 2022-06-29 at 11 40 24 AM" src="https://user-images.githubusercontent.com/640182/176478312-8f6d6df2-4c26-425c-9421-70db828ba5bd.png">|
- Fixes #issue
- #issue
- …

Fixes layout issue on daily data page when there are no results

---

frontend-react/src/pages/Upload.tsx

This PR removes language about downloading data since there isn't a way for users to do this.
- Fixes #issue
- #issue
- …

Update transition banner

---

frontend-react/src/__mocks__/HistoryMockServer.ts
frontend-react/src/components/SenderModeBanner.tsx
frontend-react/src/hooks/filters/UseFilterManager.ts
frontend-react/src/hooks/filters/UsePages.ts
frontend-react/src/hooks/network/History/ReportsHooks.test.ts
frontend-react/src/hooks/network/History/ReportsHooks.ts
frontend-react/src/network/api/History/Reports.ts
frontend-react/src/network/api/NewApi.ts
frontend-react/src/network/api/mocks/MockApi.ts
frontend-react/src/pages/daily/Table/ReportsTable.test.tsx
frontend-react/src/pages/daily/Table/ReportsTable.tsx
frontend-react/src/pages/daily/Table/ReportsUtils.ts
frontend-react/src/utils/ReportUtils.ts

This PR removes `rest-hook` usage from `/daily-data` and replaces it with the new api tooling. Additionally, tests were edited to account for this, and receiver feeds logic was extracted to a module-scoped hook.
Test Steps:
1. Poke around `/daily-data` and ensure I didn't break anything.
- No visual changes
- Removal of `rest-hooks` `useResource` call from the daily data page
- Addition of ReportsApi
- Using ReportsApi in Daily Data
- Fixes #issue
- #issue
- Does this change require changes to our …

ReportsTable refactor to remove rest-hooks

---

prime-router/src/main/kotlin/history/SubmissionHistory.kt

This PR readds the ID property that is output for API requests that respond with a Details Submission History class.
Test Steps:
1. Submit a report and verify that the `id` and `reportId` properties exist in the JSON response.
2. Fetch a report history and verify that the `id` and `reportId` properties exist in the JSON response.
- Added the `id` property to be the same as `reportId` for backwards compatibility.
- Fixes #issue
- #issue
- Does …

Added getter for id to pass value on json output

---

frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
frontend-react/src/components/EditableCompare.tsx
frontend-react/src/pages/getting-started/testing-facilities/CsvSchemaDocumentation.tsx

This PR ensures values passed to `dangerouslySetInnerHTML` are sanitized first.
- Fixes #5977 
- Threat _T_, which could be achieved by _A_, …

DOMPurify unsanitized html

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0121-Mo-Fixed-PID-15-3_ORC-21-1_OBX-23-1.yml
prime-router/settings/staging/0121-Mo-Fixed-PID-15-3_ORC-21-1_OBX-23-1.yml

This PR validated and fixed message ID below:
MSH-10
24d41af-9297-490a-ba20-497b4e386df0
Fixed:              suppressHl7Field: PID-15-3
MSH-10:
a68813c0-0bf6-4b62-9e34-dcbc55a42e22
Fixed: ORC-21-1, OBX-23-1 truncated to length of 50.
Test Steps:
2. ./copy the test file to junk
3. Run: ./prime data --input junk/pdi-covid-19-mo.csv --input-schema primedatainput/pdi-covid-19 --output-dir junk/output --route
4. Verify the PID-15-3 is suppressed; ORC-21-1, OBX-23-1 is truncated to 50 characters.
Test file:
[pdi-covid-19-mo.csv](https://github.com/CDCgov/prime-reportstream/files/9075327/pdi-covid-19-mo.csv)
- Fixes #issue
- …

MO Messages Validation

---

prime-router/metadata/fhir_mapping/hl7/message/ORU_R01.yml
prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir

This PR fixes a problem with the Next of Kin information missing from the FHIR bundle.
Test Steps:
1. Download this sample HL7 file and rename the extension to `.hl7`: 
[sample_hl7.txt](https://github.com/CDCgov/prime-reportstream/files/9085039/sample_hl7.txt)
2. Convert the HL7 to FHIR by running the following PRIME CLI command: `./prime fhirdata --input-file "<location of HL7 file>" --output-file build/hca-fhir.json`
3. Verify that the Patient.contact resource has the next of kin data from the NK1 segment.
- Added NK1 segment to Patient resource
- Fixes #issue
- #issue
- Does this PR include changes in authentication and/or authorization of existing …

6058 Added NK1 segment for FHIR generation

---

prime-router/src/main/kotlin/history/azure/DatabaseDeliveryAccess.kt
prime-router/src/main/kotlin/history/azure/DeliveryFacade.kt
prime-router/src/main/kotlin/history/azure/HistoryDatabaseAccess.kt

This PR fixes some behavior issues with the List of Deliveries endpoint that were filtering out valid values.
Test Steps:
1. Using the Submissions endpoint, get the expanded details of a recently submitted report. e.g. GET api/waters/report/1269/history/
2. On the results, look for a Destination with an itemCount value higher than 0. Take note of the values on that Destination's organization_id, service and sentReports fields.
3. Using the previously noted values, download the list of deliveries endpoint /api/waters/org/{organization_id}.{service}/deliveries/
4. The reports in sentReports must include those seen on the Destination object for the organization you are searching for.
- List of deliveries now checks `send` type actions instead of `receive` type actions.
- Disabled the HTTP …

Delivery List Filter Fix

---

prime-router/settings/staging/0122-al-phd-remove-transport.yml

This PR remove the transport from staging setting.  The SFTP was setting to none exist host.  We don't need to set the SFTP in staging.  Therefore, I remove it from staging.
Test Steps:
1. none
- Fixes #issue
- #issue
If you …

Fixed AL-PHD SFTP Failure in staging

---

prime-router/settings/staging/0122-al-phd-remove-transport.yml

This PR updated the staging setting to remove transport from al-phd.elr
Test Steps:
- Fixes #issue
- #issue …

Removed transport from al-phd.elr

---

prime-router/docs/azure_database_login.md
prime-router/docs/getting-started/getting-started.md

Two small changes that would have saved me time on issues I had while getting started
This PR ...
Updates the resetting your database instructions and the connecting to prod and staging db instructions.
Test Steps:
- Fixes #issue
- #issue
- Does this PR …

Small Getting Started updates

---

prime-router/src/main/kotlin/history/ReportHistory.kt
prime-router/src/main/kotlin/history/SubmissionHistory.kt
prime-router/src/main/kotlin/history/azure/HistoryDatabaseAccess.kt
prime-router/src/test/kotlin/history/SubmissionHistoryTests.kt

This PR ...
When a receiver has no transportation mechanism set, there cannot be a sending at time since we have no mechanism through which to send the report.
It is important to not supress these reports as some STLTs use manual downloads without having a transport mechanism set.
There is no place to remove next action time without causing downstream effects so instead, this commit removes the time only in the api response.
Test Steps:
1. Comment out the transport mechanism for one of the receivers in the `prime-router/settings/organizations.yml` file. I recommend `Maryland Public Health Department` whose transport mechanism starts on line 2014.
2. Reload the settings using `./gradlew reloadSettings` to ensure the transport mechanism is removed.
3. Submit a report on your dev …

Only show sending at time on valid reciever transport

---

frontend-react/src/content/live.json
frontend-react/src/content/usa_w_territories.svg

This PR adds Indiana to the "where we're live" map and list
- #6117
- #issue
- …

Adds Indiana to where we're live map and list

---

prime-router/docs/api/reports.yml
prime-router/src/main/kotlin/history/SubmissionHistory.kt

This commit removes the reports and logs properties from the response.
It also removes the routing property from the open api spec as verbose is no longer an option and therefore routing can never be returned.
Test Steps:
1. Submit a report on your dev environment. One way is to run the following: curl -X POST -H "client:simple_report" -H "Content-Type: text/csv" --data-binary "@./examples/submission/simple_report_example.csv" "http://localhost:7071/api/reports"
2. You should not see `reports` or `logs` returned in the response.
3. Party!!
- Fixes #6043
- #issue
- new endpoint …

Make /reports response match openapi spec

---

prime-router/metadata/fhir_mapping/hl7/datatype/Identifier_Observation.yml
prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir

This PR fixes an issue where segments that include an OBR Identifier but does not have compatibility for a related OBX value will add a trailing dash.
Test Steps:
1. While in the `master` branch, convert FHIR from an HL7. e.g. `./prime fhirdata --input-file ../../5919-sample.hl7 --output-file ../../sample.fhir`. Sample data file: `https://app.zenhub.com/files/304423150/331e983d-3908-4618-af7a-0eaad063a25e/download`. Copy the document with a different name.
2. Switch to the branch of this PR and repeat.
3. Compare the two documents. Besides timestamps and ids related to the actual conversion, the only difference should be the lack of trailing dashes in Observation Identifiers. e.g. `"value" : "21:AA:B0029251S.5-"` will lose its last character.
- Added configuration override for Observation …

#5919 Fix for trailing dashes on FHIR Observation Identifier

---

frontend-react/src/network/api/WatersApi.ts
frontend-react/src/pages/Validate.tsx
frontend-react/src/styles/_reportstream.scss

Changes for https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6089
This includes, vaguely, bringing the UI in line with the designs from this Figma file https://www.figma.com/file/b2Zd1xzmp4cdwFO8O7edcI/CSV-Uploader-%26-Validation?node-id=2288%3A1157
Specifically:
Open questions: 
1. start servers on this branch with `yarn run start:localdev` from `frontend-react` and `./gradlew run` from `prime-router`
3. set up your user up as a sender that is set up to send csv files, ex. `all-in-one-health-ca`
4. activate the `validation-service` feature flag via the `admin -> feature flags` navigation
5. click `validate` in the nav bar
6. _VERIFY_: page looks like `initial` …

Experience/validation UI design

---

frontend-react/src/components/header/DropdownNav.test.tsx
frontend-react/src/components/header/DropdownNav.tsx

This PR is a hot fix for the link to Systems and Settings
Test Steps:
- Fixes #issue
- #issue …

Fixes link in HIW dropwdown

---

frontend-react/src/content/resources/referral-guide.md

This PR ...
Fixing links and typos in the content. /resources/referral-guide
Test Steps:
1. Pull latest version on branch
2. Verify links in content work
- Fixes #issue
- #issue …

referral typo guide

---

frontend-react/src/components/FileHandlers/FileHandler.tsx
frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx
frontend-react/src/network/api/WatersApi.ts

This change adds readouts on the validation and upload pages for warnings sent back from the API when validating or uploading a file.
Also includes:
* addition of `field` and `tracking ids` columns to errors table
* some styling fixes
* some text updates
* some renaming and splitting out functionality in file handler messaging
1. start servers on this branch with `yarn run start:localdev` from `frontend-react` and `./gradlew run` from `prime-router`
4. activate the `user-upload` feature flag via the `admin -> feature flags` navigation
6. refresh
3. set up your user up as a sender that is set up to send hl7 files, ex. `hcintegrations`
8. click `Validate` in the nav bar under `Upload & Validate`
10.  upload an hl7 file …

feat: validation & upload warnings [experience-6090]

---

prime-router/src/main/kotlin/FakeReport.kt

This PR fixed Fake Date and Datetime sequence generator.  Since, it cause failure for receivers to verify our test messages.
Test Steps:
2. ./prime data --input-fake 1 --input-schema primedatainput/pdi-covid-19 --output ./junk/pdi-covid-19-mo.csv --target-states MO
3. Verify the output file the following fields should have the same date.
Specimen_collection_date_time, Order_test_date, Test_date , Date_result_released
- Fixes #issue
- #issue
- Does this PR include changes in authentication and/or authorization of …

Fixed date-time sequence for fake data generator

---

frontend-react/src/components/Content/DirectoryAsPage.test.tsx
frontend-react/src/components/Content/GeneratedSideNav.test.tsx
frontend-react/src/components/Content/MarkdownDirectory.test.tsx
frontend-react/src/components/Content/MarkdownDirectory.tsx
frontend-react/src/components/Content/StaticPageFromDirectories.test.tsx
frontend-react/src/components/IACard.tsx
frontend-react/src/components/header/DropdownNav.tsx
frontend-react/src/pages/admin/InternalUserGuides.tsx
frontend-react/src/pages/product/ProductIndex.tsx
frontend-react/src/pages/resources/ResourcesIndex.tsx
frontend-react/src/pages/support/SupportIndex.tsx

This PR changes the instantiation pattern of ContentDirectory and its children classes for more flexibility and better readability.
Test Steps:
1. Pull latest on branch
2. Ensure public site still renders!
- Constructor pattern to a builder pattern for `ContentDirectory`
- Fixes #issue
- #issue …

Refactors instantiation pattern for ContentDirectory children

---

frontend-react/src/pages/support/SupportIndex.tsx

This PR fixes an issue with the new IA rollout (content not properly linked in support section)
Test Steps:
1. click "support" link in main nav
2. "contact" card should route to contact content
3. "frequently asked questions" card should route to FAQ content
- Fixes #6247
- …

Fix slug/content issue

---

frontend-react/src/utils/DateTimeUtils.test.ts

fixes issue with a new test in DateTimeUtils that is potentially dependent on the time zone where test are being run, by removing this precise test case
Test Steps:
1. tests pass locally and on CI
- Fixes #issue
- #issue
If you …

fix: remove unreliable time zone dependent test case [unticketed]

---

prime-router/src/main/kotlin/Report.kt
prime-router/src/main/kotlin/SubmissionReceiver.kt
prime-router/src/main/kotlin/azure/ReportFunction.kt
prime-router/src/test/kotlin/ReportTests.kt
prime-router/src/test/kotlin/SubmissionReceiverTests.kt
prime-router/src/test/kotlin/azure/EventTest.kt
prime-router/src/test/kotlin/azure/HttpTestUtils.kt
prime-router/src/test/kotlin/azure/ReportFunctionTests.kt

This PR ...
This commit stops swallowing errors for invalid options and starts warning when deprecated options are submitted.
It adds unit tests for both changes and the happy path of the process function.
Test Steps:
1. Submit a report with an **invalid option** set on your dev environment. You can do so via the CLI with the following: curl -X POST -H "client:simple_report" -H "Content-Type: text/csv" --data-binary "@./examples/submission/simple_report_example.csv" "http://localhost:7071/api/reports?option=InvalidOption"
2. Submit a report with a **deprecated option** set on your dev environment. You can do so via the CLI with the following: curl -X POST -H "client:simple_report" -H "Content-Type: text/csv" --data-binary "@./examples/submission/simple_report_example.csv" …

Validate submit report options

---

prime-router/src/main/kotlin/azure/ValidateFunction.kt

This PR changes the AuthorizationLevel of the /validate endpoint from FUNCTION to ANONYMOUS
Test Steps:
1. When deployed to Staging, verify that the /validate endpoint actually returns results
- Fixes #issue
- #issue
- What are the …

experience/5713-fix-auth-level: change auth type from FUNCTION to ANONYMOUS

---

frontend-react/src/components/FileHandlers/FileHandler.test.tsx
frontend-react/src/components/FileHandlers/FileHandlerMessaging.test.tsx
frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx

On a successful file upload, the confirmation id display will now link to the associated submissions detail page.
1. start servers on master with `yarn run start:localdev` from `frontend-react` and `./gradlew run` from `prime-router`
4. activate the `user-upload` feature flag via the `admin -> feature flags` navigation
5. refresh
3. set up your user up to spoof 'hcintegrations'
8. click `User Upload` in the nav bar under `Upload & Validate`
10. upload a valid hl7 file
11. _VERIFY_: success message includes a `Confirmation Code` id that is a link (see screenshot)
12. click the confirmation code link
13. _VERIFY_: you are taken to a submission detail page that matches the confirmation code id from the previous page
- …

feat: link upload success confirmation code to submission detail [experience-6286]

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0128-Mo-Revert-ORC-2_OBR-2.yml
prime-router/settings/staging/0128-Mo-Revert-ORC-2_OBR-2.yml

This PR revert the changed of ORC-2 and OBR-2.  Since, we already asked Prescryptive to fill these values.
Test Steps:
- Fixes #issue
- #issue
If you answered '_yes_' to any of the …

Revert MO Validation Error ORC-2 and OBR-2

---

prime-router/metadata/hl7_mapping/ORU_R01/base/software.yml
prime-router/src/main/kotlin/cli/ProcessFhirCommands.kt
prime-router/src/main/kotlin/fhirengine/translation/hl7/FhirToHl7Converter.kt
prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
prime-router/src/test/kotlin/fhirengine/translation/hl7/FhirToHl7ConverterTests.kt
prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/ConstantResolverTests.kt
prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirPathUtilsTests.kt

This PR makes improvements to the FHIR Path tool.
Test Steps:
1. Check out this branch and build the prime CLI by running `./gradlew fatjar`
2. Run the FHIR path tool by running `./prime fhirpath -i src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir`
3. Type in the following paths in sequence and verify you get to see the contents of the extension
```
resource: 'Bundle.entry.resource.ofType(MessageHeader)'
%resource.source.extension('https://reportstream.cdc.gov/fhir/StructureDefinition/source-software-vendor-org').value
resource = %resource.source.extension('https://reportstream.cdc.gov/fhir/StructureDefinition/source-software-vendor-org').value
%resource
```
- Allow to set the %resource by typing ANY of the following:
```
resource : …
```

Enhancements to the FHIR Path Tool

---

frontend-react/src/components/Admin/AdminReceiverDashboard.test.tsx

fixes linting errors caused by unused variables in receiver dashboard test
1. run `yarn lint` on master
2. _VERIFY_: failure
3. run `yarn lint` on this branch
4. _VERIFY_: pass
- Fixes #issue
- #issue
If you answered '_yes_' to …

fix: remove unused variables in admin receiver dashbaord test

---

prime-router/build.gradle.kts

This PR upgrades postgresql to 42.4.1.
[Change log](https://jdbc.postgresql.org/documentation/changelog.html)
Test Steps:
- upgrade postgresql from 42.3.3 AND 42.4.0 to 42.4.1
- Fixes #issue
- #issue
- Does this PR …

Bump postgresql 42.4.1

---

prime-router/src/main/kotlin/Report.kt

This PR fixes a bug where COVID reports without a Speciment Collection time fail to save.
Test Steps:
1. Submit a report on your dev environment. You can do so via the CLI with the following: `curl -X POST -H "client:simple_report" -H "Content-Type: text/csv" --data-binary "@./examples/submission/simple_report_example.csv" "http://localhost:7071/api/reports"`
2. Wait a few minutes while the test reports are being sent, then make a GET query to `/api/waters/org/ak-phd.elr/deliveries/`. Write down the deliveryId and reportId values for one of the results. If `ak-phd.elr` does not contain any deliveries, use the Submissions API to find a Destination with new reports.
3. Make a GET query to `/api/waters/report/{id}/facilities` using the `deliveryId` value from the previous step for the `id`. …

Add null check on specimenCollectionDateTime for COVID

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0129-reopenlab.yml
prime-router/settings/staging/0129-reopenlab.yml

This PR  is Onboarding Sender ReopenLab. Setting up organization.yml, prod and staging setting files.
Test Steps:
- Fixes #issue
- #issue …

Onboarding Sender ReopenLab

---

frontend-react/src/hooks/UseOktaMemberships.test.ts
frontend-react/src/hooks/UseOktaMemberships.ts

Changes in https://github.com/CDCgov/prime-reportstream/pull/6397 introduced a bug that will wipe out some stored organization data when selecting a membership type from the admin drop down. This change fixes that bug.
1. start servers on master
3. select `all-in-one-health-ca` as your oganization
4. refresh the page
5. choose `prime-admin` from the `mimic user type` drop down
6. refresh
7. _VERIFY_: your org has been corrupted - you should see something like the screenshot below
8. start servers on this branch
9. perform steps 2 - 6
10. _VERIFY_: your org still appears as `all-in-one-health-ca`
- Fixes …

fix: correctly store org override on member type change [unticketed]

---

frontend-react/src/pages/daily/Table/ReportsTable.test.tsx
frontend-react/src/pages/daily/Table/ReportsTable.tsx

This PR fixes a bug that would crash the daily data page in certain situations (with spoofed user)
1. start servers on master
3. select `all-in-one-health-ca` as your organization
4. click `daily data`
5. _VERIFY_: the page crashes
1. start servers on this branch
2. repeat 2 - 4
5. _VERIFY_: the page loads
- Fixes #issue
- #issue
- Does this change introduce new dependencies that …

fix: do not crash daily data if data comes back undefined

---

frontend-react/src/pages/product/ProductIndex.tsx

Currently when attempting to visit a product sub page directly, the app redirects to overview. This change allows you to access product sub pages directly via url, and redirects to overview on /product
1. start servers on master
2. visit http://localhost:3000/product/where-were-live
3. _VERIFY_:  you are taken to product overview
4. start servers on this branch
2. visit http://localhost:3000/product/where-were-live
3. _VERIFY_:  you are taken to product where we're live page
2. visit http://localhost:3000/product/
3. _VERIFY_:  you are taken to product overview
- Fixes #issue
- #issue …

fix: route to product sub-pages

---

frontend-react/src/components/Content/PageGenerationTools.tsx
frontend-react/src/components/Content/Templates/IACardGridTemplate.test.tsx
frontend-react/src/components/Content/Templates/IACardGridTemplate.tsx
frontend-react/src/content/resources/index.ts
frontend-react/src/content/support/index.ts
frontend-react/src/pages/resources/ResourcesCardGrid.tsx
frontend-react/src/pages/resources/legacy-page-content/__snapshots__/CsvSchemaDocumentation.test.tsx.snap

This PR adds new functionality for `IACardGridTemplate` -- it now no longer only takes a `ContentDirectory[]`. You can, instead, pass in a map of directory arrays where the map keys act as the title, and the values act as the cards to render.
For an example (commented code), see `content/resources/index.ts`!
Test Steps:
1. Ensure no IA pages are broken from this
2. To test sections, uncomment the sample in `content/resources/index.ts` then go to `pages/resources/ResourceCardGrid.tsx` and swap the value on line `17` to `resourcesContentMap` (requires you to import it now that it's uncommented in the other file). This only renders ONE section, but it shows what a section looks like.
If you tinker enough, you can try creating your own section below it! Though, take this as my proof that it …

`<IACardGridTemplate>` now optionally configurable with sections

---

prime-router/settings/organizations.yml

Updating AZ filtering to include patient_state
- Updates prime-router/settings/organizations.yml org filter settings for AZ to include patient_state

Update AZ filtering

---

frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx

Simple changes to fix the css hierarchy so the Info dialog layout is styled correctly.

Fix css layout for Last Mile failures dialog

---

frontend-react/src/App.tsx
frontend-react/src/components/AppWrapper.tsx
frontend-react/src/index.tsx

moves app provisioning elements to their own file to avoid churn on App.tsx and better compartmentalize functionality to components.
for follow ups see https://app.zenhub.com/workspaces/experience-607d9d5e68b95200150fec37/issues/cdcgov/prime-reportstream/6486
1. general regression testing
- Fixes #issue
- #issue
- Does logging …

refactor: move app provisioning elements to their own component

---

.environment/terraform-fmt/run-terraform-fmt.sh

Currently if you do not have Terraform installed you may run into a message saying it is failing the Terraform Formatting check. This is usually due to a rebase pulling merged Terraform into a feature branch & caused by the developer not having Terraform installed.
This PR is created to update the script to make it obvious it's missing the Terraform executable when failing for that reason.
Test Steps:
- Fixes #issue
- #issue
- Does this PR include changes in authentication and/or authorization of …

Update githook scripts  if it can't find Terraform

---

prime-router/host.json

This PR adds support for Azure Core Tools 4.x for local development when running Dockerless.
Test Steps:
1. Install .Net SDK 6.x
2. Install Azure Core Tools 4.x
3. Did you install Azure Core Tools 4.x before .Net SDK 6.x?  Then you need to do a repair on the Azure Core Tools 4.x, so it finds the new .NET SDK
4. Run `./gradlew run` and verify ReportStream runs.
5. Run the smoke tests and verify they all pass.
- Updated Azure version per MS Doc - https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register
- N/A
- Does this change require …

Support Azure Core Tools 4.x for local development

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0132-limsabc-nova-to-prod.yml
prime-router/settings/staging/0132-limsabc-nova-to-prod.yml

This PR updates limsabc-nova to prod
Test Steps:
1. run attached test message through Reportstream locally and ensure it would be routed to IL.
- update limsabc-nova in organizations.yml file 
- create prod and staging .yml files for limsabc-nova
- [x ] Tested locally?
- [x ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- Fixes #5863 
- Does this …

update limasabc-nova to prod

---

frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx

This PR fixes the activate call within the ValueSets UI.
Test Steps:
1. Login to RS as PrimeAdmin
2. Making sure that "value-sets" feature flag is set, mimic "prime-admin" and navigate to Admin->Value Sets
3. Click on a value set link (i.e. gender)
4. Click Edit on a row, change something and click Save
5. Change is saved. Previously, an error would occur.
- Fixes #issue
- #issue
- Does this PR include or …

experience/fix-activate-call: send valueSet name to activate API call

---

frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx

fixes a bug on master that creates unexpected behavior when editing value sets
1. start servers on master
2. go to a value set detail
3. edit and save a value
4. Validate: new value shows up in the ui, but so does the old value. Both are going up in the POST request to the table, 5. and coming back in the response to content
5. edit and save another value
6. Validate: new value shows up in the ui, but so does the old value. The first edited value disappears. The first edited value is not going up in the POST request
7. restart servers on this branch
8. repeat 2 - 5 and validate that everything saves as expected
- Fixes #issue
*Create GitHub issues to track the work …

fix: correctly save value sets by adding back idea of value set row ids

---

prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
prime-router/metadata/fhir_mapping/hl7/datatype/Identifier_SystemID.yml
prime-router/metadata/fhir_mapping/hl7/resource/DiagnosticReport.yml
prime-router/metadata/fhir_mapping/hl7/resource/ServiceRequest.yml
prime-router/metadata/hl7_mapping/ORU_R01/base/coded-element.yml
prime-router/metadata/hl7_mapping/ORU_R01/base/entity-identifier.yml
prime-router/metadata/hl7_mapping/ORU_R01/base/observation-request.yml
prime-router/metadata/hl7_mapping/ORU_R01/base/order-observation.yml
prime-router/metadata/hl7_mapping/ORU_R01/base/order.yml
prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/ConstantResolver.kt
prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir

This PR ...
Adds the missing mappers from the original HL7 -> FHIR so that we can then map them back to the regenerated HL7.
It also factors out coded element into a separated helper. Detailed list of changes bellow.
Test Steps:
Run this command to generate the HL7`./gradlew primeCLI --args='fhirdata --input-file "src/testIntegration/resources/datatests/HL7_to_FHIR/sample_co_1_20220518-0001.fhir" -s metadata/hl7_mapping/ORU_R01/ORU_R01-base.yml'`
You will notice these differences:
- OBR.3.4 doesn't include ISO at the end because it doesn't actually have a universal id. This is purposeful
- OBR.4 doesn't include the non 2.5.1 HL7 at the end
- OBR.16 Ordering Provider has MD in a different spot
- OBR.26 doesn't include the non 2.5.1 HL7 at the end
- OBR.29.2.2 is missing "RMI" (I can't get …

5839 - Generate OBR segments from FHIR

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0134-RI-Onboarding-Change-to-ri-phd.yml
prime-router/settings/staging/0134-RI-Onboarding-Change-to-ri-phd.yml

This PR changes the organization name to RI-PHD
Test Steps:
- Fixes #issue
- #issue
If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at …

Changed organizaiton name to ri-phd

---

frontend-react/src/__mocks__/LookupTableMockServer.ts
frontend-react/src/config/endpoints/lookupTables.ts
frontend-react/src/hooks/UseValueSets.test.ts
frontend-react/src/hooks/UseValueSets.ts
frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.test.tsx
frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.tsx

following up on API work done here https://github.com/CDCgov/prime-reportstream/commit/eabd48994b82e8ecd24ceb72762d88a8d2b638d2, these changes utilize the new `lookuptables/{tableName}/content` endpoint to enable fetching of lookuptable data without first fetching the most recent version number.
As a result of this change, we can now decouple calls for table metadata from calls for data, and have done so by splitting out two different hooks. This means that components that need metadata (ValueSetsIndex for example) will now call two hooks independently, and that the logic connecting this two calls within the previous implementation of useValueSetsTable is no longer necessary and has been removed.
In addition to cleaning up our functionality, this will make it much easier to work with …

refactor: new lookup table endpoint [experience-5708]

---

prime-router/metadata/schemas/HL7/hl7-ingest-covid-19-training.schema
prime-router/settings/organizations.yml
prime-router/settings/prod/0135-intrivo-onboarding-to-prod.yml
prime-router/settings/staging/0135-intrivo-onboarding-to-prod.yml

Intrivo is moving to production!
- Changed schema from `hl7-ingest-covid-19-training` to `hl7-ingest-covid-19-prod`
- Changed customerStatus from `testing` to `active`
- Fixes #5692

Onboarding Intrivo

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0136-RI-Added-MSH-3.yml
prime-router/settings/staging/0136-RI-Added-MSH-3.yml

This PR Add MSH-3-1, MSH-3-2, and MSH-3-3 to message
Test Steps:
- Fixes #issue
- https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/6457
- #issue …

Add MSH-3-2 and MSH-3-3 to message

---

frontend-react/src/AppRouter.tsx

This PR fixes the broken not-found page path
Test Steps:
1. Boot up
2. Go to `localhost:3000/fjd;alkf`
3. Hopefully it can't find that!
- Fixes #issue
- #issue …

Fixes not found route

---

frontend-react/src/content/support/index.ts
frontend-react/src/pages/support/index-legacy.ts
frontend-react/src/pages/support/legacy-page-content/Contact.tsx
frontend-react/src/pages/support/legacy-page-content/ServiceRequest.tsx
frontend-react/src/styles/_reportstream.scss

This PR ...
Adds the Smartsheet service request form to the website.
Test Steps:
1. Visit `/support/service-request`
2. Fill out the form. Any issues with validation? Problems tab navigating? Filling out the captcha? (Anything submitted to the form will end up in the support queue, connect with Sharon to remove any test entries)
3. Within a few minutes of submitting, you should get a confirmation email from Smartsheetgov with your submission details.
- Creates new support page under `/support/service-request`
- Adds new entry for service request to `/support` index
- Adds the Smartsheet service request form (iframe) to `/support/service-request`
- Updates language and links to service request form on `/support/contact`
- Fixes #6588 
*Create GitHub issues to track the work remaining, if …

Add service request from

---

.github/workflows/build_frontend_dummy.yaml

This PR is to create a dummy build for the Frontend GHA since it's required.
Test Steps:
- Fixes #issue
- #issue …

Create dummy action for Frontend

---

frontend-react/docs/data-fetching-patterns.md
frontend-react/src/components/AppWrapper.tsx
frontend-react/src/hooks/UseValueSets.test.ts
frontend-react/src/hooks/UseValueSets.ts
frontend-react/src/network/QueryClients.ts
frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.test.tsx
frontend-react/src/pages/admin/value-set-editor/ValueSetsDetail.tsx
frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.test.tsx
frontend-react/src/pages/admin/value-set-editor/ValueSetsIndex.tsx
frontend-react/src/utils/CustomRenderUtils.tsx

This PR removes error handling from react-query hooks and puts the responsibility on the component rendering system. Using helper functions, we can now wrap components with error UI and spinner UI helpers (RSErrorBoundary and Suspense). 
See docs for information.
Notable changes:
- React Query hook tests no longer test for errors, error handling integrations tests are the component's responsibility
- Added response interfaces
Test Steps:
1. Ensure the UI behaves as intended by loading the Value Sets Index and Value Sets Detail pages.
2. Ensure tests pass by running yarn test
- Fixes #6522 
- #issue
- Does this PR …

Fetch Refactor: Hook up RSErrorBoundary and Suspense to ValueSetsIndex and ValueSetsDetail

---

prime-router/settings/organizations.yml

This PR updates one of the receivers for CA in the local org file, to match what is in prod.
Test Steps:
1. generate fake data
2. fire up docker
3. reloadsettings
4. send fake data to api
5. save the generated file
6. pull settings from prod env
7. copy and paste the prod env receiver settings to replace the settings for the branch. Do not replace the transport, leave that alone.
8. reloadsettings
9. send fake data to api
10. compare generated file with the other one, make sure they are the same
- updated the prod feed for CA in the local org file

Update org file for  CA

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0139-ME-Onboarding.yml
prime-router/settings/staging/0139-ME-Onboarding.yml

This PRCreate organization and receiver settings for Maine.
Test Steps:
- Fixes #issue
- #issue …

ME Create organization and receiver settings

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0139-ME-Onboarding.yml
prime-router/settings/staging/0139-ME-Onboarding.yml

This PR Fixed MSH-5, MSH-6, and MSH-21-1
Test Steps:
2. Use the attached file as input for ./prime command
3. ./prime data --input junk/test/pdi-covid-19-me.hl7 --input-schema HL7/hl7-ingest-covid-19.schema --output-dir junk/output --route
4. Check output message:
MSH-4:  Sending Facility:                       
MSH-4-1:                                      CDC PRIME
MSH-4-2:                                      11D2030855
MSH-4-3:                                      CLIA
MSH-5:  Receiving Application:                  MEDOH
MSH-6:  Receiving Facility:                     MEDOH
'...
MSH-21: Message Profile Identifier:             
MSH-21-1:                                     PHLabReport-NoAck
MSH-21-2:                                     ELR_Receiver
MSH-21-3: …

Fixed MSH-5, MSH-6, and MSH-21-1

---

prime-router/settings/organizations.yml

This PR Fixed set stateCode to ME
Test Steps:
- Fixes #issue
- #issue
- https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/6851
- Does this PR include or remove any sensitive information …

Fixed set stateCode to ME

---

frontend-react/package.json
frontend-react/src/__mocks__/LookupTableMockServer.ts
frontend-react/src/components/Admin/AdminReceiverDashboard.tsx
frontend-react/src/components/EditableCompare.tsx
frontend-react/src/utils/diff.ts

adds a linting rule to enforce camelcase (camelCase) in variable names.
note that in cases where we need to use snake case, such as situations where we're using a param sent down by the API that uses that convention, we should add that snake case string to the `allow` array in the package.json as demonstrated in this pr
Test Steps:
1. `yarn lint`
2. _VERIFY_: passes
- Fixes #issue
- #issue
- Does this change introduce new dependencies that need …

add camel case rule

---

.github/ISSUE_TEMPLATE/api-sender-onboarding---create-org-and-sender-settings-.md
.github/ISSUE_TEMPLATE/api-sender-onboarding---go-live-coordination.md
.github/ISSUE_TEMPLATE/api-sender-onboarding---post-go-live-ad-hoc-issues.md
.github/ISSUE_TEMPLATE/api-sender-onboarding---testing-in-staging-and-prod.md
.github/ISSUE_TEMPLATE/api-sender-onboarding---validate-receiver.md
.github/ISSUE_TEMPLATE/api-sender-onboarding---validate-test-files.md

Update issue templates

---

.github/workflows/build_hub.yml

This PR ...
Test Steps:
- Fixes #7003
- #issue …

Eliminate juliangruber/sleep-action

---

prime-router/settings/organizations.yml
prime-router/settings/prod/0144-UT-Onboarding-v1.yml
prime-router/settings/staging/0144-UT-Onboarding-v1.yml

This PR Updates UT onboard prod/staging setting and organization.yml
Test Steps:
[- Fixes #issue](https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/6407)
- #issue
- Does this PR include or …

Update UT onboard prod/staging setting and organization.yml

---

.github/actions/build-backend/action.yml

This PR completes the update missed by https://github.com/CDCgov/prime-reportstream/pull/6272
Test Steps:
- Partially Fixes #7014 
- #issue …

update missed by dependabot

---

.github/workflows/codeql.yml

This PR converts V3 to V3.0.2 via checksum
Test Steps:
- Partially Fixes #7014 
- #issue
- Does this …

Convert V3 to V3.0.2 checksum

---

.github/actions/build-backend/action.yml
.github/actions/build-frontend/action.yml

This PR updates actions/upload-artifact from 3.0.0 to 3.1.0 (missed by https://github.com/CDCgov/prime-reportstream/pull/5547)
Test Steps:
- Partially Fixes #7014 
- #issue
- …

Update 3.0.0 to 3.1.0 (missed by dependabot)

---

.github/actions/vpn-azure/action.yml

This PR updates azure/login to v1.4.6 (missed by https://github.com/CDCgov/prime-reportstream/pull/6698)
Test Steps:
- Partially Fixes #7014
- #issue
- Does this PR introduce …

Update to v1.4.6 (missed by dependabot)

---

.github/workflows/validate_resources.yml

This PR is created to set nick-fields/retry action to run on NodeJs version 16
Test Steps:
- Fixes #issue
- #issue …

upgrade NodeJsto 16

---

frontend-react/src/pages/deliveries/Table/DeliveriesTable.tsx

This PR enumerates the dataAttr values for Deliveries, and fixes the missing sort order button for local sorting on Daily Data.
Test Steps:
1. Ensure you see the following descending arrow on the Available column
- Enumerate dataAttrs for Deliveries
- Change default sort column so arrow appears
- Fixes #issue
- #issue
If you answered '_yes_' …

Daily Data UI: Changes name of default sort column and adds enum

---

frontend-react/src/components/header/DropdownNav.test.tsx
frontend-react/src/components/header/DropdownNav.tsx
frontend-react/src/pages/misc/FeatureFlags.tsx

This PR Removes an uncaught use of the value-sets feature flag (unlinked from enum), and to prevent a similar issue, this PR enumerates the message ID search feature flag.
Test Steps:
- Fixes #issue
- #issue …

Remove value-sets flag, add enum for message id search

---

frontend-react/src/pages/deliveries/Deliveries.tsx

This PR is prepping the Deliveries UI for full ELR by removing static disease references.
- Fixes #issue
- #issue
- …

Remove static covid-19 reference from Deliveries UI

---

frontend-react/src/components/FileHandlers/FileHandler.tsx
frontend-react/src/components/FileHandlers/FileHandlerMessaging.tsx
frontend-react/src/components/alerts/NoServicesAlert.test.tsx
frontend-react/src/components/alerts/NoServicesAlert.tsx

This PR extracts an alert component that is useful across the application from FileHandlerMessaging, and adds tests. 
The component will be used in forthcoming work on any page that requires a sender/receiver service to be defined when one is not.
Test Steps:
1. Ensure test suite passes for new component
2. Ensure component still displays in use properly (Validation service is its only current use)
- Component takes optional params and defaults to a generic "no services for your org" message
- Component extracted from FileHandlerMessaging to its own component file with test suite
- Fixes #issue
- #issue
- Does this PR include changes in authentication and/or …

Extract `NoServicesAlert` as a common alert component

---

frontend-react/src/components/Admin/OrgsTable.tsx
frontend-react/src/components/FileHandlers/FileHandler.tsx
frontend-react/src/components/SenderModeBanner.test.tsx
frontend-react/src/components/SenderModeBanner.tsx
frontend-react/src/config/endpoints/services.ts
frontend-react/src/hooks/UseOktaMemberships.test.ts
frontend-react/src/hooks/UseOktaMemberships.ts
frontend-react/src/hooks/UseSenderResource.test.ts
frontend-react/src/hooks/UseSenderResource.ts
frontend-react/src/hooks/network/History/DeliveryHooks.test.ts
frontend-react/src/pages/deliveries/Table/DeliveriesTable.test.tsx
frontend-react/src/pages/submissions/SubmissionTable.test.tsx

This PR adds the services endpoints for #6524 and renames an interface member across _many_ files -- felt like this was just wasted diff, so I gave it its own PR!
Test Steps:
1. No actual changes, but poke around and sanity check me. I did for a bit locally to be safe.
- Adds endpoints for fetch refactor
- Renames a member across many files
- Fixes #issue
- #issue …

Interface updates and adding services endpoints

---

.github/dependabot.yml

This PR updates the dependabot configuration to include .github/actions forder and .devcontainer docker file.
Test Steps:
- Fixes #7131 
- #issue …

Add "actions" folder and ".devcontainer"

---

frontend-react/src/content/live.json
frontend-react/src/content/usa_w_territories.svg

This PR work with Ott to add two new states to the map and list as live.

Add RI and MO to live state map and list

---

frontend-react/package.json
frontend-react/yarn.lock

This PR updates @xmldom/xmldom to 0.7.8 to remediate a "high" [vulnerability](https://github.com/CDCgov/prime-reportstream/security/dependabot/30).
Test Steps:
- Fixes #issue …

Bump @xmldom/xmldom from 0.7.6 to 0.7.8 in /frontend-react

---

frontend-react/package.json
frontend-react/yarn.lock

This PR updates loader-utils from 2.0.2 to 2.0.3 to mitigated critical dependabot security [issue](https://github.com/CDCgov/prime-reportstream/security/dependabot/31).
Test Steps:
- [Release notes](https://github.com/webpack/loader-utils/releases/tag/v2.0.3)
- Fixes #issue
- #issue
- Does …

Bump loader-utils from 2.0.2 to 2.0.3 in /frontend-react

---

.github/dependabot.yml

This PR removes the duplicate path with different parameters for security testing.
Test Steps:
- Fixes #issue
- #issue …

Revert most of the changes in #7274

---

prime-router/metadata/tables/livd/LIVD-Supplemental.csv

This PR Fixed RI Error Message missing OBR-4, OBX-3.2, OBX-17
Test Steps:
- Fixes #issue
- https://app.zenhub.com/workspaces/onboarding--operations-6166edbd409257001e09f1b2/issues/cdcgov/prime-reportstream/7264
- #issue
- Does this PR include or remove …

Fixed RI Error Message missing OBR-4, OBX-3.2, OBX-17

---

frontend-react/src/components/MessageTracker/MessageTracker.tsx

show table, even when no results, on message id search
Test Steps:
1. in the message tracker page, if no search has been performed, the state of the page should start of with no table
2. do a message id search in the message tracker page that will yield no results
2. expected result: table shows with a message that there are no results!
- Fixes #7309 
*Create GitHub issues to track the …

experience/7309: show message list table, even when no results, on message id search

---

prime-router/build.gradle.kts

This PR Bumps [mockk](https://github.com/mockk/mockk) from 1.12.7 to 1.13.1.
Release notes [1.13.1](https://github.com/mockk/mockk/releases/tag/1.13.1)
Release notes [1.12.8](https://github.com/mockk/mockk/releases/tag/v1.12.8)
1.13.2 appears to have a [breaking change](https://github.com/CDCgov/prime-reportstream/pull/7348).
Test Steps:
- [Change …

Bump mockk from 1.12.7 to 1.13.1 in /prime-router

---

frontend-react/src/pages/deliveries/Table/DeliveriesTable.test.tsx
frontend-react/src/pages/deliveries/Table/DeliveriesTable.tsx

This PR fixes our broken download links on Daily Data
Test Steps:
1. Submit sample data
2. Download from the receiver's Daily Data list view
- Fixes #issue
- #issue
- What are the potential security threats and mitigations? Please list …

[Fix] Download link from Daily Data table

---

frontend-react/src/TelemetryService.ts
frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
frontend-react/src/components/Admin/EditReceiverSettings.tsx
frontend-react/src/components/Admin/EditSenderSettings.tsx
frontend-react/src/hooks/UseCreateFetch.test.ts
frontend-react/src/hooks/UseCreateFetch.ts
frontend-react/src/pages/admin/AdminOrgEdit.tsx
frontend-react/src/pages/tos-sign/TermsOfServiceForm.tsx
frontend-react/src/resources/AuthResource.ts
frontend-react/src/resources/SenderAuthResource.ts

This changeset updates our fetch creation to include a new `x-ms-session-id` header to help us identify users across client side and API requests.  We're just populating it with the App Insights-generated session id -- it should be enough for our purposes so why not piggyback on their logic!
**This is a WIP.**  The remaining TODOs are:
- More manual testing around the site
- Add tests
Test …

Experience 7609: Add AI session id to fetches

---

frontend-react/src/hooks/network/History/DeliveryHooks.ts
frontend-react/src/pages/submissions/SubmissionTable.test.tsx
frontend-react/src/pages/submissions/SubmissionTable.tsx
frontend-react/src/resources/SubmissionsResource.ts

7358 Update calls to Submission and Delivery endpoints to pass correct params
#7635 PR was reverted and this PR un-reverts it with code that doesn't break paging. The solution was to completely remove the old cursor value calculation and just use the cursor value tracked by the front-end.
Test Steps:
The root cause of #7358 was we were calling the …

Fix table sorting and remove old cursor calculation

---

frontend-react/src/TelemetryService.ts

This changeset updates the AI track calls to always send `activeMembership` -- it should be applicable to `PageviewData`, `PageviewPerformanceData`, and `RemoteDependencyData` since those are active by default, but it should also apply to `EventData` and `MetricData` if we choose to include manually tracked events as well.  (I'll double-check this, though!)
A couple of questions:
- Are there any issues with sending this information on _every_ tracked event?
- Do we need to flatten this data so we only send primitive types?  Right now it's just a stringified object, but I don't have access to the AI dashboard so I don't know what our aggregation capabilities are😅
**If you are suggesting a fix for a currently exploitable issue, please disclose the issue to the prime-reportstream team …

Proposal: Send activeMembership data with all AI track events

---

frontend-react/src/TelemetryService.test.ts
frontend-react/src/TelemetryService.ts
frontend-react/src/index.tsx

This PR ...
This changeset carries over [the SimpleReport TelemetryService logic](https://github.com/CDCgov/prime-simplereport/blob/main/frontend/src/app/TelemetryService.ts) that we want to use here.  I started refactoring it, but I decided to just copy it over verbatim for consistency, and we can make modifications to it in the future if we need.  However, one thing that could help here could be to add a dev-only AI environment so that we can always initialize the ApplicationsInsights instance.  That'd obviate the need for a lazy initialization like we're doing with `ai.initialize()`, and we could test that events are actually getting passed to the proper channels locally prior to deplying to staging or demo environments.  Something we can discuss in the future, though 🤷
**If you are …

Experience 7606: Wrap console.warn, console.error to report to AI

---

frontend-react/src/components/USLink.test.tsx
frontend-react/src/components/USLink.tsx

This PR adds component code **that will be implemented in the next PR** to solve for links in our React app refreshing the DOM at the `App` level (the blocking behavior for #7627)
Test Steps:
1. Run the test suite to ensure they pass!
- Introduces `USLink`, `USExtLink`, `USCrumbLink`, and `USNavLink`
- Adds tests for all new components
- First PR for #7730 
- #issue …

Add new `USLink` components

---

prime-router/src/main/kotlin/fhirengine/translation/hl7/utils/FhirPathUtils.kt
prime-router/src/test/kotlin/fhirengine/translation/hl7/utils/FhirPathUtilsTests.kt

This PR has no functional change, and serves only to fix a linter issue that made it to `master`

Fix linter issues in master

---

frontend-react/src/utils/Analytics.test.ts

This has just been bothering me in pull requests!

Fix empty line lint complaint

---

frontend-react/src/hooks/UseOrganizationReceiversFeed.ts

This PR adds a `find` to the receivers array fetched for Daily Data. While ongoing work will refactor this out for session-level services settings management, this patch will help mitigate some of the issue found in #7471 where inactive settings were the first in the given array.
Test Steps:
- Fixes #issue
- #issue
- Does this change require …

Prioritize active receivers on Daily Data

---

prime-router/docs/schema_documentation/hl7-color-labs-covid-19.md
prime-router/metadata/schemas/HL7/color-labs-covid-19.schema

This PR updates the color-labs schema for production
Test Steps:
1. run ./prime test locally
- update hl7/color-labs-covid-19 schema to remove hardcoded "T" processing mode code
- [X ] Tested locally?
- [X ] Ran `./prime test` or `./gradlew testSmoke` against local Docker ReportStream container?
- Fixes #7630 
- Does …

update color-labs schema for production

---

frontend-react/src/components/Admin/AdminFormEdit.tsx
frontend-react/src/components/Admin/EditSenderSettings.test.tsx
frontend-react/src/components/Admin/EditSenderSettings.tsx
frontend-react/src/resources/OrgSenderSettingsResource.ts
frontend-react/src/resources/TestResponse.ts

This PR adds an interface for altering the value of `allowDuplicates` for a sender setting.
Test Steps:
1. Ensure the tests run and pass
2. Ensure checking the box alters the JSON state
3. Ensure the checkbox loads with the proper state
- Adds field to `EditSenderSettings` form component
(Loaded with initial checked state when `allowDuplicates: true`)
(State altered when unchecked and previewed)
- Fixes #6039 
- #issue
- Does logging contain …

Allow Duplicates checkbox for Sender Settings

---

operations/dnsmasq/config/staging/hosts.local

Reverts CDCgov/prime-reportstream#8082

Revert "change staging to look at restore2 when using old FQDN"

---

operations/dnsmasq/config/staging/hosts.local

change the old db name to point at restore2

change it so pdhstaging-pgsql resolves to restore2

---

frontend-react/src/pages/TermsOfService.tsx

This PR updates the TOS statements using the resources in #8132 
Test Steps:
1. Ensure copy changes are as-intended
- Copy only
- Fixes #issue
- #issue
- What are the potential security threats and mitigations? Please list the _STRIDE_ …

Update TOS on site

---

prime-router/build.gradle.kts

This PR just updates Jacoco to support JDK 17 and 18. This allows up to use JDK 18. Updating to JDK 19 requires one small code change, but will also require EVERYONE to migrate to JDK 19 as well.
Test Steps:
1. Build the branch using JDK 17 or 18 and verify it is successful.
2. Verify the Github build is successful.
- updates Jacoco to support JDK 17 and 18.
- Fixes #issue
- #issue
- Does this PR include or …

Updated Jacoco version to support JDK 17 and 18

---

prime-router/docs/proposals/0016-authorization.md

This PR fixes bad formatting in a markdown file.

Fix format:  markdown is swallowing the asterisks.

---

prime-router/src/test/kotlin/fhirengine/utils/FhirTranscoderTests.kt

This PR ...
Test Steps:
1. Just run the unit tests or verify that the build passes
Just did some Kotlin cleanup in the tests
- Fixes #issue 8249
- #issue
- Does this PR introduce new endpoints? No
- Does this PR include changes in authentication and/or authorization of existing endpoints? No
- Does …

FHIR Transcoder test cleanup

---

.github/ISSUE_TEMPLATE/design-issue-template.md

This PR ...
Adds a new issue template for design tickets.
Test Steps:
- Creates new ticket template
- Fixes #issue
- #issue
- …

Add new issue template for design tickets

---

frontend-react/yarn.lock

This PR eliminates obsolete and vulnerable @bable* dependencies.
Test Steps:
- Fixes #issue
- #issue …

Deduplicate @bable* dependencies

---

prime-router/docs/proposals/0019-website-api-payload-structure.md

This changeset adds a doc that proposes communication patterns between the website and the API layer.
- Fixes #8202

Experience-8202: Add proposal for website-API communication

---

.github/workflows/chromatic-master.yml
.github/workflows/chromatic-pr.yml
.gitignore
frontend-react/package.json
frontend-react/yarn.lock

This changeset adds a Chromatic GHA workflow to deploy our Storybook to Chromatic.  This'll run on any `push` event on any branch, and it'll automatically approve any changes on `master.  Hopefully this'll help during design planning and review since we'll have a central component styleguide!
- Fixes #8928

Experience-8928: Add Chromatic GHA

---

frontend-react/.storybook/main.js
frontend-react/config/webpack.config.js
frontend-react/scripts/build.js
frontend-react/scripts/start.js

Fixes #9246
This PR:
- readds the rehype-slug plugin from our prior markdown implementation to MDX to both our webpack and storybook configuration
- applys the remark-gfm plugin (github markdown extensions)

MDX plugin support

---

.github/workflows/sonarcloud_master.yml

adds the workflow_dispatch trigger so we can run manually if we desire

add workflow dispatch

---

.github/actions/build-frontend/action.yml

This PR reverts the change to -Dsonar.sources made in #6372
Test Steps:
- Fixes #issue
- #issue
- …

Update sonarcloud call

---

prime-router/src/main/kotlin/fhirengine/engine/CustomFhirPathFunctions.kt
prime-router/src/main/kotlin/metadata/LivdLookup.kt
prime-router/src/main/kotlin/metadata/LivdMappers.kt
prime-router/src/test/kotlin/metadata/LivdLookupTests.kt

This PR cleans up the LivdLookup.find function so that nulls weren't having to be set all over the place. 
Test Steps:
1. Basically just make sure the unit tests still pass.  
2. Call the livdTableLookup() function on the FHIR path. Load a bundle into a terminal ./prime fhirpath -i src/testIntegration/resources/datatests/HL7_to_FHIR/bundle1.txt
then run something like resource=Bundle.entry.resource.ofType(Observation)[0]
%resource.livdTableLookup("Test Performed LOINC Code") to make sure it works. 
- Just set null as the default params on the find function
- Fixes #issue
- #issue
- Does this PR include changes in authentication and/or authorization of …

Cleaned up the calls to the LIVD lookup find function

---

.github/workflows/alert_terraform_changes.yml
.github/workflows/deploy_terraform.yml

V1.4
This PR ...
Test Steps:
- Fixes #issue
- #issue …

Action update

---

.github/workflows/build_hub.yml
.github/workflows/sonarcloud_master.yml

This PR removes the (incorrect) option sonar.skipUnchanged.  The correct option would be sonar.`java`.skipUnchanged, but the analyzer seems to be handling this properly regardless.
Test Steps:
- Fixes #issue
*Create GitHub issues to …

Let analyzer choose skipUnchanged

---

.github/workflows/build_hub.yml
.github/workflows/sonarcloud_master.yml

move towards unifying the three different calls to SonarCloud
This PR ...
Test Steps:
- Fixes #issue
- #issue
- new …

SonarCloud update

---

.github/workflows/build_hub.yml
.github/workflows/sonarcloud_master.yml

This PR ...
Test Steps:
- Fixes #issue
- #issue …

suppress testintegration for coverage and duplication

---

.github/workflows/build_hub.yml
.github/workflows/sonarcloud_master.yml

This PR ...
Test Steps:
- Fixes #issue
- #issue …

camelCase folder name

---

.github/dependabot.yml

This PR increases the limit on dependabot PRs to catch up with backlog.
Test Steps:
- Fixes #issue
- #issue
- new …

Increase PR limit

---

frontend-react/src/content/product/release-notes.md

Release notes May 2023 updates
https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/9563
Fixes #9563

Update release-notes.md May 2023

---

.github/workflows/sonarcloud_master.yml

Reverts CDCgov/prime-reportstream#9804

Revert "Update sonarcloud_master.yml"

---

.github/dependabot.yml

Change the # of Dependabot PRs to 10 each for front/back end

change # of dependabot pr limit to 10

---

.github/workflows/validate_resources.yml

and try the conditional directly on the VPN step.
This PR ...
Test Steps:
- Fixes #issue
- #issue
- …

verify dependabot username

---

prime-router/examples/generate-jwt-python/jwt-errors.md

This PR creates the page from [this ticket](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/9945) which outlines explanations and instructions for errors when generating a signed JWT.  
Test Steps:
n/a
- [Content drafted in doc](https://docs.google.com/document/d/1AqazB32yopIHRjkMOtLa8cBP-qusmu3LQiHFI43cLeo/edit#heading=h.u8u2sxj …

9945: Create jwt-errors.md

---

frontend-react/src/styles/_uswds_settings.scss

Fixes #10112
This PR fixes the uswds path regression before final vite merge.

BUG: USWDS Image/Font Paths Regression

---

frontend-react/package.json
frontend-react/yarn.lock

This PR forces "word-wrap": "aashutoshrathi/word-wrap", and "semver": ">=7.5.3" to mitigate vulnerabilities.
The original [wordwrap](https://github.com/jonschlinkert/word-wrap) is not being well maintained.
Test Steps:
- semver [changelog](https://github.com/npm/node-semver/releases)
- aashutoshrathi/word-wrap …

override to forked/patched version in /frontend-react

---

frontend-react/yarn.lock

This PR deduplicates and/or updates 90 dependencies eliminating obsolete and possibly vulnerable versions.
Test Steps:
- Fixes #issue
- #issue …

Deduplicate and update dependencies

---

prime-router/settings/staging/0149-etor.yml
prime-router/src/testIntegration/kotlin/transport/RESTTransportIntegrationTests.kt

This PR updated the staging URL for ETOR
Test Steps:
- Fixes #issue
- #issue
- …

Updating Staging URL for ETOR

---

.github/actions/build-frontend/action.yml
.github/workflows/build_hub.yml

Reverts CDCgov/prime-reportstream#10384

Revert "Update CI"

---

prime-router/metadata/fhir_mapping/config.properties
prime-router/metadata/fhir_mapping/hl7/codesystem/ExtensionUrlMapping.yml
prime-router/metadata/fhir_mapping/hl7/resource/MessageHeader.yml
prime-router/metadata/fhir_mapping/hl7/resource/MessageSender.yml
prime-router/metadata/fhir_mapping/hl7/resource/Order.yml
prime-router/metadata/fhir_mapping/hl7/resource/Patient.yml
prime-router/src/main/kotlin/SubmissionReceiver.kt

This PR ...
Adds mappings for MSH and PID
Test Steps:
Run something like ./prime fhirdata -i /Users/jessicawillis/git/prime-reportstream/prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/orm.hl7 -o /Users/jessicawillis/git/prime-reportstream/prime-router/src/testIntegration/resources/datatests/HL7_to_FHIR/orm.fhir  --output-format FHIR
and make sure that all of the data gets moved over from the message in the ticket https://app.zenhub.com/workspaces/platform-6182b02547c1130010f459db/issues/gh/cdcgov/prime-reportstream/10370
- Missing MSH fields added
- Missing PID fields added
- Ticket opened for resolving the PID.7 issue: https://github.com/LinuxForHealth/hl7v2-fhir-converter/issues/499
- Fixes #issue
- #issue
- …

MSH and PID done

---

prime-router/docs/universal-pipeline/batch.md

This PR adds documentation for the batch step.
Test Steps:
n/a
- Fills out the batch.md file
- #10213

10213: document batch step

---

frontend-react/src/hooks/UseOrganizationReceiversFeed.test.ts

Fixes #10729
This PR fixes a faulty test that occasionally fails in github actions.

Fix useOrganizationReceiversFeed test faultiness

---

.github/workflows/deployment_rollback.yml

This PR s just to update the code to get the right container id

Update deployment rollback container filter

---

.github/workflows/snyk.yml

This PR add automated Snyk Kotlin scans when merging with master.
The workflow should have no action until SNYK_TOKEN is created.
Test Steps:
- Fixes #issue
- #issue
- Does …

Add Snyk workflow

---

frontend-react/src/AppRouter.tsx
frontend-react/src/content/support/index.ts
frontend-react/src/layouts/Markdown/MarkdownLayout.tsx
frontend-react/src/pages/support/faq/FaqPage.tsx
frontend-react/src/vite-env.d.ts

Fixes #10846
This PR fixes the accidental removal of the FAQ page card from the support page and broken route.

BUG: FAQ page unavailable

---

.github/workflows/chromatic-master.yml
.github/workflows/chromatic-pr.yml

Dependabot can't find the referenced hash.
Current [version](https://github.com/chromaui/action)
This PR ...
Test Steps:
- Fixes #issue
- #issue …

unknown version

---

frontend-react/src/content/resources/ResourcesIndex.mdx
frontend-react/src/content/support/faq/FaqIndex.mdx

This PR ...
Changed class to className so that Azure does not throw exception: "Warning: Invalid DOM property `%s`. Did you mean `%s`?%s"
Test Steps:
1. Go to the Resources or FAQ page in production
2. Go to Azure -> logs
3. View exception
- Should not see the following error appear in Azure once this gets deployed

Changed class to className in mdx files to prevent exception

---

.github/actions/build-frontend/action.yml
.github/workflows/build_hub.yml
.github/workflows/sonarcloud_master.yml
prime-router/Dockerfile
prime-router/Dockerfile.build
prime-router/Dockerfile.dev
prime-router/build.gradle.kts
prime-router/docs/docs-deprecated/getting-started/Using-an-apple-silicon-mac.md
prime-router/docs/docs-deprecated/getting-started/install-openjdk.md

This reverts commit 40e17fca05cf345c46d3aa5026685f428426ebe7.
This PR reverts the Java 17 update while the GitHub builder is investigated.
- Reverts #10992

Revert "Update project to Java 17 (#10992)"

---

.github/dependabot.yml

This PR adds some grouping to backend PR's.
Test Steps:
- Fixes #issue
- #issue
- Does this PR …

dependabot backend grouping

---

prime-router/docs/getting-started/standard-operating-procedures/releases.md
prime-router/src/main/kotlin/cli/OktaCommands.kt

This reverts commit 9ce7594a0acc09c1ec4a8965b15846cb49bae557.
Test Steps:
- Fixes #issue
- #issue …

Revert "Automate Okta login when the credentials are available (#10933)"

---

prime-router/settings/staging/0154-nbs-cdc-staging.yml

This PR added a sender setting to NBS staging.  Therefore, they can send their test message to RS and see the routing.
Test Steps:
2. docker-compose up
3. ./prime multiple-settings set --env staging --input ./settings/staging/0154-nbs-staging.yml
4. curl -X POST -H "client:dataingestion" -H "content-type:application/hl7-v2" --data-binary "@./junk/KS/Testing/pdi-covid-19-ks.hl7" "http://localhost:7071/api/reports"
Test file: 
[pdi-covid-19-ks.txt](https://github.com/CDCgov/prime-reportstream/files/12479399/pdi-covid-19-ks.txt)
- Fixes #issue
- #issue …

Adding Sender Staging Setting to NBS for them to send test message

---

.github/actions/deploy-frontend/action.yml

Reverts CDCgov/prime-reportstream#11224

Revert "10262 Deploy swagger ui apidocs to staging - fix a typo in upload step"

---

operations/app/terraform/modules/log_analytics_workspace/~inputs.tf

massive change to add the variable since it's hard to use it when it's not defined :(

forgot to add the variable :(

---

frontend-react/src/AppRouter.tsx
frontend-react/src/components/header/ReportStreamNavbar.tsx
frontend-react/src/content/managing-your-connection/index.mdx

This PR ...
Fixes link for Refer healthcare organizations
Test Steps:
1. Log into RS
2. Click on the "Your Connection" navigation
3. Click the "Refer healthcare organizations" link and validate the correct page
- update Refer healthcare organizations link
- cleanup manage-your-connection path
- Fixes #11297

11297 - [BUG] Fix link for Refer healthcare organizations

---

.github/workflows/chromatic-master.yml
.github/workflows/chromatic-pr.yml

This PR updates chromaui/action from 7.0.0 to 7.1.0
Test Steps:
- Fixes #issue
- #issue
- Does this …

bump chromaui to 7.1.0

---

.github/dependabot.yml

This PR groups:
com.azure:azure-core
com.azure:azure-core-http-netty
which appear to get updated together often with http-netty dependent on core.
Test Steps:
- Fixes #issue
- …

Add azure-core group

---

frontend-react/src/content/support/index.mdx

See #10540.
This PR updates the support page with okta-related changes (per #10540).

Okta Support Page Updates (#10540)

---

.github/workflows/sonarcloud.yml

Reverts CDCgov/prime-reportstream#12029

Revert "Update github/codeql-action requirement to 4fddc51e4f3b5e5e9022f35c3464736cc10e1e98"

---

operations/app/terraform/vars/staging/locals.tf
operations/app/terraform/vars/test/locals.tf

This PR is to fix the locals file settings for okta client id

fix locals variable setting

---

frontend-react/src/App.tsx
frontend-react/src/shared/DAPScript/DAPScript.tsx

remove env block, add better safety

---

prime-router/build.gradle.kts
prime-router/src/main/kotlin/azure/DatabaseAccess.kt

This PR reverts #12334 
Test Steps:
1. Run test suite
- Reverts changes in #12334

Rollback flyway v10 upgrade & associated changes

---

.github/workflows/codeql.yml

This PR eliminates frontend CodeQL checks for backend and operations PRs by restricting to paths for javascript 
Test Steps:
- Fixes #issue
- #issue
- Does this PR introduce …

Paths for CodeQL javascript and python

---

frontend-react/src/pages/deliveries/Deliveries.tsx

This PR ...
Fixes issue where extra <Helmet> wrapper causing error and not allowing Daily data to load.
Test Steps:
1. Log into RS
2. Select an org
3. go to /daily-data and verify that data is loading
- Fixes #issue

Removed extra <Helmet> wrapper causing error and not allowing Daily data to load.

---

prime-router/Dockerfile.build

This PR updates container image `bullseye` to `bookworm`. Debian `bullseye` is EOL on October 7th, 2023.
Test Steps:
- bookworm [release](https://www.debian.org/releases/bookworm/)
- Fixes #issue
- #issue
- Does this …

Bump Debian 11.8 to 12.4

---

prime-router/docs/design/proposals/0024-original-message-passthrough.md

This PR adds a proposed design for the Original Passthrough feature.
- Add proposed design for Original Passthrough.
- #12224
- #12813 
- #12814 
- #12816

12224 Original Message Passthrough design proposal

---

frontend-react/index.html

Been a while -- need to update meta tag for verification

Update google-site-verification tag

---

.github/dependabot.yml

This PR groups dependabot updates for okta-jwt-verifier*
Test Steps:
- Fixes #issue
- #issue
- Does …

group com.okta.jwt:okta-jwt-verifier*

---

.github/dependabot.yml

This PR add the missing wildcard to group jwt-verifier
Test Steps:
- Fixes #issue
- #issue
- Does …

add missing wildcard

---

.github/workflows/codeql.yml
.github/workflows/sonarcloud.yml

This PR updates codeql actions to 2.16.1
Test Steps:
- 2.16.1 [Release Notes](https://github.com/github/codeql-action/releases/tag/codeql-bundle-v2.16.1)
- 
- Fixes #issue
- #issue
- Does this PR include changes in …

Bump codeql to 2.16.1

---

frontend-react/yarn.lock

This PR bumps socks to a version that does not use ip 2.0.0 to mitigate dependabot [alert](https://github.com/CDCgov/prime-reportstream/security/dependabot/59).
Test Steps:
- Fixes #issue
*Create GitHub issues to track the work …

bump socks from 2.7.1 to 2.8.0 in /frontend-react

---

prime-router/build.gradle.kts

This PR pins org.apache.commons:commons-compress to 1.26.0 to minigate Snyk [finding](https://app.snyk.io/org/prime-reportstream/project/3995ae6a-2093-4f94-b638-312e1e409404#issue-SNYK-JAVA-ORGAPACHECOMMONS-6254296) and [finding](https://app.snyk.io/org/prime-reportstream/project/3995ae6a-2093-4f94-b638-312e1e409404#issue-SNYK-JAVA-ORGAPACHECOMMONS-6254297).
Test Steps:
1. *Include steps …

Pin org.apache.commons:commons-compress to 1.26.0 in /prime-router

---

.github/workflows/prepare_deployment_branch.yaml

This PR fixes the "Prepare Deployment Branch" workflow.
Test Steps:
1. Wait for the workflow to trigger on schedule and check if PR has been created
- fixes the "Prepare Deployment Branch" workflow
- Fixes #13463
- @JosiahSiegel to review and merge a PR in his personal repo: https://github.com/JosiahSiegel/reliable-pull-request-action/pull/14
- Workflow updated to use his Action instead of the forked one

Fixes the "Prepare Deployment Branch" workflow.

---

.github/workflows/sonarcloud.yml

This PR updates actions/setup-java to V4 and converts to hash reference.
Test Steps:
- Fixes #issue
- #issue
- new …

Bump setup-java from V3 to 4.0.0 (hash)

---

frontend-react/.storybook/UtilizedUSWDSComponents/Select.stories.tsx
frontend-react/.storybook/main.ts
frontend-react/package.json
frontend-react/vite.config.ts
frontend-react/yarn.lock

Fixes #13793
This PR makes the changes necessary for the chromatic deploy to work again (tested via chromatic --dry-run).
- create temp fix for msw/native import issue
- remove turbosnap (built into sb8 now)
- fix dropdown->select in react-uswds story

BUG: Chromatic deploy broken with latest msw

---

.github/workflows/sonarcloud.yml
frontend-react/src/unsupportedBrowser.ts

Flakey UsePagination test causing failures
This PR ...
Test Steps:
- Fixes #issue
- #issue
- Does …

Retry frontend test

---

.gitmodules

This PR is a slack-boltjs-app submodule update
Test Steps:
- Fixes #issue
- #issue
If you answered '_yes_' to any of the questions above, conduct a detailed Review that addresses at …

slack-boltjs-app submodule update

---

prime-router/docs/universal-pipeline/receive.md

This PR updates the receive.md file to include more information/details.

Update receive step documentation to include more detail

---

prime-router/build.gradle.kts

This PR updates indirect dependency xalan to 2.7.3 (introduced in https://github.com/CDCgov/prime-reportstream/pull/13918) to mitigate [Snyk finding](https://app.snyk.io/org/prime-reportstream/project/3995ae6a-2093-4f94-b638-312e1e409404#issue-SNYK-JAVA-XALAN-2953385).
Test Steps:
- *(For web UI …

Bump xalan from 2.7.2 to 2.7.3 in /prime-router

---

frontend-react/e2e/spec/daily-data-details-page.spec.ts

Fixes #14318
This PR skips a test that isn't applicable currently.

BUG: E2E Daily Data Details Test Broken

---

prime-router/metadata/file_name_templates/file-name-templates.yml

This PR updates Texas file name template

Update to TX file name template

---

prime-router/src/main/resources/db/migration/V68__add_index_report_file.sql

Updated index flyway script to create index if not exists

Updated index flyway script to create index if not exists

---

operations/app/functions/admin/requirements.txt

This PR updates Python dependencies for the admin tools.
Test Steps:
- Fixes #issue
- #issue
- Does …

AdminTools remediations

---

frontend-react/src/config/index.ts
frontend-react/src/shared/DAPScript/DAPScript.tsx
frontend-react/vite.config.ts

This PR ...
Fixes CSP Header Issues
Test Steps:
1. Goto RS
2. Open console and you should not see CSP issues
- Fixes #14518 
- [#131](https://app.zenhub.com/workspaces/prime-devops-606cb208a8c112000fd48349/issues/gh/cdcgov/prime-devops/131)

14518 - Fixed CSP Header Issues

---

frontend-react/src/components/Table/TableFilterStatus.tsx
frontend-react/src/pages/deliveries/daily-data/DailyData.test.tsx
frontend-react/src/pages/deliveries/daily-data/DailyData.tsx

This PR ...
Reverts the updated table due to pagination issues
Test Steps:
1. Log into RS
2. Select org that has at least 100 records for Daily Data i.e. ignore
3. Navigate to Daily data
4. Click on pagination buttons to view correct data is being returned.
- Fixes #14742

14742 - Reverted table due to bug issues

---

.environment/terraform-fmt/run-terraform-fmt.sh

This PR updates the terraform pre-commit check to show the terraform version correctly.
Test Steps:
- Fixes #issue
- #issue
- new …

terraform version command failing

---

.github/workflows/frontend_ci.yml
frontend-react/vite.config.ts

This PR skips modifying comments if run by `dependabot`
Test Steps:
- Fixes #15009
- #issue
- Does …

Skip if dependabot

---

frontend-react/package.json
frontend-react/yarn.lock

Fixes #15083
This PR rolls back the eslint version.

BUG: Rollback eslint version

---

frontend-react/e2e/spec/all/last-mile-failures-page.spec.ts
frontend-react/src/components/Admin/AdminLastMileFailuresTable.tsx
frontend-react/src/hooks/api/UseCreateResend/UseCreateResend.ts
frontend-react/src/pages/admin/AdminLastMileFailures.tsx

This PR should resolve the resend functionality on the Last Mile Failures page.
**Current Broken Behavior:**
**Fixed Behavior Currently Deployed on [Trial Env 3](https://pdhstagingpublictrial03.z13.web.core.windows.net/):**
fixes #15317

title casing + receiver ID fix

---

.github/dependabot.yml

Dependabot complains about groups patterns that do not match anything explicitly listed in the manifest.
This PR ...
Test Steps:
- Fixes #issue
- #issue
- Does this PR …

Clean Dependabot groups

---

.environment/frontend/run-frontend.sh
frontend-react/.husky/pre-commit
frontend-react/scripts/postinstall.sh

Fixes #15573
This PR updates the monorepo/frontend hook code in order to continue to function as intended.

BUG: husky.sh file deprecated

---

.github/workflows/frontend_ci.yml

Various shards are hitting the 7 min. timeout repeatedly
This PR updates the matrix timeout to 10 minutes.
Test Steps:
- Fixes #issue
- #issue …

Shard timeout increase in frontend_ci.yml

---

.github/dependabot.yml

This PR adds the submissions build action to the dependabot configuration.
Test Steps:
- Fixes #issue
- #issue
- new …

Add submissions action to dependabot.yml

---

submissions/src/main/kotlin/gov/cdc/prime/reportstream/submissions/controllers/SubmissionController.kt

/submissions does not have pre-commit hooks to run ktlint
This PR ...
Test Steps:
- Fixes #issue
- #issue
- new …

ktlint in /submissions

---

.github/actions/build-auth/action.yml
.github/actions/sonarcloud/action.yml
.github/workflows/sonarcloud.yml

This PR adds a build action for `/auth` and `/auth` to sonarcloud testing.
Note that `/auth` does not have coverage statistics which may skew results.
Test Steps:
- Fixes #issue
*Create GitHub issues to track the work remaining, if …

add sonarcloud coverage for /auth microservice

---

.github/workflows/snyk.yml

This PR add Snyk testing of `/auth`
Test Steps:
- Fixes #issue
- #issue
- Does this PR include …

add snyk testing for /auth

---

frontend-react/src/content/about/roadmap.mdx

roadmap content update

---

frontend-react/e2e/spec/chromium-only/authenticated/daily-data-page-user-flow.spec.ts

Un-skip E2E test: daily-data-page-user-flow.spec.ts #16062

---

buildSrc/build.gradle.kts
prime-router/Dockerfile.build
prime-router/Dockerfile.dev
prime-router/build.gradle.kts

This PR ...
There is a 'µ' character that is lost/distorted in translation from HL7 to FHIR
Test Steps:
- 
- Fixes #issue
- #issue
- What are the potential security threats and mitigations? Please …

Demo 1 - UTF-8 char Encoding Bug

---

prime-router/host.json

This PR adds UTF-8 encoding to the JAVA_OPTS in host.json.

Add java_opts with UTF-8 encoding

---

.github/dependabot.yml

Fixes #16451
This PR updates the frontend dependabot groupings to attempt to generalize the groups and ensure more dependencies are part of a group PR rather than a one-off.

Update frontend dependabot groupings

---

.github/actions/build-vars/action.yml
.github/actions/demo-env/action.yml
.github/changelog_config.json
.github/scripts/alert_stale_branches/stale_branch_check.sh
.github/workflows/frontend_chromatic_main.yml
.github/workflows/snyk.yml
.github/workflows/sonarcloud.yml
prime-router/docs/api/admin.yml
prime-router/docs/api/api-keys.yml
prime-router/docs/api/check.yml
prime-router/docs/api/covid-result-metadata.yml
prime-router/docs/api/delivery.yml
prime-router/docs/api/email-engine.yml
prime-router/docs/api/email-sender.yml
prime-router/docs/api/messages.yml
prime-router/docs/api/reports.yml
prime-router/docs/api/requeue.yml
prime-router/docs/api/sender-files.yaml
prime-router/docs/api/settings.yml
prime-router/docs/api/submissions.yml
prime-router/docs/api/token.yml
prime-router/docs/api/validate.yml
prime-router/docs/api/waters-delivery.yml
prime-router/docs/api/waters-reports.yml
prime-router/docs/api/waters-submissions.yml

This PR fixes additional references for switching from `master` to `main`.

additional fixes for main branch

---

.github/actions/connect-ovpn/action.yml

This PR corrects an issue that was introduced where a networking testing block, disrupting the execution of the workflows **Deploy [FrontEnd/Router] Release**.  The issue was not detected during the branch merging stage and only became problematic once specific IP Addresses started to be provided (input parameters) to the GitHub Action.
By default, the OpenVPN configuration attempts to ping the 127.0.0.1 (loopback adapter) which would never fail.
Once the system attempts to ping 10.0.2.4 without the actual OpenVPN to be operational, then the process breaks.
**There are no currently exploitable issue**
- *Restructured the injected changes to be performed after the OpenVPN configuration is active*
- Does this PR introduce new endpoints? No …

Correcting a networking validation issue on pushing Artifacts to Azure

---

operations/app/terraform/modules/chatops/main.tf

This PR introduces a whitespace change to try to include TF run in CI/CD and future deployment

adding whitespece change in TF to rey to force TF deployment

---

.github/ISSUE_TEMPLATE/platform-user-story.md

This PR updates the Platform User Story issue template. Most notably, it encourages writing acceptance criteria as a list of checkboxes that can be checked off as work progresses.

Update platform user story template

---

frontend-react/e2e/pages/authenticated/admin/organization-receiver-message-test.ts
frontend-react/e2e/spec/all/authenticated/admin/organization-receiver-message-test.spec.ts

Adds simple e2e test testing downloading PDF and making sure it has contents.
Fixes #16101

download PDF and check if it has contents

---

.github/workflows/codeql.yml

removing scheduled runs

---

prime-router/docs/getting-started/postgres-database.md

Update database documentation to include guidance for creating and deploying database migrations. This comes as an action item from the following incident report: https://cdc.sharepoint.com/:w:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B5032BA7B-8604-4669-BDF2-9DCBF1399370%7D&file=2025_02_07%20-%20Database%20Outage%20Incident%20Report.docx&action=default&mobileredirect=true

Add migration creation and deployment guidance to postgres-database.md

---

.github/actions/connect-ovpn/action.yml

Testing to see if longer sleep is needed for vpn connection to be usable

bump sleep to 10s in vpn action

---

.github/actions/connect-ovpn/action.yml

This PR adds code to validate the vpn connection status

vpn connection debug

---

.github/actions/connect-ovpn/action.yml
.github/actions/vpn-azure/action.yml

This PR adds debug logging to openvpn.

add debug logging to openvpn

---

prime-router/docs/onboarding-users/sender-onboarding/mapping-sender-codes-to-condition.md
prime-router/src/main/kotlin/azure/SenderFunction.kt
prime-router/src/test/kotlin/azure/SenderFunctionTest.kt

This PR changes the output JSON keys for the `sender/conditionCode/comparison` endpoint from its original input text to camel case
Test Steps:
- Partially related to #16759 
- #issue
If …

Change condition code comparison endpoint JSON output key format

---

prime-router/build.gradle.kts
prime-router/src/main/kotlin/transport/GAENTransport.kt

This PR updates the HAPI libraries to the most recent version* and resolves any conflicts arising from this. See the github issue for more detailed technical notes.
Test Steps:
1. Unit, Integration, and E2E tests pass.
- Unpins the HAPI core libraries to allow HAPI FHIR libraries to define the version.
- Note: This is following the [HAPI FHIR recommendation](https://github.com/hapifhir/hapi-fhir/issues/6572) to not use a different version of HAPI Core than HAPI FHIR has defined. It is believed that these were [originally pinned](https://github.com/CDCgov/prime-reportstream/pull/15863) "because upgrading them would create some backward compatibility issues". However this goes against the library's own usage recommendation and the pinned version can be removed.
- Updates usage of …

Update Hapi Libraries

---

.editorconfig

Adding indenting for terraform

Update .editorconfig for TF

---

.github/workflows/alert_PD_schedule_Slack.yml

Follow-up to: #17693. Forgot to update the Monday action, only updated the Weekday action in the original PR.

Update URL for Monday PD Action

---

.github/actions/vpn-azure/action.yml
.github/workflows/alert_cert_expire.yml
.github/workflows/alert_resource_costs.yml
.github/workflows/alert_terraform_changes.yml
.github/workflows/build_hub.yml
.github/workflows/cleanup_acr_images.yml
.github/workflows/deployment_rollback.yml
.github/workflows/export_cost_data.yml
.github/workflows/release_chatops_app.yml
.github/workflows/release_to_azure.yml
.github/workflows/release_trial_frontend.yml
.github/workflows/restore_databases.yml
.github/workflows/start_test_servers.yml
.github/workflows/stop_test_servers.yml
.github/workflows/sync-translation-schemas.yml
.github/workflows/validate_resources.yml

This PR updates secret name in GH actions.

update actions Az secret

---

prime-router/docs/standard-operating-procedures/update-observation-mapping-table.md

This PR adds documentation on how to update condition table using RCTC data.
- #17661
- #issue

More documentation on how to update condition table manually

---

prime-router/metadata/file_name_templates/file-name-templates.yml

Small fix for filename template from request.
Part of #14974 
Test Steps:
- Fixes #issue
- #issue …

change filename template for NM based on request

---

.github/workflows/frontend_ci.yml
frontend-react/.pa11yci
frontend-react/pa11y.json

This PR fixes the Pa11y runner

update runner for Pa11y

---

.gitignore
auth/build.gradle.kts
prime-router/build.gradle.kts
prime-router/src/main/kotlin/azure/observability/AzureCustomDimensionsSerializable.kt
prime-router/src/main/kotlin/cli/CommandUtilities.kt
prime-router/src/main/kotlin/config/validation/ConfigurationType.kt
prime-router/src/main/kotlin/docgenerators/CsvDocumentationFactory.kt
prime-router/src/test/kotlin/azure/ReportFunctionTests.kt
submissions/build.gradle.kts

This PR applies the following dependabot updates:
- Fixes #17963 
- Fixes #17964 
- Fixes #17965 
- Fixes #17967
- Fixes #17968
- Fixes #17969 
- Fixes #17970 
- Fixes #17971

Platform dependabot 2025-04-28

---

prime-router/src/main/kotlin/azure/ReportFunction.kt
prime-router/src/main/kotlin/azure/observability/event/ReportStreamEventData.kt

This PR adds the item count that is already being calculated in ReportFunction to the REPORT_RECEIVED Azure event. This addresses a recent engagement use case that came up:
> As an engagement engineer,
I want to be able to see if large reports are being submitted to ReportStream,
so that I can more easily troubleshoot pipeline issues
Another way that this use case could be addressed is using the following query, but it has the downside that ITEM_ACCEPTED events are only sent upon successful completion of the Convert step, and so this query is not guaranteed to address the use case above.
```
customEvents
| where name == "ITEM_ACCEPTED"
| summarize avgItemTimestamp=avg(timestamp), reportCount=count() by operation_Id, tostring(customDimensions.sender), …
```

Add itemCount to REPORT_RECEIVED event

---

frontend-react/src/content/about/roadmap.mdx

This PR updates last updated date for Roadmap page

Update last updated date on Roadmap page

---

.github/scripts/tf-deprecations/check_tf_deprecations.py

This PR fixes a potential path issue

fix path issue

---

.github/workflows/frontend_ci.yml

sprinkle in debug info for runner memory and disk utilizations

sprinkle in debug info for runner memory and disk utilizations

---

.github/workflows/build_hub.yml
.github/workflows/frontend_ci.yml

This PR sprinkles in debug info for runner memory and disk utilizations in router build

build-router CI debug mesages

---

.github/actions/build-backend/action.yml
.github/workflows/build_hub.yml
.gitignore

This PR adds parallelization f integration tests based on number of available CPU cores in the runner.

Add dynamic integration test parallelization

---

util/portal-poster-reporter/README.md
util/portal-poster-reporter/src/main/java/gov/cdc/prime/router/poster/PortalPosterReporter.java
util/portal-poster-reporter/src/main/resources/application.properties

This PR contains minor changes to the Portal Poster Reporter utility.

Updating Portal Poster Reporter to properly authenticate.

---

prime-router/docs/onboarding-users/how-to-filter-by-individual-LOINC-codes.md
prime-router/docs/onboarding-users/receiver-onboarding/receivers.md

This PR adds markdown documentation for filtering by LOINC code(s).

[17171] Add documentation on how to filter by individual LOINC codes.

---

buildSrc/src/main/kotlin/reportstream.project-conventions.gradle.kts

- Updated ktlint version from 1.5.0 to 1.6.0 in `buildSrc/src/main/kotlin/reportstream.project-conventions.gradle.kts`
- Fixes #18503
- Fixes #18504 
- Does this PR introduce new endpoints? **No**
- Does this PR include changes in authentication and/or authorization of existing endpoints? **No** 
- Does this change introduce new dependencies that need vetting? **No** - This is a version update of existing ktlint tool
- Does this change require changes to our infrastructure? **No**
- Does logging contain sensitive data? **No**
- Does this PR include or remove any sensitive information itself? **No**

fix: upgrade ktlint to 1.6.0

---

operations/app/terraform/vars/prod/locals.tf
operations/app/terraform/vars/staging/locals.tf

This PR fixes db-related tf issues

Fix terraform database module configuration for prod and staging
